### ISSUE TITLE
RFP - citra

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1000]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://citra-emu.org/
Direct download URL for the software / installer : https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-windows.exe
Software summary / short description: Citra is an open-source emulator for the Nintendo 3DS capable of playing many of your favorite games.

**Comment by mikeee** [comment]
I'll pick this package up

**Comment by mikeee** [comment]
I wasn't able to add this package without AHK jank at this time. Apologies I'll de-assign myself.

**Comment by pauby** [comment]
This was closed as the project was discontinued.
