### ISSUE TITLE
RFP - breaktimer

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1001]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://breaktimer.app/
Direct download URL for the software / installer : https://github.com/tom-james-watson/breaktimer-app/releases/latest/download/BreakTimer.exe
Software summary / short description: BreakTimer allows you to set up customizable breaks and will remind you to take them.

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/breaktimer

**Comment by Aurocosh** [comment]
Package approved
