### ISSUE TITLE
RFP - hamachi

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1002]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.vpn.net/
Direct download URL for the software / installer : https://secure.logmein.com/hamachi.msi
Software summary / short description: LogMeIn Hamachi is a hosted VPN service that lets you securely extend LAN-like networks to distributed teams, mobile workers and your gamer friends alike. In minutes

**Comment by Xav83** [comment]
Hi  @soredake, 

I took a look at this issue, and the [following Chocolatey package](https://community.chocolatey.org/packages/hamachi), maintained by @Smart123s, is available and seems up to date with the [release that can be downloaded on Hamachi website](https://www.vpn.net/). :slightly_smiling_face:
