### ISSUE TITLE
RFM - minishift

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#1006]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/minishift
Package source URL: https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/minishift

**Comment by dgalbraith** [comment]
I am happy to pick this one up - Chocolatey user name dgalbraith.

**Comment by abejenaru** [comment]
> I am happy to pick this one up - Chocolatey user name dgalbraith.

Thanks! I've added you as maintainer, please check your email (also the spam folder) for a confirmation message.
I also have one PR pending, don't transfer the package just yet!

**Comment by dgalbraith** [comment]
Maintainer confirmation accepted.

**Comment by pauby** [comment]
This package is maintained by the [Chocolatey Community Chocolatey Packages repository](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/minishift). I've removed the other maintainers and will close this issue.
