### ISSUE TITLE
RFP - pcloud

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1007]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.pcloud.com
Direct download URL for the software / installer : https://p-def7.pcloud.com/cBZxU1NhDZo9pE8TZQwBrZXZl7rpv7ZAkZZ6RFZkZFATNkZuzZKFZ8JZFFZvJZHzZSVZ4pZiFZ2zZ0zZopZipZvHZ5wSDXZDcP44s4FiqH3kn0AVhV8QuDHtLO7/pCloud_Windows_3.10.4_x64.exe
Software summary / short description:
Service to provide safe and affordable cloud storages.

**Comment by pauby** [comment]
This package [now exists](https://community.chocolatey.org/packages/pcloud).
