### ISSUE TITLE
RFP - cheat

### ISSUE THREAD

**Issue by Unpublished** [chocolatey-community/chocolatey-package-requests#1009]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/cheat/cheat 
Direct download URL for the software / installer: https://github.com/cheat/cheat/releases/download/4.2.1/cheat-windows-amd64.exe.zip
Software summary / short description: cheat allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.

**Comment by jakublevy** [comment]
Package created
https://community.chocolatey.org/packages/cheat

**Comment by jakublevy** [comment]
Package approved.

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @jakublevy
