### ISSUE TITLE
RFP - manga-py

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1011]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/manga-py/manga-py
Direct download URL for the software / installer : https://github.com/manga-py/manga-py/archive/refs/tags/1.30.0.zip
Software summary / short description: Manga Archiver similar to gallery-dl and youtube-dl

**Comment by jakublevy** [comment]
Package created: https://community.chocolatey.org/packages/manga-py

**Comment by jakublevy** [comment]
Package approved.
