### ISSUE TITLE
RFP - fanficfare

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1012]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/JimmXinu/FanFicFare
Direct download URL for the software / installer : https://github.com/JimmXinu/FanFicFare/releases/download/v4.3.0/FanFicFarePlugin-v4.3.0.zip
Software summary / short description: Fanfiction Archiver

**Comment by TheCakeIsNaOH** [comment]
### Note to maintainers looking into creating this package

The linked zip archive is a calibre plugin. You may want to base your package on the `calibre-dedrm` package, 
https://community.chocolatey.org/packages/calibre-dedrm

There is also a command line version of this software, but it is only available through pypi.

**Comment by BrandonKMLee** [comment]
It is because it is from PyPI that I hope that there is a standard installer for the tool, similar to Youtube-DL

**Comment by Xav83** [comment]
I pick up this package 🙂  

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/fanficfare) which is currently waiting for the review of Moderators :wink:

**Comment by pauby** [comment]
@Xav83 all the package versions submitted have been rejected. Are you planning on updating the package?

**Comment by Xav83** [comment]
Hi @pauby  :slightly_smiling_face: 

I am currently updating my repository with the chocolatey packages I maintain (processing the issues, ...).
The [package fanficfare](https://github.com/Xav83/chocolatey-packages/tree/develop/automatic/fanficfare) is almost finished, but is not on my priority list. I should work on it again mid february, once the issue on the existing packages I maintained are settled.

If someone want to, I am open to Pull Requests :wink:

**Comment by Xav83** [comment]
Hi again @pauby,

I have finally done it, the [fanficfare package](https://community.chocolatey.org/packages/fanficfare) is now validated and available for everyone to use :tada:
