### ISSUE TITLE
RFM - mupdf

### ISSUE THREAD

**Issue by braderhart** [chocolatey-community/chocolatey-package-requests#1014]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/mupdf
Package source URL: https://github.com/braderhart/choco/tree/master/auto/mupdf

**Comment by teknowledgist** [comment]
I can pick this up.  @braderhart, can you add me as a maintainer?  (same username)

**Comment by braderhart** [comment]
@teknowledgist Done. At your earliest convenience can you please fork the package source and update the package accordingly.

**Comment by teknowledgist** [comment]
@braderhart I've got the package ready to go (not anything needed, really), but there isn't a new application release yet.  

I don't see a need to push an interim package unless you want the package source to reflect my repo over yours.  Is that what you would like?

**Comment by braderhart** [comment]
@teknowledgist There isn't an immediate need, but if there are no new releases for some time then I may ask that you push a new package release so that I can remove the package source from GitHub.

**Comment by pauby** [comment]
Even though there is no new packages being published, I have added that label and will close this.

@AdmiringWorm Thoughs on a new 'New Maintainer' or 'Maintainer Request Complete' or something else label?

**Comment by mkevenaar** [comment]
> @AdmiringWorm Thoughs on a new 'New Maintainer' or 'Maintainer Request Complete' or something else label?

While I am not @AdmiringWorm, I think that could be a status in the workflow that we can add.

**Comment by AdmiringWorm** [comment]
@pauby I'm not against adding a new label for `New Maintainer` or `Maintainer Request Complete` for cases like this.

However, I do agree with @mkevenaar that it should probably be a status workflow label.

Considering that the current label `Status: Published` is for requests that have been completed by publishing a new package to the new community repository, maybe we should have a label saying `Status: Complete` or `Status: Done` for cases where there won't be a new package that completes the request?

**Comment by pauby** [comment]
> Considering that the current label Status: Published is for requests that have been completed by publishing a new package to the new community repository, maybe we should have a label saying Status: Complete or Status: Done for cases where there won't be a new package that completes the request?

If I had to pick I'd say 'Status: Completed' but it really doesn't matter which one as long as we know what it is.

**Comment by braderhart** [comment]
@teknowledgist Hey, was hoping you could go ahead and remove me as a package maintainer on this package. Thanks!

**Comment by teknowledgist** [comment]
@braderhart Sure.  No problem.  You have been removed as a maintainer.
