### ISSUE TITLE
RFP - openproject

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1015]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.openproject.org/
Direct download URL for the software / installer : https://github.com/opf/openproject/archive/refs/tags/v11.4.1.zip
Software summary / short description: FOSS Project management software

**Comment by Xav83** [comment]
I pick up this package then 😆 

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/openproject) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/openproject/12.2.5) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
