### ISSUE TITLE
RFP - logseq

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1020]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/logseq/logseq
Direct download URL for the software / installer : https://github.com/logseq/logseq/releases/download/0.4.4/logseq-win-x64-0.4.4.exe
Software summary / short description: An Open Source login-free version of Obsidian, an aesthetically better alternative to Trilium, Foam and Dendron without VSCode

**Comment by Xav83** [comment]
Hi @BrandonKMLee, @pauby, :slightly_smiling_face: 

There is actually a Chocolatey package which already exists for logseq. You can find it [here](https://community.chocolatey.org/packages/logseq) and it is maintained by wizard (@w0 on GitHub) :wink:
