### ISSUE TITLE
RFP - nicotine+

### ISSUE THREAD

**Issue by heroku-miraheze** [chocolatey-community/chocolatey-package-requests#1022]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://nicotine-plus.github.io/nicotine-plus/
Direct download URL for the software / installer : https://github.com/Nicotine-Plus/nicotine-plus/releases/latest/download/windows-x86_64-installer.zip
Software summary / short description: Nicotine+ is a graphical client for the Soulseek peer-to-peer file sharing network.

**Comment by TheCakeIsNaOH** [comment]
@majkinetor has created a package here:
https://community.chocolatey.org/packages/nicotine-plus
