### ISSUE TITLE
RFM - openvpn

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#1024]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/openvpn
Package source URL: https://github.com/wget/chocolatey-package-openvpn

Date the maintainer was contacted (in YYYY-MM-DD): 2021-06-22
How the maintainer was contacted: See below

Note that communication was established with the current maintainer in a couple of separate ways. The package has been outdated for some time, but the maintainer has been unable to update it to the latest version. I'm not casting any judgements on why that is. The current maintainer has done a fantastic job of picking it up and updating it. However, I've let them know I'm raising this and have pointed them to it.

See this [GitHub issue](https://github.com/wget/chocolatey-package-openvpn/issues/14) and the [package Disqus comments](https://community.chocolatey.org/packages/openvpn#discussion).

**Comment by dgalbraith** [comment]
@pauby I am happy to pick this one up

**Comment by pauby** [comment]
@dgalbraith Can you send the usual email to the Site Admins and reference this issue in case I don't get to pick it up?

**Comment by pauby** [comment]
@dgalbraith I don't see any progress on this. My intention is to open it up to other maintainer?

**Comment by dgalbraith** [comment]
@pauby base streams setup and migration is done.  Have been stalled on a clean upgrade path from older package versions should they be installed.

Is it acceptable for an upgrade from an older version to require an uninstall/reinstall?

**Comment by 29039** [comment]
@dgalbraith what's happening? You're listed as a maintainer on the chocolatey site so you should have access.

**Comment by pauby** [comment]
Since there hasn't been any movement on this I think we should look at moving it into https://github.com/chocolatey-community/chocolatey-packages. I'll add this to my todo to start doing this.

**Comment by pauby** [comment]
Awesome work @dgalbraith! Because there have been many issues with this package to avoid confusion it may be an idea to remove all other maintainers. That's nothing more than a suggestion.
