### ISSUE TITLE
RFP - flameshot

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1032]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/flameshot-org/flameshot
Direct download URL for the software / installer : https://github.com/flameshot-org/flameshot/releases/download/v0.9.0/Flameshot-0.9.0-win64.msi
Software summary / short description:
Screenshot app for Windows

**Comment by dtantono** [comment]
Hi, i saw this issue is sitll unsolved and closed abruptly. may I know what happened?

**Comment by pauby** [comment]
See the above [comment](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1032#issuecomment-873573809) - there is already a request for this.
