### ISSUE TITLE
RFP - pcsxr

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1033]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://deskreen.com/lang-en
Direct download URL for the software / installer : https://codeplexarchive.blob.core.windows.net/archive/projects/pcsxr/pcsxr.zip
Software summary / short description:
Playstation emulator

**Comment by pauby** [comment]
The download location for the software (Codeplex) no longer operates. The website doesn't appear to offer the software.

Closing this issue.
