### ISSUE TITLE
RFP - vysor

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1034]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.vysor.io/
Direct download URL for the software / installer : https://github.com/koush/vysor.io/releases/download/v4.1.27/Vysor-win-4.1.27.exe
Software summary / short description:
Phone mirroring app

**Comment by Xav83** [comment]
Hi @dtantono, @pauby,

I have taken a look at this issue, and, in the [vysor licence](https://www.vysor.io/VysorLicense.pdf), written by the software author @koush, I found the following section:
> 2.3. No DistributionNo distribution of code or binaries is allowed. Code can be hosted on Licensee's servers / sites.

Does this mean that no Chocolatey package should be created for this software ?

**Comment by mkevenaar** [comment]
> Hi @dtantono, @pauby,
> 
> 
> 
> I have taken a look at this issue, and, in the [vysor licence](https://www.vysor.io/VysorLicense.pdf), written by the software author @koush, I found the following section:
> 
> > 2.3. No DistributionNo distribution of code or binaries is allowed. Code can be hosted on Licensee's servers / sites.
> 
> 
> 
> Does this mean that no Chocolatey package should be created for this software ?

No, a Chocolatey package can be created for software that needs to be downloaded from the internet. There is no requirement for a package to redistribute the software. 

If the package is build to download the software from the original site, it's nothing more then a 'wrapper' around the installer for automation.

**Comment by Xav83** [comment]
Thanks for the information @mkevenaar :slightly_smiling_face:

I pick up this package then 😆 

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/vysor) which is currently waiting for the review of Moderators :wink:
