### ISSUE TITLE
RFP - beeper

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1038]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.beeper.com/
Direct download URL for the software / installer : https://download.beeper.com/windows/nsis/x64
Software summary / short description:
messenger wrapper that integrates multiple services

**Comment by dtantono** [comment]
Hi, it seems this ticket is closed and it is still unfinished. may I know why?

**Comment by pauby** [comment]
See [this comment](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1038#issuecomment-877739193). There was no update from you after that.
