### ISSUE TITLE
RFP - ryujinx

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1039]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://ryujinx.org/download/
Direct download URL for the software / installer :https://ci.appveyor.com/api/buildjobs/xtc2ipape33d1fip/artifacts/ryujinx-1.0.6970-win_x64.zip
Software summary / short description:
Nintendo Switch Emulator

**Comment by jakublevy** [comment]
Somebody have already created the package: https://community.chocolatey.org/packages/ryujinx

**Comment by TheCakeIsNaOH** [comment]
Package approved is approved.
