### ISSUE TITLE
RFP - switchhosts

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1040]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://swh.app/
Direct download URL for the software / installer : https://github.com/oldj/SwitchHosts/releases/download/v4.0.2/SwitchHosts_installer_4.0.2.6057.exe
Software summary / short description: Host File Manager

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/switchhosts) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/switchhosts/4.1.2) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:

**Comment by C-Duv** [comment]
It looks like the package is not using the 64-bits installer.

The `chocolateyInstall.ps1` in [`switchhosts.4.1.2.nupkg`](https://community.chocolatey.org/api/v2/package/switchhosts/4.1.2) refers to `SwitchHosts_windows_installer_4.1.2.6086.exe`.

Is it on purpose or a bug I should report?

**Comment by pauby** [comment]
@C-Duv Please contact the maintainer about this.
