### ISSUE TITLE
RFP - astiga

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1044]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://asti.ga/
Direct download URL for the software / installer : https://s3.eu-central-1.wasabisys.com/astiga-dist/astiga%20Web%20Setup%200.1.2.exe
Software summary / short description:
app for listen music to the cloud

**Comment by pauby** [comment]
The download link works. But on the website, I can't find anywhere to validate the link. This looks to be for Android or Web player only.
