### ISSUE TITLE
RFP - bot-framework-composer

### ISSUE THREAD

**Issue by drdamour** [chocolatey-community/chocolatey-package-requests#1045]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/microsoft/BotFramework-Composer
Direct download URL for the software / installer :  https://aka.ms/bf-composer-download-win (via https://dev.botframework.com/ )
Software summary / short description: composer is an IDE for creating bots using the MS bot sdk

**Comment by drdamour** [comment]
rerun?

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/bot-framework-composer) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/bot-framework-composer/2.1.2) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
