### ISSUE TITLE
RFP - archivebox

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1048]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ArchiveBox/electron-archivebox
Direct download URL for the software / installer : https://get.archivebox.io
Software summary / short description: Personal Archive of Websites

**Comment by pauby** [comment]
The Direct Download URL is a script that says:

```
Supported Platforms: Ubuntu/Debian/FreeBSD/macOS
```

On the GitHub page, I can't see any Windows installer / scripts / setup other than a mention of `Linux Bash on Windows`. 

I'm going to go ahead and close this but if there is a Windows install, then let us know, and we can reopen it again.
