### ISSUE TITLE
RFM - backupper-standard

### ISSUE THREAD

**Issue by holysaiyan1** [chocolatey-community/chocolatey-package-requests#1050]
**I DON'T Want To Become The Maintainer**
------
- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

**Checklist**
------
- [x] Issue title starts with 'RFM - '

**Existing Package Details**
------
Package URL: https://chocolatey.org/packages/backupper-standard
Package source URL: https://github.com/bcurran3/ChocolateyPackages

Date the maintainer was contacted (in YYYY-MM-DD): 2021-07-09
How the maintainer was contacted: Contacted him through 'Contact Maintainers' on the package page stating the package is no longer up to date. Maintainer replied on July 24 that he is no longer interested in maintaining.

I contacted the site admins on 2021-07-30 and received a reply directing me to file an RFM.

**Comment by tunisiano187** [comment]
Hello,
I'll take this package.
It's ready on my repo.
Thank you.

**Comment by gep13** [comment]
@tunisiano187 I have replied to your request email. I am not sure if there is a need for this package to change maintainer.

**Comment by tunisiano187** [comment]
Indeed.
i think we can close this issue then.
Thank you.

**Comment by pauby** [comment]
@gep13 @tunisiano187 can you please confirm what was discussed by email so we know why this was closed?

**Comment by tunisiano187** [comment]
@pauby , of course, the maintainer has pushed a newer version, so no need to take over.

**Comment by pauby** [comment]
Thanks @tunisiano187
