### ISSUE TITLE
RFP - xxd

### ISSUE THREAD

**Issue by MohammadRaziei** [chocolatey-community/chocolatey-package-requests#1052]
Checklist

- [x]  The package I am requesting does not already exist on [https://chocolatey.org/packages](https://chocolatey.org/packages);  
- [x] There is no open issue for this package;  
- [x] The issue title starts with 'RFP - ';  
- [x] The download URL is public and not locked behind a paywall / login;  

## Package Details
Software project URL : https://sourceforge.net/projects/xxd-for-windows/ 
Direct download URL for the software / installer :  https://sourceforge.net/projects/xxd-for-windows/files/latest/download
Software summary / short description: unix xxd but for windows

**Comment by jakublevy** [comment]
Package created
https://community.chocolatey.org/packages/xxd

**Comment by jakublevy** [comment]
Package approved

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package, @jakublevy
