### ISSUE TITLE
RFP - r128gain

### ISSUE THREAD

**Issue by damian101** [chocolatey-community/chocolatey-package-requests#1057]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/desbma/r128gain
Direct download URL for the software / installer: https://github.com/desbma/r128gain/releases/download/1.0.3/r128gain_win64.zip
Software summary / short description: audio loudness scanner & tagger

**Comment by jakublevy** [comment]
Hi,
I created the package, here it is: https://community.chocolatey.org/packages/r128gain.

It is currently under moderation. If you want to install it, you can do so by:

1. checking yourself the content of scripts
2. executing `choco install r128gain --version 1.0.3`

**Comment by jakublevy** [comment]
The package was approved, close please.

**Comment by damian101** [comment]
awesome!
