### ISSUE TITLE
RFP - standard-notes

### ISSUE THREAD

**Issue by wickles** [chocolatey-community/chocolatey-package-requests#1058]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://standardnotes.com/
Direct download URL for the software / installer : https://github.com/standardnotes/desktop/releases/download/v3.8.18/standard-notes-3.8.18-win.exe
Software summary / short description:
Standard Notes is a safe place for your notes, thoughts, and life's work.
A free, open-source, and completely encrypted notes app.

**Comment by teknowledgist** [comment]
This was [proposed a while back](https://github.com/chocolatey-community/chocolatey-package-requests/issues/732), but for now, it is not really possible.  

Buried in that issue thread is [the link to the Standard Notes request for a "machine install"](https://github.com/standardnotes/desktop/issues/469).   If you want a Chocolatey package, make some noise over there.
