### ISSUE TITLE
RFP - iasl

### ISSUE THREAD

**Issue by RandomDSdevel** [chocolatey-community/chocolatey-package-requests#1060]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL:  https://acpica.org/
Direct download URL for the software/installer:  https://acpica.org/sites/acpica/files/iasl-win-20210331.zip
Software summary/short description:  iASL is the ACPI source-code compiler and disassembler.  

Related issue:  #1059.

**Comment by RandomDSdevel** [comment]
> - Is this the package you are requesting: https://chocolatey.org/packages/iasl. There is no listed versions, which means it do not show up during a search on chocolatey.org. If this is not the package you are looking for, please update the issue title to something else that won't conflict with existing packages on chocolatey.org.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yes, that's an older, quite-outdated version of the package I'm requesting with this issue.

**Comment by pauby** [comment]
> Yes, that's an older, quite-outdated version of the package I'm requesting with this issue.

The version aside, that is still the same package / software?

**Comment by RandomDSdevel** [comment]
> > Yes, that's an older, quite-outdated version of the package I'm requesting with this issue.
> 
> The version aside, that is still the same package / software?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exactly.

**Comment by RandomDSdevel** [comment]
@AdmiringWorm:  

> As the package exists, please follow the triage process for any further action on this software: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Where, if I might ask?  It doesn't show up in any of:  

 - '`choco search iasl`'
 - [A search for 'iasl'](https://community.chocolatey.org/packages?q=iasl) in [the Chocolatey Community Packages web tree](https://community.chocolatey.org/packages)
 - [A search for 'iasl'](https://github.com/chocolatey-community/chocolatey-packages/search?q=iasl) in [the 'chocolatey-community/chocolatey-packages' GitHub repository](https://github.com/chocolatey-community/chocolatey-packages).  

I'd ask if the 'iasl' package was a non-maintainer upload since, matching the documentation, it doesn't show up in the package web tree, but '`choco search`' can't find it, either.  

---

(This is kind of academic at this point, though, since I gave up on trying to build the UEFI shell that one time and never went back to make another attempt.)

**Comment by pauby** [comment]
It's at https://community.chocolatey.org/packages/iasl

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK; thank you, @pauby.

**Comment by RandomDSdevel** [comment]
@AdmiringWorm:  

> As the package exists, please follow the triage process for any further action on this software: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This has now been started with warexify/chocolatey-edk2-buildtools#1, a PR to the package source's host GitHub repository.
