### ISSUE TITLE
RFP - monitorian

### ISSUE THREAD

**Issue by savbran** [chocolatey-community/chocolatey-package-requests#1061]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/emoacht/Monitorian
Direct download URL for the software / installer : https://github.com/emoacht/Monitorian/releases/download/3.4.0-Installer/MonitorianInstaller340.zip
Software summary / short description: Monitorian is a Windows desktop tool to adjust the brightness of multiple monitors with ease.

The package should be installed and then it runs in background, an icon is visible in taskbar notification area that can be clicked to adjust the monitors (all the attached monitors) brightness simply using a handler for each attached monitor.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/monitorian) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/monitorian) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
