### ISSUE TITLE
RFP - proxallium

### ISSUE THREAD

**Issue by TheDcoder** [chocolatey-community/chocolatey-package-requests#1062]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://proxallium.dtw.tools
Direct download URL for the software / installer : https://github.com/DcodingTheWeb/ProxAllium/releases/download/v0.4.2/ProxAllium-v0.4.2.7z
Software summary / short description: ProxAllium is a GUI front-end for [Tor](https://www.torproject.org), it can be used to circumvent censorship and allow freely browsing the internet.

**Comment by Cossey** [comment]
Please assign this to me. I'll take on maintaining this package for Damon. 

Daman, ill include the files direct in the chocolatey package. I can also include a start menu entry as well. My updating script will pull from github releases and update whenever the "latest" version tag differs. 

I'll use the release text on github as the release notes. Also let me know how you want it tagged  on community repository and what you want it to say on the description text so I can get it the way you want.

**Comment by TheDcoder** [comment]
@Cossey Thank you so much for adopting this package! :grin:

> Also let me know how you want it tagged on community repository and what you want it to say on the description text so I can get it the way you want.

These are the tags on the top of my head: privacy, security, anonymity, tor, proxy, vpn, portable etc.

As for the description I think we can keep it simple:
> ProxAllium is a GUI frontend to Tor, you can use it to easily create a proxy and use with it programs (like browsers, mail clients, chat clients etc.) to circumvent censorship and also to encrypt your connection.

Let me know if you need more info, cheers!

**Comment by Cossey** [comment]
That is fine for now. I'll include files direct in the package instead of shimming them from GitHub.

Is just the current version fine to have on the community repository or do you need some older versions too?

Please give me up to a week to build an updating script, do testing and get the package(s) submitted.

**Comment by TheDcoder** [comment]
> Is just the current version fine to have on the community repository or do you need some older versions too?

The current is fine, no need to have older versions with less features in the repository. They also used to come with Tor pre-packaged, which means they would be exposed to security risks if there are any in the old versions of Tor. The latest version doesn't package Tor so it's for the best.

> Please give me up to a week to build an updating script, do testing and get the package(s) submitted.

Of course, please feel free to take your time, I am grateful for your effort and enthusiasm :smile:

**Comment by Cossey** [comment]
Okay, the package is nearly ready to be pushed, but should it `dependencies` the tor package (It will install the tor package when installed)? If so which tor package should it install? (https://community.chocolatey.org/packages?q=tor).

**Comment by pauby** [comment]
If there are several different dependencies a package can work with it's usually better not taking a direct dependency on any of them but instead highlight what is required in the package description and let the user decide which dependent package to install.

**Comment by TheDcoder** [comment]
@Cossey ProxAllium doesn't have a hard dependency, it can use any version of Tor. On the first start it prompts the user to go through the setup guide, which lets them choose a folder containing Tor, or a folder containing the Tor Browser (which includes Tor).

The choice is normally left up to the user, what I recommend to users is to install Tor browser so that Tor is kept updated whenever TB is updated.

But since the user in this case would be using chocolatey, I am not sure what the best way of doing things is. How easy is it for the user to locate `tor.exe` if it is added as a dependency?

Perhaps I can even add a feature to auto-detect the appropriate version of Tor if installed via chocolatey.

For now I think we should take @pauby's advice and mention that the user can install Tor or Tor Browser in the description and let them make the choice.

**Comment by Cossey** [comment]
Okay, it is submitted and there is a mention of the requirement of Tor.
https://community.chocolatey.org/packages/proxallium/0.4.2

**Comment by TheDcoder** [comment]
@Cossey Cool!

I have two comments:

1. The website has been migrated to a new domain: https://proxallium.dtw.tools (the old one still works and redirects to the new one)
2. The description says "requires" packages, but it doesn't really require them if the user already has Tor (Browser) installed outside of chocolatey, I'd phrase it something like this: "**Requires Tor to function, you can get it from the `tor` or `tor-browser` bundle packages.**"

**Comment by Cossey** [comment]
Okay I have made changes to those two points, but before I push again, is there a new url for https://download.tuxfamily.org/proxallium/icons/128.png that I should be using? (This is the icon that displays on the chocolatey community repository).

**Comment by TheDcoder** [comment]
Thanks, you can use the 256 pixel version of the icon for more resolution: https://download.tuxfamily.org/proxallium/icons/256.png

The download repository is still hosted at TuxFamily.

**Comment by Cossey** [comment]
Done.

**Comment by Cossey** [comment]
Waiting on moderator to approve. Unfortunately it has been flagged by VirusTotal as malicious by 8 vendors which will require moderator approval regardless. I noticed that you've posted on the virustotal page about that @TheDcoder . If you have not already, might I suggest you contact some of these vendors to report a false positive? That way this will improve your score on VirusTotal as well as not flag your software on those users devices. 

I've done this before with one of my installers that was flagged by my partners endpoint protection software for her work. I submitted a report and it was a turnaround of 3 days if I recall (don't remember the software that was being used).

This is a pretty good list provided by VirusTotal which list contact details for reporting false positives:
https://github.com/yaronelh/False-Positive-Center

Here are some links to the vendors that have reported the exe as Malicious
https://www.secureage.com/article-report-false-positive
https://www.maxsecureantivirus.com/maxis/submit_aFalse_Positive.htm
https://service.mcafee.com/?locale=en-IN&articleId=TS102751&fromSearch=true&page=shell&shell=article-view
https://support.quickheal.com/v4/index.php?/Knowledgebase/Article/View/137/0/how-to-submit-a-false-positive

Even if you can get at least 4 of those vendors to approve as false positive this would drastically improve your score on VirusTotal.

**Comment by TheDcoder** [comment]
@Cossey Thank you for the information. I did send emails to AV vendors a while back and some of them responded positively, but most of them just ignored me. I think the turnaround time for me was longer than 3 days, and it didn't eliminate all false positives.

The reason for such a high positivity rate is due to how AutoIt (the programming language in which ProxAllium is written) is used, as it is easy to learn and use, a certain portion of malicious users have written viruses in it, and since the compiled programs are nothing more than the AutoIt interpreter and the code, the signature for a virus matches with many other totally different AutoIt programs, more info can be obtained from this forum post: https://www.autoitscript.com/forum/topic/34658-are-my-autoit-exes-really-infected/

Never the less, I am going to release an update to ProxAllium soon, so I will contact the vendors again at that time to get it "whitelisted". I hope it can be approved by manual review until then.

**Comment by Cossey** [comment]
That's really unfortunate how some have not responded.

Any updates you make and release will be automatically picked up and deployed out to the community repo. It checks approximately every 4 hours (DELAY=240) via the GitHub API. 

However please do open an issue at https://github.com/Cossey/choco and give me a heads up if you plan on doing something like drastically change the folder structure or executable file names etc in any future releases etc as I may have to upgrade the script.

**Comment by Cossey** [comment]
Package has been approved. RFP completed.

**Comment by TheDcoder** [comment]
Awesome! @Cossey Thanks for picking it up :)

**Comment by TheCakeIsNaOH** [comment]
Package approved:
https://community.chocolatey.org/packages/proxallium/0.4.2
