### ISSUE TITLE
RFP - athens

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1063]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.athensresearch.org/
Direct download URL for the software / installer : https://github.com/athensresearch/athens/releases/download/v1.0.0-beta.89/Athens-Setup-1.0.0-beta.89.exe
Software summary / short description: Knowledge Database

**Comment by BrandonKMLee** [comment]
Also cross-reference https://github.com/chocolatey-community/chocolatey-package-requests/issues/1020

**Comment by pauby** [comment]
Why the linking cross-reference?

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/athens) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/athens/2.1.0) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
