### ISSUE TITLE
RFP - magpie

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1064]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Blinue/Magpie
Direct download URL for the software / installer : https://github.com/Blinue/Magpie/releases/download/v0.6.0/Magpie_v0.6.0.zip
Software summary / short description: Magpie can enlarge any window to full screen and supports a variety of advanced zoom algorithms, including Lanczos, Anime4K, FSR, FSRCNNX, etc.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/magpie) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/magpie) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:

**Comment by soredake** [comment]
@Xav83 thank you!
