### ISSUE TITLE
RFP - yt-dlp

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1065]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/yt-dlp/yt-dlp
Direct download URL for the software / installer : https://github.com/yt-dlp/yt-dlp/releases/download/2021.09.02/yt-dlp.exe
Software summary / short description: yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project

**Comment by TheCakeIsNaOH** [comment]
I'll take this one, package current in review:
https://community.chocolatey.org/packages/yt-dlp/2021.09.02

**Comment by TheCakeIsNaOH** [comment]
This can be closed as the first version package has been approved.
