### ISSUE TITLE
RFM - nasm

### ISSUE THREAD

**Issue by RandomDSdevel** [chocolatey-community/chocolatey-package-requests#1068]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/nasm
Package source URL:  https://github.com/andyli/nasm-choco

Date the maintainer was contacted (in YYYY-MM-DD): 2021-09-03
How the maintainer was contacted:  E-mail via package index page's 'Contact Maintainers' link.  

 - Contact attempt 2:  
    - 2021-09-11
    - [Pull request](https://github.com/andyli/nasm-choco/pull/1) to package source repository.

**Comment by teknowledgist** [comment]
I can pick this up as a maintainer.

**Comment by teknowledgist** [comment]
I'm ready to submit.  Do I need to do anything else to be made a maintainer?  I thought claiming it (above) was enough.

**Comment by TheCakeIsNaOH** [comment]
I've sent an invitation.

**Comment by teknowledgist** [comment]
[Updated package](https://community.chocolatey.org/packages/nasm/2.15.05) submitted.

**Comment by TheCakeIsNaOH** [comment]
Thanks for picking up this package @teknowledgist
