### ISSUE TITLE
RFM - windowtop

### ISSUE THREAD

**Issue by gileli121** [chocolatey-community/chocolatey-package-requests#1069]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/windowtop
Package source URL: https://github.com/BiGilSoft/WindowTop

**Comment by AdmiringWorm** [comment]
Closing request as you have not completed the request body.
Please follow the [package triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process)
