### ISSUE TITLE
RFM - cura-lulzbot

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-package-requests#1070]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/cura-lulzbot
Package source URL: https://github.com/jtcmedia/chocolatey-packages/tree/master/cura-lulzbot

**Comment by tunisiano187** [comment]
Package automated, this issue can be closed

**Comment by tunisiano187** [comment]
@jtcmedia can yyou close this issue?
