### ISSUE TITLE
RFP - crowtranslate

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1075]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://crow-translate.github.io/
Direct download URL for the software / installer : https://github.com/crow-translate/crow-translate/releases/download/2.8.7/crow-translate-2.8.7-win64.exe
Software summary / short description:
Translation app

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/crowtranslate) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/crowtranslate) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
