### ISSUE TITLE
RFP - qrcp

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1077]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://claudiodangelis.com/qrcp/
Direct download URL for the software / installer : https://github.com/claudiodangelis/qrcp/releases/download/0.8.4/qrcp_0.8.4_Windows_x86_64.tar.gz
Software summary / short description:
Transfer files over Wi-Fi from your computer to a mobile device by scanning a QR code without leaving the terminal

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/qrcp) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/qrcp) has been reviewed and approved by @gep13 :slightly_smiling_face:

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @Xav83
