### ISSUE TITLE
RFP - nanazip

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1078]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/M2Team/NanaZip
Direct download URL for the software / installer : https://github.com/M2Team/NanaZip/releases/download/1.0-Preview3/NanaZipPackage_1.0.46.0_x86_x64_arm64.msixbundle
Software summary / short description:  The 7-Zip derivative intended for the modern Windows experience.

**Comment by jarihu** [comment]
It's maintained: https://community.chocolatey.org/packages/nanazip
