### ISSUE TITLE
RFM - ds4windows

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-package-requests#1082]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/ds4windows
Package source URL: https://github.com/jtcmedia/chocolatey-packages/tree/master/ds4windows

**Comment by AdmiringWorm** [comment]
Additional note to maintainers, if switching to a different fork means a new package as well unless the software author of the current edition has officially handed it over to that new fork.

**Comment by soredake** [comment]
DS4Windows development is resumed https://github.com/Ryochan7/DS4Windows

**Comment by tunisiano187** [comment]
Hello,
I'll take this package
@AdmiringWorm, or @TheCakeIsNaOH , can you add me as maintainer(tunisiano) and assign this issue ?

Thank you

**Comment by jtcmedia** [comment]
I've added you as maintainer. Please remove me once approved.

**Comment by tunisiano187** [comment]
Done, thanks

**Comment by tunisiano187** [comment]
Update pushed
