### ISSUE TITLE
RFM - httpie

### ISSUE THREAD

**Issue by BoboTiG** [chocolatey-community/chocolatey-package-requests#1083]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/httpie
Package source URL: https://github.com/httpie/httpie/tree/master/docs/packaging/windows-chocolatey

**Comment by AdmiringWorm** [comment]
@jakubroztocil as it looks like you have been added as the maintainer to the package, I'll mark this request as In Progress.

Please let us know when you have pushed a new version of the package, as well as when that version have been approved.

**Comment by TheCakeIsNaOH** [comment]
Looks like new versions have been approved.
