### ISSUE TITLE
RFP - threema

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1084]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://threema.ch/en/download
Direct download URL for the software / installer : https://releases.threema.ch/web-electron/v1/release/Threema-Latest.exe
Software summary / short description:
messaging app

**Comment by Xav83** [comment]
Hi  @dtantono @pauby, 

I took a look at this issue, and the [following Chocolatey package](https://community.chocolatey.org/packages/threema-desktop), maintained by @Starz0r, is available and seems up to date with the [release that can be downloaded on Threema website](https://threema.ch/en/download). :slightly_smiling_face:

**Comment by dtantono** [comment]
I think it looks okay and I can close it
