### ISSUE TITLE
RFP - languagetools

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1088]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://languagetool.org/windows
Direct download URL for the software / installer : https://languagetool.org/download/windows-app/LanguageTool-1.0.2.exe
Software summary / short description:
spellcheck app

**Comment by pauby** [comment]
This looks to be the same package as mentioned [above](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1088#issuecomment-954892696). If it's out of date then follow the process mentioned [here](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1088#issuecomment-954905288). I'm going to go ahead and close this.
