### ISSUE TITLE
RFP - sophia

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1091]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/farag2/Sophia-Script-for-Windows
Direct download URL for the software / installer :https://github.com/farag2/Sophia-Script-for-Windows/releases/download/6.0.6/Sophia.Script.for.Windows.10.LTSC.v5.2.16.zip
Software summary / short description: WIndows Debloating Tool

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/sophia) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/sophia) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
