### ISSUE TITLE
RFM - inputdirector

### ISSUE THREAD

**Issue by bsasealteam6** [chocolatey-community/chocolatey-package-requests#1092]
- [X] I am the maintainer of the package and wish to pass it to someone else;

Checklist

- [x] Issue title starts with 'RFM - '
Package URL: https://chocolatey.org/packages/inputdirector
Package source URL:  https://github.com/bsasealteam6/Chocolatey-Packages/tree/master/InputDirector

**Comment by teknowledgist** [comment]
@bsasealteam6 Make me a maintainer, and I'll try to set the InputDirector package to auto-update.

**Comment by bsasealteam6** [comment]
What's your chocolatey.org username?

**Comment by teknowledgist** [comment]
Same as here.  😉

**Comment by AdmiringWorm** [comment]
As the RFM request was not completed, I'll be closing this issue.
Feel free to create a new issue, or let us know to re-open this issue once the request body have been fully filled out.
