### ISSUE TITLE
RFP - gmail-desktop

### ISSUE THREAD

**Issue by karolzlot** [chocolatey-community/chocolatey-package-requests#1093]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/timche/gmail-desktop/releases/tag/v2.25.3
Direct download URL for the software / installer : https://github.com/timche/gmail-desktop/releases/tag/v2.25.3
Software summary / short description: Gmail Desktop
Nifty Gmail desktop app for macOS, Linux & Windows

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/gmail-desktop) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/gmail-desktop/3.0.0) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
