### ISSUE TITLE
RFP - discordchatexporter

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1095]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Tyrrrz/DiscordChatExporter
Direct download URL for the software / installer : https://github.com/Tyrrrz/DiscordChatExporter/releases/download/2.30.1/DiscordChatExporter.zip
Software summary / short description: Archiver for Discord Channels

**Comment by pauby** [comment]
This [package](https://community.chocolatey.org/packages/discordchatexporter) (as highlighted above) is the same one from the same author. However, the most [recent version](https://community.chocolatey.org/packages/discordchatexporter#versionhistory) is out of date. So it may be a case of going through the [triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process).
