### ISSUE TITLE
RFP - rare

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1099]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/Dummerle/Rare/releases/tag/1.7.0
Direct download URL for the software / installer : https://github.com/Dummerle/Rare/releases/download/1.7.0/Rare-1.7.0.msi
Software summary / short description:
GUI frontend for Epic Games Store

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/rare) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/rare) has been reviewed and approved by @Windos :slightly_smiling_face:
