### ISSUE TITLE
RFM - etcher

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-package-requests#1101]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/etcher
Package source URL: https://github.com/majkinetor/au-packages/tree/master/etcher

## Notes

Package is currently embedded and got larger then 200MB. I don't want to maintain non-embedded packages, plus I don't use etcher, so I would like someone else to take over.

**Comment by mkevenaar** [comment]
I am willing to take over, can you add mkevenaar please?

**Comment by majkinetor** [comment]
Added. Thanks.
