### ISSUE TITLE
RFM - solr

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-package-requests#1107]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/solr
Package source URL: https://github.com/majkinetor/au-packages/tree/master/solr

Package became too big to be embedded. I don't want to maintain non-embeddable packages.

**Comment by pauby** [comment]
@majkinetor Why does the maintainer need to support AU streams?

**Comment by majkinetor** [comment]
Because it currently work that ways. Each version is released. Check out the version dates.

**Comment by pauby** [comment]
@majkinetor If you're handing the package over to another maintainer then it's up to them how they maintain it. They don't have to support anything the current maintainer does.

I've removed that part from the original message.

**Comment by majkinetor** [comment]
Lets ignore this req then.
