### ISSUE TITLE
RFP - msedgeredirect

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1108]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/rcmaehl/MSEdgeRedirect
Direct download URL for the software / installer : https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe
Software summary / short description:
A Tool to Redirect News, Search, Widgets, Weather and More to Your Default Browser

**Comment by pauby** [comment]
I will pick this up.

**Comment by pauby** [comment]
This has [already been created](https://community.chocolatey.org/packages/msedgeredirect/).
