### ISSUE TITLE
RFP - filen.io-sync-desktop

### ISSUE THREAD

**Issue by BirdInFire** [chocolatey-community/chocolatey-package-requests#1109]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://filen.io/
Direct download URL for the software / installer : https://cdn.filen.io/sync/updates/filen-setup.exe
Software summary / short description:

Virus total result : [VirusTotal](https://www.virustotal.com/gui/file/86b6e6ae1f0f33a3b5a86dc8092fa896db0253fec9dabe44aba70f73ada7f021)

This is one of the only actual opensource E2E encrypted sync provider (like Mega) but unlike Mega, they do not impose bandwidth limitation. 

## Package Expectations

I actually expect (unlike other package) to update it from chocolatey i don't have seen in the app an auto updater so it must be the best to update it though chocolatey.

Thanks for the one who will do it since they aren't many totally opensource sync provider out there.

**Comment by jakublevy** [comment]
Package created: https://community.chocolatey.org/packages/filen-sync

**Comment by BirdInFire** [comment]
> Package created: https://community.chocolatey.org/packages/filen-sync

Thanks ;)

**Comment by dtantono** [comment]
try this https://github.com/FilenCloudDienste/filen-desktop/releases/download/1.6.2/filen-setup.exe

**Comment by jakublevy** [comment]
> try this https://github.com/FilenCloudDienste/filen-desktop/releases/download/1.6.2/filen-setup.exe

Yeah, I use this link in the install script https://github.com/jakublevy/chocopkgs/blob/80ccfd6c5063b3e49c426ece7a37af9180b46591/filen-sync/tools/chocolateyinstall.ps1#L8

**Comment by jakublevy** [comment]
Package approved.
