### ISSUE TITLE
RFP - internxt-drive

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1111]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://internxt.com/
Direct download URL for the software / installer : https://github.com/internxt/drive-desktop/releases/download/v1.5.0/internxt-drive-1.5.0.exe
Software summary / short description:
Cloud Service

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/internxt-drive) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
