### ISSUE TITLE
RFM - clamav

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1115]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/clamav
Package source URL: https://www.clamav.net/downloads/production/clamav-0.104.1.win.x64.msi

Date the maintainer was contacted (in YYYY-MM-DD): N/A
How the maintainer was contacted: The User is non-existent

**Comment by TheCakeIsNaOH** [comment]
This package does have a maintainer:
![image](https://user-images.githubusercontent.com/38865330/147685825-b7286246-5492-44e8-bbc8-ed873a194756.png)

Please follow the package triage process:
https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process

This issue can be re-opened if needed, after the triage process is complete.
