### ISSUE TITLE
RFM - peazip.portable

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1117]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/peazip.portable
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/peazip.portable/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
The peazip and peazip.install packages are maintained in the [community repository](https://github.com/chocolatey-community/chocolatey-packages). Please open up a discussion there to get the portable variant moved to the same repository.
