### ISSUE TITLE
RFM - newsbin

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1121]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/newsbin
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/newsbin/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
I'll take this request.
The package is ready on my git and the request to admins sent.

Have a nice day.

**Comment by gep13** [comment]
@tunisiano187 thanks for your help with this package!
