### ISSUE TITLE
RFM - nexusfile.install

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1130]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/nexusfile.install
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
Closing due to the [following comment](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1132#issuecomment-1033292427).

Only the meta-package should be opened as an RFM request unless there are different maintainers for the install/portable package.
