### ISSUE TITLE
RFM - nexusfile

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1132]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/nexusfile
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
this request also covers nexusfile.install and nexusfile.portable

**Comment by tunisiano187** [comment]
Hello, I'll take these 3 packages.
They are ready on my git, and requested to be added as maintainer.

Have a nice day

**Comment by tunisiano187** [comment]
Hello,
The packages are updating.
Have a nice day
