### ISSUE TITLE
RFM - dropit

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1138]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/dropit
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/dropit/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
this request covers the packages dropit.install and dropit.portable as well

**Comment by tunisiano187** [comment]
Hello,
This isn't updated since 2018, and the latest update is the same version as on the community repository.
So i don't think it's interesting to push something new.
