### ISSUE TITLE
RFM - thebrain

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1139]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/thebrain
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/thebrain/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
this request covers the packages thebrain.install and thebrain.portable as well.

**Comment by tunisiano187** [comment]
Hello,
This one is done and approved.
You can close it.

Thank you.
