### ISSUE TITLE
RFM - winedt

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1141]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/winedt#files
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/winedt/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
Hello,
I'll take this package.
Have a nice day.

**Comment by tunisiano187** [comment]
Package Pushed.
Have a nice day.

**Comment by tunisiano187** [comment]
Done and approved
Have a nice day
