### ISSUE TITLE
RFM - gamedownloader.install

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1144]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gamedownloader.install
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
Closing due to the [following comment](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1145#issuecomment-1033282843).

Different requests for install/portable editions should only be made if there are different maintainers.
