### ISSUE TITLE
RFM - gdevelop

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1146]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gdevelop
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/gdevelop/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment]
note: this request covers the packages gdevelop.install and gdevelop.portable as well.

**Comment by tunisiano187** [comment]
Hello,
I'll take this package.

Have a nice day.

**Comment by tunisiano187** [comment]
Hello,
I'm the current maintainer of this package.
It's updated for some time now.
You can close this issue.
Have a nice day.
