### ISSUE TITLE
RFM - hashdeep

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1153]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/hashdeep
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/hashdeep/4.4

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
Hello, 
It hasn't been updated since 2014, so i don't think it's worth it.
Have a nice day

**Comment by pauby** [comment]
Given the above, I'll close this request.
