### ISSUE TITLE
RFM - wavpack

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1156]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/wavpack
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/wavpack/4.80.0

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
Hello,
I'll take this package.
It's ready on my git.
I'll ask to be added as maintainer and create the PR on dtgm's.
Have a nice day.

**Comment by tunisiano187** [comment]
Done and approved
Have a nice day
