### ISSUE TITLE
RFM - ekiga

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1161]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/ekiga
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
Hello,
This software is not updated anymore.
So the package won't need to be updated anymore.
Have a nice day.
