### ISSUE TITLE
RFP - yt-dlg

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#1162]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/oleksis/youtube-dl-gui (There is also https://github.com/yt-dlg/yt-dlg, which looks like it's intended to be the official repo, but it doesn't have release binaries)
Direct download URL for the software / installer : https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.2/yt-dlg.exe or https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.2/yt-dlg.msi
Software summary / short description: A cross platform front-end GUI of the popular youtube-dl written in wxPython.

The project this was forked from hasn't seen a new release since 2017. This one is kept up to date. Maybe the original one should be archived or removed from Chocolatey in favour of this one?

**Comment by opusforlife2** [comment]
@joachimschmidt557 I'm pinging you as the maintainer of the current youtube-dl-gui Chocolatey package. Are you interested in maintaining this? Sorry for the unsolicited ping.

**Comment by joachimschmidt557** [comment]
Yes, maintaining `yt-dlg` doesn't seem too be very complex as it's probably similar to `youtube-dl-gui`. I'd be happy to maintain that as well.

**Comment by opusforlife2** [comment]
Thank you!

**Comment by opusforlife2** [comment]
The package says it's ready to be reviewed. Is there anything else left to be done?

**Comment by TheCakeIsNaOH** [comment]
@opusforlife2 
Packages that are ready for review or where the maintainer has updated/responded are put in a queue for human moderation.

You can go here https://ch0.co/moderation to see the current queue.

**Comment by opusforlife2** [comment]
Oh... I see. 237 ready packages. 😅

TIL. I will definitely be more patient with the process. Thanks.

**Comment by opusforlife2** [comment]
Oh. This package has been available for quite a while. I forgot to close this. Please change the label.
