### ISSUE TITLE
RFP - kde-elisa

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1168]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://elisa.kde.org/
Direct download URL for the software / installer : https://binary-factory.kde.org/view/Windows%2064-bit/job/Elisa_Release_win64/lastSuccessfulBuild/artifact/elisa-21.12.0-998-windows-msvc2019_64-cl.exe
Software summary / short description:
music player by KDE

**Comment by TakataSanshiro** [comment]
I just submitted the package.
https://community.chocolatey.org/packages/elisa

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @TakataSanshiro
