### ISSUE TITLE
RFP - deadbeef

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1170]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://deadbeef.sourceforge.io/download.html
Direct download URL for from the software / installer :https://jaist.dl.sourceforge.net/project/deadbeef/travis/windows/1.8.8/deadbeef-1.8.8-windows-x86_64.exe
Software summary / short description:
Music Player

**Comment by pauby** [comment]
As the 'Software project URL' above, and the 'Software Site' on the package page are the same I'm going to go ahead and close this.

**Comment by dtantono** [comment]
how come it is the same? the url  and the webpage is totally different.

**Comment by pauby** [comment]
The 'Software project URL' above is https://deadbeef.sourceforge.io

The 'Software Site' on the [package page](https://community.chocolatey.org/packages/deadbeef) is https://deadbeef.sourceforge.io

It's therefore the same software.
