### ISSUE TITLE
RFP - open-video-downloader

### ISSUE THREAD

**Issue by AzimsTech** [chocolatey-community/chocolatey-package-requests#1171]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/jely2002/youtube-dl-gui
Direct download URL for the software / installer : https://github.com/jely2002/youtube-dl-gui/releases/download/v2.4.0/Open-Video-Downloader-Setup-2.4.0.exe
Software summary / short description: A cross-platform GUI for youtube-dl made in Electron and node.js

**Comment by Xav83** [comment]
Hi @pauby,

Actually, this package already exists [here](https://community.chocolatey.org/packages/open-video-downloader) and seems up to date. The maintainer of this package is @A-d-r-i.

**Comment by pauby** [comment]
Thanks @Xav83 . I'll go ahead and close this now.
