### ISSUE TITLE
RFM - videocacheview

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1173]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/videocacheview
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/videocacheview/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by tunisiano187** [comment]
Hello,
This package is up to date and maintained by Sanshiro

Have a nice day
