### ISSUE TITLE
RFM - privoxy

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1174]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/privoxy
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/privoxy/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by TakataSanshiro** [comment]
I submitted the package.
Package has been approved.
https://community.chocolatey.org/packages/privoxy/3.0.33

**Comment by TheCakeIsNaOH** [comment]
Thanks @TakataSanshiro
