### ISSUE TITLE
RFM - keepass-plugin-trayrecent

### ISSUE THREAD

**Issue by FoxInTheClouds** [chocolatey-community/chocolatey-package-requests#1175]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/keepass-plugin-trayrecent
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/keepass-plugin-trayrecent/0.0.2

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Email

**Comment by tunisiano187** [comment]
Hello,
The version on the repository is up-to-date and no update of the plugin has been published since 2015.
Have a nice day
