### ISSUE TITLE
RFM - cccp

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1176]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/cccp
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/cccp/2015.10.18

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by AdmiringWorm** [comment]
The software site for this package is gone, as such the package can not be updated to use any official sources, and from what I remember of CCCP it did not allow redistribution so the package can not be updated to use embedded binaries either.

As such, I will be closing this issue as invalid.
