### ISSUE TITLE
RFM - lili

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1178]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/lili
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/lili/2.9.4

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by tunisiano187** [comment]
Hello, Lili has been abandoned, https://www.linuxliveusb.com/fr/blog/frontpage
So, it's not required to be updated anymore.
Have a nice day.
