### ISSUE TITLE
RFM - hte

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1179]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/hte
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by tunisiano187** [comment]
Hello,
This software isn't updated since the last package 2015.
The package updating isn't required.

as this is a dtgm package, should we remove it from it's git ? is that an official way about it ?
Thank you.

**Comment by pauby** [comment]
That is a good question.

@gep13 what are your thoughts?

**Comment by gep13** [comment]
Hmm, that is an interesting point...

Since the package version is still the current version, I would be inclined to leave it in the dtgm repository, until someone takes over maintenance of it, if/when there is a new version available.

**Comment by pauby** [comment]
I'll go ahead and close this issue.
