### ISSUE TITLE
RFP - phpmyadmin

### ISSUE THREAD

**Issue by photodude** [chocolatey-community/chocolatey-package-requests#118]
We already have the pg admin install option for managing PostgreSQL, it would be very helpful to also have the phpMyAdmin install option for managing MySQL.

downloads
https://www.phpmyadmin.net/downloads/

PHPMyAdmin should be installed with PHP, MySQL and a webserver like Apache, IIS, or nginx

check if MySQL is installed, install if it's not
check if a webserver is installed, install one if not (default to Apache???)
Check if PHP is installed, install it if it's not

**Comment by tunisiano187** [comment]
Hello, i think i'll use wamp-server for this, is it ok for you ?

**Comment by tunisiano187** [comment]
I am on the triage process of WAMP-server.
It already includes phpmyadmin

**Comment by photodude** [comment]
@tunisiano187 this request for phpadmin is intended for those building a custom *AMP setup outside of WAMP.

WAMP was not meeting my needs and had too many limits so I went the road of building a custom *AMP via chocolatey.

**Comment by photodude** [comment]
@tunisiano187 here is a link to the article I wrote on building a custom *AMP setup using chocolatey.  It's a bit dated and I haven't reviewed it in a while for process updates.
https://brian.teeman.net/joomla/885-install-amp-on-windows-with-chocolatey

**Comment by Windos** [comment]
It looks like this package has been added to the community repository outside of the RFP process and is available here now: https://community.chocolatey.org/packages/phpmyadmin

**Comment by photodude** [comment]
@Windos thank you. That's great news.
