### ISSUE TITLE
RFM - diskmon

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1180]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/diskmon
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/diskmon/2.01

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by Thilas** [comment]
I'm already maintaining a couple of Sysinternals packages, I can take care of this one as well.

**Comment by pauby** [comment]
@Thilas Can you send a request to pickup the package to the Site Admins (go to the package page -> Contact Site Admins)?

**Comment by Thilas** [comment]
@pauby, already done earlier today.

**Comment by Thilas** [comment]
@pauby, new package created and pushed. PR to remove from dtgm repo sent.

**Comment by gep13** [comment]
@Thilas thank you for picking up this package!
