### ISSUE TITLE
RFM - multimonitortool

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1195]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/multimonitortool
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/multimonitortool/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by brogers5** [comment]
I'll pick this one up.

**Comment by brogers5** [comment]
> Can you use the 'Contact the Site Admins' link on the package page to request to be added as a maintainer and reference this GitHub issue?

Done.

**Comment by brogers5** [comment]
I've accepted the maintainer request.

I worked on an updated version in parallel and just pushed it up for review:
https://community.chocolatey.org/packages/multimonitortool/1.96

**Comment by brogers5** [comment]
The new package version 1.96 has just been approved. Issue can now be closed.
