### ISSUE TITLE
RFM - myuninst

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1212]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/myuninst
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/myuninst/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
Hello,
Not updated anymore and replaced by UninstallView, that is maintained and up-to-date by sanshiro
Have a nice day

**Comment by pauby** [comment]
I will likely pick this up just to deprecate it.

**Comment by pauby** [comment]
That's been done. New package has been pushed. Removed package from dtgm repository.
