### ISSUE TITLE
RFM - mweather

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1214]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/mweather
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/mweather/1.73

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by tunisiano187** [comment]
I'll take this package request.
Can you assign i to me ?
I've sent a request via the admins link on the mweather and the mweather.install packages.

Thank you.

**Comment by tunisiano187** [comment]
Hello,
This package as been approved
so this issue can be closed as complete.
Thank you.
