### ISSUE TITLE
RFM - riecoin

### ISSUE THREAD

**Issue by FoxInTheClouds** [chocolatey-community/chocolatey-package-requests#1221]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/riecoin
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Email

**Comment by tunisiano187** [comment]
Hello,
This project hasn't been updated since 2014.
Why do you want to update it's packages ?

**Comment by pauby** [comment]
The [last version was 2014](https://github.com/riecoin/riecoin/tags) and that is the one on the Chocolatey Community Repository. It's unlikely that it will be updated now.

I'll close this issue.
