### ISSUE TITLE
RFP - antidupl

### ISSUE THREAD

**Issue by Elaborendum** [chocolatey-community/chocolatey-package-requests#1225]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ermig1979/AntiDupl
Direct download URL for the software / installer : https://github.com/ermig1979/AntiDupl/releases/download/v2.3.10/AntiDupl.NET-2.3.10.exe
Software summary / short description: A program to search similar and defect pictures on the disk

**Comment by Xav83** [comment]
Hi @pauby,

Actually, there is already an [existing package for antidupl](https://community.chocolatey.org/packages/antidupl), but it has been updated to the latest version yet. I have sent a message to the maintainer to know if he has planned to update the package, and to see if it is still actively maintained. :slightly_smiling_face:

**Comment by pauby** [comment]
@Xav83 Thanks for that. I'll go ahead and close this issue, as it looks like you're going to follow the normal triage process.
