### ISSUE TITLE
RFM - ntfsinfo

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1250]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/ntfsinfo
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/ntfsinfo/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by tunisiano187** [comment]
I'll update this package.
Thank you

**Comment by tunisiano187** [comment]
Package ready to be pushed : https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/ntfsinfo
Waiting to be added as maintainer.
PR on dtgm's repo : https://github.com/dtgm/chocolatey-packages/pull/639

Have a nice day
