### ISSUE TITLE
RFM - cryptsync

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1253]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/cryptsync
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/cryptsync/

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by tunisiano187** [comment]
Hello, i'll take this package.
Package ready on [my repo](https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/cryptsync)
And i've sent a request to be added via the contact admins form.

Have a nice day.
Thank you
