### ISSUE TITLE
RFM - Source Han Code JP

### ISSUE THREAD

**Issue by katz** [chocolatey-community/chocolatey-package-requests#126]
> Source Han Code JP is a derivative of Source Han Sans OpenType fonts that replaces its proportional Latin glyphs with fixed-width 667-unit glyphs from Source Code Pro. The Latin glyphs are scaled to match the glyphs for Japanese kana and kanji, and their widths are adjusted to be exactly 667 units (two-thirds of an EM). Source Han Code JP is intended to be used as a UI font for mixed Latin and Japanese text on displays, for programming, editing HTML/CSS, viewing text or inputing to the command line in a terminal app, and so on.
> 
> Source Han Code JP is based on the Japanese subset of Source Han Sans, Source Han Sans JP, whose glyph set supports only Japanese.

The fonts are distributed from https://github.com/adobe-fonts/source-han-code-jp

Chocolatey package is subumitted as https://chocolatey.org/packages/source-han-code-jp , and waiting review.

**Comment by AdmiringWorm** [comment]
@katz you've still not fixed the requested changes for this package, if they're not fixed within the next 14 days the package will be automatically rejected.

**Comment by AdmiringWorm** [comment]
As nothing have happened to the submitted package, and no reply have been given here on github.
This request is changed to a RFM, and opened to be picked up by someone else.

**Comment by chtof** [comment]
**Status: In Progress - Waiting to be added as maintainer to pusblished [the updated version](https://github.com/chtof/chocolatey-packages/tree/master/automatic/source-han-code-jp)** (request sent to contact site admins)

**Comment by chtof** [comment]
**Status: Review** (https://chocolatey.org/packages/source-han-code-jp)

**Comment by chtof** [comment]
Status: closed
