### ISSUE TITLE
RFM - cmdermini

### ISSUE THREAD

**Issue by NomsterDude** [chocolatey-community/chocolatey-package-requests#1261]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/cmdermini
Package source URL: https://github.com/admiringworm/chocolatey-packages/tree/master/automatic/cmdermini

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Contacted via Email

**Comment by AdmiringWorm** [comment]
I am the maintainer of this package, and I have not been contacted regarding it.
Nor is this package outdated, please refrain from opening false RFM requests.
