### ISSUE TITLE
RFM - popcorntime

### ISSUE THREAD

**Issue by Hitmanforrent** [chocolatey-community/chocolatey-package-requests#1269]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/popcorntime
Package source URL: https://github.com/popcorn-official/popcorn-desktop

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-10
How the maintainer was contacted: Email

**Comment by pauby** [comment]
@tunisiano187 this is one of your packages. Just want top reach out here to confirm you didn't miss the contact email?

**Comment by tunisiano187** [comment]
Thank you pauby, I didn't receive the mail, but i'll take a look to update it.

**Comment by tunisiano187** [comment]
@pauby or @Hitmanforrent you can close the issue.
Sorry for the update delay
