### ISSUE TITLE
RFM - Myrica

### ISSUE THREAD

**Issue by katz** [chocolatey-community/chocolatey-package-requests#127]
> Myrica is a free TrueType fonts for programming.

The fonts are distributed from https://github.com/tomokuni/Myrica

Chocolatey package is subumitted as https://chocolatey.org/packages/myrica , and waiting review.

**Comment by AdmiringWorm** [comment]
@katz you've still not fixed the requested changes for this package, if they're not fixed within the next 14 days the package will be automatically rejected.

**Comment by AdmiringWorm** [comment]
As nothing have happened to the submitted package, and no reply have been given here on github.
This request is changed to a RFM, and opened to be picked up by someone else.

**Comment by chtof** [comment]
**Status: Waiting to be added as maintainer** (Request sent to contact site admins)

(Package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/myrica)

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/myrica/2.006.20150301.20190415

**Comment by chtof** [comment]
Status: closed
