### ISSUE TITLE
RFM - files

### ISSUE THREAD

**Issue by Starz0r** [chocolatey-community/chocolatey-package-requests#1270]
## Current Maintainer
- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/files
Package source URL: https://github.com/Starz0r/ChocolateyPackagingScripts

**Comment by w0** [comment]
@TheCakeIsNaOH ill take it over

**Comment by TheCakeIsNaOH** [comment]
@w0 you should have a confirmation email.

**Comment by pauby** [comment]
It looks like this package has already been picked up by `wizard`?

**Comment by TheCakeIsNaOH** [comment]
@pauby `wizard` is @w0

**Comment by w0** [comment]
What is the maximum package size for the community repo? This just over 300mb

`Chocolatey v0.12.1 Attempting to push files.2.1.13.nupkg to https://push.chocolatey.org Failed to process request. 'Request Entity Too Large'.  The remote server returned an error: (413) Request Entity Too Large..`

**Comment by TheCakeIsNaOH** [comment]
Yup there is. 200mb is the max, unfortunately.
https://github.com/chocolatey/home/issues/59

**Comment by w0** [comment]
Updated version submitted

**Comment by AndrewIsBest69** [comment]
Yes of course I understand that, sorry I just wanted more detailed information regarding this package. And you have to admit that 5 months is a pretty old version.

**Comment by w0** [comment]
It was without a maintainer for that time. I just submitted the newer version about a week ago. Once it gets reviewed it will be available. If you see packages that are out of date you can always request the maintainer update them; or take over maintenance

**Comment by pauby** [comment]
@AndrewIsBest69 I just wanted to take a minute to remind you (and anybody else reading this) that the packages provided / maintained for free (by @wo and others) are all provided free of charge and maintained in their spare time. Nobody is being paid for this work. So you're using a free tool that is managing packages provided for free by people who do it for free in their spare time for the good of the community.

If you find a package that is outdated, the best thing you can do is to join the community of maintainers and help out by maintaining that package. That benefits everybody.

**Comment by TheCakeIsNaOH** [comment]
Whoop, this has been approved for a while. Thanks for taking over this package @w0
