### ISSUE TITLE
RFM - aaclr

### ISSUE THREAD

**Issue by FoxInTheClouds** [chocolatey-community/chocolatey-package-requests#1273]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/aaclr
Package source URL: https://github.com/dtgm/chocolatey-packages

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Email

**Comment by kamack38** [comment]
This software doesn't seem to be maintained...

**Comment by tunisiano187** [comment]
@pauby ,Hello, this package is from dtgm, but the latest release matches with the published one... Is this still relevant?
the package may be updated to current chocolatey version, but that's all ...

Thank you

**Comment by pauby** [comment]
👍 Ordinarily, it would be good to still have another maintainer for when the software is updated. However, the last update was over 7 years ago, so I think we can agree with @kamack38 and conclude it's been abandoned. 

I think we can go ahead and close this.
