### ISSUE TITLE
RFM - datamash

### ISSUE THREAD

**Issue by FoxInTheClouds** [chocolatey-community/chocolatey-package-requests#1278]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/datamash
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/datamash/1.0.6

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: Email

**Comment by tunisiano187** [comment]
I'll take this package.
As requested the package is now ready on https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/datamash
@pauby Can you assign this to me?
Thank you
[dtgm PR](https://github.com/dtgm/chocolatey-packages/pull/631)

**Comment by tunisiano187** [comment]
Package Pushed

**Comment by TheCakeIsNaOH** [comment]
Approved, thanks for picking up the package @tunisiano187
