### ISSUE TITLE
RFP - achievement-watcher

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1279]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/xan105/Achievement-Watcher
Direct download URL for the software / installer : https://github.com/xan105/Achievement-Watcher/releases/download/1.6.5/Achievement.Watcher.Setup.exe
Software summary / short description: A sexy achievement file parser with real-time notification, automatic screenshot and playtime tracking. View every achievements earned on your PC whether it's coming from Steam, a Steam emulator, and more.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/achievement-watcher) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
