### ISSUE TITLE
RFP - emusak-ui

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1280]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/CapitaineJSparrow/emusak-ui
Direct download URL for the software / installer : https://github.com/CapitaineJSparrow/emusak-ui/releases/download/v1.0.108/emusak-1.0.108.Setup.exe
Software summary / short description:  This is a tool which allows you to download saves or mods for Nintendo Switch emulators using a compatible Emusak backend

**Comment by pauby** [comment]
@soredake I can't find a package for this. Can you confirm what the URL is / what it was called?

**Comment by soredake** [comment]
@pauby this software is discontinued and will stop working soon
![изображение](https://user-images.githubusercontent.com/5204968/191299552-0c0758a4-29d7-4c4a-a1b3-2646f3f5350b.png)
