### ISSUE TITLE
RFP - sophiapp

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1281]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Sophia-Community/SophiApp
Direct download URL for the software / installer :  https://github.com/Sophia-Community/SophiApp/releases/download/1.0.0.0/SophiApp.zip
Software summary / short description:  ⚡ The next chapter of the Sophia Script project. A GUI app for fine-tuning and tweaking Windows 10 & Windows 11 (in the future)

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/sophiapp) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
