### ISSUE TITLE
RFP - asana

### ISSUE THREAD

**Issue by warfuric** [chocolatey-community/chocolatey-package-requests#1282]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://asana.com/download
Direct download URL for the software / installer : https://desktop-downloads.asana.com/win32_x64/prod/latest/AsanaSetup.exe
Software summary / short description: Only project management software. This is the windows 64bit client.
A 32bit option is available here: 32-bit Download: https://desktop-downloads.asana.com/win32_ia32/prod/latest/AsanaSetup.exe 

On installation, Asana will open and add itself to the Desktop via shortcut and the start menu. Opening on installation isn't ideal, I would prefer if this was a silent install, if possible.

**Comment by warfuric** [comment]
Updated OP with checklist.

**Comment by mikeee** [comment]
Submitted a package which is maintained automatically 👍
