### ISSUE TITLE
RFP - ksnip

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1283]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/ksnip/ksnip
Direct download URL for the software / installer : https://github.com/ksnip/ksnip/releases/download/v1.9.2/ksnip-1.9.2.msi
Software summary / short description:
Screenshot app with annotator

**Comment by TakataSanshiro** [comment]
I just submitted the packages.
https://community.chocolatey.org/packages/ksnip
https://community.chocolatey.org/packages/ksnip.install
https://community.chocolatey.org/packages/ksnip.portable

**Comment by TheCakeIsNaOH** [comment]
@TakataSanshiro it looks like the verifier is failing because the package would require a dependency on the `chocolatey-core.extension`.

**Comment by TakataSanshiro** [comment]
I added the dependency and ready for review.

**Comment by TakataSanshiro** [comment]
Package has been approved.

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the packages @TakataSanshiro
