### ISSUE TITLE
RFP - ivpn

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1284]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.ivpn.net/apps-windows/
Direct download URL for the software / installer : https://repo.ivpn.net/windows/bin/IVPN-Client-v3.5.2.exe
Software summary / short description:
Cheap and reliable VPN client

**Comment by pauby** [comment]
@dtantono The package suggested in the comment above is the same one you are requesting. However, it looks like the package has no published versions. Can you follow the [triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) and if no response raise an RFM request?
