### ISSUE TITLE
RFP - downzemall!

### ISSUE THREAD

**Issue by Hitmanforrent** [chocolatey-community/chocolatey-package-requests#1287]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://setvisible.github.io/DownZemAll/
Direct download URL for the software / installer : https://github.com/setvisible/DownZemAll/releases/download/v2.5.5/DownZemAll_x64_Setup.exe
Software summary / short description: A download manager that's a successor to the legacy DownThemAll!

Probably start menu shortcuts.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/downzemall) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
