### ISSUE TITLE
RFP - superf4

### ISSUE THREAD

**Issue by Hitmanforrent** [chocolatey-community/chocolatey-package-requests#1288]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://stefansundin.github.io/superf4/
Direct download URL for the software / installer : https://github.com/stefansundin/superf4/releases/download/v1.4/SuperF4-1.4.exe
Software summary / short description:
A really nice little taskbar process that kills the focused task when pressing Ctrl+Alt+F4.

**Comment by Xav83** [comment]
Hi @pauby, :slightly_smiling_face: 

I want to pick up this package, but I found out that somebody has already tried to create one for this software [here](https://community.chocolatey.org/packages/superf4), and it seems to be broken.
I don't really know what to do in that case. Should I try to contact the owner/maintainer of this package ? Or should I create one and publish it (if this is even possible as one already exists) ? Or maybe some other solution I didn't think about ?

Thenk you in advance for your answer and your great work :slightly_smiling_face:

**Comment by pauby** [comment]
@Xav83 Have a read of the [package triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) which outlines what needs to be done to pick up the package.

**Comment by Xav83** [comment]
Thank you @pauby , this is a great resource ! I'll check it out ! :slightly_smiling_face:

**Comment by Xav83** [comment]
Since I am now officially a maintainer of the package, I pick up this package request :slightly_smiling_face:

I actually already have uploaded a [Chocolatey package](https://community.chocolatey.org/packages/monitorian) which is currently waiting for the review of Moderators :wink:

**Comment by pauby** [comment]
@Xav83 I think you gave the wrong link - should be https://community.chocolatey.org/packages/superf4

**Comment by Xav83** [comment]
Oops, indeed, I failed the copy-paste of the link :laughing:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/superf4) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:

**Comment by stefansundin** [comment]
Nice work @Xav83 👍 

I just have one question, isn't the Copyright section supposed to have my name?

<img width="396" alt="Screenshot 2022-10-31 at 10 25 28" src="https://user-images.githubusercontent.com/1991151/199070853-21a3a6a4-a1d1-4724-9eca-1f642308373a.png">

SuperF4 is licensed under GPLv3 but is not authored by FSF. :)

I see that some other packages don't have a Copyright section at all and that would be fine too.

I'll have to give Chocolatey a try some day. I have not used it personally. But I'm cool with the community creating packages for my programs. 👍

**Comment by Xav83** [comment]
Hi @steviecoaster,

I have re-used the Copyright mention from the [LICENCE file](https://github.com/stefansundin/superf4/blob/master/LICENSE) of the SuperF4 repository.

If you want I can change it to include your name, something like `Copyright (C) Stefan Sundin`, for example (feel free to tell me exactly what you want me to specify as the copyright mention :wink:).

**Comment by stefansundin** [comment]
> Hi steviecoaster,

Sorry steviecoaster, if you see this, Xav83 mentioned you by mistake.

> I have re-used the Copyright mention from the [LICENSE file](https://github.com/stefansundin/superf4/blob/master/LICENSE) of the SuperF4 repository.

That's the copyright for the license itself, not for the program.

> If you want I can change it to include your name, something like `Copyright (C) Stefan Sundin`, for example (feel free to tell me exactly what you want me to specify as the copyright mention 😉).

Awesome, changing it to `Copyright (C) Stefan Sundin` sounds great! I'm also Ok with removing the Copyright statement (I noticed not all packages have it). I don't feel like it necessarily have to be everywhere.

Thank you!

**Comment by Xav83** [comment]
> Sorry steviecoaster, if you see this, Xav83 mentioned you by mistake.

Oops sorry steviecoaster :pray: 

> That's the copyright for the license itself, not for the program.

Oohh I see ! I'll change it in the package source in a few days, when I will be in front of my computer :wink: 

Thank you @stefansundin (I've got you pseudo right this time :laughing:) for helping me making the package information more accurate. If in the future, you have any other element to improve the superf4 (or any package that I maintain), you can create issues directly on my [personal Chocolatey pakages repository](https://github.com/Xav83/chocolatey-packages/tree/develop/automatic/superf4) :slightly_smiling_face:

**Comment by Windos** [comment]
Thanks for picking this up @Xav83!
