### ISSUE TITLE
RFP - dbgate

### ISSUE THREAD

**Issue by janproch** [chocolatey-community/chocolatey-package-requests#1290]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://dbgate.org
Direct download URL for the software / installer : https://github.com/dbgate/dbgate/releases/download/v4.7.1/dbgate-4.7.1-win_x64.exe
Software summary / short description: Database manager for MySQL, PostgreSQL, SQL Server, MongoDB, SQLite and others

**Comment by dgalbraith** [comment]
Packages have been pushed and are ready for review - [dbgate](https://community.chocolatey.org/packages/dbgate/4.7.1), [dbgate.install](https://community.chocolatey.org/packages/dbgate.install/4.7.1) and [dbgate.portable](https://community.chocolatey.org/packages/dbgate.portable/4.7.1).

**Comment by dgalbraith** [comment]
Initial packages have been reviewed and are now available in the community repository.

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the packages @dgalbraith
