### ISSUE TITLE
RFP - super-productivity

### ISSUE THREAD

**Issue by Elaborendum** [chocolatey-community/chocolatey-package-requests#1293]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/johannesjo/super-productivity
Direct download URL for the software / installer : https://github.com/johannesjo/super-productivity/releases/download/v7.10.1/superProductivity-7.10.1.exe
Software summary / short description: Super Productivity is an advanced todo list app with integrated Timeboxing and time tracking capabilities. It also comes with integrations for Jira, Gitlab, GitHub and Open Project.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/super-productivity) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
