### ISSUE TITLE
RFP - camotics

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#1295]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://camotics.org/
Direct download URL for the software / installer : https://camotics.org/builds/release/windows-10-64bit/camotics_1.2.0_AMD64.exe
Software summary / short description: With CAMotics, you can simulate 3-axis [GCode](https://camotics.org/gcode.html) programs for [CNC](http://en.wikipedia.org/wiki/CNC)s and visualize the results in 3D.

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/camotics

**Comment by luzpaz** [comment]
Any maintainers interested?

**Comment by TheCakeIsNaOH** [comment]
Package was approved: https://community.chocolatey.org/packages/camotics
