### ISSUE TITLE
RFP - nanoleaf-desktop-app

### ISSUE THREAD

**Issue by TheNavyBear** [chocolatey-community/chocolatey-package-requests#1299]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://nanoleaf.me/en-US/integration-hub/desktop-app/
Direct download URL for the software / installer : https://my.nanoleaf.me/api/v2/desktopApp/latest/win
Software summary / short description: With the Nanoleaf Desktop App, you can control your Lines, Shapes, Essentials*, Elements, Canvas or Light Panels from your computer (Windows or Mac). Create and download new Scenes, set Schedules and use your other favorite features right from your computer. The Desktop App was designed to simplify the management of larger installations and offer control of many different layouts at once.

*Essentials require Thread Border Router (like Nanoleaf panels or Apple HomePod mini) to work with the Desktop App. [Learn more.](https://nanoleaf.me/en-US/integration-hub/thread/)

**Comment by mikeee** [comment]
Happy to pick this package up

**Comment by mikeee** [comment]
Package pushed, awaiting review.

**Comment by mikeee** [comment]
https://community.chocolatey.org/packages/nanoleaf#versionhistory
Package functional/complete.

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @mikeee
