### ISSUE TITLE
RFP - android-messages-desktop

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1300]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/OrangeDrangon/android-messages-desktop
Direct download URL for the software / installer : https://github.com/OrangeDrangon/android-messages-desktop/releases/download/v5.3.1/AndroidMessages-v5.3.1-win-x64.exe
Software summary / short description:
This app is for sync messages between Android and Windows PC

**Comment by dtantono** [comment]
The one that shows in the chocolatey bot it seems abandoned project and this one is newest project

**Comment by pauby** [comment]
As it's the same software (just a fork of the original) it could be published under the same the package name. And in that case this would need to be an RFM request.
