### ISSUE TITLE
RFM - android-messages-desktop

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1301]
I DON'T Want To Become The Maintainer
- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;;
Checklist
- [x] Issue title starts with 'RFM - '
Existing Package Details
Package URL: https://chocolatey.org/packages/android-messages-desktop
Package source URL: https://github.com/OrangeDrangon/android-messages-desktop/releases/download/v5.3.1/AndroidMessages-v5.3.1-win-x64.exe

Date the maintainer was contacted (in YYYY-MM-DD): 2022-02-01
How the maintainer was contacted: Email

**Comment by pauby** [comment]
@dtantono I close this issue [over here](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1300) about this but the date on this issue, for when you contacted the maintainer, is 1 Feb?

**Comment by dtantono** [comment]
I checked my Inbox and I remembered that emailed the maintainer in the past. But, no response from the maintainer since then.

**Comment by tunisiano187** [comment]
Hello,
i've prepared this package on my automated repository.
so i'll take it.
@pauby can you add me as maintainer and assign me this issue?
Thank you.

**Comment by tunisiano187** [comment]
@dtantono, the package as been pushed, so it will be vailable soon.

Have a nice day

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for picking it up @tunisiano187
