### ISSUE TITLE
RFM - ivpn

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1302]
I DON'T Want To Become The Maintainer
- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;;
Checklist
- [x] Issue title starts with 'RFM - '
Existing Package Details
Package URL: https://chocolatey.org/packages/ivpn
Package source URL: https://repo.ivpn.net/windows/bin/IVPN-Client-v3.5.2.exe

Date the maintainer was contacted (in YYYY-MM-DD): 2022-02-01
How the maintainer was contacted: Email

**Comment by tunisiano187** [comment]
Hello,
I'll take this package.
Can you assign me the issue?
I'll request the maintainership on the choco page

**Comment by tunisiano187** [comment]
Thanks, it will be pushed the next run

**Comment by tunisiano187** [comment]
Pushed

**Comment by pauby** [comment]
This is now approved. Thanks @tunisiano187
