### ISSUE TITLE
RFP - desktop-restore

### ISSUE THREAD

**Issue by Germs2004** [chocolatey-community/chocolatey-package-requests#1303]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://www.midiox.com/index.htm?http://www.midiox.com/desktoprestore.htm
Direct download URL for the software / installer : http://www.midiox.com/zip/DesktopRestoreInstall.exe
Software summary / short description:

Name: Desktop Restore
Author: Midi-Ox

This is a very simple program that saves the positions of your desktop icons and allows you to easily restore the saved positions.

**Comment by teknowledgist** [comment]
I will pick this up.

**Comment by teknowledgist** [comment]
This has been submitted.  https://community.chocolatey.org/packages/desktop-restore

**Comment by Germs2004** [comment]
Thank you, @teknowledgist!  The world is now a better place :)

**Comment by TheCakeIsNaOH** [comment]
Package approved a while ago, thanks for creating the package @teknowledgist
