### ISSUE TITLE
RFP - embrava-connect

### ISSUE THREAD

**Issue by TheNavyBear** [chocolatey-community/chocolatey-package-requests#1305]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://embrava.com/pages/software
Direct download URL for the software / installer : https://embrava.github.io/embrava/EmbravaConnectForWindows/EmbravaConnect_v5.2.69.zip
Software summary / short description:  Embrava Connect can tell your colleagues when you are on a call or a deadline so that they know when they can talk to you and expect a response.
(This software is required to use the Blynclight cubical presence indicators)

**Comment by pauby** [comment]
I know the bit.ly link is on the software download page, but we're not going to be able to accept it for the Chocolatey Community Repository.

Is there a permanent, not bit.ly link that can be used?

**Comment by TheNavyBear** [comment]
The bit.ly link converts to: https://embrava.github.io/embrava/EmbravaConnectForWindows/EmbravaConnect_v5.2.69.zip
This link obviously changes with each new version, which is why I think they used bit.ly, so they have one link that works across multiple versions.

**Comment by TheNavyBear** [comment]
That appears to be the case. That link (with version number changed) should work as well.

**Comment by pauby** [comment]
Can you go ahead and update your original message with the link that can be used?

**Comment by TheNavyBear** [comment]
> Can you go ahead and update your original message with the link that can be used?

Updated. Sorry for the delay, GitHub was failing to notify me for this post...

**Comment by pauby** [comment]
Why was this closed @TheNavyBear ?
