### ISSUE TITLE
RFP - skype-insider

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1306]
Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.skype.com/en/insider/
Direct download URL for the software / installer : https://download.skype.com/s4l/download/win/Skype-8.83.76.406.exe
Software summary / short description:
Beta version of Skype

**Comment by AdmiringWorm** [comment]
This sounds like it would be better to be provided inside the same skype package or at the very least the same maintainers of the package (if it can't be in the same package).

Could you instead open an issue/discussion over at https://github.com/chocolatey-community/chocolatey-packages/issues/new/choose where the `skype` package is maintained?

I'll be closing this issue in the meantime, but can always be re-opened if it is decided to not want to be handled by the same maintainers.
