### ISSUE TITLE
RFP - hakunekonightly

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1307]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/manga-download/hakuneko
Direct download URL for the software / installer : https://github.com/manga-download/hakuneko/releases/download/nightly-20200705.1/hakuneko-desktop_8.3.4_windows-setup_amd64.exe
Software summary / short description:
HakuNeko is a cross-platform downloader for manga and anime from various websites. HakuNeko does not host anything by itself.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/hakunekonightly) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
