### ISSUE TITLE
RFP - unofficial-Google-Chat-Electron 

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1309]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/ankurk91/google-chat-electron
Direct download URL for the software / installer : https://github.com/ankurk91/google-chat-electron/releases/download/2.15.1/google-chat-electron-setup-win-x64-2.15.1.exe
Software summary / short description:
Google chat client wrapped in electron

**Comment by pauby** [comment]
The title of whatever package is created should reflect that is unofficial. My concern is that if there is an official google chat package created in future, it will clash.

**Comment by dtantono** [comment]
title changed

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/unofficial-Google-Chat-Electron) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
