### ISSUE TITLE
RFM - AtmelStudio

### ISSUE THREAD

**Issue by stefan-muc** [chocolatey-community/chocolatey-package-requests#131]
About the software:
> Studio 7 is the integrated development platform (IDP) for developing and debugging all AVR® and SAM microcontroller applications. The Atmel Studio 7 IDP gives you a seamless and easy-to-use environment to write, build and debug your applications written in C/C++ or assembly code. ([Source](http://www.microchip.com/development-tools/atmel-studio-7))

It's quite common IDE for developing software for Atmel microcontrollers

Download links for older versions:
https://www.mikrocontroller.net/articles/Atmel_Studio#Direktlinks_Installer
Current version:
http://www.microchip.com/development-tools/atmel-studio-7#Tabs

**Comment by pauby** [comment]
@AdmiringWorm I can't seem to find that package - have you got a URL?

**Comment by AdmiringWorm** [comment]
@pauby https://chocolatey.org/packages/atmel-studio

**Comment by pauby** [comment]
@AdmiringWorm ... I tried everything but the dash in the middle. Sods law....

**Comment by AdmiringWorm** [comment]
hehe, it's always the one you don't try.

BTW, I've started slowly looking into creating a package for this one (so far looks like it would require a exemption from automated testing though 😢)

**Comment by pauby** [comment]
Awesome. That's another one off the list. I was going to come here and say that the gist from the last rejection will have been purged by now so whoever takes it on will need to start from scratch... but you're doing that anyway!

**Comment by AdmiringWorm** [comment]
yup, I am. Almost regret it already though.

Just installed the program in a VM (through a temp package) to figure out the dependencies, and got quite the surprise.

I'm always amazed when a program have more dependencies installed than Visual Studio, which this one do.

**Comment by pauby** [comment]
What in earth does it need?!?!

**Comment by AdmiringWorm** [comment]
well, so far from what it installed itself, pretty much all of the .NET frameworks between 3.5 and 4.6, vcredist from 2010 to 2015 (maybe even 2017), Microsoft Build tools 14.0 and a few more that I have no idea what they are.

**Comment by AdmiringWorm** [comment]
This includes default runtimes, additional runtimes, debug runtimes, SDK's, etc.

**Comment by pauby** [comment]
Wow. That's quite a catalogue of, what would appear to be, unnecessary software! Maybe the authors are not really sure themselves to installing everything is the solution?

**Comment by AdmiringWorm** [comment]
I would think so yes.

Also found a few KB's it needs, that doesn't yet exist on chocolatey.
So in the meantime, I'm putting the work on this package on hold until I've gotten around to creating them.

So far the list of KB's that it needs (and doesn't exist) is:
- [ ] [KB2978092](https://support.microsoft.com/help/2978092)
- [ ] [KB2975719](https://support.microsoft.com/help/2975719)
- [ ] [KB2975331](https://support.microsoft.com/help/2975331)

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/atmel-studio

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/atmel-studio

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/atmel-studio

Can be closed.
