### ISSUE TITLE
RFP - unofficial-google-meet

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1311]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/arjun-g/google-meet-desktop/releases
Direct download URL for the software / installer : https://github.com/arjun-g/google-meet-desktop/releases/download/v1.2.0/Google.Meet.Setup.1.2.0.exe
Software summary / short description:
Google meet client wrapped in electron

**Comment by pauby** [comment]
The title of whatever package is created should reflect that is unofficial. My concern is that if there is an official google-meet package created in future, it will clash.

**Comment by dtantono** [comment]
title changed

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/unofficial-google-meet) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
