### ISSUE TITLE
RFP - unofficial-google-docs-client

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1312]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/Comp-Labs/Google-Docs/releases/tag/v2022.3.10
Direct download URL for the software / installer : https://github.com/Comp-Labs/Google-Docs/releases/download/v2022.3.10/Google-Docs.exe
Software summary / short description:
This is an unofficial Google Docs/Sheets/Slides client

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/unofficial-google-docs-client) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This package has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
