### ISSUE TITLE
RFP - twemoji

### ISSUE THREAD

**Issue by karolzlot** [chocolatey-community/chocolatey-package-requests#1314]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/eosrei/twemoji-color-font#install-on-windows
Direct download URL for the software / installer : https://github.com/eosrei/twemoji-color-font/releases/download/v13.1.0/TwitterColorEmoji-SVGinOT-Win-13.1.0.zip
Software summary / short description: Twitter Unicode emoji color OpenType-SVG font

-------

This package is pretty useful because I think it fixes this issue: https://answers.microsoft.com/en-us/windows/forum/windows_10-networking/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05

(I would prefer the choco package to install it by default in a way which fixes this issue)

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/twemoji) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
