### ISSUE TITLE
RFP - steam-rom-manager

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1315]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/SteamGridDB/steam-rom-manager
Direct download URL for the software / installer : https://github.com/SteamGridDB/steam-rom-manager/releases/download/v2.3.37/Steam-ROM-Manager-Setup-2.3.37.exe
Software summary / short description: An app for managing ROMs in Steam

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/steam-rom-manager) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
