### ISSUE TITLE
RFP - aemulusmodmanager

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1316]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/TekkaGB/AemulusModManager
Direct download URL for the software / installer : https://github.com/TekkaGB/AemulusModManager/releases/download/5.6.0/AemulusPackageManagerv5.6.0.7z
Software summary / short description: Aemulus Package Manager P3F PS2/P4G PC/P5 PS3/P5S PC

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/aemulusmodmanager) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
