### ISSUE TITLE
RFP - steamlink

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1317]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://steamcommunity.com/app/353380/discussions/8/3105764348181505385
Direct download URL for the software / installer : https://media.steampowered.com/steamlink/windows/latest/SteamLink.zip
Software summary / short description: Steam Link for Windows 10

**Comment by pauby** [comment]
I will pick this up.

**Comment by pauby** [comment]
Package created and [pushed](https://community.chocolatey.org/packages/steamlink).

**Comment by soredake** [comment]
Thank you!
