### ISSUE TITLE
RFP - surfshark

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1319]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://surfshark.com/download/windows
Direct download URL for the software / installer : https://downloads.surfshark.com/windows/latest/SurfsharkSetup.exe
Software summary / short description:
affordable vpn client

**Comment by pauby** [comment]
No response. Closing this assuming the request is not needed.
