### ISSUE TITLE
RFP - rustdesk

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1322]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://rustdesk.com/
Direct download URL for the software / installer : https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-windows_x64.zip
Software summary / short description:
open source solution of teamviewer

**Comment by Xav83** [comment]
Hi  @dtantono @pauby, 

I took a look at this issue, and the [following Chocolatey package](https://community.chocolatey.org/packages/rustdesk), maintained by @bdukes, is available and seems up to date with the [releases of rustdesk](https://github.com/rustdesk/rustdesk/releases). :slightly_smiling_face:

**Comment by dtantono** [comment]
that means somebody already submitted the package without being noticed by the automated system. I will close this.
