### ISSUE TITLE
RFP - keepassxc-legacy

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#1323]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/keepassxreboot/keepassxc/releases
Direct download URL for the software / installer : https://github.com/keepassxreboot/keepassxc/releases/download/2.7.1/KeePassXC-2.7.1-Win64-LegacyWindows.msi
Software summary / short description: The latest versions of KeePassXC have stopped working on legacy Windows versions, like Windows 7 and 8.1. The developers graciously release a separate legacy version of the Windows installer.

This Chocolatey package should exist side-by-side the keepassxc package. Maybe with an explicit note in the description that it is the one to be installed on Windows 8.1 and below.

The relevant GH issue for context: https://github.com/keepassxreboot/keepassxc/issues/7564

## Package Expectations
It should behave the same way as the keepassxc package.

**Comment by opusforlife2** [comment]
Maybe the maintainer of the keepassxc package would like to look at this, since the difference is basically one URL?

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/keepassxc-legacy) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This package has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:

**Comment by opusforlife2** [comment]
Awesome. Thanks, @Xav83!
