### ISSUE TITLE
RFP - steascree

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1324]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://github.com/awthwathje/SteaScree
Direct download URL for the software / installer : https://steascree.download/steascree-1.5.4-windows.exe
Software summary / short description:  SteaScree: Steam Cloud Screenshot Uploader

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/steascree
https://community.chocolatey.org/packages/steascree.install
https://community.chocolatey.org/packages/steascree.portable

**Comment by TheCakeIsNaOH** [comment]
Packages approved, thanks for creating the packages @chtof
