### ISSUE TITLE
RFP - steamachievementmanager

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1325]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/gibbed/SteamAchievementManager
Direct download URL for the software / installer : https://github.com/gibbed/SteamAchievementManager/releases/download/7.0.25/SteamAchievementManager-7.0.25.zip
Software summary / short description:  A manager for game achievements in Steam.

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/steamachievementmanager

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @chtof
