### ISSUE TITLE
RFP - cheat-engine

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1326]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/cheat-engine/cheat-engine
Direct download URL for the software / installer : https://github.com/cheat-engine/cheat-engine/releases/download/7.4/CheatEngine74.exe
Software summary / short description: Cheat Engine is a development environment focused on modding games and applications for personal use.

**Comment by pauby** [comment]
This is the same package as already exists called `cheat-engine` (links to the same GitHub repo). Closing.
