### ISSUE TITLE
RFP - bluebubbles

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1327]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/BlueBubblesApp/bluebubbles-app/releases/tag/v1.8.0%2B27
Direct download URL for the software / installer : https://github.com/BlueBubblesApp/bluebubbles-app/releases/download/v1.8.0%2B27/bluebubbles_installer.exe
Software summary / short description:
unofficial client for Imessage

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @chtof
