### ISSUE TITLE
RFP - comictagger

### ISSUE THREAD

**Issue by killo3967** [chocolatey-community/chocolatey-package-requests#1332]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/comictagger/comictagger
Direct download URL for the software / installer : https://github.com/comictagger/comictagger/releases/download/1.4.3/ComicTagger-1.4.3-win-AMD64.exe.zip
Software summary / short description: ComicTagger is a app for writing metadata to digital comics with scrapping options from ComicVine Web

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/comictagger) which, for now, allow you to install the latest version of `comictagger`, which is a beta version :wink:

**Comment by pauby** [comment]
@Xav83 The package has failed validation.

**Comment by Xav83** [comment]
Oops... I forgot to publish the fixed version :sweat_smile: 
The list of tags was separated using commas instead of spaces. I fixed it in my source code but forgot to push the package again.
I will correct it in the evening :wink:

**Comment by Xav83** [comment]
For information, everything has been fixed on the [new version](https://community.chocolatey.org/packages/comictagger/1.4.4) (`1.4.4`) of the package, which is now waiting for the moderators' review :slightly_smiling_face:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
