### ISSUE TITLE
RFP - send-to-kindle

### ISSUE THREAD

**Issue by TheNavyBear** [chocolatey-community/chocolatey-package-requests#1333]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

This was a package on the community repo, but it is gone when searching the repo, and I don't see an open request for it on GitHub. If a RFP is not the right one, let me know and I will do a RFM. Thank you.

Software project URL : https://www.amazon.com/gp/sendtokindle/pc/
Direct download URL for the software / installer : https://s3.amazonaws.com/sendtokindle/SendToKindleForPC-installer.exe
Software summary / short description: When you download and install Send to Kindle for PC, Kindle will appear when you right click on a file in Windows Explorer and select "Send to". To send multiple documents to Kindle without opening them, simply select documents and choose Kindle from the right-click sub-menu in Windows Explorer.

You can read personal documents from any Kindle device or using the free reading app on your iOS or Android device. Whispersync of notes, highlights, bookmarks and last page read is available on your personal documents that have been converted into Kindle format.

**Comment by pauby** [comment]
@TheNavyBear Is it [this package](https://community.chocolatey.org/packages/sendtokindle)?

**Comment by TheNavyBear** [comment]
Yes it is. I swear I repeatedly searched the repo last night using both the Chocolatey GUI search and the web search, and it wasn't showing up at all. I will try again on my system this evening, and hope it shows up this time.

**Comment by TheNavyBear** [comment]
@pauby I am not sure if there is a bug with the repo search, or if I have some weird issue on my end, but as shown below, when I search for this package even now (2022-06-02 at 1900PDT) it does not show up for me. It also doesn't show in the Chocolatey GUI (as seen below as well).

![Screenshot 2022-06-02 191400](https://user-images.githubusercontent.com/20147831/171773527-a99025c4-8a59-409c-81b7-dcbc797fad64.png)

![Screenshot 2022-06-02 190930](https://user-images.githubusercontent.com/20147831/171773211-3068298f-1630-40bb-b3ec-1f8b44d61d5d.png)

**Comment by TheNavyBear** [comment]
Awesome, as long as y'all are aware of the issue I will deal with it while it is fixed. I know this wasn't the thread for this issue but wasn't really sure where it should go. Since it is something y'all are aware of, I see no reason to push it further or open new tickets for it (unless you would like me to, then just point me to where I need to post it, please). Thank you for the information.

**Comment by pauby** [comment]
@TheNavyBear I found this [issue](https://github.com/chocolatey/home/issues/8) for it and pinned it. I did think we had more of those issues.
