### ISSUE TITLE
RFP - messenger

### ISSUE THREAD

**Issue by tibbing** [chocolatey-community/chocolatey-package-requests#1334]
## Checklist
 
* [x]  The package I am requesting does not already exist on https://chocolatey.org/packages;
* [x]  There is no open issue for this package;
* [x] The issue title starts with 'RFP - ';
* [x]  The download URL is public and not locked behind a paywall / login;
 
## Package Details
Software project URL: https://www.messenger.com/desktop/
Direct download URL for the software / installer: https://scontent-sjc3-1.xx.fbcdn.net/v/t39.2270-6/10000000_69120310267733160_2008923837914728295_n.exe/Messenger.151.0.0.5.114.exe?_nc_cat=103&ccb=1-7&_nc_sid=435822&_nc_ohc=9vq5Hwyh5jUAX9N9naR&_nc_ht=scontent-sjc3-1.xx&oh=00_AT-yRWgwB4rjUExYHL7BKYcq_0KXIEjMNGWCunGLxpEc-A&oe=62A1A166&dl=1 (dynamic, may change)
Software summary / short description: Facebook messenger for Windows

**Comment by pauby** [comment]
If the download URL is dynamic and may change then this wouldn't be easily managed on the Chocolatey Community Repository.

**Comment by tibbing** [comment]
@pauby Haven't looked very deep into this, but seems like the download button calls https://www.messenger.com/messenger/desktop/downloadV2/?platform=win to get a temporary download url. Maybe that is something chocolatey could use?

**Comment by pauby** [comment]
Hmmm. Perhaps. I'll open it up to maintainers and somebody can try to get it working.

**Comment by brogers5** [comment]
I'll pick this one up.

**Comment by brogers5** [comment]
Package has just been approved. This issue can now be closed.

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @brogers5
