### ISSUE TITLE
RFP - sidebar-diagnostics

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#1337]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ArcadeRenegade/SidebarDiagnostics
Direct download URL for the software / installer : https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/download/v3.6.2/Setup.msi
Software summary / short description: A simple sidebar for Windows desktop that displays hardware diagnostic information.

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/sidebar-diagnostics
