### ISSUE TITLE
RFP - glossi

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1338]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Alia5/GlosSI
Direct download URL for the software / installer : https://github.com/Alia5/GlosSI/releases/download/0.0.7.0/GlosSI-0.0.7.0.zip
Software summary / short description:  Tool for using Steam-Input controller rebinding at a system level alongside a global overlay

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/glossi).
But, for now, it seems that the file ` GlosSI-0.0.7.0.zip` is flagged as dangerous by too much security vendors (cf. [Virus scan log](https://www.virustotal.com/gui/file/66d7a1e1c239ed77c65055f2ab72597e1e017e22ee4c39704ee8449db428cf3c/detection/f-66d7a1e1c239ed77c65055f2ab72597e1e017e22ee4c39704ee8449db428cf3c-1658795815))

**Comment by Xav83** [comment]
@soredake Do you want me to contact @Alia5, directly in the repository of GloSI, in order to see how to reproduce the issue of the Virus scan ?

**Comment by Alia5** [comment]
Odd.
Just tried myself, pretty much only GlosSIConfig.exe get's flagged. ¯\_(ツ)_/¯
Dunno why. Perhaps it's my shitty shortcuts.vdf parser that has too many hex string in there?

**Comment by Xav83** [comment]
Indeed @Alia5, **VirusTotal** only flag GloSIConfig.exe :thinking: 

![Screenshot from 2022-08-02 08-41-24](https://user-images.githubusercontent.com/6787157/182309165-7646f4f8-2cf6-4673-8bf9-3896e2144943.png)

Maybe one way to have more information about this issue, would be to set up something like the [VirusTotal GitHub Action](https://github.com/marketplace/actions/virustotal-github-action).

**Comment by Alia5** [comment]
I did a lot of changes compared to the last release.
It seems that VirusTotal is now fine with GlosSI again
https://www.virustotal.com/gui/url/871382ac12fd2d51d81497c9634f78c9db72dd0936f0446ce6db48ea62904e96?nocache=1

You can validate this yourself with the latest release
https://github.com/Alia5/GlosSI/releases/tag/0.0.8.0

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/glossi) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
