### ISSUE TITLE
RFM - easyeda

### ISSUE THREAD

**Issue by chemputer** [chocolatey-community/chocolatey-package-requests#1342]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/easyeda
Package source URL: https://github.com/chemputer/choco_easyeda

**Comment by chemputer** [comment]
/confirm your-chocolatey-username

HTBDT

**Comment by chemputer** [comment]
@pauby can you reopen this issue? Apologies for not getting to it until now, my life is kinda crazy right now which is why I want to pass on the package maintainer.

**Comment by w0** [comment]
Ill take this on. @pauby

**Comment by w0** [comment]
@pauby Looks like I am not yet listed as a maintainer. Package will be pushed once I am listed. 

https://gist.github.com/w0/a569e20fa01812b6a86bd6d0c3663614

**Comment by pauby** [comment]
@w0 Did you request to be added as a maintainer?

**Comment by w0** [comment]
Yea in this issue. Do I need to do it from the package page?

**Comment by pauby** [comment]
Ahh. Yes. Go to the package page and click 'Contact Site Admins', request to take over the package and mention this issue.

**Comment by w0** [comment]
package submitted. For some reason the download 404's during verification. I cannot recreate this 

https://community.chocolatey.org/packages/easyeda/6.5.15

**Comment by TheCakeIsNaOH** [comment]
@w0 looks like you are running into this: https://github.com/chocolatey/home/issues/11
I've added an exemption.
