### ISSUE TITLE
RFP - webtorrent

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1343]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://webtorrent.io/
Direct download URL for the software / installer : https://github.com/webtorrent/webtorrent-desktop/releases/download/v0.24.0/WebTorrentSetup-v0.24.0.exe
Software summary / short description:
an encrypted torrent client

**Comment by brogers5** [comment]
I was considering picking this up, but it appears this already exists under the `webtorrent-desktop` package:
https://community.chocolatey.org/packages/webtorrent-desktop

**Comment by dtantono** [comment]
closed
