### ISSUE TITLE
RFP - green-tunnel

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1346]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/SadeghHayeri/GreenTunnel
Direct download URL for the software / installer : https://github.com/SadeghHayeri/GreenTunnel/releases/download/v1.8.3/green-tunnel-windows.zip
Software summary / short description:
GreenTunnel bypasses DPI (Deep Packet Inspection) systems found in many ISPs (Internet Service Providers) which block access to certain websites.

**Comment by brogers5** [comment]
I will pick this one up.

**Comment by brogers5** [comment]
Packages for v1.8.3 have been submitted and are now pending review:

https://community.chocolatey.org/packages/green-tunnel-gui/1.8.3
https://community.chocolatey.org/packages/green-tunnel-cli/1.8.3

**Comment by brogers5** [comment]
CLI package has recently been approved and is now live for public consumption.

GUI package is still awaiting review.

**Comment by TheCakeIsNaOH** [comment]
Both approved, thanks for creating the packages @brogers5
