### ISSUE TITLE
RFP - sharik

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1347]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/marchellodev/sharik
Direct download URL for the software / installer : https://github.com/marchellodev/sharik/releases/download/v3.1/sharik_v3.1_windows.msi
Software summary / short description:
Cross platform file sharing app

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/sharik) which is currently waiting for the review of Moderators :wink:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
