### ISSUE TITLE
RFP - wsldiskshrinker

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1349]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/kxxt/WSLDiskShrinker
Direct download URL for the software / installer : https://github.com/kxxt/WSLDiskShrinker/releases/download/v0.2.2/wsl-disk-shrinker-setup.exe
Software summary / short description:  Reduce WSL disk usage.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/wsldiskshrinker) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/wsldiskshrinker) has been reviewed and approved by @Windos :slightly_smiling_face:

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package, @Xav83
