### ISSUE TITLE
RFP - hidhide

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1352]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ViGEm/HidHide
Direct download URL for the software / installer : https://github.com/ViGEm/HidHide/releases/download/v1.2.98.0/HidHide_1.2.98_x64.exe
Software summary / short description:  Gaming Input Peripherals Device Firewall for Windows.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/hidhide) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/hidhide) has been reviewed and approved by @Windos :slightly_smiling_face:

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package, @Xav83
