### ISSUE TITLE
RFP - visualvm

### ISSUE THREAD

**Issue by mkoertgen** [chocolatey-community/chocolatey-package-requests#1357]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://visualvm.github.io/
Direct download URL for the software / installer : https://github.com/oracle/visualvm/releases (zip only)
Software summary / short description:

**Comment by mkoertgen** [comment]
I will be happy to submit a package, PR somewhere. Could you point me in the right direction on how to best submit a package?

**Comment by mkoertgen** [comment]
Nice bot-action. Yes, in fact that should be the one but it got rejected already in 2019. Maintainer seems to be https://community.chocolatey.org/profiles/pablofomenta

Still, I would be happy to submit a valid package not containing a choco command.

**Comment by pauby** [comment]
@mkoertgen Can you follow the [Package Triage Process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) to pick up this package?

**Comment by mkoertgen** [comment]
Hi @pauby ,

Contact maintainers have chosen not to be contacted by email.
![image](https://user-images.githubusercontent.com/7235760/186436175-edd44d4a-2c60-435c-94cd-2fddd3f59dca.png)

How should I proceeed?

**Comment by mkoertgen** [comment]
Package Source is also outdated: https://github.com/fomenta/scripts/tree/master/Java/visualvm-package (404)
I guess, since the package has already been rejected 2019 there is not much sense in triaging the package, is it?

**Comment by mkoertgen** [comment]
Left a short notice the site admins that I offer to take ownership of the package.

**Comment by pauby** [comment]
@mkoertgen Contacting the Site Admins was the correct next step. Thanks for doing that.

**Comment by mkoertgen** [comment]
Thanks, co-package-owner now.

**Comment by mkoertgen** [comment]
Stubbed here: https://github.com/mkoertgen/chocolatey-packages/tree/main/automatic/visualvm

**Comment by mkoertgen** [comment]
@pauby Getting familiar with the chocolatey package creation process. Probably a good idea to submit it to the community-packages-repo. We will see.
