### ISSUE TITLE
RFM - gsmartcontrol

### ISSUE THREAD

**Issue by unforgettableid** [chocolatey-community/chocolatey-package-requests#1360]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package
- [x] There is no existing open maintainer request for this package

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/gsmartcontrol
Package source URL: https://github.com/search?q=repo%3Adtgm%2Fchocolatey-packages+filename%3Agsmartcontrol

Date the maintainer was contacted: 2022-06-03 (in [another GitHub issue](https://github.com/dtgm/chocolatey-packages/issues/621)), and September '22 (by email).  No reply.
How the maintainer was contacted:  both via GitHub and via private email

The inactive existing maintainer is @dtgm, who appears to have been inactive for years.

Thank you for reading this!

**Comment by tunisiano187** [comment]
Hello, I'll update it

**Comment by TheCakeIsNaOH** [comment]
Added @tunisiano187 as a maintainer.

**Comment by unforgettableid** [comment]
Dear @tunisiano187:  I see you've now published a GSmartControl 1.1.4 package.  Thank you very much!

Closing.
