### ISSUE TITLE
RFP - dell-alienware-update

### ISSUE THREAD

**Issue by ITNEXTGEN** [chocolatey-community/chocolatey-package-requests#1361]
New request for package - Dell Alienware Update

Package Details
Software project URL : https://www.dell.com/support/home/de-de/drivers/DriversDetails?driverId=YX736
Direct download URL for the software / installer: https://dl.dell.com/FOLDER08335051M/2/Dell-Alienware-Update-Windows-Universal-Application_YX736_WIN_4.5.0_A00_01.EXE
Software summary / short description: Dell Alienware Update Software

**Comment by pauby** [comment]
@ITNEXTGEN Can you go back and complete the template? Othwerwise we will need to close this issue.

**Comment by AdmiringWorm** [comment]
Closing as the template was not updated as requested
