### ISSUE TITLE
RFP - authme

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1366]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://authme.levminer.com/#downloads or https://github.com/Levminer/authme
Direct download URL for the software / installer : https://github.com/Levminer/authme/releases/download/3.3.4/authme-3.3.4-windows-x64-installer.exe
Software summary / short description:
an authenticator app

**Comment by dgalbraith** [comment]
I will pick this one up.

**Comment by dgalbraith** [comment]
Packages have been pushed and are now ready for review:

- https://community.chocolatey.org/packages/authme/3.3.4
- https://community.chocolatey.org/packages/authme.install/3.3.4
- https://community.chocolatey.org/packages/authme.portable/3.3.4

**Comment by dgalbraith** [comment]
Packaged have been reviewed and are now available in the Community repository.
