### ISSUE TITLE
RFP - hopsan

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#1368]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://liu.se/en/research/hopsan
Direct download URL for the software / installer : https://github.com/Hopsan/hopsan/releases
Software summary / short description: Hopsan is an open-source multi-domain system simulation tool developed at the division of Fluid and Mechatronic Systems at Linköping University.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/hopsan) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/hopsan) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
