### ISSUE TITLE
RFP - sqlean-sqlite-extensions

### ISSUE THREAD

**Issue by qqii** [chocolatey-community/chocolatey-package-requests#1369]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/nalgeon/sqlean
Direct download URL for the software / installer : https://github.com/nalgeon/sqlean/releases/tag/0.17.1 and https://github.com/nalgeon/sqlean/releases/tag/incubator
Software summary / short description: Various extensions to SQLite that are not build as part of the binary.

Ideally `dll` files would be put into `C:\ProgramData\chocolatey\bin` or something like `C:\ProgramData\chocolatey\bin\sqlite3-ext`.

**Comment by dgalbraith** [comment]
I will pick this up.

Point to note - the extensions are compiled as 64-bit so are not compatible with the existing distributions / packages containing the  sqlite command line shell ([SQLite](https://community.chocolatey.org/packages/SQLite) or [sqlite.shel](https://community.chocolatey.org/packages/sqlite.shell)).

Until the main distribution is updated with a 64-bit version of the [command line shell](https://www.sqlite.org/cli.html) these extensions will need the [unofficial 64-bit version of the command line shell](https://github.com/nalgeon/sqlite) provided by the editor of the extensions package [Anton Zhiyanov](https://github.com/nalgeon)

Any thoughts on this being bundled with the extensions or packaged separately with the extensions having a dependency?

**Comment by pauby** [comment]
@dgalbraith this doesn't look to have been submitted yet?

**Comment by dgalbraith** [comment]
A few packages have been pushed covering this request:
- [sqlean](https://community.chocolatey.org/packages/sqlean/0.21.8) - the sqlean extensions
- [sqlean-shell](https://community.chocolatey.org/packages/sqlean-shell/3.43.0) - a custom sqlite shell with the sqlean extensions embedded
- [sqlite-shell-x64](https://community.chocolatey.org/packages/sqlite-shell-x64/3.43.0) - a 64-bit sqlite shell build for the stand-alone sqlean extensions which require a 64-bit process

Packages are now in moderation.

**Comment by dgalbraith** [comment]
Moderation complete and the packages are now available in the community repository.
