### ISSUE TITLE
RFP - local

### ISSUE THREAD

**Issue by musosoft** [chocolatey-community/chocolatey-package-requests#1373]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://localwp.com/
Direct download URL for the software / installer : https://cdn.localwp.com/releases-stable/6.4.3+6116/local-6.4.3-windows.exe
Software summary / short description: Local is a development tool used to run WordPress easily on any computer.

Latest version link is available at https://localwp.com/releases/

**Comment by mikeee** [comment]
I'll push this package - will have to do something slightly janky for an updater script.

**Comment by mikeee** [comment]
Package request complete -
https://community.chocolatey.org/packages/local#versionhistory 3 functional versions submitted

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @mikeee
