### ISSUE TITLE
RFM - iasl

### ISSUE THREAD

**Issue by RandomDSdevel** [chocolatey-community/chocolatey-package-requests#1374]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/iasl
Package source URL:  https://github.com/warexify/chocolatey-edk2-buildtools/tree/master/manual/iasl

Date the maintainer was contacted (in YYYY-MM-DD:)  2022-10-01
How the maintainer was contacted:  [Pull request](https://github.com/warexify/chocolatey-edk2-buildtools/pull/1) to [warexify/chocolatey-edk2-buildtools](https://github.com/warexify/chocolatey-edk2-buildtools), the iasl package's host repository.  

Date the Chocolatey Community Packages site admins were contacted (in YYYY-MM-DD:)  2022-10-13
How the Chocolatey Community Packages site admins were contacted:  E-mail via form reached from the iasl package's Chocolatey Community Packages description page's 'Contact Site Admins' link.  

---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Continues following up on #1060.

**Comment by dgalbraith** [comment]
I am happy to pick this one up.

**Comment by TheCakeIsNaOH** [comment]
@dgalbraith I've added you as a maintainer, you should have a confirmation email.

**Comment by RandomDSdevel** [comment]
@dgalbraith, CC @TheCakeIsNaOH:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Doesn't dgalbraith/chocolatey-packages#446 getting merged there also close this issue?

**Comment by TheCakeIsNaOH** [comment]
@RandomDSdevel issues generally stay open until the package has been approved by a moderator. Currently, the package is still in moderation: https://community.chocolatey.org/packages/iasl/2022.03.31

**Comment by RandomDSdevel** [comment]
> @RandomDSdevel issues generally stay open until the package has been approved by a moderator. Currently, the package is still in moderation: https://community.chocolatey.org/packages/iasl/2022.03.31

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Right, got it; thanks.

**Comment by dgalbraith** [comment]
@RandomDSdevel There is an automatically updating package package now available but as @TheCakeIsNaOH says still awaiting moderation.

It is a little strange and needs a moderator to review - the package is currently failing validation but I do not think that this is a valid error.

Once a moderator has taken a look this will be confirmed or additional updates requested before the package is published/made available.

In the interim it is possible to install the under-moderation versions

```
choco install -y iasl --version 2022.03.31
```

but please note that there has not been any independent review as yet.

**Comment by dgalbraith** [comment]
Package has now been reviewed and is available on the Community Repository.

**Comment by TheCakeIsNaOH** [comment]
Thanks for picking up the package @dgalbraith
