### ISSUE TITLE
RFM - traffic-monitor

### ISSUE THREAD

**Issue by mictaege** [chocolatey-community/chocolatey-package-requests#1375]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/traffic-monitor
Package source URL: https://github.com/iYato/chocolatey-packages/tree/master/traffic-monitor

Date the maintainer was contacted (in YYYY-MM-DD): 2022-09-22
How the maintainer was contacted: via the `Contact Maintainer` link on the package site

**Comment by tunisiano187** [comment]
Hello, i'll pick this package.
It's ready on repo.
@pauby , cn you assign me this issue?
And add me to the package mintainers ? https://community.chocolatey.org/packages/traffic-monitor

Thank you very much
