### ISSUE TITLE
RFP - wsl2-distro-manager

### ISSUE THREAD

**Issue by karolzlot** [chocolatey-community/chocolatey-package-requests#1376]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/bostrot/wsl2-distro-manager
Direct download URL for the software / installer : https://github.com/bostrot/wsl2-distro-manager/releases/download/v1.4.2/wsl2-distro-manager-v1.4.2.zip
Software summary / short description: A quick way to manage your WSL instances with a GUI.

## Package Expectations
A few ways to install it, not sure which will be the best for chocolatey to use.

**Comment by pauby** [comment]
I've gone ahead and updated the download URL.

**Comment by karolzlot** [comment]
@pauby This URL will change every version, this is why I put general one with links to versions. Not sure why this is preferred.

**Comment by pauby** [comment]
@karolzlot That's understood. For the request, the automation requires a link to the current download, else we get a [message like above](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1376#issuecomment-1296340763).

**Comment by mikeee** [comment]
Pushed an update script, awaiting packages to hit the community feed.

**Comment by mikeee** [comment]
This can be closed, the package is in the repo.
