### ISSUE TITLE
RFM - citrix-sharefile-sync

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#1377]
Please remove the 'Current Maintainer' section if you are not the current maintainer of the package,
otherwise if you are the current maintainer of the package please remove the 'I DON'T Want To Become The Maintainer' section.

## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/citrix-sharefile-sync
Package source URL: https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/citrix-sharefile-sync

**Comment by ravager-dk** [comment]
Sharefile Sync is deprecated and replaced by ShareFile for Windows. Recommend closing this issue and referring to below package. https://community.chocolatey.org/packages/sharefile-for-windows

**Comment by pauby** [comment]
@ravager-dk can you confirm where the official notification for this is?

**Comment by pauby** [comment]
Thanks @ravager-dk.

> ShareFile sync is on the path to be deprecated. The end of life of the tool is set for 2021 (please see the [Product Lifecycle Matrix](https://www.citrix.com/support/product-lifecycle/product-matrix.html)), so we encourage all of our customers to leverage this built-in utility to move users from ShareFile sync to Citrix Files for Windows.

Based on the above, I'm going to go ahead and close this issue.
