### ISSUE TITLE
RFP - spark-desktop

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#1378]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://sparkmailapp.com/
Direct download URL for the software / installer: https://downloads.sparkmailapp.com/Spark3/win/dist/3.1.0.38675/Spark.exe
Software summary / short description: Fast, cross-platform email designed to filter out the noise - so you can focus on what's important.

**Comment by mikeee** [comment]
Submitted the package. Should be available soon.

**Comment by mikeee** [comment]
This can be closed, the package is in the repo.
