### ISSUE TITLE
RFM - meson

### ISSUE THREAD

**Issue by justinpryzby** [chocolatey-community/chocolatey-package-requests#1380]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/meson
Package source URL: https://github.com/mesonbuild/ https://mesonbuild.com/

Date the maintainer was contacted (in YYYY-MM-DD): 2022-10-06 and 2022-11-07
How the maintainer was contacted: choco admin page and email to github address

## Detail

I made a request to update the 'meson' packages on Oct 6, but didn't hear back.
There's a bug in version 0.55 which makes it unusable for me (skipped tests are considered to be failed).
I already changed to install via pip, but it'd be better if choco had a newer version.
I found that there's a PR on the maintainer's github since 2 years ago.

**Comment by mikeee** [comment]
Sent a request for maintainer access, happy to pick this package up.

**Comment by justinpryzby** [comment]
Thanks for doing so !

**Comment by mikeee** [comment]
This can be closed, the package is in the repo.
