### ISSUE TITLE
RFP - gdl-(gnu-data-language)

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#1381]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/gnudatalanguage/gdl
Direct download URL for the software / installer : https://github.com/gnudatalanguage/gdl/releases/
Software summary / short description: GDL is a free/libre/open source incremental compiler compatible with IDL (Interactive Data Language) and to some extent with PV-WAVE.

**Comment by pauby** [comment]
@Foadsf Can you see the validation message above and update your original request?

**Comment by pauby** [comment]
There has been no update to this, so I'm going to close it.
