### ISSUE TITLE
RFP - endless-sky

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#1382]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://endless-sky.github.io/
Direct download URL for the software / installer : https://github.com/endless-sky/endless-sky/releases/download/v0.9.16.1/endless-sky-win64-v0.9.16.1.zip
Software summary / short description: Endless Sky is a 2D space trading and combat game similar to the classic Escape Velocity series.

**Comment by mikeee** [comment]
I'll have a package submitted for this req 🛠️

**Comment by mikeee** [comment]
Package submitted, awaiting approvals 👍
