### ISSUE TITLE
RFM - clamav

### ISSUE THREAD

**Issue by prettybits** [chocolatey-community/chocolatey-package-requests#1383]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/clamav
Package source URL: https://github.com/xdimquax/choco (defunct)

Date the maintainer was contacted (in YYYY-MM-DD): 2022-11-08
How the maintainer was contacted: "Contact Maintainers" form on package page

**Comment by pauby** [comment]
I'll pick this up.

**Comment by pauby** [comment]
Thsi has been published.
