### ISSUE TITLE
RFM - jdownloader

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#1384]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/jdownloader
Package source URL: https://github.com/aronovgj/choco-auto

Date the maintainer was contacted (in YYYY-MM-DD): 2022-11-04
How the maintainer was contacted: Contact Maintainers

**Comment by tunisiano187** [comment]
request to admin to be added sent, and package ready.

**Comment by mikeee** [comment]
I can have a look at this package

**Comment by mikeee** [comment]
Email sent to the maintainers requesting access, failing this I'll come back in 7 days.

**Comment by mikeee** [comment]
Complete - https://community.chocolatey.org/packages/jdownloader#versionhistory

**Comment by TheCakeIsNaOH** [comment]
Thanks for taking the package over @mikeee
