### ISSUE TITLE
RFM - solr

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#1385]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
**See below - package triage process was not followed as a previous RFM request was made.**
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/solr
Package source URL: https://github.com/majkinetor/au-packages/tree/master/solr

Date the maintainer was contacted (in YYYY-MM-DD):
How the maintainer was contacted:

The maintainer raised an [issue which is closed](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1107). Package updates have been [disabled](https://github.com/majkinetor/au-packages/commit/7cac2cea6335174a6973e634462cb89a2197ab3f) and the package is out of date (latest version available in CCR is 8.9.0 but 9.1.0 is available). Raising this request again for a new maintainer to pick up.

**Comment by pauby** [comment]
@majkinetor tagging you for visibility.

**Comment by majkinetor** [comment]
I am not ready to give up this package. 

Create new one any time.

**Comment by pauby** [comment]
The package is out of date and updates have been disabled. We need to offer this to another maintainer who will maintain it.

**Comment by pauby** [comment]
As a heads-up, I'm going to look to pick this package up over the holidays and move it over to Community Packages repository.

**Comment by majkinetor** [comment]
Sure, under different name. Like I said, I am not giving it, because I dont accept double standards.

**Comment by pauby** [comment]
This has been updated for version 8.11.2, 9.0.0 and 9.1.0. Will migrate it over to Chocolatey Community Chocolatey Packages repository soon.

**Comment by majkinetor** [comment]
Thanks for stealing it and removing me silently as moderator without my consent.  That info is public now.

**Comment by TheCakeIsNaOH** [comment]
@majkinetor on the Community Repository, maintainers get some privileges when maintaining packages such as:
- Choosing what (if any) package parameters to support
- Assuming the package is under 200mb and the software allows redistribution, picking between embedded and non-embedded
- Choosing (or not) to uploading older versions (e.g. streams) and/or prerelease versions if applicable.
- Adding features like desktop/start shortcuts, or search registration

However, maintainers also have some responsibilities, such as:
- Uploading packages that meet moderation requirements (and fixing them if changes are required). 
- Keeping the package up to date (where technically possible)
- Fixing the package if the latest version is broken (where technically possible)

This issue was opened, and the package was taken over because the `solr` package was out of date, and there was no technical reason for it being out of date (e.g. developers making the download url non-public). Instead, it was outdated because of a preference for packages being embedded.

**Comment by majkinetor** [comment]
It was not a preference for being embeded, that was a mistake, but about streams, as originaly stated:

> majkinetor wrote:
> > I am not ready to give up this package unless it is streamed.

> However, maintainers also have some responsibilities, such as:

I told that I will update the package myself when time allows:

> majkinetor wrote:
>> I will maintain it when I get into it.

The choco team also does this cherry picking where some animals are treated more equal then others. When I requrested to get moderation for example of FreeRdp package, I was denied, although it was 6 years outdated.  

**I guess this is against me then, a personal vendeta from the user @pauby** who seems not to have anything to do but molest me on GitHub. The original code is GNU, i wasn't mentioned anywhere, although parts of original code are still there. 

**This is unaceptable and I am ready to pursue this further. This is shameful and without any respect, particulary against a prominent member of community doing more then half decade of free work**. 

/cc @ferventcoder @TheCakeIsNaOH @gep13

**Comment by majkinetor** [comment]
Nice try @pauby 

My latest version was Solr 8.9.0, updated 6 months ago. Few months without update is certainly not enough time to steal my package given that there numerous packages that didn't get updated for years and given that I have very long history of updating packages in reasonable amount of time, I am shocked that this required such immediate attention. I also explicitly stated above to @pauby that I don't allow it, that I will update it myself, which he ignored. Which only means one thing, that it is against me personally.

Pauby already showed less then adequate behavior toward me here on GitHub, I complained multiple times and suggested him to just avoid me, however, he continues to steal my code and my time. Enough is enough, we need to resolve this now.

I humbly suggest to other Chocolatey core members to:

1. Order @pauby as Chocolatey employee to keep his distance from me in appropriate digital space
2. Return me moderation rights for Solr package that I personally started and kept it up to date for years in most professional way, with streams, given it is more like library then a tool, which requires it to have older versions updated too.

In the meantime, I will consult with my lawyers regarding legal aspects of it, as I suspect this kind of undeserved hostility will continue regarding my work and might even involve other Chocolatey employees.
