### ISSUE TITLE
RFP - visualstudio-wdk

### ISSUE THREAD

**Issue by gtrevi** [chocolatey-community/chocolatey-package-requests#1386]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk
Direct download URL for the software / installer : https://go.microsoft.com/fwlink/?linkid=2166289
Software summary / short description: to develop drivers on Win11 22H2/Visual Studio 2022, WDK version 10.0.22621.382 is required.

**Comment by gtrevi** [comment]
> I updated the title to be visualstudio-wdk. However, I'm struggling to understand the difference between this and [`windowsdriverkit11`](https://community.chocolatey.org/packages/windowsdriverkit11)?

No problem for the name, simply, I wasn't allowed to use that token. Adding another version to `windowsdriverkit11` would be absolutely fine.

Just heads up that the WDK is not related to Visual Studio, but to windows, hence why I continued to use the `windowsdriverkit**` prefix.

**Comment by pauby** [comment]
> Adding another version to windowsdriverkit11 would be absolutely fine.

Just to be clear, the `windowsdriverkit11` and this package are the same thing? When we say version, we mean version number of the same thing, so when you say the above do you just mean a later / more recent version number of `windowsdriverkit11` as it's outdated?

**Comment by gtrevi** [comment]
Let me better clarify: this is the latest WDK update for developing drivers on Win 11 22H2. In my initial naming, i.e. `windowsdriverkit12`, I simply followed the existing logic: in the current Chocolatey database

- [windowsdriverkit10](https://community.chocolatey.org/packages/windowsdriverkit10) (version 10.0.19041.685)
- [windowsdriverkit11](https://community.chocolatey.org/packages/windowsdriverkit11) (version 10.0.22000.1)

and consequently, my proposal was:

- [windowsdriverkit12](https://community.chocolatey.org/packages/windowsdriverkit12) (version 10.0.22621.382)

**Comment by TheCakeIsNaOH** [comment]
@gtrevi My understanding of `windowsdriverkit10` is that it is the WDK for Windows 10, and the `windowsdriverkit11` is for the WDK for Windows 11.

As per the table here: https://learn.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads#step-2-install-the-wdk, there are quite a few different versions of the WDK for various Windows 10 major updates, and (at the moment) two version of the WDK for Windows 11, for 21H2 and 22H2. 

So, the latest version of the WDK `10.0.22621.382`, is for Windows 11 22H2, correct? If so, I think it should be added as a version to `windowsdriverkit11`.
