### ISSUE TITLE
RFP - zebra-designer-3

### ISSUE THREAD

**Issue by thekyoshi** [chocolatey-community/chocolatey-package-requests#1388]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.zebra.com/us/en/support-downloads/printer-software/zebra-designer-3-downloads.html
Direct download URL for the software / installer :

https://www.zebra.com/content/dam/zebra_new_ia/en-us/software-printer/productivity-apps/zebra-designer-3/zebradesigner3-322611.exe

Software summary / short description:
Used for Labels for Zebra Printers

Thank you

**Comment by mikeee** [comment]
I'll pick this up

**Comment by mikeee** [comment]
Unfortunately I cannot find any silent flags for the installer, I'm not too good with automating the install using AHK or similar so will have to yield this package to someone else. Sorry!

**Comment by thekyoshi** [comment]
the msi is packaged into a exe
/s is the slient switch
it uses the install aware packaging

**Comment by pauby** [comment]
@mikeee Does the above comment help or do you still want to pass this back for another maintainer?

**Comment by pauby** [comment]
No problem. I've assigned it back to you now.

**Comment by mikeee** [comment]
https://community.chocolatey.org/packages/zebradesigner reviewed and complete
