### ISSUE TITLE
RFP - vscode-user

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1389]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://code.visualstudio.com/
Direct download URL for the software / installer : https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user
Software summary / short description: vscode user-mode installer

**Comment by pauby** [comment]
As the `vscode` packages are maintained over at https://github.com/chocolatey-community/chocolatey-packages it would make sense for the package to live there. As I mentioned in the [discussion](https://github.com/chocolatey-community/chocolatey-packages/discussions/2040#discussioncomment-4312362), can you raise a PR to add the code over there?

**Comment by pauby** [comment]
As we have a [discussion](https://github.com/chocolatey-community/chocolatey-packages/discussions/2040#discussioncomment-4312362) about this on the maintainers GitHub repository, I'm going to go ahead and close this.
