### ISSUE TITLE
RFP - lychee

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1391]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/lycheeverse/lychee
Direct download URL for the software / installer : https://github.com/lycheeverse/lychee/releases/download/v0.10.3/lychee-v0.10.3-windows-x86_64.exe
Software summary / short description:  ⚡ Fast, async, stream-based link checker written in Rust. Finds broken URLs and mail addresses inside Markdown, HTML, reStructuredText, websites and more!

**Comment by Aurocosh** [comment]
Package added. It is in moderation queue: https://community.chocolatey.org/packages/lychee

**Comment by Aurocosh** [comment]
The package is approved.
