### ISSUE TITLE
RFM - vault

### ISSUE THREAD

**Issue by flcdrg** [chocolatey-community/chocolatey-package-requests#1392]
## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/vault
Package source URL: https://github.com/tico24/chocolatey-packages

Existing maintainer asked to be removed via email to chocolatey-moderators on 16-Dec-2022
> I can no longer maintain this. I have no access to a windows machine. Please remove me as a maintainer to allow others to offer their services.

**Comment by flcdrg** [comment]
I'm interested in picking up this package

**Comment by pauby** [comment]
@flcdrg I saw your request come through so I've added you as maintainer, and added you to this issue. Thanks for picking it up.
