### ISSUE TITLE
RFP - fastfetch

### ISSUE THREAD

**Issue by CarterLi** [chocolatey-community/chocolatey-package-requests#1395]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/LinusDierheimer/fastfetch
Direct download URL for the software / installer : https://github.com/LinusDierheimer/fastfetch/releases/download/1.8.2/fastfetch-1.8.2-Windows.zip
Software summary / short description: `Like neofetch, but much faster because written in C.`

**Comment by Aurocosh** [comment]
I wanted to add this package to choco, but it apparently already exists.
Link to the package: https://community.chocolatey.org/packages/fastfetch
