### ISSUE TITLE
RFM - plexmediaserver

### ISSUE THREAD

**Issue by mikecole** [chocolatey-community/chocolatey-package-requests#1396]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/plexmediaserver
Package source URL: https://github.com/mikecole/chocolatey-packages/tree/master/automatic/plexmediaserver

This is a working package with a functional AU script. I simply don't have the capacity to keep it updated as it is a popular package. Currently, there are a handful of requests to add the 64-bit version and I have not been able to field these requests. I will help as much as I can to transfer ownership.

**Comment by mkevenaar** [comment]
@mikecole I would love to pick this up. I am @mkevenaar on Chocolatey as well

**Comment by mikecole** [comment]
I added you as a maintainer. Feel free to remove me whenever you are ready. Here's a copy/paste from an email with the only pending request off the top of my head:

_Could you please add support for the 64-bit version? Most people will be installing that and it also seems much more stable than the 32bit one._

**Comment by tunisiano187** [comment]
Can you close this issue ? thank you
