### ISSUE TITLE
RFP - bvckup2

### ISSUE THREAD

**Issue by e-monsters** [chocolatey-community/chocolatey-package-requests#1398]
## Checklist

- [ ] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://bvckup2.com/
Direct download URL for the software / installer : https://bvckup2.com/files/bvckup2-setup-1.82.5.0.exe
Software summary / short description: Light, versatile and very capable software for professional data replication.

**Comment by pauby** [comment]
This package already exists on the Chocolatey Community Repository. Please follow the [package triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) to progress this.
