### ISSUE TITLE
RFM - libreoffice-help

### ISSUE THREAD

**Issue by sremick** [chocolatey-community/chocolatey-package-requests#1400]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/libreoffice-help
Package source URL: https://github.com/chocolatey/chocolatey-coreteampackages

Date the maintainer was contacted (in YYYY-MM-DD): 2023-01-31
How the maintainer was contacted: https://community.chocolatey.org/packages/libreoffice-help/ContactOwners

**Comment by sremick** [comment]
I did search, but there wasn't a checkbox for that. How do I pacify the validation bot?

**Comment by pauby** [comment]
There is a checkbox for that in the original message. It's the second one (on my phone otherwise I'd screenshot it).

**Comment by sremick** [comment]
I'm afraid I'm not seeing it... I must be dense. Here's the entirety of the original message, unedited:
`

## Current Maintainer



- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [ ] There is no existing open maintainer request for this package;

## Checklist

- [ ] Issue title starts with 'RFM - '

## Existing Package Details



Package URL:
Package source URL:



Date the maintainer was contacted (in YYYY-MM-DD):
How the maintainer was contacted:
`

**Comment by TheCakeIsNaOH** [comment]
![Screenshot 2023-02-04 145402](https://user-images.githubusercontent.com/38865330/216789150-444fb965-f956-4e8a-92dc-33286f857840.png)

**Comment by sremick** [comment]
Wow, major eyeball fail. I read that a million times but my eyes skipped over the word "request"... I thought it was saying there was no existing MAINTAINER for the package, which of course is not true so I left it unchecked.

I'm sorry.

**Comment by pauby** [comment]
@sremick You may get traction by raising an issue on the maintainers respository - https://github.com/chocolatey-community/chocolatey-packages/issues

**Comment by pauby** [comment]
I don't see an issue in the repository for this package, so I'm going to go ahead and close it.
