### ISSUE TITLE
RFM - tigervnc

### ISSUE THREAD

**Issue by graham-collinson** [chocolatey-community/chocolatey-package-requests#1404]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/tigervnc
Package source URL: https://github.com/qzo/chocolatey-packages/tree/master/packages/manual/tigervnc_m/tigervnc 

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-07
How the maintainer was contacted: Comments - http://disq.us/p/2l7ysjz

**Comment by tunisiano187** [comment]
Requested to be added as maintainer.
I'll update it asap

**Comment by pauby** [comment]
@tunisiano187 Just as an FYI, we haven't received any request to add you as maintainer to the package.
