### ISSUE TITLE
RFM - office365proplus

### ISSUE THREAD

**Issue by mikecole** [chocolatey-community/chocolatey-package-requests#1406]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/office365proplus
Package source URL: https://github.com/mikecole/chocolatey-packages

I currently do not have the bandwidth to maintain this package. There is a new version and it's not currently passing the automatic testing process, so some troubleshooting is required.

**Comment by dgalbraith** [comment]
@mikecole happy to pick this one up.  Have sent a request via Chocolatey to be added as a package maintainer.

**Comment by mikecole** [comment]
@dgalbraith added. Thanks! Let me know how I can help.

**Comment by pauby** [comment]
@dgalbraith Can you provide an update on this one?

**Comment by dgalbraith** [comment]
[Office365proplus package](https://community.chocolatey.org/packages/Office365ProPlus) is updated and approved.
