### ISSUE TITLE
RFP - localsend

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1410]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/localsend/localsend
Direct download URL for the software / installer : https://github.com/localsend/localsend/releases/download/v1.8.0/LocalSend-1.8.0.msix or https://github.com/localsend/localsend/releases/download/v1.8.0/LocalSend-1.8.0-windows.zip
Software summary / short description:
LocalSend is a free, open-source app that allows you to securely share files and messages with nearby devices over your local network, without needing an internet connection.

**Comment by brogers5** [comment]
I'll pick this one up.

**Comment by brogers5** [comment]
v1.8.0 has been packaged and submitted for review:
https://community.chocolatey.org/packages/localsend

**Comment by brogers5** [comment]
v1.8.0 was approved yesterday and should now be live for consumption.

Issue can now be closed.
