### ISSUE TITLE
RFP - simple-ip-config

### ISSUE THREAD

**Issue by pdg1** [chocolatey-community/chocolatey-package-requests#1412]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/KurtisLiggett/Simple-IP-Config
Direct download URL for the software / installer : https://github.com/KurtisLiggett/Simple-IP-Config/releases/download/2.9.7/Simple.IP.Config.Setup.2.9.7.exe
Software summary / short description: Simple IP Config is a small, portable ip changer utility to change common Windows network settings quickly and easily without having to click through the endless system windows.

**Comment by pauby** [comment]
This package already exists (same GitHub repo you provided). In going to go ahead and close this.
