### ISSUE TITLE
RFP - pulsar

### ISSUE THREAD

**Issue by S0NGER** [chocolatey-community/chocolatey-package-requests#1413]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://pulsar-edit.dev
Direct download URL for the software / installer : https://download.pulsar-edit.dev/?os=windows&type=windows_setup
Software summary / short description: A community-made fork of GitHub's now sunset Atom

**Comment by S0NGER** [comment]
Just want to update this and say that this is now on Chocolatey, though it's not up to the latest version (v1.108.0) as of writing this (currently v1.103.0).
https://community.chocolatey.org/packages/pulsar

**Comment by pauby** [comment]
Thanks for updating this. The current version was approved in April after this was submitted so I'll go ahead and close it.

If the package is outdated, please go ahead and contact the maintainer using the 'Contact Maintainer' link on the page to let them know.
