### ISSUE TITLE
RFP - filelight

### ISSUE THREAD

**Issue by beyond9thousand** [chocolatey-community/chocolatey-package-requests#1420]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://apps.kde.org/filelight/
Direct download URL for the software / installer : https://download.kde.org/stable/release-service/23.04.0/windows/filelight-23.04.0-1330-windows-cl-msvc2019-x86_64.exe
Software summary / short description: Filelight is an application to visualize the disk usage on your computer by showing folders using an easy-to-understand view of concentric rings. Filelight makes it simple to free up space!

**Comment by TakataSanshiro** [comment]
I just submitted the package.
https://community.chocolatey.org/packages/filelight

**Comment by TakataSanshiro** [comment]
The package has been approved.
