### ISSUE TITLE
RFM - visualstudio2012premwithwebtools

### ISSUE THREAD

**Issue by Windos** [chocolatey-community/chocolatey-package-requests#1424]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/visualstudio2012premwithwebtools
Package source URL:

**Note**: Previous maintainer requested account deletion.

**Comment by pauby** [comment]
@Windos it looks like [Visual Studio 2012 is no longer supported](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2012). I haven't looked at the package to see the last version, but is it a case of adding a final release or closing this?

**Comment by pauby** [comment]
I wonder if it's also covered by one of the other [VS 2012 packages](https://community.chocolatey.org/packages?q=Visual+studio+2012) and we can just deprecate it. I'll pick this up and sort it out.

**Comment by pauby** [comment]
I added a comment to the comments on the package page and unlisted the only version.

![image](https://github.com/chocolatey-community/chocolatey-package-requests/assets/12760779/38cda8f7-ee0f-451a-8ed4-65e912039b88)
