### ISSUE TITLE
RFP - yuzu-mainline

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1425]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/yuzu-emu/yuzu
Direct download URL for the software / installer : https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1447/yuzu-windows-msvc-20230526-fbe86b889.7z
Software summary / short description: yuzu is the world's most popular, open-source, Nintendo Switch emulator — started by the creators of [Citra](https://citra-emu.org/). It is written in C++ with portability in mind, and we actively maintain builds for Windows and Linux.

**Comment by pauby** [comment]
@soredake please include a comment for the reason you are closing issues.
