### ISSUE TITLE
RFP - openrocket

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#1429]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://openrocket.info/
Direct download URL for the software / installer : https://github.com/openrocket/openrocket/releases/download/release-22.02/OpenRocket-22.02-Windows.exe
Software summary / short description: OpenRocket is an free, fully featured model rocket simulator

**Comment by luzpaz** [comment]
Winget: https://github.com/microsoft/winget-pkgs/pull/111615

**Comment by teknowledgist** [comment]
I got this one:  https://community.chocolatey.org/packages/openrocket

**Comment by luzpaz** [comment]
Looks like it can be closed, see https://community.chocolatey.org/packages/openrocket  
Thanks!
