### ISSUE TITLE
RFM - jitsi-meet-electron

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#1433]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/jitsi-meet-electron
Package source URL: https://github.com/cmorty/au-packages/

Date the maintainer was contacted (in YYYY-MM-DD): 2023-07-15
How the maintainer was contacted: https://github.com/cmorty/au-packages/pull/1#issuecomment-1636677681

**Comment by tunisiano187** [comment]
Hello, I'll take this package.
I'll send a request to be added as maintainer.
