### ISSUE TITLE
RFP - ossia-score

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#1435]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Source code: https://github.com/ossia/score  
Software project URL: https://ossia.io/  
Direct download URL for the software / installer: https://github.com/ossia/score/releases/download/v3.1.11/ossia.score-3.1.11-win64.exe  
Release Notes: https://github.com/ossia/score/releases/tag/v3.1.11
Software summary / short description:  
An interactive sequencer for the intermedia arts

## Package Expectations

> * Recommended: Windows 10. Must be at least Windows 7 with all system updates installed.
> * score and *libossia* use Bonjour for the OSCQuery automatic discovery feature. This means that on Windows, you must install the [Bonjour Print Services](https://support.apple.com/kb/dl999?locale=en_US) for this to work.

**Comment by luzpaz** [comment]
That is indeed the package but the URL here is  https://github.com/ossia/score/releases/download/v3.1.11/ossia.score-3.1.11-win64.exe which is a direct URL. Not sure what the issue is??

**Comment by pauby** [comment]
As this package exists, I'm going to close this issue.

**Comment by jcelerier** [comment]
@pauby someone else (outside of the development team) submitted the package to chocolatey but it got rejected (https://community.chocolatey.org/packages/ossia-score) - what can we do, as actual developers of the software, to take over the maintainership of the package and submit it so that it is actually available?

**Comment by pauby** [comment]
@jcelerier The normal [triage process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) should be followed.
