### ISSUE TITLE
RFP - codeproject-ai

### ISSUE THREAD

**Issue by Germs2004** [chocolatey-community/chocolatey-package-requests#1442]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.codeproject.com/ai/index.aspx

Direct download URL for the software / installer : https://www.codeproject.com/ai/latest.aspx

Software summary / short description:
This software acts like a background server which provides a service to other software via an API.  The service it provides is AI processing.  For example, BlueIris security camera software integrates with this CodeProject.AI to analyze images to distinguish people, dogs, cats, cars, bikes, etc.  Once installed, it can be accessed/managed via its web GUI.

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/codeproject-ai

**Comment by Aurocosh** [comment]
The package is approved.
