### ISSUE TITLE
RFM - hexchat

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#1445]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/hexchat
Package source URL: https://github.com/MItsutoshiNAKANO/chocolatey-hexchat/

Date the maintainer was contacted (in YYYY-MM-DD): 2023-08-09
How the maintainer was contacted: Contact Maintainers link on the package page.

NOTE: This was a request that came into the 'Contact Site Admins' mailing list from drone621. I'm just raising this issue.

**Comment by TheCakeIsNaOH** [comment]
I'll take this package over.
