### ISSUE TITLE
RFP - protondrive

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1447]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://proton.me/drive/download
Direct download URL for the software / installer : https://proton.me/download/drive/windows/Proton%20Drive%20Setup%201.3.13.exe
Software summary / short description:
Free end-to-end encrypted cloud storage made by Proton AG. Securely backup and share your files. Open source, publicly audited, and Swiss based.

**Comment by TakataSanshiro** [comment]
ProtonDrive has been approved.
https://community.chocolatey.org/packages/protondrive/1.4.3
