### ISSUE TITLE
RFM - PandaFreeAntivirus

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-package-requests#145]
The maintainers from the [PandaFreeAntivirus](https://chocolatey.org/packages/PandaFreeAntivirus) recently decided to stop maintaining this package and is requesting a new maintainer for it.

The source of the package is available [here](https://github.com/chocolatey/chocolatey-coreteampackages/tree/a1202463831ee4198950c04c9fac4cdf0816c46e/automatic/pandafreeantivirus).

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/pandafreeantivirus

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/pandafreeantivirus

**Comment by AdmiringWorm** [comment]
Looks like the package have been approved.
