### ISSUE TITLE
RFP - cmocka

### ISSUE THREAD

**Issue by stephenbarton** [chocolatey-community/chocolatey-package-requests#1450]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [ ] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
Direct download URL for the software / installer :
Software summary / short description:

**Comment by stephenbarton** [comment]
Not sure on the URL or the format required to submit.
Do you require binaries?

**Comment by pauby** [comment]
You haven't ticked that the software URL is public? If the software is not public then a package can't be created.

**Comment by stephenbarton** [comment]
The software is public. I just don't know if I am supposed to reach out to the cmocka team to request they create a binary.

**Comment by pauby** [comment]
How do you install the software if there is no binary? What is the location of the software?

**Comment by stephenbarton** [comment]
I have reached out to cmocka to see if they are willing to provide a binary url.
Thanks for your help.

**Comment by pauby** [comment]
I'm going to go ahead and close this. Once you have everything required we can either reopen or create a new issue.
