### ISSUE TITLE
RFM - lilypond

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-package-requests#1453]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/lilypond
Package source URL: https://github.com/AdmiringWorm/chocolatey-packages/tree/ac03f7e22630221b951374e1f5a3d089ac74841d/automatic/lilypond

**Comment by teknowledgist** [comment]
I will pick this up.  If you can make me a maintainer, I will post again when I've submitted the updated package.

**Comment by AdmiringWorm** [comment]
@teknowledgist I have added you as the maintainer of the package.

Feel free to remove me when you have accepted.

**Comment by pauby** [comment]
@teknowledgist is there any progress on this one?

**Comment by teknowledgist** [comment]
Yes.  The package has been updated, "enhanced" and submitted.  It's just waiting on review.
