### ISSUE TITLE
RFM - todobackup

### ISSUE THREAD

**Issue by Ginko77** [chocolatey-community/chocolatey-package-requests#1456]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else.

## Checklist

- [x] Issue title starts with 'RFM - todobackup '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/todobackup
Package source URL: https://www.easeus.fr/
-----
I'm no longer in a position to maintain this package, so I'll give way if anyone is interested.

Thanks in advance.

**Comment by pauby** [comment]
@Ginko77 Can you back to the title and update it with the actual package name? [`easeus-todo-backup-free`](https://community.chocolatey.org/packages/easeus-todo-backup-free) doesn't exist.
