### ISSUE TITLE
RFP - gittyup

### ISSUE THREAD

**Issue by benedictleejh** [chocolatey-community/chocolatey-package-requests#1464]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://murmele.github.io/Gittyup
Direct download URL for the software / installer : https://github.com/Murmele/Gittyup/releases/download/gittyup_v1.3.0/Gittyup-win64-1.3.0.exe
Software summary / short description:
Gittyup is a graphical Git client designed to help you understand and manage your source code history.

Gittyup is a continuation of the [GitAhead](https://github.com/gitahead/gitahead) client.

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/gittyup

**Comment by Aurocosh** [comment]
The package is approved.
