### ISSUE TITLE
RFM - inter

### ISSUE THREAD

**Issue by benedictleejh** [chocolatey-community/chocolatey-package-requests#1466]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/inter
Package source URL: (there appears to be no packageSourceUrl defined).

Date the maintainer was contacted (in YYYY-MM-DD): 2023-11-12
How the maintainer was contacted: Contact Maintainers form from Package URL

**Comment by teknowledgist** [comment]
I will pick this up.

**Comment by teknowledgist** [comment]
I'm ready to submit the updated package to the repo, but I need to be assigned maintainer status.

**Comment by flcdrg** [comment]
Added @teknowledgist as a maintainer in response to request via Site Admins

**Comment by teknowledgist** [comment]
This is (long) submitted and approved by moderators and can be closed.
