### ISSUE TITLE
RFP - sonobus

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#1468]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://sonobus.net/
Direct download URL for the software / installer : https://sonobus.net/releases/sonobus-1.7.0-win.exe
Software summary / short description:  

>SonoBus is an easy to use application for streaming high-quality, low-latency peer-to-peer audio between devices over the internet or a local network.

>Connects multiple users together to send and receive audio among all in a group, with fine-grained control over latency, quality and overall mix. Includes optional input compression, noise gate, and EQ effects, along with a master reverb. All settings are dynamic, network statistics are clearly visible.

>Works as a standalone application on macOS, Windows, iOS, and Linux, and as an audio plugin (AU, VST) on macOS and Windows. Use it on your desktop or in your DAW, or on your mobile device.

>Easy to setup and use, yet still provides all the details that audio nerds want to see. Audio quality can be instantly adjusted from full uncompressed PCM (16, 24, or 32 bit) or with various compressed bitrates (16-256 kbps per channel) using the low-latency Opus codec, and you can do this independently for any of the users you are connected with in a group.

Github: https://github.com/sonosaurus/sonobus  
Latest release: https://github.com/sonosaurus/sonobus/releases/tag/1.7.0

**Comment by Aurocosh** [comment]
Package created and is currently in the moderation queue: [https://community.chocolatey.org/packages/sonobus/1.7.2](https://community.chocolatey.org/packages/sonobus/1.7.2).

**Comment by Aurocosh** [comment]
The package is approved.
