### ISSUE TITLE
RFM - monosnap

### ISSUE THREAD

**Issue by TakataSanshiro** [chocolatey-community/chocolatey-package-requests#1470]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/monosnap
Package source URL: https://github.com/TakataSanshiro/Chocolatey-Packages/tree/master/automatic/monosnap

**Comment by tunisiano187** [comment]
I'll Take this one too.
can you add tunisiano as maintainer ?
Thank you.

**Comment by tunisiano187** [comment]
Hello,
This package as been approved
so this issue can be closed as complete.
Thank you.
