### ISSUE TITLE
RFM - quaternion

### ISSUE THREAD

**Issue by KitsuneRal** [chocolatey-community/chocolatey-package-requests#1475]
I am the developer of this application; however, I'm not a Windows user so cannot honestly be a maintainer of a Chocolatey package. I reached out to a previous maintainer (xdimquax) but he did not return. Getting a Chocolatey package wasn't a priority for me so this was lying in the backyard for almost 5 years... anyway:

I'm happy to work together with whoever is willing to pick this package up - despite the passed years, an update process should be straightforward as the means of building the package didn't change much. Ultimately, generation of new Chocolatey packages can be incorporated into my CI pipeline for even lower maintenance; but someone will have to be around to reinvigorate the package first, and validate the artifacts from time to time.

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/quaternion
Package source URL: https://github.com/xdimquax/choco

Date the maintainer was contacted (in YYYY-MM-DD): 2019-08-12 (as I said, almost 5 years ago)
How the maintainer was contacted: https://community.chocolatey.org/packages/quaternion/0.0.9.4-beta1/ContactOwners

**Comment by pauby** [comment]
As the last contact with the maintainer was 5 years ago, can you try again?

**Comment by KitsuneRal** [comment]
He deleted his account from GitHub, and his packages were up for grabs even then. But I can try once again as a formality...

**Comment by pauby** [comment]
If that's the case then it's reasonable to assume the maintainer has stopped maintaining their packages. There's no need, in my opinion, to contact them under these circumstances.

**Comment by tunisiano187** [comment]
Thae package is ready, i've asked to be added as maintainer.
Have a nice day.

**Comment by tunisiano187** [comment]
That's weird, as the other packages have been assigned as maintainer, this one, even with the contact admins on the 4th i still haven't received any answers.
@pauby , can you help ?

**Comment by pauby** [comment]
I don't know why that was missed. I see messages today, 7 and 4 March.

I've added you as a maintainer.

**Comment by tunisiano187** [comment]
Thank you very much

**Comment by tunisiano187** [comment]
Done and approved
Have a nice day
