### ISSUE TITLE
RFP - roboform

### ISSUE THREAD

**Issue by manglewurzle** [chocolatey-community/chocolatey-package-requests#1476]
Installing package gives following errors.  I do have Roboform already installed, version 9.5.6.6

But mine is not enterprise.

ERROR: Checksum for 'C:\Users\mross\AppData\Local\Temp\chocolatey\RoboForm\9.4.7\RoboForm-v9-Enterprise.msi' did not meet '9d0d9f988b5fd088cc14e1e96113af6dc20d4ed0f832131d69b12d7ad896c5c7' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of roboform was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\RoboForm\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

## Package Details

Software project URL : https://www.roboform.com/
Direct download URL for the software / installer : https://www.roboform.com/dist/RoboForm-v9-Setup.exe
Software summary / short description: Password Manager

**Comment by pauby** [comment]
This repository is not the place to report issues with packages. Please reach out to the package maintainer.

**Comment by manglewurzle** [comment]
Ok, thanks for the update.

**Comment by manglewurzle** [comment]
Where should I go to request a package for Roboform?  The one you have is
only for Roboform Enterprise.

Sorry to trouble you but I did try very hard to post in the correct place.
I did not find the instructions actually pointed to the right place!

So far Chocolately is performing very well.

Thanks and regards,

Martin
