### ISSUE TITLE
RFM - vim-tux

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#1480]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/vim-tux
Package source URL: https://github.com/pauby/ChocoPackages/tree/master/automatic/vim-tux.install

**Comment by pauby** [comment]
NOTE: The `vim-tux` package hasn't been updated in a while and there is no source for it. There are also two other packages:

* [`vim-tux.install`](https://github.com/pauby/ChocoPackages/tree/master/automatic/vim-tux.install)
* [`vim-tux.portable`](https://github.com/pauby/ChocoPackages/tree/master/automatic/vim-tux.portable)

**Comment by tunisiano187** [comment]
hello, @pauby , i see you're the current maintainer of the package, vim-tux, do you want me to take them ?

**Comment by pauby** [comment]
I am maintaining the package Closing this request.
