### ISSUE TITLE
RFP - cocogitto

### ISSUE THREAD

**Issue by qubitz** [chocolatey-community/chocolatey-package-requests#1481]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://docs.cocogitto.io/
Direct download URL for the software / installer : https://github.com/cocogitto/cocogitto/releases/download/6.0.1/cocogitto-6.0.1-x86_64-pc-windows-msvc.tar.gz
Software summary / short description:

> The Conventional Commits toolbox
>
> **Verified commits**: create conventional compliant commits with ease.
> **Automatic Version bump and changelog**: automatically bump versions and generate changelogs with your own custom steps and workflows.
> **Release profiles**: your branching model requires different steps for releases, pre-release, hotfixes ? We got you covered !
> **Depends only on libgit2**: cocogitto has one standalone binary, the only system dependency is libgit2.
> **Conventional git log**: search your commit history matching Conventional Commits items such as scope and commit type.
> **GitHub integration**: enforce the conventional commits specification with our GitHub action and bot.
> **Monorepo support**: Automatic versioning for mono-repositories is supported out of the box.

**Comment by Aurocosh** [comment]
Package created: https://community.chocolatey.org/packages/cocogitto

**Comment by Aurocosh** [comment]
The package is approved.
