### ISSUE TITLE
RFM - newfiletime

### ISSUE THREAD

**Issue by fromSmolsoft** [chocolatey-community/chocolatey-package-requests#1482]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer [request for this package](https://github.com/chocolatey-community/chocolatey-package-requests/issues?q=is%3Aissue+is%3Aopen+NewFileTime);  

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/newfiletime
Package source URL: https://github.com/echizenryoma/Chocolatey-Package/tree/master/newfiletime

Date the maintainer was contacted (in YYYY-MM-DD): 2023-03-23 (the first known try), 2024-01-30 (The latest try)
How the maintainer was contacted: Disqus and Cholatey's [Contact Maintainers](https://community.chocolatey.org/packages/newfiletime/ContactOwners)  option.

Edit:
- TheCakeIsNaOH from [Contact Site Admins](https://community.chocolatey.org/packages/newfiletime/6.88/ContactAdmins) confirmed the package to be abandoned and they asked me to open this issue here on github.
- Latest Disqus comment was marked as spam, so it temporarily disappeared from the forum .  
- Someone tried to contact maintainer via [Disqus](http://disq.us/p/2tcqo2z) approximately a year ago about outdated package but the package was not updated even back then. 
- I tried to reach maintainer via "contact maintainers" link on Chocolatey and it says "All the owners of this package have chosen not to receive email communication." [Chocolatey contact owners](https://community.chocolatey.org/packages/newfiletime/ContactOwners)
- I tried to go to source and got error "404 - page not found, The master branch of Chocolatey-Package does not contain the path Newfiletime." [Package source](https://github.com/echizenryoma/Chocolatey-Package/tree/master/newfiletime)
- Packaged software version is at minimum 7 versions or  one year late after current software version . [NewFileTime official site](http://www.softwareok.com/?seite=Microsoft/NewFileTime/History)

**Comment by pauby** [comment]
We ask for you to wait at least 7 days before considering that the maintainer is no longer maintaining it. I don't see any Disqus comments on the package page recently.

![image](https://github.com/chocolatey-community/chocolatey-package-requests/assets/12760779/853b888d-7fec-4a88-b25a-06765d19bc0a)

The maintainer also has a GitHub repository so I would suggest you raise an issue there as belt-and-braces.

I'll go ahead and close this but we can always reopen it later.

**Comment by fromSmolsoft** [comment]
> We ask for you to wait at least 7 days before considering that the maintainer is no longer maintaining it. I don't see any Disqus comments on the package page recently.
> 
> ![image](https://private-user-images.githubusercontent.com/12760779/301916910-853b888d-7fec-4a88-b25a-06765d19bc0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzc5MTAsIm5iZiI6MTcwODI3NzYxMCwicGF0aCI6Ii8xMjc2MDc3OS8zMDE5MTY5MTAtODUzYjg4OGQtN2ZlYy00YTg4LWIyNWEtMDY3NjVkMTliYzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE3MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGFlNTBhMWY0OWFjNGIzMjc5M2I3OGY3YTNlNTliMjg0YTFkZjk1NjNlYjJhNDE5MWRkNWMyNzFkOGMwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3VAfgYrYYDCAcN3Rx60BgH9brxeBowmo9Zkl3P6Wr0)
> 
> The maintainer also has a GitHub repository so I would suggest you raise an issue there as belt-and-braces.
> 
> I'll go ahead and close this but we can always reopen it later.

![image](https://github.com/chocolatey-community/chocolatey-package-requests/assets/130222605/213359e2-422d-4308-bd10-d0d7efda5468)

Because comment in discus was marked as spam by someone.     
Also If you just read and checked other things in request you can't seriously consider package to be still maintained.

**Comment by TheCakeIsNaOH** [comment]
> The maintainer also has a GitHub repository so I would suggest you raise an issue there as belt-and-braces.

When I clicked the package source link, it 404-ed.

**Comment by fromSmolsoft** [comment]
@AdmiringWorm 
Feel free to check the DIsqus under the package now.  They re-enabled latest comment.  
![image](https://github.com/chocolatey-community/chocolatey-package-requests/assets/130222605/cf91d800-314f-4bc0-8c72-e10df980d677)

**Comment by pauby** [comment]
> Because comment in disqus was marked as spam by someone.

Nobody marked the comment as spam. It was likely done automatically by Disqus. Not all maintainers read the Disqus comments, so we don't use it as a way to contact a maintainer.

> Also If you just read and checked other things in request you can't seriously consider package to be still maintained.

I take each issue at face value and don't generally dig into them as I simply don't have the time. I go with the information provided and what was provided _at the time_, provided no context as to why anything but the date contacted should be used.

> Maybe i should mention that TheCakeIsNaOH from [Contact Site Admins](https://community.chocolatey.org/packages/newfiletime/6.88/ContactAdmins) confirmed the package to be abandoned and they asked me to open this issue here on github.

Thank you for adding the issue. Had that information been provided at the time, I would have handled this issue differently.

I'll go ahead and open this again.

**Comment by tunisiano187** [comment]
Hello,
I've prepared the updater, so i'll take this package.
Have a nice day.

**Comment by tunisiano187** [comment]
Package ready for approval.
Have a nice day

**Comment by tunisiano187** [comment]
This one is accepter, the Issue can be closed, thank you.
