### ISSUE TITLE
RFM - paraview

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#1483]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/paraview
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2024-02-04
How the maintainer was contacted: via 'Contact Maintainers' link

Package has not been updated since 16 Aug 2019 and there have been multiple request on the discussion page for updates over the years.

**Comment by pauby** [comment]
Please wait at least 7 days from contacting the maintainer (the date on this issue is `> 2024-02-04`) via the 'Contact Maintainer' link before raising an issue for a new maintainer. Can you also raise an issue on their 'Package Source' link?

I'll close this issue but we can reopen it if needed.

**Comment by luzpaz** [comment]
cc @pauby :point_up_2:

**Comment by tunisiano187** [comment]
The package is ready to be accepted on the repository

**Comment by tunisiano187** [comment]
This package as been accepted by reviewers.
This issue can be closed
Thank you
