### ISSUE TITLE
RFM - dokany

### ISSUE THREAD

**Issue by Liryna** [chocolatey-community/chocolatey-package-requests#1484]
I am the maintainer of [Dokany](https://github.com/dokan-dev/dokany) project. Previous maintainer of the choco package [dokany](https://community.chocolatey.org/packages/dokany) approved that I can take over the maintenance of the package.

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/dokany
Package source URL: https://github.com/bcurran3/ChocolateyPackages/tree/master/dokany

Date the maintainer was contacted (in YYYY-MM-DD): 2024-02-04
How the maintainer was contacted: Github - https://github.com/bcurran3/ChocolateyPackages/issues/360

**Comment by pauby** [comment]
Can you go to the package page and click on 'Contaxt Site Admins' with this request?
