### ISSUE TITLE
RFM - logitech-options

### ISSUE THREAD

**Issue by nykBM** [chocolatey-community/chocolatey-package-requests#1485]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/logitech-options
Package source URL: https://github.com/bcurran3/ChocolateyPackages/tree/5afb3d4e348cf5f86bd17223f4c8fca75e92352e/logitech-options

Date the maintainer was contacted (in YYYY-MM-DD): 2024-02-04
How the maintainer was contacted: Chocolatey e-mail form on the community page.

**Comment by nykBM** [comment]
Fixed title problem.

**Comment by pauby** [comment]
I updated the Package Source URL and moved the link to the latest version, to here - https://support.logi.com/hc/en-us/articles/4418699283607-Logi-Options (new version is available)

**Comment by tunisiano187** [comment]
Hello, i've prepared the updater for this package, but they've started back to 1.62.518518, and the current version on chocolatey is 10.10.58.
as they've changed the name to logi-options, may i rename it to that name and create a meta package with the current name requiring the new package ?

Thank you for your help.

**Comment by gep13** [comment]
@virtualex-itv isnt this the package, or one of them, that we were discussing in Discord?

**Comment by tunisiano187** [comment]
indeed, i've just found this on his github, i'll take another one from dtgm (deluge)

**Comment by virtualex-itv** [comment]
> @virtualex-itv isnt this the package, or one of them, that we were discussing in Discord?

Similar - my package is `logioptionsplus`..."plus" being the key differentiator.  But I didn't look into this one thoroughly so it's either an older app or the same as mine without the plus in the name

**Comment by TheCakeIsNaOH** [comment]
> But I didn't look into this one thoroughly so it's either an older app or the same as mine without the plus in the name

It is an older app, the `plus` app is the replacement for the non-plus app.

The non-plus app is still being updated occasionally (a new version was released a couple of weeks ago) and last time I looked it has support for some older hardware that the plus app does not support. 

I took over this package a few days ago, v10.20.11 is in moderation.

**Comment by TheCakeIsNaOH** [comment]
v10.20.11 is approved.
