### ISSUE TITLE
RFP - topgrade

### ISSUE THREAD

**Issue by niStee** [chocolatey-community/chocolatey-package-requests#1489]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/topgrade-rs/topgrade
Direct download URL for the software / installer : https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip
Software summary / short description: Keeping your system up to date usually involves invoking multiple package managers. This results in big, non-portable shell one-liners saved in your shell. To remedy this, Topgrade detects which tools you use and runs the appropriate commands to update them.

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/topgrade

**Comment by Aurocosh** [comment]
The package is approved.
