### ISSUE TITLE
RFP - sioyek

### ISSUE THREAD

**Issue by smopucilowski** [chocolatey-community/chocolatey-package-requests#1490]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://sioyek.info/ , https://github.com/ahrm/sioyek
Direct download URL for the software / installer : https://github.com/ahrm/sioyek/releases/download/v2.0.0/sioyek-release-windows.zip
Software summary / short description: Sioyek is a PDF viewer with a focus on textbooks and research papers

**Comment by teknowledgist** [comment]
I got it.  (Don't ask me how to pronounce it! 😄 )  
Package submitted:  https://community.chocolatey.org/packages/sioyek
