### ISSUE TITLE
RFP - solid-edge

### ISSUE THREAD

**Issue by minjakas** [chocolatey-community/chocolatey-package-requests#1492]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/SolidEdgeCommunity/SolidEdge.Community
Direct download URL for the software / installer : https://intern.2f-leuchten.com/data/Solid_Edge_2024_2310.exe
Software summary / short description: Solid Edge is a portfolio of affordable, easy-to-use software tools that addresses all aspects of the product development process – 3D design, simulation, manufacturing, technical publications, data management, and more.

**Comment by pauby** [comment]
This hasn't been updated with a working download URL and I can't seem to find one. The software project URL points to an archived site.

Because of this, I'm going to close this request. We can always open it again if necessary.
