### ISSUE TITLE
RFP - nuzu

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1494]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/Nikilites/nuzu
Direct download URL for the software / installer : https://github.com/Nikilites/nuzu/releases/download/Nuzu/Windows-Nuzu.YUZU.-EA-4176.zip
Software summary / short description:
Nuzu is an open-source Nintendo Switch emulator

**Comment by Aurocosh** [comment]
All links are broken

**Comment by dtantono** [comment]
the project is dead
