### ISSUE TITLE
RFM - lidarr

### ISSUE THREAD

**Issue by JourneyOver** [chocolatey-community/chocolatey-package-requests#1499]
I am mostly stepping away from chocolatey as I do not really use it anymore and don't really have time to upkeep my packages (fixing issues or checking and seeing if everything is still working as it should be) I have been maintaining for a good while now, so I am currently on the lookout for someone to take over pretty much all my packages (I'll be creating an issue for each package).

-----------------------------------------------------------------------------------------------------------------

## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/lidarr
Package source URL: https://github.com/JourneyOver/chocolatey-packages/tree/5046f4d352f51a07a95bd40762275339949f6b81/automatic/lidarr

**Comment by mkevenaar** [comment]
I would like to take this one, @mkevenaar is my Chocolatey username

**Comment by JourneyOver** [comment]
@mkevenaar I have added you as a maintainer (that you need to accept), thanks for taking over the package.
