### ISSUE TITLE
RFM - prowlarr

### ISSUE THREAD

**Issue by JourneyOver** [chocolatey-community/chocolatey-package-requests#1505]
I am mostly stepping away from chocolatey as I do not really use it anymore and don't really have time to upkeep my packages (fixing issues or checking and seeing if everything is still working as it should be) I have been maintaining for a good while now, so I am currently on the lookout for someone to take over pretty much all my packages (I'll be creating an issue for each package).

-----------------------------------------------------------------------------------------------------------------

## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/prowlarr
Package source URL: https://github.com/JourneyOver/chocolatey-packages/tree/5046f4d352f51a07a95bd40762275339949f6b81/automatic/prowlarr

**Comment by JourneyOver** [comment]
@mkevenaar I have added you as a maintainer (that you need to accept), thanks for taking over the package.

As per #1498 I'll either fork and PR or you can manually add the packages to your repo (answer on whichever issue you want about which way you will want it to be done)

**Comment by mkevenaar** [comment]
I did not get an request for this one, I think.

As for a PR, feel free to submit a PR, that way you'll keep the credit for the code until I change it. This is valid for all packages

**Comment by JourneyOver** [comment]
> I did not get an request for this one, I think.

Hmm that is strange as I def added you 
![image](https://github.com/chocolatey-community/chocolatey-package-requests/assets/13910285/68ca805c-b84e-47dc-85dc-047a3464b3a8)


I'll remove and try sending it again though.

> As for a PR, feel free to submit a PR, that way you'll keep the credit for the code until I change it. This is valid for all packages

Alright sounds good! Will get a fork going and PR over everything to you here shortly :) Thanks again for taking over at least some of my packages ^^.

**Comment by JourneyOver** [comment]
@mkevenaar sent the request again, hopefully you got it this time?

**Comment by JourneyOver** [comment]
Not a problem -- working on PR right now before I go to bed so will shoot it over your way here shortly :)

**Comment by JourneyOver** [comment]
PR for all packages that you are taking over has been submited ( I didnt fill out the checklist as it was multiple packages in a single PR, but feel free to go through and change things as you see fit once you accept the PR ^^ )
