### ISSUE TITLE
RFM - tinymediamanager

### ISSUE THREAD

**Issue by JourneyOver** [chocolatey-community/chocolatey-package-requests#1509]
I am mostly stepping away from chocolatey as I do not really use it anymore and don't really have time to upkeep my packages (fixing issues or checking and seeing if everything is still working as it should be) I have been maintaining for a good while now, so I am currently on the lookout for someone to take over pretty much all my packages (I'll be creating an issue for each package).

-----------------------------------------------------------------------------------------------------------------

## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/tinymediamanager
Package source URL: https://github.com/JourneyOver/chocolatey-packages/tree/5046f4d352f51a07a95bd40762275339949f6b81/automatic/tinymediamanager

**Comment by AdmiringWorm** [comment]
As this is a software that I am personally using, I would like to take over the maintenance of this package.

@JourneyOver could you add me as an additional maintainer for this package?

**Comment by JourneyOver** [comment]
Sure thing @AdmiringWorm I will put you as an additional maintainer.

Are you going to add the package manually to your repo or you want me to fork and PR it over to you after?

**Comment by JourneyOver** [comment]
Sounds good! anyways I've disabled the update script on my side for this package so it doesn't try to auto update off my side. Thanks for taking over the package :)

**Comment by AdmiringWorm** [comment]
A new version of this package has been pushed and approved on Chocolatey Community Repository.
