### ISSUE TITLE
RFM - vortex

### ISSUE THREAD

**Issue by JourneyOver** [chocolatey-community/chocolatey-package-requests#1511]
I am mostly stepping away from chocolatey as I do not really use it anymore and don't really have time to upkeep my packages (fixing issues or checking and seeing if everything is still working as it should be) I have been maintaining for a good while now, so I am currently on the lookout for someone to take over pretty much all my packages (I'll be creating an issue for each package).

-----------------------------------------------------------------------------------------------------------------

## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/vortex
Package source URL: https://github.com/JourneyOver/chocolatey-packages/tree/5046f4d352f51a07a95bd40762275339949f6b81/automatic/vortex

**Comment by pauby** [comment]
I'll pick this one up. Username is `pauby`.

**Comment by JourneyOver** [comment]
@pauby I have added you as a maintainer (that you need to accept), thanks for taking over the package.

As per https://github.com/chocolatey-community/chocolatey-package-requests/issues/1508 I'll either fork and PR or you can manually add the packages to your repo (answer on whichever issue you want about which way you will want it to be done)

**Comment by pauby** [comment]
@JourneyOver thank you for the offer but I can't ask you to do that.

You've done enough as a package maintainer (and thank you for doing that!). I'll move the package over. 

Do you want me to submit a PR to remove it from your repository when I've moved it over (which will likely be this week)?

**Comment by JourneyOver** [comment]
Answered in #1508

**Comment by pauby** [comment]
@JourneyOver both this and the[ `streamlabs-obs`](https://github.com/JourneyOver/chocolatey-packages/issues/70) package have been migrated over to my repository ([`vortex`](https://github.com/pauby/ChocoPackages/commit/5414ce05f442d1a0358e91dbf9ee1b0c62292bf4) and [`streamlabs-obs`](https://github.com/pauby/ChocoPackages/commit/c9951c82dfcd2d6a4645dd0b4bea3db68cc59221)).

I'll go ahead and close this now.
