### ISSUE TITLE
RFM - bonjour

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#1514]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/bonjour
Package source URL: https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/bonjour

**Comment by tunisiano187** [comment]
Currently solved thanks to one of the users.

**Comment by pauby** [comment]
@tunisiano187 can you be clearer about what was solved. The labels on the issue, now that it's closed, are incorrect.

**Comment by tunisiano187** [comment]
A user gave me the new way (i didn't found it myself) to install it, so i've pushed a newer version of the bonjour package that works well.
So no need to find another maintainer that can find one.
