### ISSUE TITLE
RFP - en-croissant

### ISSUE THREAD

**Issue by klonislaw** [chocolatey-community/chocolatey-package-requests#1520]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://encroissant.org/
Direct download URL for the software / installer : https://github.com/franciscoBSalgueiro/en-croissant/releases/download/v0.10.0/en-croissant_0.10.0_x64_en-US.msi
Software summary / short description: An open-source, cross-platform chess GUI that aims to be powerful, customizable and easy to use.

**Comment by brogers5** [comment]
I'll pick this one up.

**Comment by brogers5** [comment]
v0.10.0 has been packaged, submitted, and is now awaiting moderator approval.

https://community.chocolatey.org/packages/en-croissant/0.10.0

**Comment by brogers5** [comment]
Package has been approved and should now be available for consumption.

Issue can be closed.
