### ISSUE TITLE
RFM - flac

### ISSUE THREAD

**Issue by Spunkie** [chocolatey-community/chocolatey-package-requests#1521]
The `flac` package is stuck on version `1.3.2` and is missing releases for `1.4.0`, `1.4.1`, `1.4.2`, and finally `1.4.3`. 

Manually putting together the packages for these new versions is fairly easy but I haven't used windows for years now and am unable to actually test them. So I'm looking for a new maintainer to take over.

## Current Maintainer
- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist
- [x] Issue title starts with 'RFM - ';

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/flac
Package source URL: https://github.com/Spunkie/chocolatey-packages/blob/master/automatic/flac/tools/chocolateyInstall.ps1
___
I'm pretty sure an updated `chocolateyInstall.ps1` for this would look something like this:
```powershell
$ErrorActionPreference = 'Stop'
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$packageArgs = @{
    packageName   = 'flac'
    unzipLocation = $toolsDir
    fileType      = 'ZIP'
    url           = 'http://downloads.xiph.org/releases/flac/flac-1.4.3-win.zip'
    checksum      = '4cca0acfa829921ab647f48e83f4b40288f2018d7819f0b15230d3992c13c966'
    checksumType  = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs


$packageVersion = '1.4.3'
$installFolder = "flac-$packageVersion-win"

if (Get-OSArchitectureWidth -eq 64) {
	Remove-Item -Recurse (Join-Path "$toolsDir" (Join-Path "$installFolder" 'Win32'))
} else {
	Remove-Item -Recurse (Join-Path "$toolsDir" (Join-Path "$installFolder" 'Win64'))
}
```

Also awhile ago, a user reported in a comment that:

> This installs the 64bit version on 32bit systems! It deletes the tools\win32 folder and links to the tools\win64 folder. Of course, there maybe something wrong in my installation. Does anyone else have the same problem?

But again I don't have a windows environment to actually investigate.

**Comment by pauby** [comment]
I'll pick this and the [flac-frontend](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1163) package up.

**Comment by pauby** [comment]
I've now been added as a maintainer of this package.
