### ISSUE TITLE
RFM - tortoisesvn

### ISSUE THREAD

**Issue by tanareed** [chocolatey-community/chocolatey-package-requests#1524]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/tortoisesvn
Package source URL: https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/tortoisesvn

Date the maintainer was contacted (in YYYY-MM-DD): 2024-01-04, contacted again 2024-04-26 after another update.
How the maintainer was contacted: Contact Maintainers link, Disqus thread, pinging the maintainers on the existing thread in package source issues (https://github.com/chocolatey-community/chocolatey-packages/issues/2413).

**Comment by pauby** [comment]
This is maintained by the Chocolatey Community Chocolatey Packages team. Please use the Package Source link, on the package page, to search for or raise issues.
