### ISSUE TITLE
RFM - hashcat

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#1527]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/hashcat
Package source URL: https://github.com/hashcat/hashcat

Date the maintainer was contacted (in YYYY-MM-DD): 2024-05-17
How the maintainer was contacted: Via contact maintainers. The maintainer responded and requested that I open a RFM issue.

**Comment by tunisiano187** [comment]
I'll take it

**Comment by tunisiano187** [comment]
FYI, it's ready, i've requested the maintainer to add me as maintainer (maybe should i request it to the admins directly ? as it's not him/her that requested a new maintainer)

**Comment by TheCakeIsNaOH** [comment]
It looks like you were added as a maintainer, and a package version has been approved. 

In the future, for RFM issues that are not by the current maintainer, go ahead and use contact site admins to request to get added to the package.
