### ISSUE TITLE
RFM - ledger-live

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-package-requests#1530]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

Existing Package Details
Package URL: https://community.chocolatey.org/packages/ledger-live
Package source URL: https://www.ledger.com/ledger-live

Date the maintainer was contacted (in YYYY-MM-DD): 2024-05-22
New version 2.81.2 is available.

How the maintainer was contacted: Via contact maintainers package link. Also opened issue on 2024-05-28 at maintainer's github: https://github.com/RalfEs73/chocolatey-packages/issues

No response from maintainer.

**Comment by mstick99** [comment]
## I DON'T Want To Become The Maintainer
- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [ ] There is no existing open maintainer request for this package;
## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

**Comment by pauby** [comment]
@mstick99 You need to make the changes in the very first description above.

**Comment by brogers5** [comment]
I'll pick this one up.

**Comment by brogers5** [comment]
Maintainer role has been secured.

I've been working through the package handover process and implementing some improvements in parallel. Should have an up-to-date package pushed later today if all goes well.

**Comment by brogers5** [comment]
v2.81.2 has been submitted, and is now working its way through the moderation process.

https://community.chocolatey.org/packages/ledger-live/2.81.2

**Comment by brogers5** [comment]
Package has been approved and should now be available for consumption.

Issue can be closed.
