### ISSUE TITLE
RFP - kiwix

### ISSUE THREAD

**Issue by Elaborendum** [chocolatey-community/chocolatey-package-requests#1533]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://kiwix.org
Direct download URL for the software / installer : https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip
Software summary / short description: Kiwix is an offline reader for online content like Wikipedia, Project Gutenberg, or TED Talks. It makes knowledge available to people with no or limited internet access. The software as well as the content is free to use for anyone.

## Package Expectations

As it is, the link above downloads a zip file that has to be extracted, but Kiwix isn't really "installed" anywhere. So perhaps it should be better for it to get a proper Start Menu and Desktop shortcut.

Additionally, I see this had a previous request and a even older entry in https://community.chocolatey.org/packages/kiwix, but that seemed to be rejected just because of the wrong package name.

**Comment by pauby** [comment]
You have requested a package be created for a package that already exists. As there is nothing to do here, the issue was closed.
