### ISSUE TITLE
RFP - ab-download-manager

### ISSUE THREAD

**Issue by dnet890** [chocolatey-community/chocolatey-package-requests#1535]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://abdownloadmanager.com/
Direct download URL for the software / installer :https://github.com/amir1376/ab-download-manager/releases/download/v1.0.7/ABDownloadManager_1.0.7_windows.msi
Software summary / short description:
AB Download Manager is a desktop app which lets you manage and organize your download files better than before

**Comment by Aurocosh** [comment]
Package added
Install version: [https://community.chocolatey.org/packages/ab-download-manager](https://community.chocolatey.org/packages/ab-download-manager)
Portable version: [https://community.chocolatey.org/packages/ab-download-manager.portable](https://community.chocolatey.org/packages/ab-download-manager.portable)

**Comment by Aurocosh** [comment]
Both packages are approved
