### ISSUE TITLE
RFP - zotero-x64

### ISSUE THREAD

**Issue by Elaborendum** [chocolatey-community/chocolatey-package-requests#1536]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://zotero.org
Direct download URL for the software / installer : https://www.zotero.org/download/client/dl?channel=release&platform=win-x64
Software summary / short description:  Zotero [zoh-TAIR-oh] is a free, easy-to-use tool to help you collect, organize, cite, and share your research sources. 

## Package Expectations

This is the newly released 64bit version of Zotero, currently Chocolatey only has the 32bit version. If possible, some way of picking between this one or the 32bit version depending on the user's device would be ideal.

**Comment by pauby** [comment]
> This is the newly released 64bit version of Zotero, currently Chocolatey only has the 32bit version. If possible, some way of picking between this one or the 32bit version depending on the user's device would be ideal.

As you indicated, this package already exists. Chocolatey supports different architectures in the same package so a new package is not needed.

Please contact the current package maintainer.

**Comment by pauby** [comment]
Use the Package Source link (from the package page) to search for an issue that is asking for this. If it doesn't exist, create one.
