### ISSUE TITLE
RFP - regedix

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#1537]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://regedix.webrox.fr/
Direct download URL for the software / installer : https://regedix.webrox.fr/download.php?v=2.0.0.0&file=2.0.0.0/Regedix_installer-2.0.0.exe
Software summary / short description: Windows Registry editor. Breadcrumb navigation, favorites, dark theme...

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/regedix

**Comment by Aurocosh** [comment]
Package approved
