### ISSUE TITLE
RFP - miru

### ISSUE THREAD

**Issue by dnet890** [chocolatey-community/chocolatey-package-requests#1539]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://miru.watch/
Direct download URL for the software / installer :https://github.com/ThaUnknown/miru/releases/download/v5.5.6/win-Miru-5.5.6-installer.exe
Software summary / short description:
an anime streaming application.

**Comment by Aurocosh** [comment]
Package created: https://community.chocolatey.org/packages/miru

**Comment by Aurocosh** [comment]
Package approved
