### ISSUE TITLE
RFM - cuetools

### ISSUE THREAD

**Issue by wadoli** [chocolatey-community/chocolatey-package-requests#1542]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else.

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/cuetools
Package source URL: https://github.com/wadoli/chocolatey-pkg-cuetools

**Comment by wadoli** [comment]
wadoli /confirm your-chocolatey-username

**Comment by pauby** [comment]
@wadoli can you please read what you're typing and read the comment that is asking you to type it.

What does it say?

**Comment by wadoli** [comment]
> @wadoli can you please read what you're typing and read the comment that is asking you to type it.
> 
> What does it say?

Thank you, It's late at night here and this process is somewhat tedious, given that my GitHub username and my chocolatey community username are identical and that I've added my GitHub username to my chocolatey community profile ...

**Comment by pauby** [comment]
> this process is somewhat tedious

With all respect @widoli, it asked you to add one comment, in a specific format, confirming your username. I disagree that its tedious.

> I've added my GitHub username to my chocolatey community profile

That is just a profile link. It's not used here as it could be anything (I could add yours for example, and you, mine).

**Comment by wadoli** [comment]
Thanks for your reply, @pauby 

It was a somewhat grumpy late night feedback, sorry for that. I was tired and didn't read enough, granted.

If I might add some more "user story" context: The journey didn't start here on GitHub, it started on the chocolatey community pages. From a user perspective it would be nice to have a big button on the users community profile page under each package, saying "Find new maintainer" or something.

Less of a change: It might have helped my tired brain to somehow mark the expected parameter, e.g. /confirm **[** your-chocolatey-username **]**

Anyway, thank you for keeping chocolatey tidy, I got a lot of use out of it, while I could use it. 👋

**Comment by pauby** [comment]
> it would be nice to have a big button on the users community profile page under each package, saying "Find new maintainer" or something.

That's maybe something we could explore by adding a link to this repository. I've [raised an issue for that](https://github.com/chocolatey/home/issues/331).

> Less of a change: It might have helped my tired brain to somehow mark the expected parameter, e.g. /confirm [ your-chocolatey-username ]

Agreed. I've raised a [PR for this](https://github.com/chocolatey-community/chocolatey-package-requests/pull/1544) to make it clearer.

> Anyway, thank you for keeping chocolatey tidy, I got a lot of use out of it, while I could use it. 👋

Thank you for maintaining the packages. We're sorry to see you leave!

**Comment by wadoli** [comment]
I noticed and was very impressed by your speed! 🚀 Thank you @pauby !

**Comment by wadoli** [comment]
Hi @tunisiano187 

Thank you for reaching out! I've added you as a package maintainer.

Good luck!
