### ISSUE TITLE
RFM - protonpass

### ISSUE THREAD

**Issue by wadoli** [chocolatey-community/chocolatey-package-requests#1543]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else.

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/protonpass
Package source URL: https://github.com/wadoli/chocolatey-pkg-protonpass

**Comment by tunisiano187** [comment]
Hello,
I'll take the maintainer role.
Can you add me as maintainer ?
tunisiano

**Comment by wadoli** [comment]
Hi @tunisiano187 

That's great news, thank you! I've added you as a package maintainer.

Thank you and good luck!

**Comment by wadoli** [comment]
Thank you, @tunisiano187 

Feel free to remove me, I won't be able to contribute (because 🍫 isn't for 🐧🐧).

**Comment by tunisiano187** [comment]
You can close the issue.
Have a nice day
