### ISSUE TITLE
RFM - calibre

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-package-requests#1545]
- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package.
- [X] There is no existing open maintainer request for this package.

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://community.chocolatey.org/packages/calibre
Package source URL: https://download.calibre-ebook.com/7.18.0/calibre-64bit-7.18.0.msi

Date the maintainer was contacted (in YYYY-MM-DD): maintainer not accepting emails
How the maintainer was contacted: maintainer not accepting emails

**Comment by mkevenaar** [comment]
The `chocolatey-community` user maintains this package. This is a community-maintained user and repository. An issue for the outdated calibre package has already been created there: https://github.com/chocolatey-community/chocolatey-packages/issues/2538
