### ISSUE TITLE
RFP - dra

### ISSUE THREAD

**Issue by sebma** [chocolatey-community/chocolatey-package-requests#1546]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/devmatteini/dra
Direct download URL for the software / installer : https://github.com/devmatteini/dra/releases/latest/download/dra-0.6.2-x86_64-pc-windows-msvc.zip
Software summary / short description: A command line tool to download release assets from GitHub

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/dra

**Comment by sebma** [comment]
@Aurocosh Great thanks, can you please leave a comment here once it's approved so I can install it via chocolatey ?

**Comment by Aurocosh** [comment]
Yeah, i'll comment here when it's approved

**Comment by Aurocosh** [comment]
Package approved
