### ISSUE TITLE
RFP - intellifile

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-package-requests#1547]
Checklist
- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

Package Details

Software project URL :  https://github.com/mihaimoga/IntelliFile
Direct download URL for the software / installer : https://github.com/mihaimoga/IntelliFile/releases/tag/v1.33
Software summary / short description: IntelliFile is an alternative Windows version to the famous Total Commander

**Comment by mstick99** [comment]
Direct download URL for the software / installer: https://github.com/mihaimoga/IntelliFile/releases/download/v1.33/IntelliFileSetup.msi

**Comment by pauby** [comment]
You need to update the description above with that file name, not in a comment.

**Comment by Aurocosh** [comment]
Package added
Install: https://community.chocolatey.org/packages/intellifile
Portable: https://community.chocolatey.org/packages/intellifile.portable

**Comment by Aurocosh** [comment]
Package approved
