### ISSUE TITLE
RFP - rix

### ISSUE THREAD

**Issue by sebma** [chocolatey-community/chocolatey-package-requests#1549]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/rh/rix
Direct download URL for the software / installer : https://github.com/rh/rix/archive/refs/tags/v0.2.0.tar.gz
Software summary / short description: Command-line XML editing and refactoring

**Comment by pauby** [comment]
This doesn't appear to be a Windows binary. Installation is through Ruby gems, and it was last updated in 2011. This is not a good candidate for a package.
