### ISSUE TITLE
RFM - squeezelite-x

### ISSUE THREAD

**Issue by annomatik** [chocolatey-community/chocolatey-package-requests#1550]
## Current Maintainer

needs_new_maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else.

## I DON'T Want To Become The Maintainer

- [ ] The maintainer is not `needs_new_maintainer`.
- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package.
- [ ] The last attempt to contact the maintainer was _at least_ 7 days ago.
- [X] There is no existing open maintainer request for this package.

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/squeezelite-x
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD):
How the maintainer was contacted:

**Comment by pauby** [comment]
There is a tickbox that says  `The maintainer is not needs_new_maintainer.` and this having that maintainer means that you cannot use this to request a new maintainer.
