### ISSUE TITLE
RFP - lan-mouse

### ISSUE THREAD

**Issue by hapnan** [chocolatey-community/chocolatey-package-requests#1551]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/feschber/lan-mouse
Direct download URL for the software / installer : https://github.com/feschber/lan-mouse/releases/download/v0.9.1/lan-mouse-windows.zip
Software summary / short description: mouse & keyboard sharing via LAN

**Comment by Aurocosh** [comment]
Package created: https://community.chocolatey.org/packages/lan-mouse

**Comment by Aurocosh** [comment]
Package approved
