### ISSUE TITLE
RFP - 7-zip-zstd

### ISSUE THREAD

**Issue by sebma** [chocolatey-community/chocolatey-package-requests#1556]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/mcmilk/7-Zip-zstd
Direct download URL for the software / installer : https://github.com/mcmilk/7-Zip-zstd/releases/download/v22.01-v1.5.5-R3/7z22.01-zstd-x64.exe
Software summary / short description : 7-Zip with support for Brotli, Fast-LZMA2, Lizard, LZ4, LZ5 and Zstandard

**Comment by pauby** [comment]
[This package already exists](https://community.chocolatey.org/packages/7zip-zstd).

**Comment by sebma** [comment]
@pauby My bad, I don't know how I missed this. I must have been tired.
