### ISSUE TITLE
RFP - crip

### ISSUE THREAD

**Issue by sebma** [chocolatey-community/chocolatey-package-requests#1557]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Hakky54/certificate-ripper
Direct download URL for the software / installer : https://github.com/Hakky54/certificate-ripper/releases/download/2.3.0/crip-windows-amd64.zip
Software summary / short description : A CLI tool to extract server certificates

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/crip

**Comment by Aurocosh** [comment]
Package approved
