### ISSUE TITLE
RFP - sourcegit

### ISSUE THREAD

**Issue by gadfly3173** [chocolatey-community/chocolatey-package-requests#1558]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/sourcegit-scm/sourcegit
Direct download URL for the software / installer : https://github.com/sourcegit-scm/sourcegit/releases/download/v8.36/sourcegit_8.36.win-x64.zip
  - x64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.36/sourcegit_8.36.win-x64.zip
  - arm64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.36/sourcegit_8.36.win-arm64.zip

Software summary / short description: Open-source & Free Git GUI Client

**Comment by Aurocosh** [comment]
Package approved
