### ISSUE TITLE
RFM - DNSCrypt Proxy

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#156]
https://chocolatey.org/packages/dnscrypt-proxy

I don't want to maintain it anymore.

**Comment by zero77** [comment]
Why don’t you move the Install.ps1 and update.ps1 to 
github.com/chocolatey/chocolatey-coreteampackages

**Comment by chtof** [comment]
Ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/dnscrypt-proxy, just waiting to be added as maintainer (request sent) and review.

**Comment by chtof** [comment]
Updated version under review: https://chocolatey.org/packages/dnscrypt-proxy/2.0.22

**Comment by chtof** [comment]
Status: closed
