### ISSUE TITLE
RFP - nix

### ISSUE THREAD

**Issue by Ericson2314** [chocolatey-community/chocolatey-package-requests#1560]
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://nixos.org/
Windows port chat room: https://matrix.to/#/#windows:nixos.org
Direct download URL for the software / installer : https://github.com/nixos/nix
Software summary / short description: Nix is a package manager with an currently-in-progress Windows port.

## Package Expectations

First of all, we completely understand if it is premature to ask this before our Windows port is finished. (It currently does build, but some key features are missing.)

The most selfish reason we are asking is we'd love more ways to get development environments for Nix as we work on it. The middle reason is the port should still be done, and then we want as many way for Windows users to try out Nix as possible. The most collaborative reason is running Nix on Windows is just the first step; having good package definitions is just as important. We'd love to learn from the and share knowledge with the existing Windows-supporting package managers as much as possible in this regard.

**Comment by Ericson2314** [comment]
I'm not sure what to do about this notice, since this package is supposed to be built from source! We do have cross-to-windows builds in CI, but I doubt you will want to use those.

**Comment by pauby** [comment]
> since this package is supposed to be built from source! 

Chocolatey uses the native installers to install the software. While it's possible to built packages from source as part of a Chocolatey package, it's not something that would be accepted on the Chocolatey Community Repository. If the build requirements are pretty light, it may be accepted.

Worthwhile asking in the [Community Hub](https://ch0.co/community).

**Comment by Ericson2314** [comment]
Hmm OK, it sounds like I have misunderstood what chocolatey is. I thought it was more directly competing with the likes of vcpkg, msys (but no mingw assumption), etc.

**Comment by pauby** [comment]
> I thought it was more directly competing with the likes of vcpkg, msys

vcpkgs is generally used for managing and building libraries. msys is a development environment. So I['m a little confused.

Chocolatey CLI is the package manager for Windows. It manages packages similarly to apt, yum, dnf, brew etc. As mentioned, you should ask about how best to package this in the [Community Chat](https://ch0.co/community).

**Comment by pauby** [comment]
@Ericson2314 My goal was to try to help with your understanding of what both Chocolatey CLI and Chocolatey Community Repository are, and on how software built from source has been received in the past for the community maintained repository. If you are discussing this on the Community Hub, then having a separate discussion here feels counterproductive.

Chocolatey packages can absolutely do what you need. That is not the issue. The issue is whether it would be accepted on the community maintained, Chocolatey Community Repository.

I need to understand if this issue stays open (i.e. the Community Moderators would accept a package that is built with the artefacts you have) or should be closed.

**Comment by Ericson2314** [comment]
Nothing was redundant; I already joined the discord but didn't discuss things there yet.

> My current need is to understand if this issue stays open (i.e. the Community Moderators would accept a package that is built with the artefacts you have) or should be closed.

I am fine closing it for now. I don't think we yet have the needed artifacts. I can reopen it once we do. At that point I think we would be accepted, as Nix is a major software project.
