### ISSUE TITLE
RFP - gyroflow

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#1562]
## Checklist

- [X] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://gyroflow.xyz/
Direct download URL for the software / installer : https://github.com/gyroflow/gyroflow/releases/download/v1.6.0/Gyroflow-windows64.zip
Software summary / short description:  Gyroflow is an application that can stabilize your video by using motion data from a gyroscope and optionally an accelerometer.

Winget package for reference: https://github.com/microsoft/winget-pkgs/pull/190807/files

**Comment by Aurocosh** [comment]
Package added: https://community.chocolatey.org/packages/gyroflow

**Comment by Aurocosh** [comment]
Package approved
