### ISSUE TITLE
RFP - zVirtualDesktop

### ISSUE THREAD

**Issue by mzomparelli** [chocolatey-community/chocolatey-package-requests#178]
I'm trying to create a package on my own, but I'm having trouble figuring it out.

zVirtualDesktop is a utility for managing Windows 10 Virtual Desktops. Requires only the EXE itself, no external libraries.
-Configurable hotkeys
-Set different wallpapers for each desktop
-Name desktops
-System Tray Icons
-DesktopView - A TaskView replacement

https://github.com/mzomparelli/zVirtualDesktop

The most current build can always be grabbed from this link. This link downloads the EXE only.
https://zomp.co/files.aspx?id=zvdexe

A link to a zip file containing the most current build.
https://zomp.co/files.aspx?id=zvd

EDIT:
https://github.com/mzomparelli/zVirtualDesktop/issues/96

**Comment by mzomparelli** [comment]
Is it possible for Chocolatey to install the exe (or a shortcut) to the user's startup folder? Sorry, I'm new to Chocolatey. I can modify zVirtualDesktop as necessary. Please let me know.

**Comment by mzomparelli** [comment]
Was I wrong to create an issue here? I'm only here because my users want it and I'm unable to figure it out on my own.

**Comment by AdmiringWorm** [comment]
@mzomparelli it isn't really wrong, but the wording from your initial post seem to be that you are actually creating the package yourself, rather than requesting a maintainer to create this package.

If it's the former, then it's better to reach out on the [gitter channel](https://gitter.im/chocolatey/choco).
If it's the later, then you just need to be patient until a maintainer picks this package up.

**Comment by mzomparelli** [comment]
Thanks @AdmiringWorm , I was looking to do it myself, but it seems overly complicated so I decided to come here and let someone else do it. I would be interested in seeing how it is packaged so that I can learn from it.

**Comment by AdmiringWorm** [comment]
I see, in that case you just need to be patient and until a maintainer is willing to pick it up.

**Comment by bcurran3** [comment]
@mzomparelli I'd like to encourage you to make the package yourself.

Read: https://github.com/chocolatey/choco/wiki/CreatePackages

Then use this as a template: https://chocolatey.org/packages/raidar everything you need is there.

**Comment by mzomparelli** [comment]
Thanks @bcurran3, I'll give it a try.

**Comment by chtof** [comment]
- Software is not listed in "Program and features".
- No uninstaller found in standard folders.

 @mzomparelli : Hi, could you tell us the way to uninstall properly zVirtualDesktop ?

**Comment by mzomparelli** [comment]
*	Delete the exe
*	Delete Folder: C:\Users\[User]\AppData\Roaming\zVirtualDesktop
*	Registry Key: Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\zVirtualDesktop

 

Those are the only files that zVirtualDesktop creates.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/zvirtualdesktop

**Comment by mzomparelli** [comment]
Yes, I can do that.

**Comment by chtof** [comment]
Status: closed
