### ISSUE TITLE
RFM - Ace Stream

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#184]
Ace Stream is an innovative media platform of a new generation, which will take you to a new high-quality level of multimedia space on the Internet.

https://chocolatey.org/packages/acestream

I'm seeking for a new maintainer.

**Comment by chtof** [comment]
- Ready to be published for review: https://github.com/chtof/chocolatey-packages/tree/master/automatic/acestream
- Status: Request just sent to be added as maintainer.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/acestream
