### ISSUE TITLE
RFM - Dexpot

### ISSUE THREAD

**Issue by brianmego** [chocolatey-community/chocolatey-package-requests#190]
Do not do enough Windows development to justify being the main maintainer of this package any longer. 

Source for the existing package exists here: https://github.com/brianmego/Chocolatey

**Comment by tunisiano187** [comment]
Hi, i've created the package, i'll ask for the maintainership.

**Comment by tunisiano187** [comment]
Can you assign it to me ? to ease the followup.
Thank you

**Comment by tunisiano187** [comment]
Thank @pauby for adding me on others, can you add me here too ?
i'll try to work on the oldest to close most of them (limited by my knowledge)

**Comment by pauby** [comment]
> can you add me here too ?

If you mean add you to this issue, I'll do that.

If you mean add you to this package then you need to follow the same process for each package - either @brianmego can add you or you can send a message to the Site Admins referencing this issue.

**Comment by tunisiano187** [comment]
Yes it was for this issue ;-) thank you
I've asked for the maintainership with the form for maintainers, i'm waiting for the triage process

**Comment by tunisiano187** [comment]
yes, that's just tunisiano on chocolatey.

**Comment by tunisiano187** [comment]
Package sent (10 Jun 2020) waiting for review

**Comment by tunisiano187** [comment]
This package as been approved, so the issue can be closed.
Thank you
