### ISSUE TITLE
RFP - SkyMPC

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#202]
SkyMPC is a simple MPD (Music Player Daemon) client, powered by Qt5.

http://www.soramimi.jp/skympc/

**Comment by majkinetor** [comment]
Meh... 
cantata is alraedy available

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/skympc

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/skympc

Can be closed.
