### ISSUE TITLE
RFP - B1 Free Archiver

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#208]
B1 Free Archiver is a cross-platform file archiver and file manager.

https://www.b1.org/windows/

https://b1.org/download-windows

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/b1freearchiver

**Comment by chtof** [comment]
Status: **Rejected***
_* due to high AV detection count._

- https://chocolatey.org/packages/b1freearchiver

Can be closed.
