### ISSUE TITLE
RFP - Sublight

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#210]
Sublight is very popular and easy to use application for automatic searching and downloading subtitles for your movies and TV series. It is suitable for total beginners as well as advanced users.

Sublight automates multiple boring and time-consuming tasks into single double-click action and saves your precious time. Is downloaded subtitle not good enough for you? No problem, just double-click next one in list!

http://www.sublight.me/

**Comment by chtof** [comment]
Don't know if it's for a long time but https://www.sublight.me displays a message _"Sorry, we are currently not accepting new registrations."_
- There is no explaination in https://www.sublight.me/history
- The download link displayed in https://www.sublight.me/history redirect also to _"Sorry, we are currently not accepting new registrations."_

Maybe to reject if no change within a few months?

**Comment by pauby** [comment]
What is people who already have registrations? Or can you not download unless you have a registration? I may have missed the reason why registrations are relevant for the package.

**Comment by chtof** [comment]
I have no more information.
The download link redirect to the homepage without asking for an authentication.
https://www.sublight.me/premium/ redirect also to the homepage.

It can be a dead site.

**Comment by AdmiringWorm** [comment]
Hmm, could be that they have encountered some issues that they need to resolve before they can let any new user on the platform.

I'll mark it as blocked upstream for now, and if it's still down after a few months we can probably close this issue.

**Comment by chtof** [comment]
The site is still down pretty 6 months later so what about to close it?

**Comment by pauby** [comment]
@AdmiringWorm suggested this too so agreed. Should the situation change we can always re-open it.
