### ISSUE TITLE
RFP - Umbrello UML Modeller

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#220]
Umbrello UML Modeller is a Unified Modelling Language (UML) diagram program based on KDE Technology. UML allows you to create diagrams of software and other systems in a standard format to document or design the structure of your programs.

https://umbrello.kde.org/

**Comment by chtof** [comment]
Status: **Review**

https://chocolatey.org/packages/umbrello
https://chocolatey.org/packages/umbrello.install
https://chocolatey.org/packages/umbrello.portable

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/umbrello
- https://chocolatey.org/packages/umbrello.install
- https://chocolatey.org/packages/umbrello.portable

Can be closed.
