### ISSUE TITLE
RFP - asciinema

### ISSUE THREAD

**Issue by dodjango** [chocolatey-community/chocolatey-package-requests#221]
asciinema is a command line Utility to record terminal sessions and share them.
https://asciinema.org/

**Comment by AdmiringWorm** [comment]
It seems like they don't provide any compiled binary for windows, as such a package for this software isn't possible until they do.

As such, I'm closing this request, feel free to reopen it if they start providing one in the future.

**Comment by AdmiringWorm** [comment]
hmm, seems like I was a little hasty, seems like they provide it through pip.
Opening the request again.

**Comment by chtof** [comment]
The installation with pip is not compatible with Windows:

```
python -m pip install asciinema==2.0.2
(...)
Collecting asciinema==2.0.2
  Downloading https://files.pythonhosted.org/packages/a7/71/771c859795e02c71c187546f34f7535487b97425bc1dad1e5f6ad2651357/asciinema-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\******\Temp\pip-install-0phbj0zg\asciinema\setup.py", line 1, in <module>
        import asciinema
      File "C:\******\Temp\pip-install-0phbj0zg\asciinema\asciinema\__init__.py", line 15, in <module>
        import asciinema.pty as pty
      File "C:\******\Temp\pip-install-0phbj0zg\asciinema\asciinema\pty.py", line 3, in <module>
        import fcntl
    ModuleNotFoundError: No module named 'fcntl'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\******\Temp\pip-install-0phbj0zg\asciinema\
```
Regarding the error _"ModuleNotFoundError: No module named 'fcntl'"_, according https://github.com/cs01/gdbgui/issues/18, the fcntl module is for unix(like) systems only.

So, if you agree, we can close this case.

**Comment by chtof** [comment]
According https://asciinema.org/a/135330,
- Windows bash shell needs to be installed:
https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10                  
- Install python3-pip from the Windows bash shell:                                                                                               
```
apt-get install python3-pip
pip3 install asciinema
asciinema rec
```

**Comment by chtof** [comment]
So, the chocolatey package should:
if (Windows bash shell is not installed)
  Write "Under Windows, Asciinema runs only with a Windows Bash Shell.  See https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10 to activate it.)
else
  bash -c "apt-get install --yes python3-pip ; python3 -m pip install asciinema==2.0.2"

**Comment by Mugane** [comment]
No, it's not useless. It's completely reasonable to expect to be able to use one package manager to install everything, and since it's so simple to do, there is no reason that it shouldn't be done in Chocolatey. For example, I had to do a web search and read through this entire thread to figure out that I needed to use the apt-get to install it, and that would not have been necessary if there was a package that did it. Which is basically why Chocolatey exists in the first place. Please re-open.

**Comment by TheCakeIsNaOH** [comment]
@Mugane Chocolatey is a windows package manager, not a Linux package manager. This piece of software appears to not be windows compatible, therefore, it is not appropriate for a Chocolatey package to be created for it. Sure, you can run it indirectly on a Windows system, but only via WSL or another emulation/virtualization effort. 

Chocolatey does have the ability to call other package managers via alternate sources (e.g. pip, ruby gems, windows features, etc), so you can install things from those places directly through Chocolatey. It does not support apt via WSL, but there is a feature request open here: https://github.com/chocolatey/choco/issues/678

If that gets implemented into Chocolatey, you should be able to do `choco install asciinema --source=wsl-apt` or similar.
