### ISSUE TITLE
RFM - GravitDesigner

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey-community/chocolatey-package-requests#228]
https://chocolatey.org/packages/GravitDesigner/3.1.3

**Comment by chtof** [comment]
Status: **In progress**

- Request sent to be added as maintainer of this package.
- Updated packages ready to be pushed:
https://github.com/chtof/chocolatey-packages/tree/master/automatic/gravitdesigner
https://github.com/chtof/chocolatey-packages/tree/master/automatic/gravitdesigner.install
https://github.com/chtof/chocolatey-packages/tree/master/automatic/gravitdesigner.portable

**Comment by chtof** [comment]
Status; **Review**
https://www.chocolatey.org/packages/GravitDesigner/3.5.14

**Comment by chtof** [comment]
Status: **Published**

- https://www.chocolatey.org/packages/GravitDesigner/3.5.14
- https://www.chocolatey.org/packages/gravitdesigner.install/3.5.14
- https://www.chocolatey.org/packages/gravitdesigner.portable/3.5.14

Can be closed.
