### ISSUE TITLE
RFP SonarLint for Visual Studio 2017

### ISSUE THREAD

**Issue by sumo300** [chocolatey-community/chocolatey-package-requests#237]
SonarLint spots bugs and quality issues as fast as you code.

https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/sonarlint-vs2017

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/sonarlint-vs2017

Can be closed.
