### ISSUE TITLE
RFP - HelixALM

### ISSUE THREAD

**Issue by kcclemo** [chocolatey-community/chocolatey-package-requests#241]
It would be nice to have the HelixALM client added to the repository:
https://www.perforce.com/downloads/helix-alm-client

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/helix-alm-client

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/helix-alm-client

Can be closed.
