### ISSUE TITLE
RFM - uncrustify

### ISSUE THREAD

**Issue by stephengroat** [chocolatey-community/chocolatey-package-requests#245]
Currently have a PR (https://github.com/StevenWolfe/choco-uncrustify/pull/1) with whom I believe to be the current maintainer, but haven't seen any movement.

Need an update or some stable version to be pushed

I can work on it, i just need it opened up

**Comment by AdmiringWorm** [comment]
lets give @StevenWolfe a few more days before we open this request up for new maintainers.

**Comment by stephengroat** [comment]
no problem, sounds good!

**Comment by stephengroat** [comment]
@AdmiringWorm StevenWolfe/choco-uncrustify#1 was merged, but still no updated package pushed.

i'm giving another week to try to get the package updated

**Comment by AdmiringWorm** [comment]
@stephengroat I had a look at the package source he is hosting on the github repo, and if he pushes the package as it currently stands in the repo it won't be approved at the community repo.

Three of the files that will be included in the package is just the template values, and shouldn't be included in those cases. as well as the uninstall script needs to be cleaned up (removing unneeded comments).

**Comment by AdmiringWorm** [comment]
@stephengroat I've also tried to get in contact with the maintainer of this package, with no luck.
If you still want to become the maintainer of the package, just respond here as well as sending of a message to the site admins on the package page.

If you don't want to become the maintainer anymore, I could take over it myself (just let me know if you don't).

**Comment by stephengroat** [comment]
i'll maintain. might take me a few tries to get the exact syntax right, but i think there are enough examples floating around i can figure it out.

thanks!

**Comment by AdmiringWorm** [comment]
👍 

In that case, please send of a message to the site admins so we can get you added as a maintainer.

https://chocolatey.org/packages/uncrustify/0.64-alpha1/ContactAdmins

**Comment by AdmiringWorm** [comment]
@stephengroat just wanted to follow up on this to find out what the status of the package is, are you getting anywhere or do you perhaps need some help?

**Comment by pauby** [comment]
@stephengroat before we close this with 'no update', can you confirm what stage this is at?

**Comment by pauby** [comment]
No response. Opening this up for maintainers.

**Comment by chtof** [comment]
Status: **In progress**

- Waiting to be added as maintainer for this package.
- Updated version ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/uncrustify

**Comment by chtof** [comment]
Status: **Review**

**Comment by chtof** [comment]
Status: **Published**

- https://www.chocolatey.org/packages/uncrustify/0.68.1

Can be closed.
