### ISSUE TITLE
RFM - Luminance HDR

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#250]
https://www.chocolatey.org/packages/luminance
https://www.chocolatey.org/packages/luminance.install

EDIT:
Also adding portable package, as it haven't gotten any package updates since 2014
https://www.chocolatey.org/packages/luminance.portable

**Comment by chtof** [comment]
Status: **In progress**

- Request sent to be added as maintainer of luminance/luminance.install/luminance.portable
- Updated packages ready to be pushed:
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/luminance
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/luminance.install
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/luminance.portable

**Comment by chtof** [comment]
Status: **Review**

- https://www.chocolatey.org/packages/luminance/2.5.1.20190425
- https://www.chocolatey.org/packages/luminance.install/2.5.1
- https://www.chocolatey.org/packages/luminance.portable/2.5.1

**Comment by chtof** [comment]
Status: **Published**

- https://www.chocolatey.org/packages/luminance/2.5.1.20190425
- https://www.chocolatey.org/packages/luminance.install/2.5.1
- https://www.chocolatey.org/packages/luminance.portable/2.5.1

Can be closed.
