### ISSUE TITLE
RFM - Hugin

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#251]
https://chocolatey.org/packages/hugin

**Comment by chtof** [comment]
**Status: In progress** - Waiting to be added as maintainer (request sent).

- https://github.com/chtof/chocolatey-packages/tree/master/automatic/hugin
- https://github.com/chtof/chocolatey-packages/tree/master/automatic/hugin.install
- hugin.portable will be updated within the next days.

**Comment by chtof** [comment]
Status: 
- hugin.install: **Review**
- hugin: **Review**
- hugin.portable: **In Progress**

Regarding hugin.portable: the portable version is no longer available:
- In the previous portable chocolatey package, there is a portable version "Hugin_2015.0.0_64bit.7z" in https://sourceforge.net/projects/hugin/files/hugin/hugin-2015.0/  . And in the latest version, no portable version "*_64bit.7z" is available: https://sourceforge.net/projects/hugin/files/hugin/hugin-2019.0/
--> I will contact hugin team to know if we should deprecate the portable version or if they can release again portable versions.

**Comment by chtof** [comment]
Regarding hugin.portable, I think this package should be deprecated as they are no longer sources to maintain the portable version.
See the answer of Hugin Team to my case: https://bugs.launchpad.net/hugin/+bug/1825030/comments/2

Ok for you?

**Comment by pauby** [comment]
The current version of the portable package has embedded binaries. No need to deprecate it.

However the .install package uses an MSI installer. The .portable is a ZIP file. My understanding is that a portable package doesn't install anything. Which this doesn't. However it does update the registry.

**Comment by chtof** [comment]
Ok, if a user install hugin.install, he will have the latest version and an
old version (probably never updated) if he install the portable version.
Little bit confusing.

If we let the portable as is, then this issue can be closed.

Le sam. 20 avr. 2019 à 18:31, Paul Broadwith <notifications@github.com> a
écrit :

**Comment by pauby** [comment]
> Ok, if a user install hugin.install, he will have the latest version and an old version (probably never updated) if he install the portable version. Little bit confusing.

That will be the same for any package where the user installs one .portable and one .install. That's the users perogative to do that (perhaps it's required) but it's also the users responsibility so make sure what they have installed is what they want. the .portable and .install packages are two separate packages.

As the packages you've submitted are not approved we will keep the issue open until they are all approved.

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/hugin

- https://chocolatey.org/packages/hugin.install

Can be closed.
