### ISSUE TITLE
RFM - PDFsam

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#252]
https://chocolatey.org/packages/pdfsam

**Comment by AdmiringWorm** [comment]
@pauby was the maintainer tried to be contacted?
From my understanding it was only in the comments section, not using `Contact Maintainer`

**Comment by chtof** [comment]
Already up to date with the latest version 4.0.1

Maybe a portable version can be added for the portable version : https://github.com/torakiki/pdfsam/releases/download/v4.0.1/pdfsam-4.0.1-windows.zip

So, RFM to RFP for the portable version?

**Comment by pauby** [comment]
@chtof if it's something you need then yeah, raise an issue. Because there is no template in this issue (it was raised before we added those) then I'd rather close this and re-open a new one to capture all the information.

**Comment by pauby** [comment]
And good catch @chtof !
