### ISSUE TITLE
RFP Spywareblaster

### ISSUE THREAD

**Issue by churchthecat** [chocolatey-community/chocolatey-package-requests#257]
Why SpywareBlaster? Spyware, adware, browser hijackers, and dialers are some of the most annoying and pervasive threats on the Internet today. By simply browsing a web page, you could find your computer to be the brand-new host of one of these unwanted fiends!

The most important step you can take is to secure your system.
And SpywareBlaster is the most powerful protection program available.

Multi-Angle Protection

    Prevent the installation of ActiveX-based spyware and other potentially unwanted programs.
    Block spying / tracking via cookies.
    Restrict the actions of potentially unwanted or dangerous web sites.

https://www.brightfort.com/spywareblaster.html

**Comment by AdmiringWorm** [comment]
I will be looking into creating a package for this one.

**Comment by AdmiringWorm** [comment]
Seems like they have denied silent installation on purpose, because of this it will take a little longer to create a package for this one.

**Comment by churchthecat** [comment]
:( hope it will work anyway

**Comment by AdmiringWorm** [comment]
Well, I got something, just doing some final tests before I can push the package to chocolatey

**Comment by AdmiringWorm** [comment]
Initial package have been submitted to chocolatey: https://chocolatey.org/packages/SpywareBlaster/5.5

**Comment by AdmiringWorm** [comment]
The package have been approved.
