### ISSUE TITLE
RFP: VueScan

### ISSUE THREAD

**Issue by RiseT** [chocolatey-community/chocolatey-package-requests#260]
https://www.hamrick.com/

- Of the few that exist, this is to my knowledge by far the best manufacturer-independent scanner software for Windows (comparable alternatives are much more expensive). Available for Mac OS and Linux as well.

- As it brings its own drivers, it's also very useful for older scanners for which manufacturers don't provide updated drivers anymore (e. g. support for the latest Windows versions).

- Nearly 6000 supported scanners: https://www.hamrick.com/vuescan/supported-scanners.html

- 30-day trial, "Standard" and "Professional" editions all use the same download, i. e. the same setup file (edition and thus available features are set by the serial number entered into the application). 32 and 64 bit versions are separate downloads, though: https://www.hamrick.com/old-versions.html

- Updates every one to two weeks (e. g. in order to add drivers for new scanner hardware), so automation would make sense.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vuescan

**Comment by RiseT** [comment]
@chtof Here are alternative, direct download URLs without cloudfront, if you're interested. Don't know which ones are better, though.

Example for v9.6:

32 Bit:
https://www.hamrick.com/files/vuex3296.exe

64 Bit:
https://www.hamrick.com/files/vuex6496.exe

**Comment by chtof** [comment]
@RiseT  Great, thank you for these links and for your feedback!
You are true, the main download link ("big green download button") on the site was "adapted" to my OS system. And I checked once again and now I saw a download link for other OS, mobile etc...
Package has just been submitted with these changes.
Thanks again!

**Comment by RiseT** [comment]
@chtof Hey, just tried to install the VueScan package and it failed because of a checksum error. When I inspected the current chocolateyinstall.ps1, I noticed that both "url" and "url64" contain the same 32 bit URL. So on my 64 bit system, it downloads the 32 bit version and compares its hash with the 64 bit hash, which of course fails.

**Comment by chtof** [comment]
@RiseT , corrected version has been published. Well, thanks again!

**Comment by chtof** [comment]
@RiseT  it fails again and the version of Vuescan has not changed. I think the file is built regularly and maybe something like a date change the checksum of the file:
PS C:\*****\GitHub\chocolatey-packages\automatic\vuescan> get-remotechecksum https://www.hamrick.com/files/vuex6496.exe
142bacb60e7047a003b6f62e595bc6b06f7e928d44cad17a156755976444f200
PS C:\*****\GitHub\chocolatey-packages\automatic\vuescan> get-remotechecksum https://www.hamrick.com/files/vuex3296.exe
4aab8beeca3857462dccb67c095dc0cb6f4e69f0121f2b22ffd9bc27f52307d9

**Comment by RiseT** [comment]
Mh. Passed the automatic test & installing the current package went without problems for me.

**Comment by RiseT** [comment]
@chtof I've noticed you're adding a start menu link manually in the latest script. Do you have any idea why the VueScan installer doesn't behave as usual with Chocolatey, i. e. doesn't place any links? I mean one would think an installer does what it always does, independently of Chocolatey.

**Comment by chtof** [comment]
The checksum changes every day (without new version released), so how to handle this?
Version 9.6.45 - Checksum was 4aab8beeca3857462dccb67c095dc0cb6f4e69f0121f2b22ffd9bc27f52307d9 when I submitted the package.

Yesterday, 20th of July:
get-remotechecksum https://www.hamrick.com/files/vuex3296.exe
ca2f24554df70313ca9d34afbdeab374e353b66cc76c77219e12503c66b79286

Today, 21th of July:
get-remotechecksum https://www.hamrick.com/files/vuex3296.exe
9abaf104ea5fb5697766625aedd5d560aac5d922bdda0ae50a5b7531bac379cb

**Comment by RiseT** [comment]
@ferventcoder Any idea what to do if checksums change on a daily basis without a version change?

**Comment by pauby** [comment]
@RiseT The author could genuinely be updating the software but not updating the version (happens a LOT). Or they could be doing it to generate a new checksum and defeats direct links to the file from something like Chocolatey. Either way I can't see a way around it.

A suggestion may be to look at embedding the software either using the redistribution rights in the license (if it allows it) or reaching out to the software author directly to see if they would allow it. Note I haven't looked at the license so the first part may be a complete non-starter.

**Comment by RiseT** [comment]
VueScan has been updated to 9.6.46, so you can check if the automatic script generation works.

**Comment by chtof** [comment]
@RiseT The automatic update has failed as I have had the bad idea to rename for this package on my computer for example _chocolateyinstall.ps1_ into _chocolateyInstall.ps1_ and github desktop doesn't published a such change and so, update.ps1 doesn't find the renamed file.
The first point is to know how to handle this package as its checksum changes regularly for a same version. I have written to the editor and he isn't interested to improve this situation, even if it was a way to promote his software without embedding his software but only to give an easier way to install it.
I have raised an issue to Chocolatey support an "-insecure" option but it can take times to have an answer as it needs to know if it would be a good idea to integrate such packages and even if it is case, it would take time to implement it.

**Comment by AdmiringWorm** [comment]
@chtof do the version stay exactly the same every time? if not, you could perhaps use something similar to what I am doing for the origin package (checking the response for if the etag have changed, if so create push a new version).

https://github.com/AdmiringWorm/chocolatey-packages/blob/develop/scripts/Update-OnHeaderChanged.ps1
and
https://github.com/AdmiringWorm/chocolatey-packages/blob/develop/automatic/origin/update.ps1#L37 (The call name is different due to having a small helper between the actual script and the updater).

If the version stay the same, there is also the option to set the global variable (`$global:au_Force = $true`) to force a fix version. Just remember to reset it when the package is updated.

**Comment by RiseT** [comment]
> I have written to the editor and he isn't interested to improve this situation, even if it was a way to promote his software without embedding his software but only to give an easier way to install it.

Except for for the people checking out VueScan just as a trial, those who will utiliize this chocolatey package are customers who have purchased VueScan 😠

**Comment by chtof** [comment]
@RiseT What abour to end your request as customer to the software editor, it can helps.

**Comment by chtof** [comment]
> @RiseT What about to send your request as customer to the software editor, it can helps.

**Comment by RiseT** [comment]
@AdmiringWorm
The version stated within the (setup) file name only changes for major versions (like 9.5 or 9.6), while on the download page, the full version (9.6.46) is mentioned:
https://www.hamrick.com/alternate-versions.html

Also, the properties of the setup file contain the full version (e. g. 9.6.46.0):
![vue](https://user-images.githubusercontent.com/12624674/61945882-61633d80-afa1-11e9-848d-e1359c99fa19.PNG)

@chtof Will do, although I'm somewhat in doubt that it will have any effect.

**Comment by AdmiringWorm** [comment]
@RiseT I think it would be appropriate to use just the first 3-parts, then when the checksum changed to use the 4th part as the fix version (ie `9.6.46.20190726`, the date is recommended to be used as a fix part of the version)

**Comment by RiseT** [comment]
@chtof 
> I have written to the editor and he isn't interested to improve this situation, even if it was a way to promote his software without embedding his software but only to give an easier way to install it.

Sorry, I've tried, and same here...

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/vuescan

Can be closed.
