### ISSUE TITLE
RFP - NetSetMan (Network Settings Manager)

### ISSUE THREAD

**Issue by TuRDMaN** [chocolatey-community/chocolatey-package-requests#261]
http://www.netsetman.com/en/freeware#download

A handy utility to easily switch between different network configurations.

There is a free version, as well as a paid version (package for the free version would be the main priority).

From the download page: 
> 3in1: Setup, Update & Portable in one file!
> License: Non-Commercial Freeware
> Release date: 2017-11-29
> Language: Multilingual
> For Windows: XP/Vista/7/8/10 (32/64 Bit)

**Comment by nicolafarina** [comment]
I can take it.

**Comment by nicolafarina** [comment]
I wrote to the developer yesterday to explore his support and to having some details about download repository. Waiting for an answer.

**Comment by nicolafarina** [comment]
Developers don't provide specific download URL for each version, so it need a rapid package maintainer. Actually I can't take anymore packages other than I use daily. Sorry.

**Comment by 3zmana** [comment]
Packages available :)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/netsetman

**Comment by chtof** [comment]
Status: **Published**
Already published and approved : https://chocolatey.org/packages/netsetman (by @3zmana)

So, can be closed.
