### ISSUE TITLE
RFM - RethinkDB

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#262]
https://chocolatey.org/packages/rethinkdb/2.3.2

**Comment by AdmiringWorm** [comment]
I have just set a message to the site admins requesting to be added as a maintainer for this request.

**Comment by AdmiringWorm** [comment]
A new version have been submitted to chocolatey: https://chocolatey.org/packages/rethinkdb/2.3.6

**Comment by AdmiringWorm** [comment]
The submitted version have been approved
