### ISSUE TITLE
RFM - x64dbg

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#263]
https://chocolatey.org/packages/x64dbg.portable

**Comment by boubou** [comment]
Please add me as a maintainer.
I will update the package as soon as I can!

**Comment by AdmiringWorm** [comment]
@boubou you need to send a message through the site admins on the package page (as is mentioned in the README docs): https://github.com/chocolatey-community/chocolatey-package-requests#how-to-create-packages-for-a-request

**Comment by AdmiringWorm** [comment]
Closing as it seems this package is being maintained.

**Comment by stevemk14ebr** [comment]
The current package version is out of date, please update or reopen

**Comment by pauby** [comment]
The package has a new maintainer or the packaged is being updated so this issue is no longer needed. Please contact the maintainer directly.

**Comment by stevemk14ebr** [comment]
The maintainer has communications disabled

**Comment by pauby** [comment]
This issue is closed so there is nothing to be done here.

My suggestion is to follow the package triage process by clicking the link 'Package Outdated?' on the package page. The package was last updated on 15 January so the maintainer has not abandoned it, but the 'Package Source' link doesn't indicate the package is in their repository. My suggestion would be to raise a GitHub issue to get clarification.
