### ISSUE TITLE
RFP - classyshark

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#272]
<http://classyshark.com/>

Not sure whether this fits Chocolatey, because ClassyShark downloads new version on start up. New version is placed in ~~the same folder~~ `$PWD`.

In addition, should this be `classyshark.portable`? Or `classy-shark` or `classy_shark`?

**Comment by AdmiringWorm** [comment]
I'm unable to view the webpage to see what is available, and how they write the name on the webpage.

If only a portable edition is available, and the name is actually spelt without spaces the id should be `classyshark`, if it contains a space then `classy-shark`.

`.portable` and `.install` is only used when both an installer and portable package exist.

**Comment by franklinyu** [comment]
There is some issue with GitHub Pages or the domain. Source is available in <https://github.com/google/android-classyshark>.

**Comment by AdmiringWorm** [comment]
Correct me if I'm wrong, but from the looks of it this is software for android, not for windows.

If that is the case, a package can't be created until a windows release is available for the software.

**Comment by franklinyu** [comment]
It’s used to decompile Android package on desktop (Windows, macOS, Linux, etc.).

**Comment by AdmiringWorm** [comment]
Ah, I see. I guess I misunderstood the software then, my bad.

**Comment by FranklinYu** [comment]
I have finished the package, but it is blocked by chocolatey/choco#1686.

**Comment by pauby** [comment]
@FranklinYu Is this progressing?

**Comment by FranklinYu** [comment]
@pauby This has been blocked by chocolatey/choco#1686 until last Friday. After I finish #63, I would verify chocolatey/choco#1686 in Chocolatey 0.10.13 before releasing this package. The shortcut is the last piece.

**Comment by pauby** [comment]
@FranklinYu Can you provide an update on this?

**Comment by FranklinYu** [comment]
@pauby Thanks for the heads-up. Since chocolatey/choco#1686 has been released, I will try it this weekend to see whether it works for this package.

**Comment by FranklinYu** [comment]
https://chocolatey.org/packages/classyshark
