### ISSUE TITLE
RFP - splint

### ISSUE THREAD

**Issue by mcandre** [chocolatey-community/chocolatey-package-requests#274]
Would love to see the traditional C security linter splint available on Chocolatey!

Homepage

http://lclint.cs.virginia.edu/

MSI's are already available:

https://github.com/maoserr/splint_win32/downloads

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/splint
https://chocolatey.org/packages/splint.install
https://chocolatey.org/packages/splint.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/splint
- https://chocolatey.org/packages/splint.install
- https://chocolatey.org/packages/splint.portable

Can be closed.
