### ISSUE TITLE
RFP - BuddyBackup

### ISSUE THREAD

**Issue by jnm2** [chocolatey-community/chocolatey-package-requests#275]
Since CrashPlan is discontinuing its peer-to-peer backup service, http://www.buddybackup.com/ seems to be the best alternative.

**Comment by itzonban** [comment]
@jnm2 
I know it's an old issue.. but it looks like BuddyBackup is not in development anymore.. no new version in years and central servers are often reported down.

https://syncthing.net/ looks like a good alternative and there already exists a package.
https://chocolatey.org/packages/syncthing

**Comment by jnm2** [comment]
I will check that out, thanks!

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/buddybackup

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/buddybackup

Can be closed.

**Comment by jnm2** [comment]
@chtof Thank you!
