### ISSUE TITLE
RFM - carotdav

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#278]
https://chocolatey.org/packages/carotdav/1.9.9

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/carotdav

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/carotdav
https://chocolatey.org/packages/carotdav.portable
https://chocolatey.org/packages/carotdav.install

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/carotdav
- https://chocolatey.org/packages/carotdav.portable
- https://chocolatey.org/packages/carotdav.install

Can be closed.
