### ISSUE TITLE
RFM - IObit Advanced SystemCare

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey-community/chocolatey-package-requests#280]
I am requesting a package to be made.
Application website:
https://www.iobit.com/en/index.php

**Comment by AdmiringWorm** [comment]
Package already exist:
https://chocolatey.org/packages/Afedteated

I see it is truly outdated right now, but if you could please contact the maintainer first to see if he/she is willing to update the package first before we open this to new maintainers.

**Comment by franklinyu** [comment]
If that is updated, please also update the “Software Site”. Currently it points to direct download link of an executable, not very informative.

**Comment by AdmiringWorm** [comment]
@franklinyu you'll need to try contacting the maintainer for updates to a package, if you don't get any response from him/her though (usually 1 or more weeks after contact) then please post back here and we can open it up for new maintainers

**Comment by franklinyu** [comment]
There seems to be three versions: [Free](https://www.iobit.com/en/advancedsystemcarefree.php), [Pro](https://www.iobit.com/en/advancedsystemcarepro.php) and [Ultimate](https://www.iobit.com/en/advanced-systemcare-antivirus.php). The Pro version is as mentioned above, but why is it called Afedteated? There is also Free version called [`advancedsystemcarefree`](https://chocolatey.org/packages/advancedsystemcarefree), but it is unlisted and hidden, for some reason. The Ultimate version seems to be totally different product, despite of the very confusing name.

**Comment by AdmiringWorm** [comment]
> but why is it called Afedteated

that is actually something you'll need to ask the maintainer of the package, I honestly have no idea.

> I think it would be easier to simply revive advancedsystemcarefree.

That is definitely an option, if there is someone that is interested in maintaining it.

> (Why wasn’t it called Advanced-SystemCare-Free in the first place? The vendor calls it “Advanced SystemCare Free”.)

Again, that is something you'll need to ask the maintainer of the package, and not something I can answer.
The maintainers is the ones that decide on the naming when they push the package for the first time.
Also, small correction: it should be `advanced-systemcare-free` in that case, packages should always be named in lowercase characters.

**Comment by Chronoshift111** [comment]
This is more specifically the website of the program:
https://www.iobit.com/en/advancedsystemcarefree.php

**Comment by pauby** [comment]
@Chronoshift111 @franklinyu have you contacted the maintainer of the existing package to move this forward?

**Comment by franklinyu** [comment]
@pauby No, I have not yet. I’m still hesitating to take this package (or package series) because I don’t use it myself. I have three RFPs queued before this RFM.

**Comment by pauby** [comment]
That's fine. In the meantime I've flagged this as being available. If you want to pick it up again when you have more time just come back and let us know.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/afedteated

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/afedteated

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/afedteated

Can be closed.
