### ISSUE TITLE
RFM - Battle.net

### ISSUE THREAD

**Issue by Wh1t3Rose** [chocolatey-community/chocolatey-package-requests#287]
https://chocolatey.org/packages/battle.net

**Comment by AdmiringWorm** [comment]
@Wh1t3Rose have you tried to contact the maintainers of this package before submitting this request?

I know one of the maintainers (@bcurran3) is quire active in the community.

**Comment by bcurran3** [comment]
I've been busy of late and this is sitting on the back shelf at the moment. Might have time next month. From what I remember it's going to need AHK and probably take hours of testing to get it right that I just don't have at the moment.

**Comment by bcurran3** [comment]
@Wh1t3Rose - if you find me a command to silently install the program, I'll give you a package in less than 24 hours.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/battle-net

**Comment by mkevenaar** [comment]
@chtof why did you used a new package ID?

**Comment by chtof** [comment]
@mkevenaar Because I have an issue when I used "battle.net" and I thought it was due to the "." in the package name. From my computer W10, chocolatey didn't find battle.net when using "`-dv -s".;chocolatey" `" but it worked on a chocolatey-test-environment.
After several attempts, I have preferred to use a new package name and it solves the issue on my computer.

**Comment by mkevenaar** [comment]
@chtof does the link on the first issue work for you?

We can go down two roads:
1. Keep this new package ID and depricate the Battle.net package.
2. Keep the old package ID and reject the newly submitted package. (and use the name of the software as the package name)

I would suggest to go with option No 2

@pauby / @AdmiringWorm what do you think?

**Comment by pauby** [comment]
I'd keep the new package and deprecate battle.net as that package name isn't using the correct naming convention. In addition there has only been one version of battle.net released so it's not a huge issue to deprecate it in favour of the new one.

**Comment by bcurran3** [comment]
Shouldn't be against naming conventions as "battle.net" IS the name of the program. (Sorry, but I can't quote a resource as chocolatey.org is not working for me.)

Simple solution is to have him added as a maintainer; deprecation of the old one makes no sense to me.

**Comment by AdmiringWorm** [comment]
@majkinetor  @pauby I actually agree with the second option and what @bcurran3 is saying.

Quoting the chocolatey documentation:
> Don't use dots. They should be used only if the original application name contains dots (e.  g. Paint.NET).

So in this case where the name of the application is `battle.net` that should also be the package id.

https://chocolatey.org/docs/create-packages#naming-your-package

*NOTE: I probably won't be able to respond further until after the weekend, as I will be mostly offline for the next few days.*

**Comment by pauby** [comment]
Wasn't ware the software was called battle.net @AdmiringWorm and in that case it should follow the naming of the software so I'll switch to 2 @mkevenaar

**Comment by AdmiringWorm** [comment]
@pauby the full name is actually `Blizzard Battle.net Desktop App`, but I would said battle.net is the short name for the app.

**Comment by pauby** [comment]
Bear in mind that the guidelines _allow_ software that has a dot in the name to use it for the package I'd. It doesn't say you _have_ to use it.

**Comment by mkevenaar** [comment]
I agree, but the issue in this case is existing package ID vs new package ID. 

https://chocolatey.org/packages/battle.net Already exists.

**Comment by pauby** [comment]
@mkevenaar I was clarifying the guidelines, in general, for the future for anybody else reading this.

**Comment by chtof** [comment]
Status: **Package rejected**
Package rejected as the checksum of the installer changes all the time and on another hand, the license doesn't allow to embed the installer. So there is no way to integrate this package in the official Chocolatey repository.

Can be closed.
