### ISSUE TITLE
RFP - BetterDiscord

### ISSUE THREAD

**Issue by Wh1t3Rose** [chocolatey-community/chocolatey-package-requests#289]
https://betterdiscord.net
https://github.com/jiiks/betterdiscordapp

**Comment by chtof** [comment]
Notes: It will be difficult to script this package as:
- Silent args haven't been found.
- An ahk script need to handle options according already installed discord app (discord, discord canary or discord PTB).

**Comment by Xav83** [comment]
The `BetterDiscord` website specifies that it is no longer maintained.
It is also tell that future development can be found [here](https://github.com/JsSucks/BetterDiscordApp).

I don't know if this is the software that @Wh1t3Rose wanted though :/

**Comment by alazymeme** [comment]
BandagedBetterDiscord is the maintained version:
https://github.com/rauenzi/BetterDiscordApp
https://github.com/rauenzi/BBDInstaller

**Comment by KaKi87** [comment]
Hello,
Here's the up-to-date BetterDiscord installer : https://github.com/BetterDiscord/Installer
Thanks

**Comment by kamack38** [comment]
BetterDiscord is already on Chocolatey: https://community.chocolatey.org/packages/betterdiscord

**Comment by TheCakeIsNaOH** [comment]
Thanks for creating the package @kamack38
