### ISSUE TITLE
RFP - openconnect-gui

### ISSUE THREAD

**Issue by kaovilai** [chocolatey-community/chocolatey-package-requests#298]
Gui for Windows ported openconnect
https://openconnect.github.io/openconnect-gui/

**Comment by facorread** [comment]
I would like to maintain this package. I set up a repository [here](https://github.com/facorread/openconnect-gui-chocolatey). What do you think?

**Comment by AdmiringWorm** [comment]
@facorread this is a request for a new non-existing package, so if you wish to maintain it then feel free to do as such.

**Comment by AdmiringWorm** [comment]
Seems that a package have been pushed and approved.

@facorread in the future, please post a comment so we know what the status of the request is at (In progress, Review, Approved). This way we can mark the request with the correct label, and close the request when it have been completed.
