### ISSUE TITLE
RFP - eclipse-java-oxygen

### ISSUE THREAD

**Issue by kaovilai** [chocolatey-community/chocolatey-package-requests#300]
http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/oxygen3

**Comment by AdmiringWorm** [comment]
please also give the link to the project page of the software that you're requesting.
Otherwise we can't mark this as available for maintainers.

**Comment by kaovilai** [comment]
updated

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/eclipse-java-oxygen

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/eclipse-java-oxygen

Can be closed.
