### ISSUE TITLE
RFP - eclipse-cpp-oxygen

### ISSUE THREAD

**Issue by kaovilai** [chocolatey-community/chocolatey-package-requests#301]
http://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/oxygen3

**Comment by AdmiringWorm** [comment]
please also give the link to the project page of the software that you're requesting.
Otherwise we can't mark this as available for maintainers.

**Comment by kaovilai** [comment]
Link updated

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/eclipse-cpp-oxygen

**Comment by AdmiringWorm** [comment]
seems like the package have been approved
