### ISSUE TITLE
RFP - PhonerLite

### ISSUE THREAD

**Issue by MisterT87** [chocolatey-community/chocolatey-package-requests#307]
Very nice VOIP Softphone (SIP only)(Windows only) - multi language support and a lot of VOIP providers are supported, FritzBox devices also supported and have profiles for easy setup...

newest Version: 2.6.1

URL: [http://phonerlite.de/download_en.htm](http://phonerlite.de/download_en.htm)

Only the first two files are important:
PhonerLiteSetup.exe - Install version
PhonerLite.zip - Portable version

EDIT: PhonerLite ist completly free - not open source!

**Comment by chtof** [comment]
https://chocolatey.org/packages/phonerlite already available (Version 2.70 - install version)

I have just pushed:
https://chocolatey.org/packages/phonerlite.install 
https://chocolatey.org/packages/phonerlite.portable

Maybe https://chocolatey.org/packages/phonerlite would have changed to have a version dependency on phonerlite.install

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/phonerlite
- https://chocolatey.org/packages/phonerlite.install
- https://chocolatey.org/packages/phonerlite.portable

Can be closed.
