### ISSUE TITLE
RFP - Infinitex

### ISSUE THREAD

**Issue by joachimschmidt557** [chocolatey-community/chocolatey-package-requests#309]
Infinitex : A LaTeX and WYSIWYG editor with academic search functionality and other helpful tools

GitHub source: https://github.com/fetacore/Infinitex

GitHub releases: https://github.com/fetacore/Infinitex/releases

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/infinitex
- https://chocolatey.org/packages/infinitex.install
- https://chocolatey.org/packages/infinitex.portable

**Comment by joachimschmidt557** [comment]
The packages are approved. Thank you!
