### ISSUE TITLE
RFP - gSubs

### ISSUE THREAD

**Issue by joachimschmidt557** [chocolatey-community/chocolatey-package-requests#311]
gSubs finds matching subtitles to videos.

Homepage: https://cholaware.com/gsubs/

GitHub source: https://github.com/sanjevirau/gsubs

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/gsubs

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/gsubs

Can be closed.
