### ISSUE TITLE
RFP - BandLab Assistant

### ISSUE THREAD

**Issue by joachimschmidt557** [chocolatey-community/chocolatey-package-requests#322]
BandLab Desktop Assistant (Beta)

Create and upload new projects or continue your recent ones in just a few clicks from the convenience of your desktop. BandLab Assistant provides handy shortcuts and keeps you updated via desktop notifications.

Website: https://www.bandlab.com/download

**Comment by chtof** [comment]
For information, maybe the website has been redesigned, https://www.bandlab.com/download requires login/sign up but the desktop assistant can be now directly downloaded from https://www.bandlab.com/products/desktop/assistant

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/bandlab-assistant

**Comment by AdmiringWorm** [comment]
Seems like the package have been approved.
