### ISSUE TITLE
RFP - weasel

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#324]
Homepage: <http://rime.im/> (Chinese)
Download link: <https://dl.bintray.com/rime/weasel/weasel-0.11.1.0-installer.exe>
Keywords: rime, weasel

(“Weasel” is a kind of [ink brush](https://en.wikipedia.org/wiki/Ink_brush).)

Note: the installer and uninstaller is made from NSIS, but `uninstaller.exe /S` is not silent, for unknown reason.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/weasel

**Comment by FranklinYu** [comment]
@chtof What’s AHK here for?

**Comment by chtof** [comment]
@FranklinYu weasel is automatically launched at end of installation. So, the AHK script closes weasel.

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/weasel

Can be closed.
