### ISSUE TITLE
RFP - Flutter

### ISSUE THREAD

**Issue by sameerh1808** [chocolatey-community/chocolatey-package-requests#326]
A new mobile app SDK to help developers and designers build modern mobile apps for iOS and Android. Flutter is an open-source project currently in beta.

Homepage: https://flutter.io/

GitHub source: https://github.com/flutter/flutter

**Comment by pauby** [comment]
Whoever picks this up please note the [installation instructions](https://flutter.io/setup-windows/) particularly the System Requirements.

**Comment by chtof** [comment]
Already exists: https://chocolatey.org/packages/flutter

**Can be closed.**
