### ISSUE TITLE
RFP - torrent-file-editor

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#327]
> Qt based GUI tool designed to create and edit `.torrent` files.

Home page: <https://sourceforge.net/projects/torrent-file-editor/>
Source: <https://github.com/drizt/torrent-file-editor>
Downloads: <https://sourceforge.net/projects/torrent-file-editor/files/v0.3.10/>

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/torrent-file-editor

**Comment by FranklinYu** [comment]
@chtof Thank you! Two nitpick:

1. The icon broke.
2. The “license” links to SourceForge page.

**Comment by chtof** [comment]
@FranklinYu 
1. icon uploaded.
2. There is no license to download and I have only find license information on the SourceForge page ("GNU General Public License version 3.0 (GPLv3)").

**Comment by FranklinYu** [comment]
There is license on GitHub.

**Comment by chtof** [comment]
@FranklinYu Corrected, thank you!

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/torrent-file-editor

Can be closed.
