### ISSUE TITLE
RFP - lossless-cut

### ISSUE THREAD

**Issue by dematch1** [chocolatey-community/chocolatey-package-requests#328]
https://github.com/mifi/lossless-cut

**Comment by qqgg231** [comment]
> Simple and ultra fast cross platform tool for lossless trimming/cutting of video and audio files. Great for saving space by rough cutting your large video files taken from a video camera, GoPro, drone, etc. It lets you quickly extract the good parts from your videos and discard many gigabytes of data without doing a slow re-encode and thereby losing quality. It extremely fast because it does an almost direct data copy. It uses the awesome ffmpeg (included) for doing the grunt work.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/lossless-cut

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/lossless-cut

Can be closed.
