### ISSUE TITLE
RFP - ncollector-studio

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#331]
Homepage: <http://www.calluna-software.com/>
Download: <http://www.calluna-software.com/downloads/ncollector/NCollectorStudioLite.msi>

A crawler and offline browser.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/ncollector-studio-lite

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/ncollector-studio-lite

Can be closed.
