### ISSUE TITLE
RFM - CloudBerry Explorer for Amazon S3

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#335]
https://chocolatey.org/packages/CloudBerryExplorer.AmazonS3

**Comment by boubou** [comment]
I will pick it up!
Add me as a maintainer!

**Comment by boubou** [comment]
No new release.
Developement seem stopped.

**Comment by pauby** [comment]
I'll close this in the meantime and we can always reopen it later.

**Comment by imakiro** [comment]
Hi, can we please reopen this issue? The software is updated to Current version: 6.4.0.27 from the main download page
https://www.msp360.com/download.aspx?prod=cbes3free

**Comment by pauby** [comment]
@imakiro As we now use a new template and automated system can I ask you to raise a new issue for this?
