### ISSUE TITLE
RFM - CloudBerry Explorer for Microsoft Azure Cloud Storage

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#336]
https://chocolatey.org/packages/CloudBerryExplorer.AzureStorage

**Comment by boubou** [comment]
I will pick it up!
Please add me as a maintainer!

**Comment by boubou** [comment]
No new release.
Developement seem stopped.

**Comment by pauby** [comment]
I'll close this in the meantime and we can always reopen it later.
