### ISSUE TITLE
RFP - npcap

### ISSUE THREAD

**Issue by MagicGreenDragon** [chocolatey-community/chocolatey-package-requests#343]
Someone can add the support for this package?
https://github.com/nmap/npcap

I ask it because the nmap package install npcap, but sometimes it is not the latest version.

Thanks in advance!

**Comment by pauby** [comment]
Windows installer at https://nmap.org/npcap/#download

**Comment by jtcmedia** [comment]
A package for Npcap is a no-go. A silent installation is only offered by their OEM licenses. I wrote an email to the authors who responded that they do not want a Chocolatey package for Npcap.

**Comment by pauby** [comment]
Could it be automated with AutoHotkey?

**Comment by jtcmedia** [comment]
> 
> 
> Could it be automated with AutoHotkey?

Yes, it could, but then you're circumventing a feature that they sell with their OEM paid licenses. This is why I wrote the software authors who have specifically requested that a Chocolatey package **not** be made with a silent installation.

**Comment by chtof** [comment]
So, should we keep this issue opened? Or package the software without silent actions and notice that in the package page?

**Comment by pauby** [comment]
Given the current state of play with this we should really close this issue.
