### ISSUE TITLE
RFP - SpeedCrunch (Installer)

### ISSUE THREAD

**Issue by Sirove** [chocolatey-community/chocolatey-package-requests#347]
http://speedcrunch.org/download.html

We do have SpeedCrunch (**Portable**) as a package but that's not an option for a multi-user-environment because every user shares the same configuration and calculation history.

The installer works with the `/S` parameter for a completely unattended and silent installation!

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/speedcrunch
- https://chocolatey.org/packages/speedcrunch.install
- https://chocolatey.org/packages/speedcrunch.portable
