### ISSUE TITLE
RFP - K-Lite Codec Pack Basic

### ISSUE THREAD

**Issue by Sirove** [chocolatey-community/chocolatey-package-requests#348]
https://codecguide.com/download_k-lite_codec_pack_basic.htm

The "Full" and "Mega" Packs are overpowered for the average Windows user. 
Would be very nice to have the minimalists favorite "Basic" Pack as an alternative!

The `/verysilent` parameter works just fine!

**Comment by pauby** [comment]
@zersh would you be interested in picking this up as you maintain the Mega and Full packages?

**Comment by chtof** [comment]
Already exists: https://chocolatey.org/packages/k-litecodecpackbasic

**Can be closed.**

**Comment by chtof** [comment]
> Already exists: https://chocolatey.org/packages/k-litecodecpackbasic
> 
> **Can be closed.**
