### ISSUE TITLE
RFM - Little System Cleaner

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#35]
[Little System Cleaner](https://www.little-system-cleaner.com/) is an all in one system cleaner for Windows computers. Little System Cleaner combines several tools created by Little Apps into one, these tools include a registry cleaner, registry optimizer, disk cleaner, privacy cleaner, duplicate finder, startup manager and uninstall manager.

Downloads: https://sourceforge.net/projects/little-system-cleaner/

**Comment by mikecole** [comment]
I'll claim this.

**Comment by mikecole** [comment]
Pushed: https://chocolatey.org/packages/little-system-cleaner

**Comment by mkevenaar** [comment]
@mikecole this package is currently in a failed state. Are you still working on this?

**Comment by mikecole** [comment]
@mkevenaar Kinda, yeah. Got busy with other things and turns out I need to script the install because there's no silent installer arguments. I'll get to it sometime.

**Comment by mkevenaar** [comment]
@mikecole The current release of this package is now in a Rejected state. Do you have an update or do you want me to put this on available again?

**Comment by mikecole** [comment]
Yes please. Sorry, I got busy. I may pick it up again at some point in the future.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/little-system-cleaner

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/little-system-cleaner/0.3

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/little-system-cleaner/0.3

Can be closed.
