### ISSUE TITLE
RFP - Kafka Tool

### ISSUE THREAD

**Issue by butekx** [chocolatey-community/chocolatey-package-requests#350]
Homepage: http://www.kafkatool.com
Description: Kafka Tool is a GUI application for managing and using Apache Kafka clusters. It provides an intuitive UI that allows one to quickly view objects within a Kafka cluster as well as the messages stored in the topics of the cluster. It contains features geared towards both developers and administrators. Some of the key features include

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/kafka-tool

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/kafka-tool

Can be closed.
