### ISSUE TITLE
RFM - rtmpdump

### ISSUE THREAD

**Issue by MagicGreenDragon** [chocolatey-community/chocolatey-package-requests#356]
A package for rtmpdump exists, but is outdated.

The latest version is 2.4, and can be found here:
https://www.videohelp.com/software/RTMPDump

Thanks in advance.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/rtmpdump

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/rtmpdump

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/rtmpdump

Can be closed.
