### ISSUE TITLE
RFP - avinaptic

### ISSUE THREAD

**Issue by MagicGreenDragon** [chocolatey-community/chocolatey-package-requests#357]
Someone can add avinaptic package (the program is x32 only)?

Website:
http://fsinapsi.altervista.org/code/avinaptic/index.html

Lastest version:
http://fsinapsi.altervista.org/code/avinaptic/avinaptic2-win32-20111218.zip

Thanks in advance!

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/avinaptic

**Comment by AdmiringWorm** [comment]
seems like the package have been approved
