### ISSUE TITLE
RFP - Bluestacks

### ISSUE THREAD

**Issue by Bradley-Kars** [chocolatey-community/chocolatey-package-requests#358]
Could someone add Bluestacks?

Website:
https://www.bluestacks.com/

Lastest version:
https://www.bluestacks.com/download.html?utm_campaign=homepage-dl-button-en#download

Thanks in advance!

**Comment by pauby** [comment]
@daddydeadpool Which is it - a request for Bluestacks or Nox App Player?

**Comment by daddydeadpool** [comment]
bluestacks tried editing it sorry

**Comment by soredake** [comment]
Any progress on this?

**Comment by AdmiringWorm** [comment]
@soredake there is no one that has posted that they would like to pick up the issue.
So it is still open for new maintainers AFAIK.

**Comment by mikeee** [comment]
I'll pick this package up

**Comment by mikeee** [comment]
Package submitted, awaiting moderation

**Comment by mikeee** [comment]
reviewed and complete https://community.chocolatey.org/packages/bluestacks/
