### ISSUE TITLE
RFP - Unified-Hosts-AutoUpdate

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#359]
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate - see issue #337

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/unified-hosts-autoupdate

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/unified-hosts-update

Can be closed.
