### ISSUE TITLE
RFM - LyX

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#364]
https://chocolatey.org/packages/lyx/2.2.3.2

**Comment by chtof** [comment]
Lyx Chocolatey script is available with the latest version (2.3.2 / https://chocolatey.org/packages/lyx/2.3.2), so updates have been submitted since this RFM.
The status is in an error state due to miktex.install but miktext.install has been corrected recently.
So, can be closed.

**Comment by pauby** [comment]
@chtof we're looking for a new maintainer for this one as dtgm is not updating packages directly. There has been a new version pushed as the repository is being managed by others, where possible, to submit new version of some packages.

So while there is a new version available, the request for a new maintainer is still needed.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/lyx

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/lyx

Can be closed.
