### ISSUE TITLE
RFP - Ocenaudio

### ISSUE THREAD

**Issue by CypherNL** [chocolatey-community/chocolatey-package-requests#371]
Ocenaudio is a singe-track editor which feature set is here: https://www.ocenaudio.com/features
I use this program quite often for spectral analyst or checking the waveform or using the statistics feature to see if there's any possible clipping. It's updated quite often and it doesn't have a proper update system so i think this package would be a nice addition to the Chocolatey repository.

The program's website: https://www.ocenaudio.com/

Download page: https://www.ocenaudio.com/download

The program has 32-bit and 64-bit version with the installer and portable versions so you can create a package for both versions if you wish. But i will use the installer one if this package is submitted and accepted into the repository.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/ocenaudio
- https://chocolatey.org/packages/ocenaudio.install
- https://chocolatey.org/packages/ocenaudio.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/ocenaudio
- https://chocolatey.org/packages/ocenaudio.install
- https://chocolatey.org/packages/ocenaudio.portable

Can be closed.
