### ISSUE TITLE
RFP - antimony

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#376]
> Antimony is a computer-aided design (CAD) tool from a parallel universe in which CAD software evolved from Lisp machines rather than drafting tables.

website: http://www.mattkeeter.com/projects/antimony/3/
github: https://github.com/mkeeter/antimony

was discussed here in[ this github issue](https://github.com/mkeeter/antimony/issues/195).

P.S. Is there any way for Chocolatey to compile from the source like HomeBrew?

**Comment by Foadsf** [comment]
@pauby thanks for the immediate reply. Two questions:

1. Can you provide me with some instructions or examples of Chocolatey scripts used for building from source code?
2. Any idea if there are other Windows package managers which can compile from the source?

**Comment by pauby** [comment]
I know of no other packages that build from source code. As I said unless it's incredibly simple, it wouldn't be viable to do as a package.

With regards to other packages you would need to check them out individually. I think getting the developer to provide **A** windows package would be a good start (an MSI if possible) and the Chocolatey community could pick that up and create a package from it. Building the package from scratch using the package manager is doing things the wrong way around.

**Comment by pauby** [comment]
@Foadsf Where are we with this one?

**Comment by ComFreek** [comment]
@pauby I don't know @Foadsf's status on this, but I tried working on it and got stuck in building it on Windows, see https://github.com/mkeeter/antimony/issues/195#issuecomment-406175974. It seems to be a Boost (linking) issue, I am not sure where exactly the error stems from: https://github.com/mkeeter/antimony/issues/178#issuecomment-406779755

**Comment by pauby** [comment]
Given this has been open for a while, it needs to be compiled from source, [Chocolatey in the short-term will not have this functionality](https://github.com/chocolatey/choco/issues/1709), and there being  little traction on the Boost issue, it would appear a package we use on the Chocolatey Community Repository is a long way off?

I am of the mind to close this for the time being with a view to reopening when this changes?

@AdmiringWorm @ComFreek @Foadsf what are your thoughts?

**Comment by ComFreek** [comment]
I agree on closing this for the time being.

**Comment by AdmiringWorm** [comment]
@pauby I agree with you. We can always open this one in the future if anything changes.
