### ISSUE TITLE
RFP - Fluxfonts

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#382]
**Fluxfonts - a continual font generator for increased privacy**

> A unique tool that blurs your device’s unique font fingerprint by continuously installing and uninstalling new fonts that are generated on the fly.

Latest release at https://github.com/da2x/fluxfonts/releases

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/fluxfonts

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/fluxfonts

Can be closed.
