### ISSUE TITLE
RFP - TIBCO Jaspersoft Studio

### ISSUE THREAD

**Issue by PacMo66** [chocolatey-community/chocolatey-package-requests#384]
Eclipse-based Editor for creating Jaspersoft Reports

> TIBCO Jaspersoft® Studio is editing software for TIBCO JasperReports®. It will help you design and run report templates; build report queries; write complex expressions; layout visual components like 50+ types of charts, maps, tables, crosstabs, and custom visualizations; and much more. It integrates TIBCO JasperReports® Server to create powerful report publishing workflows. 

latest via https://community.jaspersoft.com/project/jaspersoft-studio

**Comment by saxnot** [comment]
i too have interest in this package
it's more useful than iReports IMHO

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/tjs
- https://chocolatey.org/packages/tjs.install
- https://chocolatey.org/packages/tjs.portable

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/tjs
- https://chocolatey.org/packages/tjs.install
- https://chocolatey.org/packages/tjs.portable

Can be closed.
