### ISSUE TITLE
RFM - hMailServer

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#385]
https://chocolatey.org/packages/hmailserver

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/hmailserver

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/hmailserver

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/hmailserver

Can be closed.
