### ISSUE TITLE
RFP - Eddie (AirVPN)

### ISSUE THREAD

**Issue by Sirove** [chocolatey-community/chocolatey-package-requests#386]
https://github.com/AirVPN/Eddie

"Eddie is developed by and is the official client of [AirVPN](https://airvpn.org), a VPN service based on OpenVPN and operated by activists and hacktivists in defence of net neutrality, privacy and against censorship."

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/eddie
- https://chocolatey.org/packages/eddie.install
- https://chocolatey.org/packages/eddie.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/eddie
- https://chocolatey.org/packages/eddie.install
- https://chocolatey.org/packages/eddie.portable

Can be closed.
