### ISSUE TITLE
RFP: nip2 - a user interface for the VIPS image processing library

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#387]
**nip2** is a GUI for the VIPS image processing library. It's a little like a spreadsheet: you create a set of formula connecting your objects together, and on a change nip2 recalculates.

Repository: https://github.com/jcupitt/nip2
Releases: https://github.com/jcupitt/nip2/releases

Depends on: **libvips** - a fast image processing library with low memory needs.

Repository: https://github.com/jcupitt/libvips
Releases: https://github.com/jcupitt/libvips/releases

> libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory. It has around 300 operations covering arithmetic, histograms, convolution, morphological operations, frequency filtering, colour, resampling, statistics and others. It supports a large range of numeric formats, from 8-bit int to 128-bit complex. Images can have any number of bands. It supports a good range of image formats, including JPEG, TIFF, OME-TIFF, PNG, WebP, FITS, Matlab, OpenEXR, PDF, SVG, HDR, PPM, CSV, GIF, Analyze, DeepZoom, and OpenSlide. It can also load images via ImageMagick or GraphicsMagick, letting it load formats like DICOM.
> 
> It comes with bindings for C, C++, and the command-line. Full bindings are available for Ruby, Python, PHP, .NET, Go, and Lua. libvips is used as an image processing engine by sharp (on node.js), bimg, sharp for Go, Ruby on Rails, carrierwave-vips, mediawiki, PhotoFlow and others. The official libvips GUI is nip2, a strange combination of a spreadsheet and an photo editor.
> 
> The download area has the source code plus pre-compiled binaries for Windows; you can install on macOS with homebrew, MacPorts or Fink; and it’s available in most Linux package managers. See the install notes. libvips is licensed under the LGPL 2.1+.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/nip2

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/nip2

Can be closed.
