### ISSUE TITLE
RFP - Dacia Media Nav Toolbox

### ISSUE THREAD

**Issue by valentind44** [chocolatey-community/chocolatey-package-requests#389]
https://dacia.naviextras.com/shop/portal/download?type=x-toolbox/engine

Dacia Media Nav Toolbox is a Windows utility. It can sync new updates and add new content to your Dacia MediaNav head unit.

**Comment by pauby** [comment]
@valentind44 Is there a public URL to download from?

**Comment by valentind44** [comment]
If you click the link I provided, it will redirect to the latest version. The direct link is http://azure.distrib.naviextras.com/content/!application/LG/ToolboxDacia/2016042601_3.18.5.647040_STRICT_dacia/Dacia_Media_Nav_Toolbox_Setup.exe .

**Comment by pauby** [comment]
@valentind44 The link in the first message takes me to a login box. The link you provided above - where does it come from? Is this the official Dacia one (obtained when logging into the site in the first URL)?

**Comment by valentind44** [comment]
I didn't realize it wasn't available if you're not logged in, sorry. Yes I obtained the link when I was logged in. It's the official link.

**Comment by pauby** [comment]
👍

**Comment by valentind44** [comment]
So I took some time to learn how to make chocolatey packages. I uploaded the corresponding package here https://chocolatey.org/packages/dacia-media-nav-toolbox/3.18.5.647040 . It is waiting for review. I am now looking for maintainers. I uploaded sources here https://github.com/valentind44/chocolatey-packages/tree/master/manual .

**Comment by chtof** [comment]
Latest package downloads http://azure.distrib.naviextras.com/content/!application/LG/ToolboxDacia/2016042601_3.18.5.647040_STRICT_dacia/Dacia_Media_Nav_Toolbox_Setup.exe

On the website https://dacia.welcome.naviextras.com/#how-to-update, I see http://cdns.distrib.naviextras.com/content/!application/TOOLBOX/Agents/ReDa_ULC_4/2019_07_15_16_20/Dacia/DaciaMediaNavEvolutionToolbox-inst.exe

The first link posted by @valentind44 redirects to DaciaMediaNavEvolutionToolbox-inst.exe. So it seems the package can be updated with the second link.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/dacia-toolbox

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/dacia-toolbox

Can be closed.
