### ISSUE TITLE
RFP - Huggle

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#397]
https://en.wikipedia.org/wiki/Wikipedia:Huggle

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/huggle

**Comment by AdmiringWorm** [comment]
@chtof your package is currently failing. Seems like you have a mixed remote and embedded package. (using embedded parameters, but remote helpers. As well as not including the binary, if this is supposed to be a embedded package).

I'll mark it as a package `In Progress`, let us know when the package gets updated.

**Comment by FranklinYu** [comment]
@chtof Please embed since this is GPL. Thanks!

**Comment by chtof** [comment]
@FranklinYu Not possible as the sum of installers exceed 200 MB, reason for which I have had to modify the script.
@AdmiringWorm Corrected and under review.

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/huggle

Can be closed.
