### ISSUE TITLE
RFM - pidgin-otr

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#398]
https://chocolatey.org/packages/pidgin-otr/4.0.1

**Comment by itzonban** [comment]
Hi.
I reported the missing maintainer / old version last year, and I would like to become the new maintainer for this package.

Best regards
Daniel

**Comment by mkevenaar** [comment]
Hi @itzonban,

the best way to do that is by using the "Contact Admins" link on the package page. An Admin will reply to you and add you as a maintainer.

**Comment by itzonban** [comment]
Hi @mkevenaar 

Thanks. I contacted the admins and I'm the maintainer now.

**Comment by AdmiringWorm** [comment]
@itzonban I just wanted to follow up on this request, have you been able to create an updated package after you were made the maintainer?

**Comment by itzonban** [comment]
@AdmiringWorm 
Yes, I created an updated package and it is already approved and online.
https://chocolatey.org/packages/pidgin-otr

**Comment by mkevenaar** [comment]
@itzonban Thanks for letting us know.
