### ISSUE TITLE
RFM - multipar

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#399]
https://chocolatey.org/packages/multipar.install/1.2.9.9

Please also see https://www.livebusinesschat.com/smf/index.php?topic=6108.0 which indicates that the multipar.eu site (where the current package downloads the installer from) could be malicious. So any new package should look to use the official download locations (see https://www.livebusinesschat.com/smf/index.php?board=396.0 for those).

**Comment by AdmiringWorm** [comment]
> So any new package should look to use the official download locations

Or better yet, embed the package as the license allows it (LGPL)

**Comment by chtof** [comment]
Status: **In Progress** (Waiting to be added as maintainer, request sent to Contact site admins).

Updated packages are ready to be published:

- https://github.com/chtof/chocolatey-packages/tree/master/automatic/multipar

- https://github.com/chtof/chocolatey-packages/tree/master/automatic/multipar.install

- https://github.com/chtof/chocolatey-packages/tree/master/automatic/multipar.portable

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/multipar
- https://chocolatey.org/packages/multipar.install
- https://chocolatey.org/packages/multipar.portable

Can be closed.
