### ISSUE TITLE
RFP - Egnyte Connect / Egnyte Drive

### ISSUE THREAD

**Issue by Huevos-y-Bacon** [chocolatey-community/chocolatey-package-requests#403]
**Egnyte Connect / Egnyte Drive**

Enterprise cloud storage - Windows desktop agent

- [Mass Deployment Guide, incl uninstall](https://helpdesk.egnyte.com/hc/en-us/articles/216688268-Egnyte-Connect-Desktop-App-for-Windows-Mass-Deployment-Guide)
- [MSI installer](https://helpdesk.egnyte.com/hc/en-us/articles/205237150-Download-Desktop-App-Egnyte-Drive-Installers)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/egnyte-connect

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/egnyte-connect

Can be closed.
