### ISSUE TITLE
RFP - WLAN Optimizer

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#407]
**WLAN Optimizer**

> It's a small freeware tool for Windows (Vista / Windows 7 / Windows 8 / Windows 10) disabling the periodical background scan activity for wireless networks. It improves latency time of wireless connections. Hence it is useful for people with wireless connections getting lag spikes (especially during online gaming, audio and video streaming).

![WLAN Optimizer][screenshot]

About: http://www.martin-majowski.de/index.html
Download: http://www.martin-majowski.de/downloads.html

[screenshot]: http://www.martin-majowski.de/mediapool/61/613886/resources/37311388.gif "WLAN Optimizer"

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/wlan-optimizer

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/wlan-optimizer

Can be closed.
