### ISSUE TITLE
RFM - you-get

### ISSUE THREAD

**Issue by chantisnake** [chocolatey-community/chocolatey-package-requests#412]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).

  You can find previous version of you-get packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/you-get-choco
  The chocolatey package page for you-get : https://chocolatey.org/packages/you-get

**Comment by boubou** [comment]
I will pick it up!
Please add me as a maintainer!

**Comment by boubou** [comment]
Can be close.
Package approuved.
https://chocolatey.org/packages/you-get
