### ISSUE TITLE
RFM - bitdiffer

### ISSUE THREAD

**Issue by chantisnake** [chocolatey-community/chocolatey-package-requests#417]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of bitdiffer packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/bitdiffer-choco
  The chocolatey package page for bitdiffer : https://chocolatey.org/packages/bitdiffer

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by boubou** [comment]
I picked this package.
Developement of bitdiffer seem stopped.
There is no no release!

**Comment by boubou** [comment]
Can be close!
