### ISSUE TITLE
[RFP] BBC iplayer

### ISSUE THREAD

**Issue by b16r05** [chocolatey-community/chocolatey-package-requests#426]
I want to request a package called BBC iplayer.
Everything about it is here: https://www.bbc.co.uk/iplayer/install
Note that this is not an open source package. 
I assume it should work as other packages, but not quite sure.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/bbc-iplayer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/bbc-iplayer

Can be closed.
