### ISSUE TITLE
RFP - Startup organizer 

### ISSUE THREAD

**Issue by dreamss** [chocolatey-community/chocolatey-package-requests#427]
https://metaproducts.com/products/startup-organizer

Startup Organizer is a Windows 95/98/ME/NT/2000/XP/2003/Vista/7 program that was developed to provide quick access to all of the programs that are automatically started when you turn on or logon to your computer.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/startup-organizer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/startup-organizer

Can be closed.
