### ISSUE TITLE
RFP - EVGA precision 

### ISSUE THREAD

**Issue by dreamss** [chocolatey-community/chocolatey-package-requests#428]
https://www.evga.com/precisionxoc/

The next generation of EVGA Precision has arrived with EVGA Precision XOC. This software allows you to fine tune your NVIDIA graphics card, maximizing cooling and performance. This new version of Precision is built for the latest NVIDIA graphics cards and combines the best of EVGA Precision and EVGA OC Scanner to give you never before seen overclocking features and built in automatic tuning.

**Comment by pauby** [comment]
@dreamss Do you have a download location for the software that doesn't require you to login?

**Comment by dreamss** [comment]
https://www.techspot.com/downloads/6973-evga-precision-xoc.html ?

**Comment by dreamss** [comment]
http://storage.cdn.evga.com/software/EVGA_PrecisionX_OC_Setup_v6.2.7.exe

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/evga-precision-xoc

**Comment by AdmiringWorm** [comment]
seems like the package have been approved
