### ISSUE TITLE
RFP - EVGA ELEET 

### ISSUE THREAD

**Issue by dreamss** [chocolatey-community/chocolatey-package-requests#429]
NOT ELEETX, Older version for x58 motherboards

ELeetTune_1104_setup.exe 

https://1drv.ms/u/s!AudyZ2x3gFfZjPxqY9YJZ2j9gOiwWQ

**Comment by pauby** [comment]
@dreamss That download location is a OneDrive folder. That's not a suitable location to take a download from for the package. In order to embed it, we need a license that allows it. Where did the software come from and does the license allow redistribution?

**Comment by dreamss** [comment]
https://virustotalcloud.appspot.com/nui/index.html#/file/353785bbc78af950cbab516d864d78635f378f96a07f25f8e86bceb083f252f6/detection

**Comment by pauby** [comment]
@dreamss Appreciate that is a mirror, however it's not a usual download location. I'm not saying it can't be used, but I wouldn't be happy with it as a moderator and will ask that question.

In addition, to embed it, we need a specific license saying it can be redistributed. Unfortunately we can't accept anything other than that.

**Comment by dreamss** [comment]
AHA found the actual file on their page, as u can see crc/md5 matches my prev linked file

http://storage.cdn.evga.com/software/eleet.zip
https://www.evga.com/EVGA/GeneralDownloading.aspx?file=eleet.zip

as far as redist eula? I see NO licence attached to this file AT ALL, BUT u could try asking them directly. call them or email they open 24hr

https://www.evga.com/about/contactus/
https://www.evga.com/support/custsupp.asp

**Comment by pauby** [comment]
> as far as redist eula? I see NO licence attached to this file AT ALL, BUT u could try asking them directly. call them or email they open 24hr

@dreamss That's not the way it works. If there is no explicit redistribution license then it can't be redistributed.

**Comment by pauby** [comment]
Ignore previous question - you addressed that [here](https://github.com/chocolatey/chocolatey-package-requests/issues/429#issuecomment-423818399) - my bad.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/evga-eleet

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/evga-eleet

Can be closed.
