### ISSUE TITLE
RFP - Acronis Virtual Disk Driver

### ISSUE THREAD

**Issue by dreamss** [chocolatey-community/chocolatey-package-requests#430]
Easy support for 3+tb HDD, it creates a 2TB disk and a vrtual one with rest of the space.  ffee

https://kb.acronis.com/content/38937

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/acronis-vdi

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/acronis-vdi

Can be closed.
