### ISSUE TITLE
RFP - Acronis Drive Monitor

### ISSUE THREAD

**Issue by dreamss** [chocolatey-community/chocolatey-package-requests#431]
Acronis Drive Monitor is a free, downloadable software application developed by Acronis to monitor server, workstation and PC hard disk drives. 

Great smart monitor tool that can support custom controller devices with   command line or scripts, see https://kb.acronis.com/content/9698

Download: https://kb.acronis.com/content/58078

**Comment by dreamss** [comment]
actually while not specficly listed it supports any windows NT os, runs great on windows 10.

it does not really need software updates imo

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/acronis-drive-monitor

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/acronis-drive-monitor

Can be closed.
