### ISSUE TITLE
RFP - Davmail

### ISSUE THREAD

**Issue by b16r05** [chocolatey-community/chocolatey-package-requests#432]
I want to request an open source package called Davmail.
Details page here: http://davmail.sourceforge.net/
Download files here: https://sourceforge.net/projects/davmail/files/
Source code here: https://sourceforge.net/p/davmail/code/HEAD/tree/

**Comment by b16r05** [comment]
Nevermind, this is already in: https://chocolatey.org/packages/clementine

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/davmail

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/davmail

Can be closed.

**Comment by b16r05** [comment]
This got done. Awesome, thank you : )
