### ISSUE TITLE
RFP: Tabula - liberate table data from PDF files

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#434]
Tabula is a tool for liberating data tables trapped inside PDF files 

**About:** http://tabula.technology
**Releases:** https://github.com/tabulapdf/tabula/releases

**Why:** If you’ve ever tried to do anything with data provided to you in PDFs, you know how painful this is — you can’t easily copy-and-paste rows of data out of PDF files. Tabula allows you to extract that data in CSV format, through a simple web interface.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/tabula

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/tabula

Can be closed.

**Comment by maphew** [comment]
Thank you!
