### ISSUE TITLE
RFP Adobe Stack (Photoshop, Illustrator, ...)

### ISSUE THREAD

**Issue by swonder900** [chocolatey-community/chocolatey-package-requests#435]
The Adobe software suite (Photoshop, Illustrator, InDesign, ...) is one of the most popular (propertiary) software products in industry use.

Since Adobe doesn't use "traditional setups" but instead an web installer / download manager this might become a bit tricky.
I recommend installing the 30 day trial. After installing the user can log in and thus enable the license.

Since "stack" is a bit vague I would explicitly request the following packages:
- Adobe Photoshop
- Adobe Illustrator
- Adobe InDesign
- Adobe Acrobat Pro
- Adobe Bridge

(these are not all adobe products as listed on [the product list](https://www.adobe.com/creativecloud/catalog/desktop.html) but based on personal preference. Please re-prioritize according to your own experience)

<sub>
Download link structure:

https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v1/wam/download?sapCode=PHSP&productName=[ExactProductName]

e. g. https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v1/wam/download?sapCode=PHSP&productName=Photoshop
</sub>

**Comment by AdmiringWorm** [comment]
please use 1 issue per software, in that case we can close a issue single issue when that exact software is published on chocolatey.org

**Comment by pauby** [comment]
@swonder900 That URL you provide only works for Photoshop (or I'll clarify that - _I_ could only get it to work for Photoshop). If you actually click on it as is - https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v1/wam/download?sapCode=PHSP&productName=[ExactProductName] - it downloads the Photoshop installer. If you change `{ExactProductName}` to `Illustrator` for example, it still downloads the Photoshop installer.

You also need to log in / create an account to progress the installer so it wouldn't be silent and couldn't be automated with Autohotkey (easily).

Given that the premise behind Chocolatey packages are for them to be silent (as much as possible) and to install / upgrade without user intervention I'm don't feel they would make good _Chocolatey_ packages.

**Comment by pauby** [comment]
No update. Closing.

**Comment by sumo300** [comment]
@pauby Not sure if me chiming in on this would be helpful, but I did 5 seconds of research and it looks like you need to be able to log into Adobe and use their Creative Cloud Packager to create silent installers.  And, depending on your licensing, you either have a choice to require the end-user to log in to the product to license it or if you have Enterprise, to package it with a serial #.

Reference: https://www.pdq.com/blog/silently-install-adobe-creative-cloud/

**Comment by pauby** [comment]
@sumo300 If you create the silent installer how will that be distributed? 

* If it is to be distributed with the package then we need the license to allow that - I'm _guessing_ that Adobe won't allow that.
* If it's to be downloaded then do Adobe have a direct URL to allow that download?

If the answer to both of those is no then it's still not suitable for the community repository. It would however be good for an internal (read private) repository.

**Comment by sumo300** [comment]
@pauby I'm assuming no to both of those, but I do not know definitively.  Just trying to help with a little bit of research.  You have to be a licensed Adobe Creative Cloud user to even get the tool and I think the MSIs it generates are specific to that account.

https://helpx.adobe.com/enterprise/package/help/creating-packages.html

**Comment by wget** [comment]
Hello everyone. I'm posting this link here. ProDesign Tools has been very keen for ages into trying to provide offline installers for the Adobe Stack.
Thanks to the creation of a single Adobe account, and the recovery of a specific cookie, it is possible to download the stack locally.
https://prodesigntools.com/adobe-cc-2019-direct-download-links.html
Bundling won't be authorized though AFAIK (legally) and *especially* as these packages far exceed the 200Mio limitation.

**Comment by pauby** [comment]
@wget I appreciate this was a while ago. It looks like there will not, in the foreseeable future, be a way to create a package for this that can be used on the Chocolatey Community Repository? If that is the case then I'm of the mind to close this.

@AdmiringWorm what's your thoughts?

**Comment by AdmiringWorm** [comment]
@pauby I agree with you, no need to keep this one open.
If something change in the future it could always be re-opened then.
