### ISSUE TITLE
RFP - Brandy

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#437]
**Brandy**
> Keep brand assets in sync with your team and right at your fingertips for quick use. 

About / Download: https://getbrandy.io/

**Comment by chtof** [comment]
@vintagesucks The link provided for download is temporary and so, changes each time. Also, the installer can't be embedded as I haven't find license for Brandy.
If the developer doesn't provide a static link to download software, we can't integrate it in Chocolatey package repository.

**Comment by vintagesucks** [comment]
@chtof I [contacted](https://twitter.com/VintageSucks/status/1157732871664259073) the developer on Twitter to let him know.

**Comment by AdmiringWorm** [comment]
@vintagesucks 
I am putting this into the triage stage until you hear back from him.
That means of course that the package is not to be picked up until an answer have been received.

**Comment by pauby** [comment]
@vintagesucks As there has not been any update on this it will be closed in the next three days. Please let us have an update before then.
