### ISSUE TITLE
RFP - PowerFolder

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#442]
Sync Client for PowerFolder (similar to the `nextcloud-client` or `dropbox` package).

Download Page: https://www.powerfolder.com/download-powerfolder-file-sync/
latest Windows installer: https://my.powerfolder.com/dl/firSoD3LMSiXaonvfcs2TQf/PowerFolder_Latest_Installer.exe

**Comment by bcurran3** [comment]
I'm looking into this and will most likely add support in https://chocolatey.org/packages/choco-package-list-backup

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/powerfolder

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/powerfolder

@bcurran3 See if you are still interested to ass support in choco-package-list-backup.

Can be closed.
