### ISSUE TITLE
Open Shell (Fork of Classic shell)

### ISSUE THREAD

**Issue by Mightyretro** [chocolatey-community/chocolatey-package-requests#444]
Hi guys :)

i would love to see this software in choco repo soon becouse how love windows start menu now days :(...

https://github.com/Open-Shell/Open-Shell-Menu/releases

Kind Regards // Guys

**Comment by bcurran3** [comment]
Done.

https://chocolatey.org/packages/open-shell/4.4.131

**Comment by chtof** [comment]
See previous post, so can be closed.
