### ISSUE TITLE
RFM - Adobe Shockwave Player

### ISSUE THREAD

**Issue by b16r05** [chocolatey-community/chocolatey-package-requests#446]
Not too bad, but the current version on choco [ 12.2.8.198 ] is just over a year old. Maintainer is unresponsive as various messages have been sent: https://chocolatey.org/packages/adobeshockwaveplayer

Latest version is: 12.3.4.204 
https://en.wikipedia.org/wiki/Adobe_Shockwave_Player

**Comment by pauby** [comment]
@b16r05 if you're looking to take over this package please use the 'Contact Site Admins' link from the package page.

**Comment by mkevenaar** [comment]
Shockwave is EOL: https://helpx.adobe.com/shockwave/shockwave-end-of-life-faq.html
Because of that, I am going to close this issue

**Comment by pauby** [comment]
@mkevenaar I think we should keep this open. Appreciate it's not updated but the last version pushed is not the most recent (according to this). I might actually just pick this up just so it's _done_ so to speak.

The download URL is https://filehippo.com/download_shockwave/ and the current package is using FileHippo.

**Comment by mkevenaar** [comment]
@pauby both options is fine by me.

**Comment by pauby** [comment]
Requested to be added to the package. I'll update here so we can get this closed asap.

**Comment by pauby** [comment]
I've just pushed a new (final) version.

**Comment by b16r05** [comment]
I just installed this on two PCs. First one, showed a dialog box that wanted input. I clicked "next" and the installation went through fine. The second one, everything went perfectly. 

I did this over independent existing installations (non-chocolatey). Not sure what happens? 
Also, not sure sometimes why two installations show with | FALSE flag?

**Comment by pauby** [comment]
@b16r05 I'm not sure what has happened. I'm not sure what you mean with the |FALSE flag.

If it's an issue, can you raise it at https://github.com/pauby/chocopackages
