### ISSUE TITLE
RFM - tor

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#447]
https://chocolatey.org/packages/tor

If you pick this up please submit a Pull Request to remove the package from [dtgm repository](https://github.com/dtgm/chocolatey-packages/tree/master/automatic/tor/) and the [Ketarin file](https://github.com/dtgm/chocolatey-packages/blob/master/ketarin/tor.xml)

**Comment by TakataSanshiro** [comment]
I’d like to become a new maintainer of one.
My Chocolatey name is 'Sanshiro'.

I couldn't send a message via Contact Site Admins.

> Unable to correctly validate spam validation response:
> missing-input-response

**Comment by mkevenaar** [comment]
@TakataSanshiro Could you please try this again? 

If that is not working, you might need to disable your ad blockers, and/or approve some parts to allow the CAPTCHA to work.

**Comment by TakataSanshiro** [comment]
@mkevenaar Thanks.
I could send a message via Contact Site Admins.

**Comment by TakataSanshiro** [comment]
I submitted a PR to dtgm repository.
https://github.com/dtgm/chocolatey-packages/pull/468

**Comment by TakataSanshiro** [comment]
Status: Published
The PR has been merged.

Can be closed.
