### ISSUE TITLE
RFP - SQL Multi Select

### ISSUE THREAD

**Issue by rplhalim** [chocolatey-community/chocolatey-package-requests#460]
Installer resides in this website
https://www.yohz.com/sms_details.htm

When using pgadmin and having multiple databases, this program allows me to run the same query on all databases at once.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/sql-multi-select

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/sql-multi-select

Can be closed.
