### ISSUE TITLE
RFP - X32-Edit

### ISSUE THREAD

**Issue by max-stockhausen** [chocolatey-community/chocolatey-package-requests#462]
Download of package: [LINK](https://downloads.music-group.com/software/behringer/X32/X32-Edit_PC_3.2.zip)
On this website: [LINK](https://www.musictribe.com/Categories/Behringer/Mixers/Digital-Mixers/X32-COMPACT/p/P0AAP/downloads)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/x32-edit

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/x32-edit

Can be closed.
