### ISSUE TITLE
RFP - mitmproxy 

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#464]
mitmproxy is an interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.

https://mitmproxy.org/

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/mitmproxy

**Comment by chtof** [comment]
Already exists and is up to update.
https://chocolatey.org/packages/mitmproxy

Can be closed.

**Comment by AdmiringWorm** [comment]
Seems like the package was pushed after the request was made.
