### ISSUE TITLE
RFP - Basilisk browser

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#465]
Basilisk is a free and Open Source XUL-based web browser, featuring the well-known Firefox-style interface and operation. It is based on the Goanna layout and rendering engine (a fork of Gecko) and builds on the Unified XUL Platform (UXP), which in turn is a fork of the Mozilla code base without Servo or Rust.

https://basilisk-browser.org/

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/basilisk
- https://chocolatey.org/packages/basilisk.install
- https://chocolatey.org/packages/basilisk.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/basilisk
- https://chocolatey.org/packages/basilisk.install
- https://chocolatey.org/packages/basilisk.portable

Can be closed.
