### ISSUE TITLE
RFM - FBReader 

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#469]
https://chocolatey.org/packages/FBReader

I've contacted the maintainer few weeks ago, he didn't answer yet.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/fbreader

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/fbreader

Can be closed.
