### ISSUE TITLE
RFP - Unar

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#472]
The Unarchiver is a macOS app, but the underlying unarchiving code can run on other OSes, too. There is not yet any GUI app for any other OS, but there are two command-line tools, unar and lsar, which can be used on macOS, Windows and Linux.

https://theunarchiver.com/command-line

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/unar

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/unar

Can be closed.
