### ISSUE TITLE
RFP - Busybox

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#473]
WIN32 native port of BusyBox. BusyBox is a single binary that contains many common Unix tools. It's often found in embedded Linux systems like routers, in Android smartphones, in Linux containers and anywhere else it would be handy to have a compact set of Unix command line tools. 

https://frippery.org/busybox/
https://github.com/rmyorston/busybox-w32

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/busybox

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/busybox

Can be closed.
