### ISSUE TITLE
RFP - Librefox

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#482]
Firefox set for a better security, privacy and performances.

https://github.com/intika/privafox-firefox

**Comment by AdmiringWorm** [comment]
seems like the project have been moved:
https://github.com/intika/Librefox-Firefox

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/librefox-firefox

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/librefox-firefox

Can be closed.
