### ISSUE TITLE
RFP - WxMaxima

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#486]
There is already formulas for [maxima ](https://chocolatey.org/packages?q=maxima)and [gnuplot ](https://chocolatey.org/packages?q=gnuplot) but there is not for [WxMaxima ](https://wxmaxima-developers.github.io/wxmaxima/)yet.

**Comment by pauby** [comment]
Download page - https://wxmaxima-developers.github.io/wxmaxima/download.html

**Comment by mkevenaar** [comment]
According to the latest download page, wxMaxima is included in Maxima. 

https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.0-Windows/

**Comment by Foadsf** [comment]
@mkevenaar so basically `choco install maxima` will install WxMaxim as well? That I didn't know. 🤔

**Comment by mkevenaar** [comment]
@Foadsf based on the release notes of the application, yes. Could you verify?

**Comment by Foadsf** [comment]
@mkevenaar I'm not able to install due to :

~~~
Attempt to get headers for https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.0-Windows/maxima-clisp-sbcl-5.43.0-win64.exe/download failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.0-Windows/maxima-clisp-sbcl-5.43.0-win64.exe/download'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
Downloading maxima 64 bit
  from 'https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.0-Windows/maxima-clisp-sbcl-5.43.0-win64.exe/download'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.43.0-Windows/maxima-clisp-sbcl-5.43.0-win64.exe/download'. Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of maxima was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\maxima\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - maxima (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\maxima\tools\chocolateyInstall.ps1'.
 See log for details.
~~~

**Comment by Foadsf** [comment]
@mkevenaar I confirm that it installs WxMaxima and seem to work properly. Maybe it could be a good idea to add WxMaxima to search query/info of the package, as well as the Chocolatey homepage. Thanks for your kind support.

**Comment by AdmiringWorm** [comment]
@Foadsf I have added the `wxmaxima` tag to the `maxima` package, however it won't show on the package page until the next version is released.

**Comment by mkevenaar** [comment]
@Foadsf Do you agree that we can close this issue?

**Comment by Foadsf** [comment]
@mkevenaar @AdmiringWorm thank you guys. this issue AFIK was due to my lack of knowledge of the new updates of the Maxima project and it can be closed.
