### ISSUE TITLE
RFP - AutoPowerOptionsOK

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#490]
automatic power options adjustment  based on timer

http://www.softwareok.com/?seite=Microsoft/AutoPowerOptionsOK

**Comment by MHketbi** [comment]
on it, ETA: 10 days.

**Comment by mkevenaar** [comment]
@MHketbi Do you have an update on this one?

**Comment by pauby** [comment]
As no package has been pushed for this, and no update in some time, I'm going to open it up to other maintainers again.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/apo-ok
- https://chocolatey.org/packages/apo-ok.install
- https://chocolatey.org/packages/apo-ok.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/apo-ok
- https://chocolatey.org/packages/apo-ok.install
- https://chocolatey.org/packages/apo-ok.portable

Can be closed.
