### ISSUE TITLE
RFM - SunsetScreen

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#491]
outdated version on choco:

https://chocolatey.org/packages/sunset-screen

No respond from:
- author of software
- author of package

http://www.skytopia.com/software/sunsetscreen/

maybe it is good idea to change package name to from `sunset-screen` to `sunsetscreen` as in oryginal there is  no space

**Comment by pauby** [comment]
@qqgg231 Did you contact the maintainer of the package? If so, how and how long ago?

**Comment by qqgg231** [comment]
@pauby 

I was all on Sun, Dec 9

I thought I contacted maintener, but now I see that I probably tried and couldn't  because it is not possible through https://chocolatey.org/packages/sunset-screen/ContactOwners 

Also GitHub page is not available

So I sent only mail to author of app (on 9 Dec )

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published:
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/sunset-screen

- Under review:
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/sunset-screen.install
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/sunset-screen.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/sunset-screen
- https://chocolatey.org/packages/sunset-screen.install
- https://chocolatey.org/packages/sunset-screen.portable

Can be closed.
