### ISSUE TITLE
RFP - flash-decompiler-trillix

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#493]
http://www.flash-decompiler.com/

Trial version is available for download. Unlimited evaluation time, limited function.

For packager: consider embedding installer in package. From [license](http://www.eltima.com/wiki/software-licenses/fd-trial.html):

> The Software can be copied and distributed on condition that the original copyright notice and disclaimer of warranty stay intact and the Licensee does not charge money or fees for the Software product, except to cover distribution costs.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/flash-decompiler-trillix

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/flash-decompiler-trillix

Can be closed.
