### ISSUE TITLE
RFP - NSudo

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#497]
NSudo is a system management tool for advanced users to launch programs with full privileges.

https://github.com/M2Team/NSudo/releases

**Comment by MHketbi** [comment]
on it, ETA: 10 days.

**Comment by mkevenaar** [comment]
@MHketbi Do you have an update on this one?

**Comment by pauby** [comment]
As no package has been pushed for this, and no update in some time, I'm going to open it up to other maintainers again.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/nsudo

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/nsudo

Can be closed.
