### ISSUE TITLE
RFM - wumgr

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#501]
This package is outdated and has no maintainers at the moment.

https://chocolatey.org/packages/wumgr

I did not contact previous maintainer @whiggs yet, since it's not possible trough the site.

---

WuMgr (Update Manager for Windows) is a tool to manage updates of Microsoft products on the Windows operating system. - https://github.com/DavidXanatos/wumgr

**Comment by pauby** [comment]
@dimqua There are no maintainers of this package.

**Comment by boubou** [comment]
Please add me as a maintainer.
I will update it!

**Comment by boubou** [comment]
This issue can be mark as resolved because I updated the package.
