### ISSUE TITLE
RFP - LuxRender and LuxCoreRender

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#503]
- LuxRender website --> http://www.luxrender.net/
- LuxCoreRender can be downloaded from --> https://luxcorerender.org/download/

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/luxcorerender
- https://chocolatey.org/packages/luxcorerender-opencl
- https://chocolatey.org/packages/luxcorerender-opencl-sdk
- https://chocolatey.org/packages/luxcorerender-sdk
