### ISSUE TITLE
RFP - LaunchyQt

### ISSUE THREAD

**Issue by snmishra** [chocolatey-community/chocolatey-package-requests#505]
The original Launchy project has been long abandoned. There is a revived fork at https://github.com/samsonwang/LaunchyQt

Launchy is a free utility designed to help you forget about your start menu, your desktop icons, and your file manager. Launchy indexes and launches your applications, documents, project files, folders, and bookmarks with just a few keystrokes!

**Comment by pauby** [comment]
If this is not a new application then we should look at add it to the current Launchy package. From what I can see this fork simply builds on the work of the previous application?

**Comment by snmishra** [comment]
It does build on existing Launchy application but there are some incompatibilities. Old plugins will not work and there's a new Python plugin system. The old application continues to function though the lack of maintenance is showing. I don't know how to judge the trade-off of potential breakage vs adding a new package.

**Comment by pauby** [comment]
In that case, given the potential to break existing installations (which will obviously have been around a long time) and an entirely new plugin systems, it's probably best to create a new package.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/launchyqt

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/launchyqt

Can be closed.

**Comment by ferventcoder** [comment]
Probably should deprecate the older launchy to point to this one if it will no longer be maintained forward.
