### ISSUE TITLE
RFP - DVD Flick 2

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#506]
Chocolatey lacks choice when it comes to DVD authoring software <sub>[(What's that?)](https://en.wikipedia.org/wiki/DVD_authoring)</sub>.

DVD Flick 2 offers more up to date encoding librarys than the original DVD Flick.

## DVD Flick 2

> As the original DVD Flick project is abandoned, this is a fork of this project to continue with basic support.
> 
> DVD Flick aims to be a tool to convert various PC video formats to a DVD that can be played on pretty much any standalone DVD player. Its main target audience is people who know at least the basics about DVDs and video and audio files.

## DVD Flick

> DVD Flick aims to be a simple but at the same time powerful DVD Authoring tool. It can take a number of video files stored on your computer and turn them into a DVD that will play back on your DVD player, Media Center or Home Cinema Set. You can add additional custom audio tracks, subtitles as well as a menu for easier navigation.

---

Sourceforge https://sourceforge.net/projects/dvdflick-v2/
License: GPL3
Download available via https://sourceforge.net/projects/dvdflick-v2/files/latest/download

<sub>The predecessor:</sub>

<sub>Website www.dvdflick.net/ </sub>
<sub>Sourceforge https://sourceforge.net/projects/dvdflick/ </sub>
<sub>License: GPL3 </sub>
<sub>Download available via https://sourceforge.net/projects/dvdflick/files/latest/download </sub>

---

The documentation of package [cdburnerxp](https://chocolatey.org/packages/cdburnerxp) refers to DVD Flick.

I have installed & tested it and it seems like a mature software to me.
The original has 8000 weekly downloads via SourceForge so there's still an active userbase.
The fork only seems to provide marginal adjustments (but I didn't take a deep look into it)
Given the active download numbers and lack up recent updates this should be a low hanging fruit

**Comment by pauby** [comment]
@JonasDralle Where is the project for DVD Flick 2 located?

**Comment by JonasDralle** [comment]
reading the reviews it seems like this package is not only old but is also using old encodings 😐.

**Comment by JonasDralle** [comment]
I have rephrased the issue to be about the fork

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/dvdflick-v2
