### ISSUE TITLE
RFP - Open DVD Producer

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#507]
Chocolatey lacks choice when it comes to DVD authoring software <sub>[(What's that?)](https://en.wikipedia.org/wiki/DVD_authoring)</sub>.

# Open DVD Producer

> The main functions of the DVD specification are implemented in the software. For example, you can create a DVD in any supported format, with various menus, with directional buttons, videos with chapters and set sections of videos to play.

---

Website https://opendvdproducer.jonata.org/
Sourcecode https://gitlab.com/jonata/opendvdproducer
License: GPL3

Download available via https://github.com/jonata/opendvdproducer/releases/download/16.11/opendvdproducer_16.11.exe.7z
(since the repo moved to GitLab this will probably change in the future)

---

Project is still maintained.

**Comment by chtof** [comment]
Status: **In progress**
- Issue to published the package: https://github.com/chocolatey/chocolatey.org/issues/613#issuecomment-495909781
- Package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/open-dvd-producer

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/open-dvd-producer

_*Successfully published 2 days later and slao from another computer_

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/open-dvd-producer

Can be closed.
