### ISSUE TITLE
RFP - K-Meleon

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#508]
# K-Meleon

> K-Meleon is a fast and customizable web browser that can be used instead of Internet Explorer on Windows. Powered by the same Gecko engine as the Firefox and Mozilla browsers, K-Meleon provides users with a secure browsing experience.

~ 10k weekly downloads on SourceForge

website: http://kmeleonbrowser.org/
sourceforge: https://sourceforge.net/projects/kmeleon/
download link: https://sourceforge.net/projects/kmeleon/files/latest/download
wikipedia https://en.wikipedia.org/wiki/K-Meleon

**Comment by dimqua** [comment]
> Latest Stable Release: K-Meleon 75.1 (20**15**-09-19)

**Comment by pauby** [comment]
@dimqua the age of the package isn't all that's looked at. If this is still widely used and a benefit to the community then that's important.

**Comment by JonasDralle** [comment]
`2016-12-20` K-Meleon 76 Release Candidate
`2017-12-15` K-Meleon 77 development started
(section "Latest News" on the website)

It seems to be software commonly used in russian internet cafés and the development is either really slow or very risk-averse. Can't tell.

Besides, the software is relevant enough to meet the [wikipedia criteria of notability](https://en.wikipedia.org/wiki/Wikipedia:Notability_(software)#Inclusion).



`chocolatey-package-requests` criteria (as far as I understand them)
✔️ package would be cool to have
✔️ no special adjustments to `choco` needed

Besides, we don't know how useful the choco-version really will be.

**Comment by pauby** [comment]
> chocolatey-package-requests criteria (as far as I understand them)
> ✔️ package would be cool to have
> ✔️ no special adjustments to choco needed

@JonasDralle Is this your interpretation or did you see this written somewhere?

**Comment by JonasDralle** [comment]
> (as far as I understand them)

I did not find a relevance criteria inside the README. There's much room to improve

**Comment by JonasDralle** [comment]
I have further researched this and [the guidelines](https://chocolatey.org/docs/create-packages#rules-to-be-observed-before-publishing-packages) says:

> Only post publicly relevant packages. You should consider whether this package is useful for others. If that is not the case, it shouldn't be published on Chocolatey.org. Reasons for that can be if the package would require a very customized configuration. You can host your personal packages on MyGet and still be able to install them with Chocolatey using the -source parameter.

no specific criteria (popularity, recency, interest in current userbase) is mentioned.

---

I'm neither a developer nor a user of `K-Meleon`. I just discovered it and thought "Hey this is lacking in the repos, let's open a request for it" 😉.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/k-meleon
- https://chocolatey.org/packages/k-meleon.install
- https://chocolatey.org/packages/k-meleon.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/k-meleon
- https://chocolatey.org/packages/k-meleon.install
- https://chocolatey.org/packages/k-meleon.portable

Can be closed.
