### ISSUE TITLE
RFP - GeoServer

### ISSUE THREAD

**Issue by JavaZauber** [chocolatey-community/chocolatey-package-requests#510]
# GeoServer

> GeoServer is an open source software server written in Java that allows users to share and edit geospatial data. Designed for interoperability, it publishes data from any major spatial data source using open standards: WMS, WFS, WCS, WPS and REST

---

website http://geoserver.org/
GitHub https://github.com/geoserver/geoserver
SourceForge https://sourceforge.net/projects/geoserver/
download page summary http://geoserver.org/release/stable/
download link https://sourceforge.net/projects/geoserver/files/latest/download
License: GPL2

~ 15k weekly downloads via SourceForge

**Comment by AdmiringWorm** [comment]
I am looking into creating a package for this request

**Comment by AdmiringWorm** [comment]
A new package for this software has been pushed to chocolatey.org and will be available here: https://chocolatey.org/packages/geoserver

**Comment by AdmiringWorm** [comment]
The package has been approved by a moderator and is available for normal consumption.
