### ISSUE TITLE
RFP - AutoClicker

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#512]
# AutoClicker

> A full-fledged autoclicker with two modes of autoclicking, at your dynamic cursor location or at a prespecified location. The maximum amounts of clicked can also be set (or left as infinite).
> 
> Hotkeys work in the background for convenience.

---

sourceforge https://sourceforge.net/projects/orphamielautoclicker/
download link https://sourceforge.net/projects/orphamielautoclicker/files/latest/download
License: CC NC 2.0

~ 568 000 weekly downloads via SourceForge

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/autoclicker

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/autoclicker

Can be closed.
