### ISSUE TITLE
RFP - Amidst

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#513]
# Amidst

> Amidst is a tool to display an overview of a Minecraft world, without actually creating it.

---

GitHub https://github.com/toolbox4minecraft/amidst
Download https://github.com/toolbox4minecraft/amidst/releases

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/amidst

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/amidst

Can be closed.
