### ISSUE TITLE
RFP - Jekyll

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#514]
# Jekyll

> Jekyll is a simple, blog-aware, static site generator perfect for personal, project, or organization sites. Think of it like a file-based CMS, without all the complexity. Jekyll takes your content, renders Markdown and Liquid templates, and spits out a complete, static website ready to be served by Apache, Nginx or another web server. Jekyll is the engine behind GitHub Pages, which you can use to host sites right from your GitHub repositories.

---

Requires package [ruby](https://chocolatey.org/packages/ruby)
then `gem install bundler jekyll`

this and [hugo](https://chocolatey.org/packages/hugo) are the most widely used static-side-generators out there.

_Comment: does it even make sense to have a package that just installs ruby and then a  single gem?_

---

website https://jekyllrb.com/
GitHub https://github.com/jekyll/jekyll

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/jekyll

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/jekyll

Can be closed.
