### ISSUE TITLE
RFM - dupeGuru

### ISSUE THREAD

**Issue by jacktose** [chocolatey-community/chocolatey-package-requests#516]
The [dupeGuru package][choco] is long abandoned and needs a new maintainer. Per [this discussion][forum], the maintainer, dtgm, is AWOL.
The package is a major version behind. It's been four years since it was updated, four and two years since complaints were made in the disqus comments, and six months since I opened [an issue on the maintainer's repo][issue].

[choco]: https://chocolatey.org/packages/dupeguru
[forum]: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chocolatey/ntoPVboXWuU/zqtrtRxxEQAJ
[issue]: https://github.com/dtgm/chocolatey-packages/issues/397

**Comment by chtof** [comment]
Updated package ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/dupeguru

Just waiting to be added as maintainer of the package (request just sent to contact site admins).

**Comment by chtof** [comment]
Updated version under review: https://chocolatey.org/packages/dupeguru/4.0.3

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/dupeguru/4.0.3

Can be closed.
