### ISSUE TITLE
RFP - Jami (formerly Ring)

### ISSUE THREAD

**Issue by b16r05** [chocolatey-community/chocolatey-package-requests#518]
Open source package, available through chocolatey, formerly called Ring, has been renamed, a-gain! Now, it is called Jami. Choco package: https://chocolatey.org/packages/ring/2018.04.14. 

which is out of date as the latest stable Desktop version is 20181123
https://en.wikipedia.org/wiki/Jami_(software)
available from where ??? 
(maybe, https://git.ring.cx/savoirfairelinux/ring-project/tree/master) 

However, a nightly is available and I just want to leave this here for now... 
Jami website: https://jami.net/discover/
Jami download: https://jami.net/download/
Jami on gitlab: https://git.ring.cx/savoirfairelinux

**Comment by pauby** [comment]
@b16r05 Have you [contacted the current maintainer](https://chocolatey.org/docs/package-triage-process)?

**Comment by b16r05** [comment]
My apologies... I missed that step. I go through that process first, before submitting a request.

**Comment by joachimschmidt557** [comment]
Hi, this is the current maintainer of `ring` here. Should I create a new package `jami`?

**Comment by b16r05** [comment]
@joachimschmidt557 
Hi, I wouldn't know. What I do know is that current Ring package can be updated, as their is a newer stable version available. Not sure where from? I think they moved or mirrored from github to gitlab. 
Jami... looks like it is still in nightly/beta. With chocolatey, I think you can have beta packages... so, maybe you could create a Jami package and have it as beta, until the final release takes place? I don't know the chocolatey process. Someone at chocolatey should respond soon : )

**Comment by joachimschmidt557** [comment]
> With chocolatey, I think you can have beta packages... 

Yes, that is the case with the `ring` packages. They are preview versions.

I would suggest creating a new package `jami` and [deprecating](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package) the ring package according to the documentation.

**Comment by pauby** [comment]
@joachimschmidt557 Cool. I'll mark this as in progress and add the Blocked Upstream tag. We can remove that once things change.

**Comment by joachimschmidt557** [comment]
Yes, I'll keep an eye on the development of Jami. Once a new version is out, I'll create the jami package and deprecate the ring package.

**Comment by b16r05** [comment]
Looks like Jami for Windows does not have nightly status anymore... https://jami.net/download-jami-windows/

**Comment by pauby** [comment]
@joachimschmidt557 It looks like Jami is providing their own version now?

**Comment by chtof** [comment]
@pauby I haven't find any version information of Jami so don't know when the package is updated.

**Comment by chtof** [comment]
Well I have just find needed information in https://dl.jami.net/windows/ !
Seems the latest jami*.msi in https://dl.jami.net/windows/archive/ is also the version provided.

**Comment by pauby** [comment]
@chtof Given that, can we remove the 'Blocked Upstream' label?

**Comment by chtof** [comment]
@pauby Yes as we know the provided installer match the latest installer in https://dl.jami.net/windows/archive/

Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/jami

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/jami

Can be closed.
