### ISSUE TITLE
RFP - Lossless Audio Checker 

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#521]
Internet music dealers currently sell "CD-Quality" tracks, or even better ("Studio-Master"), thanks to lossless audio coding formats (FLAC, ALAC). However, a lossless format does not guarantee that the audio content is what it seems to be. The audio signal may have been upscaled (increasing the resolution), upsampled (increasing the sampling rate) or even transcoded from a lossy to a lossless format. Lossless Audio Checker analyzes lossless audio tracks and detects upscaling, upsampling and transcoding.

http://losslessaudiochecker.com/#downloads

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/lossless-audio-checker

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/lossless-audio-checker

Can be closed.
