### ISSUE TITLE
RFP - OfficeToPDF

### ISSUE THREAD

**Issue by rje6459** [chocolatey-community/chocolatey-package-requests#522]
OfficeToPDF is a command line utility that converts Microsoft Office 2003, 2007, 2010, 2013 and 2016 documents from their native format into PDF using Office's in-built PDF export features.

Source: https://github.com/cognidox/OfficeToPDF

Latest Release: https://github.com/cognidox/OfficeToPDF/releases/latest

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/office-to-pdf

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/office-to-pdf

Can be closed.
