### ISSUE TITLE
RFP - SolveSpace

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#529]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

 * Software project URL : http://solvespace.com/index.pl
 * Direct download URL for the software / installer : https://github.com/solvespace/solvespace/releases/tag/v2.3
 * Software summary / short description: SOLVESPACE is a free (GPLv3) parametric 3d CAD tool
 * GitHub: https://github.com/solvespace/solvespace 
 * Maintainer: @whitequark
 * other Repositories and package managers: https://repology.org/metapackage/solvespace/versions

**Comment by pauby** [comment]
@Foadsf We have a template for requesting a package (when you go to raise an issue) - can you please edit your message above and add that?

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/solvespace

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/solvespace

Can be closed.
