### ISSUE TITLE
RFP - gtools

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#532]
## 1. Checklist

- [x] The package I am requesting does not already exist on **<https://chocolatey.org/packages>**;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

---

## 2. Package Details

Software project URL : **<http://www.p-nand-q.com/download/gtools/>**
Direct download URL for the software / installer : **<http://www.p-nand-q.com/download/gtools/gtools-current.exe>**
Software summary / short description: set Windows tools

---

## 3. Package Expectations

Windows users lost data, if user add new value for `PATH` environment variable via `set` or `setx`, but existing value are long. See more about this problem:

+ [**Adding directory to PATH Environment Variable in Windows**](https://stackoverflow.com/a/28778358/5951529)
+ [**Overcoming the 1024 character limit with setx**](https://superuser.com/q/387619/572069)

No built-in method to add new variable programmatically. [**pathed**](http://www.p-nand-q.com/download/gtools/pathed.html) — part of gtools — solve this problem.

Thanks.

**Comment by FranklinYu** [comment]
This is an old software; code was hosted on [Google Code](https://code.google.com/archive/p/pserv4/), and home page was last updated in 2014. According to the source repository, the project is distributed with BSD-3-Clause license, so we can probably embed the source.

With Google I found two GitHub mirrors exported from the Google Code project: https://github.com/maphew/pserv4 and https://github.com/gersonkurz/pserv4.

**Comment by Kristinita** [comment]
`Type: Reply`

> This is an old software; code was hosted on Google Code, and home page was last updated in 2014. 

@FranklinYu , yes, I know it, but I can't find any another tool, that simply and without loss data risks add new value for `PATH` environment. See 3 item of my request.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/gtools

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/gtools

Can be closed.
