### ISSUE TITLE
RFP - KLayout

### ISSUE THREAD

**Issue by omjunior** [chocolatey-community/chocolatey-package-requests#533]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.klayout.de/
Direct download URL for the software / installer : https://www.klayout.org/downloads/Windows/klayout-0.25.7-win64-install.exe
Software summary / short description: KLayout is a free layout viewer (GPL2) used for semiconductor engineers to view (and edit) GDSII layout files.

## Package Expectations
Associate .gds files and .gds.gz files would be nice (it gunzips internally).

**Comment by omjunior** [comment]
I am not sure what you mean.
I checked it is not a package already, that there is no pending RFP for it, it starts with 'RFP -', url is not locked.
It contains the project site, a direct download link, and a description.
Sorry, but I'm new here!

**Comment by omjunior** [comment]
Ah, ok. I saw others now. I was not supposed to remove what was there, even though it says: "PLEASE REMOVE ALL COMMENTS ONCE YOU HAVE READ THEM."
I'll do that.

**Comment by omjunior** [comment]
@pauby Done. I misinterpreted that "PLEASE REMOVE ALL COMMENTS ONCE YOU HAVE READ THEM".

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/klayout

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/klayout

Can be closed.
