### ISSUE TITLE
RFP - Spacemacs

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#534]
# Spacemacs

> Spacemacs is a new way to experience Emacs -- a sophisticated and polished set-up focused on ergonomics, mnemonics and consistency.

## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages; _yup_
- [x] There is no open issue for this package; _not in this repo, no_
- [x] The issue title starts 'RFP - '; _oh I wrote FRP again oops_
- [x] The download URL is public and not locked behind a paywall / login; _GitHub is pretty open right now (Jan 2019)_

## Package Details

Software project URL : http://spacemacs.org/
Direct download URL for the software / installer : https://github.com/syl20bnr/spacemacs/archive/master.zip
Software summary / short description: The best editor is neither Emacs nor Vim, it's Emacs _and_ Vim!

It's package [`emacs`](https://chocolatey.org/packages/Emacs) but with the additional step of cloning a config directory from GitHub.

_Notice:_ ~~I will notify the emacs package maintainers so they're aware of this RFP.~~
emacs-Package maintainers `cbilson` and `0xAFFE` contacted

**Comment by JonasDralle** [comment]
Sidenote: I am really big fan of the newly introducted GitHub Issue Template for reporting package requests. I still have a question:

1) why should I remove the HTML comments? They won't be shown

and an addition:

2) can we put the checklist inside a spoiler? You know, this Bulletinboard-Thing?

<details>
<summary>Click here to find out</summary>
Hello!

```
<details>
<summary>Click here to find out</summary>
Hello!
...
</details>
```
(Whoa this is way more meta than expected, better put dots in there)
</details>

**Comment by pauby** [comment]
@JonasDralle 

> why should I remove the HTML comments? They won't be shown

Just to keep things tidy from the issue perspective. While they might not be shown they will still be stored. It's just a request!

> put the checklist inside a spoiler? You know, this Bulletinboard-Thing?

I'd prefer they were visible but I'm open to what others think. However here really isn't the place to discuss it so I'll refer everybody to [Gitter](https://gitter.im/chocolatey/chocolatey.org)

**Comment by chtof** [comment]
@JonasDralle Hi Jonas, the link you have provided doesn't include either windows executable neither windows installer. Could you confirm and eventually, tell us if a spacemacs windows installer exists?
Thanks in advance.

**Comment by JonasDralle** [comment]
There is no windows installer. Instead [Emacs](https://chocolatey.org/packages/Emacs) would need to be installed and the config downloaded into a `emacs.d` folder

**Comment by chtof** [comment]
Thank you for this information @JonasDralle . I understood it's like a plugin for emacs.

Status: **Review**
https://chocolatey.org/packages/spacemacs

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/spacemacs

Can be closed.
