### ISSUE TITLE
RFP - RadiAnt DICOM Viewer

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#535]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.radiantviewer.com
Direct download URL for the software / installer : https://www.radiantviewer.com/download/?src=mbst&f=setup
Software summary / short description: RadiAnt is a PACS-DICOM viewer for medical images
designed to provide you with a unique experience.
With its intuitive interface and unrivaled performance,
you'll never look back.

It is free, but requires license reactivation after some time (few clicks, free)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/radiant

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/radiant

Can be closed.
