### ISSUE TITLE
RFP - MyOpenLab

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#536]
## Checklist

- [*] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [*] There is no open issue for this package;
- [*] The issue title starts 'RFP - ';
- [*] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://myopenlab.org/inicio/en/
Direct download URL for the software / installer : https://myopenlab.org/descargar-myopenlab/
Software summary / short description: MyOpenLab is a platform for finished elements (program components) that can be linked together. You can also MyOpenLab with a house builder compare the building blocks used to build his house. The modules often create others.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/myopenlab

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/myopenlab

Can be closed.
