### ISSUE TITLE
RFP - Ngspice 

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#537]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://ngspice.sourceforge.net/index.html
Direct download URL for the software / installer : http://ngspice.sourceforge.net/download.html
Software summary / short description: ngspice is the open source spice simulator for electric and electronic circuits.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/ngspice

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/ngspice

Can be closed.
