### ISSUE TITLE
RFP - Jack2

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#538]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://jackaudio.github.io
Direct download URL for the software / installer : https://github.com/jackaudio/jack2/releases/tag/v1.9.12
Software summary / short description:
> JACK2 aka jackdmp is a C++ version of the JACK low-latency audio server for multi-processor machines. It is a new implementation of the JACK server core features that aims at removing some limitations of the JACK1 design. The activation system has been changed for a data flow model and lock-free programming techniques for graph access have been used to have a more dynamic and robust system.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/jack

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/jack

Can be closed.
