### ISSUE TITLE
RFM - gcc-arm-embedded

### ISSUE THREAD

**Issue by bencefr** [chocolatey-community/chocolatey-package-requests#539]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gcc-arm-embedded
Package source URL:

The maintainer of this package doesn't allow contact and there's no package source repository.

Please note that there's a need to have `7-2018-q2-update` as well as the latest `8-2018-q4-major` versions of this package.
I do not wish to maintain this package, however I attach the ones I created as starting point.

[gcc-arm-embedded.7.3.1.20180627.zip](https://github.com/chocolatey/chocolatey-package-requests/files/2840971/gcc-arm-embedded.7.3.1.20180627.zip)
[gcc-arm-embedded.8.2.1.20181220.zip](https://github.com/chocolatey/chocolatey-package-requests/files/2840972/gcc-arm-embedded.8.2.1.20181220.zip)

**Comment by chtof** [comment]
@bencefr I have looked your package. Could you tell me how you determine if an executable should be shimmed or not (for example cc1.exe is not shimmed, why and how do you determine them)?
Thanks in advance!

**Comment by bencefr** [comment]
@pauby , I don't know what it means to shim an exe file. I simply copied the existing package and updated the contents.

**Comment by pauby** [comment]
@bencefr I think that last comment was intended for @chtof 

Shimming is a process of making an executable available on the %path% without changing the %path% itself. So the executable can sit inside the package tools folder and still be available to run directly from the command line.

I think @chtof was asking which executables should be available on the commands line directly.

**Comment by bencefr** [comment]
Sorry @pauby , I misaddressed my previous comment.
@chtof , I am a Unix dev and I expect availability of all tools without major inconvenience of all the awkwardness of Windows environment. I am also not the user of these packages, therefore I have no stong opinions what should or should not be available in the path, so I trust the original package.
However light-heartedly speaking, if I install something with choco and then I would need to dig the drive where something gets installed and then set my paths in weird ways, then I'd question the usefulness of the package manager.

**Comment by AdmiringWorm** [comment]
This have now been picked up by a new maintainer.

@n3rd4i

**Comment by n3rd4i** [comment]
Package has been updated with:
1. `gcc-arm-embedded.7.3.1.20180627.zip`

As for:
2. `gcc-arm-embedded.8.2.1.20181220.zip`
> The GNU ARM Embedded Toolchain for Windows, version 8-2018-q4-major has a critical bug and should not be used.

Based on above comment this [particular] update will be deferred.

**Comment by AdmiringWorm** [comment]
> So, this ticket could be closed?

yup it sure can. Thank you @n3rd4i for stepping up and taking over the maintenance of the package.
