### ISSUE TITLE
RFP - LibreHardwareMonitor

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#542]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
Direct download URL for the software / installer: https://ci.appveyor.com/api/buildjobs/7i88b8109pftbidc/artifacts/bin%2FRelease.zip
Software summary / short description:
similar to openhardaremonitor but active

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/libre-hardware-monitor

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/libre-hardware-monitor

Can be closed.
