### ISSUE TITLE
RFP - lean theroem prover

### ISSUE THREAD

**Issue by chantisnake** [chocolatey-community/chocolatey-package-requests#545]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

### Software project URL : 
https://leanprover.github.io/
### Direct download URL for the software / installer :
https://github.com/leanprover/lean/releases/download/v3.4.2/lean-3.4.2-windows.zip
### Software summary / short description:
Lean is an open source theorem prover and programming language being developed at Microsoft Research. Lean aims to bridge the gap between interactive and automated theorem proving, by situating automated tools and methods in a framework that supports user interaction and the construction of fully specified axiomatic proofs.
The Lean project was launched by Leonardo de Moura at Microsoft Research in 2013. It is an open source project, hosted on GitHub.
You can experiment with an online version of Lean that runs in your browser, or try the online tutorials listed under documentation.
Several users maintain the mathematical components library mathlib for Lean.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/lean

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/

Can be closed.
