### ISSUE TITLE
RFM - gitflow-avh

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey-community/chocolatey-package-requests#546]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gitflow-avh
Package source URL: https://github.com/petervanderdoes/gitflow-avh

**Comment by AdmiringWorm** [comment]
I am curious, couldn't this package actually be deprecated?
Considering that `gitflow-avh` is included in git for windows itself?

/cc @pauby

**Comment by pauby** [comment]
@AdmiringWorm [That makes sense](https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Windows#git-for-windows). You could argue if you have an earlier version of Git then you could use it but Git 2.6.4 is fairly old now.

@steviecoaster What are your thoughts?

**Comment by pauby** [comment]
@steviecoaster Can you let us know your thoughts on this? I've changed the label to Triage until we resolve this

**Comment by steviecoaster** [comment]
I think deprecation makes the most sense here, yes.

**Comment by pauby** [comment]
I'm going to pick this up and do it just so it's out of the way.

**Comment by pauby** [comment]
This has been done at https://chocolatey.org/packages/gitflow-avh/0.0.0.20200718
