### ISSUE TITLE
RFP - Scicoslab

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#553]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://www.scicoslab.org/
Direct download URL for the software / installer : http://cermics.enpc.fr/~jpc/scilab-gtk-tiddly/files/scicoslab4.4.2-install.exe
Software summary / short description:  ScicosLab is a software package providing a multi-platform environment for scientific computation

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/scicoslab

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/scicoslab

Can be closed.
