### ISSUE TITLE
RFP - OpenModelica

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#554]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://openmodelica.org/
Direct download URL for the software / installer : https://openmodelica.org/download/download-windows
Software summary / short description: OPENMODELICA is an open-source Modelica-based modeling and simulation environment intended for industrial and academic usage.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/openmodelica

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/openmodelica

Can be closed.
