### ISSUE TITLE
RFM - Detect It Easy 1.01

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey-community/chocolatey-package-requests#558]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/die/1.01
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/die/

**Comment by pauby** [comment]
Whoever picks this up please raise a PR in the current package source repository to remove it and the ketarin files.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/die

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/die

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/die/2.03
- PR raised on the dgtm repository

Can be closed.
