### ISSUE TITLE
RFM - numpy

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#560]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/numpy
Package source URL: http://www.numpy.org

Package hasn't been updated since 2014 
Chocolatey numpy package version is 1.8.1 for python2
Current numpy stable is 1.16.2

**Comment by AdmiringWorm** [comment]
@luzpaz Have you tried contacting the maintainer of the package?
If so, how did you contact them? and when did you contact them?

**Comment by luzpaz** [comment]
Through the chocolatey package page 'Contact the Maintainers' I'm not sure the first time was. But I also contacted them earlier today. The package hasn't been updated since 2014 so I thought it was relevant to just open this ticket.

**Comment by chtof** [comment]
It seems the only way to install recent versions is to use pip (See https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy).
There is no longer Windows package since version 1.10.4 on SourceForge.

**Comment by pauby** [comment]
I _think_ we already have packages that use pip. @AdmiringWorm does this ring any bells?

**Comment by AdmiringWorm** [comment]
Yes, it indeed rings a bell.
The [mkdocs](https://chocolatey.org/packages/mkdocs) is one such package that makes use of pip.

**Comment by pauby** [comment]
If we have a precedent set then no reason this can't still be a package!

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/numpy

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/numpy

Can be closed.
