### ISSUE TITLE
RFM - Station

### ISSUE THREAD

**Issue by Kilbourne** [chocolatey-community/chocolatey-package-requests#563]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://getstation.com/
Direct download URL for the software / installer : https://dl.getstation.com/download/windows
Software summary / short description: "Station is the first smart browser for busy people. A single place for all of your web applications."

**Comment by AdmiringWorm** [comment]
This one seems to have been pushed once (back in 2017), but no working edition was ever published.

Changing to RFM.

package url: https://chocolatey.org/packages/Station

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/station

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/station

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/station

Can be closed.
