### ISSUE TITLE
RFP - Genymotion Android Emulator

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#570]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

Finding the download link out requires having an account. The download link can be used without authentication.

## Package Details

Software project URL: https://genymotion.com
Direct download URL for the software / installer:
    - without VirtualBox https://dl.genymotion.com/releases/genymotion-3.0.1/genymotion-3.0.1.exe
    - with VirtualBox https://dl.genymotion.com/releases/genymotion-3.0.1/genymotion-3.0.1-vbox.exe
Software summary / short description: 

Properitary emulator for Android devices with advanced features. Supports a great variety of Device Images.

![](https://user-images.githubusercontent.com/6533815/54813927-f6ba9200-4c8e-11e9-930e-388339686d3c.png)

**Comment by pauby** [comment]
@JonasDralle As the downlaod location cannot be accessed without logging in, and unless there is a way to do this from the command line silently, this can't be a package for the Community Repository.

**Comment by JonasDralle** [comment]
it worked with https://github.com/chocolatey/chocolatey-package-requests/issues/383 tho

**Comment by pauby** [comment]
@JonasDralle Just to clarify what I said above:

> As the downlaod location cannot be accessed without logging in, and **unless there is a way to do this from the command line silently**, this can't be a package for the Community Repository.

If there is a way to do this from the command line silently then that is fine.

Can I also ask, again, to edit the initial request and use the template we provided?

**Comment by JonasDralle** [comment]
Issue content has been edited.
Theres no authentication required for the download afterall.

Setup is probably non-standard

**Comment by pauby** [comment]
I've amended the descritpion to say the download URL is public as you [confirmed](https://github.com/chocolatey/chocolatey-package-requests/issues/570#issuecomment-475893722).

**Comment by JonasDralle** [comment]
:+1:
Publicity of link was tested via Mozilla Firefox private window.
Hopefully they won't change it once automated downloads hit them.

The setup looks rather gimmicky so maybe it's non-standard. To use the software a user has to log in via the settings menu (but that's post-install configuration when Genymotion is first launched)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/genymotion

Note: I haven't create a Chocolatey script for the genymotion installer including Oracle VirtualBox as it can been installed with Chocolatey and it's a better way to have separate packages (excepted if the genymotion-vbox does additional tasks, in that case, thanks to send a feedback about it).

**Comment by chtof** [comment]
Status: **In progress**
- This package already exists with an old version (2.6.0).
- Message sent to Disqus and mail sent to package maintainers to know if they have any plans to update to the latest version 3.0.2.
- In case they can't update the package, an updated package is ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/genymotion

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/genymotion

**Comment by JavaZauber** [comment]
mention https://github.com/Genymobile/genymotion-kernel/issues/4
