### ISSUE TITLE
RFP - Auto Mouse Click

### ISSUE THREAD

**Issue by mynameiswolfy** [chocolatey-community/chocolatey-package-requests#573]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.murgee.com/auto-mouse-click/
Direct download URL for the software / installer : https://www.murgee.com/auto-mouse-click/download/setup.exe
Software summary / short description: Software Utility to auto mouse click mouse at defined location. Use Auto Mouse Click Software utility to automatically click left or right button of mouse.

 ## Package Expectations
Simple download of the installer and silent install.

**Comment by mynameiswolfy** [comment]
The installer also opens a browser window and local folder on completion, even on silent install which is an extra hurdle to overcome.

**Comment by pauby** [comment]
@mynameiswolfy If that is the case can you add the 'notSilent' tag?

**Comment by mynameiswolfy** [comment]
There might be a way to make it silent (I hope so!) but I couldn't find the switch to do that. I'm pretty new to this :)

**Comment by AdmiringWorm** [comment]
I had a look at the decompiled code for the installer, and unfortunately they have hard coded the opening of the webpage.

Other than closing the browser (which is a bad idea), there is no way to prevent this.

@mynameiswolfy ^^

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/automouseclick

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/automouseclick

Can be closed.
