### ISSUE TITLE
RFP - Moneydance

### ISSUE THREAD

**Issue by grafst** [chocolatey-community/chocolatey-package-requests#577]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://infinitekind.com/moneydance
Direct download URL for the software / installer : https://infinitekind.com/stabledl/current/Moneydance_windows_amd64.exe
Software summary / short description: Moneydance is easy to use personal finance software that is loaded with all the features you need: online banking and bill payment, account management, budgeting and investment tracking.

## Package Expectations
-maybe enter license code?
-adding icons to the desktop

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/moneydance

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/moneydance

Can be closed.
