### ISSUE TITLE
RFP - caffeinate

### ISSUE THREAD

**Issue by m2nlight** [chocolatey-community/chocolatey-package-requests#580]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/iorate/win-caffeinate
Direct download URL for the software / installer : https://github.com/iorate/win-caffeinate/releases/download/v1.2/win-caffeinate_v1.2.zip
Software summary / short description: A port of caffeinate command from macOS to Windows

This caffeinate command support -t sencods and -w PID or processName. It's good for win7~win10 keep wake up. 
It do not like caffeine (another, has existed in chocolatey packages) that would send F15 or shift key per 59s, F15 is not friendly for git-bash and vim.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/win-caffeinate

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/win-caffeinate

Can be closed.
