### ISSUE TITLE
RFM - NetBeans

### ISSUE THREAD

**Issue by ComFreek** [chocolatey-community/chocolatey-package-requests#582]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;
- [x] I tried contacting the other comaintainers (weeks ago), but did not receive a response. I've now sent another e-mail referencing this issue.

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/netbeans
Package source URL: https://github.com/ComFreek/chocolatey-packages/tree/master/netbeans

## Further notes

- The last approved package version was not pushed by me, but pushed by @Akipe, the package source probably being in https://github.com/Akipe/chocolatey-packages/tree/master/automatic.
- The JDK dependency should be removed, see https://chocolatey.org/packages/netbeans#comment-4354582774.
- The new maintainer might as well be interested in packaging Apache NetBeans (see #572) as a total replacement of NetBeans.

**Comment by pauby** [comment]
@ComFreek Are you going to fix the package version submitted on 2 March?

**Comment by ComFreek** [comment]
@pauby No, I don't intend to.

**Comment by FranklinYu** [comment]
@Akipe is probably not maintaining the package either, since last run of AU was February 2018, according to [AU logs](https://gist.github.com/Akipe/00330331551bc3703af5c89a1d82bfeb).

**Comment by chtof** [comment]
Duplicate? Related to netbeans, see also: https://github.com/chocolatey/chocolatey-package-requests/issues/572

**Comment by pauby** [comment]
@ComFreek I'm going to reject the package in that case. Will link to your comment.

**Comment by pauby** [comment]
@Akipe has updated and submitted a new version of the package. See my [comment](https://github.com/chocolatey/chocolatey-package-requests/issues/572#issuecomment-484399830). Can we please keep updates to the other issue?

**Comment by pauby** [comment]
Apologies. I was too hasty closing this as this is an RFM for the `netbeans` package. Reopening.

**Comment by tunisiano187** [comment]
I'll would like to take this package.
It's ready on my git.
Can you add me as maintainer ?

Thank you.

**Comment by tunisiano187** [comment]
@pauby , Hello, my request to admins by the form seems to be missed again, can you check and add me as maintainer of netbeans ?

Thank you

**Comment by pauby** [comment]
@tunisiano187 no request for netbeans has been received. Can you send it again?

**Comment by flcdrg** [comment]
Added @tunisiano187 as maintainer

**Comment by tunisiano187** [comment]
Hello,
This package is accepted, you can close the request.
Have a nice day.
