### ISSUE TITLE
RFP - CUDA toolkit

### ISSUE THREAD

**Issue by Trance-Paradox** [chocolatey-community/chocolatey-package-requests#588]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;ok
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://developer.nvidia.com/cuda-toolkit
Direct download URL for the software / installer : https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe

Software summary / short description:

**Comment by pauby** [comment]
@Trance-Paradox The Direct Download URL is invalid. It looks like that download link is actually a one time link. Unless somebody can figure a way around that this couldn't be packaged.

**Comment by Trance-Paradox** [comment]
can you try this link the earlier one was from my browser download links

**Comment by pauby** [comment]
@Trance-Paradox That seems to work - I did strip the numbers after the filename in the previous URL but that results in a 403 error. I'll make this available to maintainers now.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to receive (or not) an answer of the current maintainer as this package already exists (https://chocolatey.org/packages/cuda) and hasn't been updated since 2013.
- Updated package ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/cuda

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/cuda

Can be closed.
