### ISSUE TITLE
RFP - SMTube

### ISSUE THREAD

**Issue by vvch** [chocolatey-community/chocolatey-package-requests#589]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
  http://www.smtube.org/
Direct download URL for the software / installer :
  http://sourceforge.net/projects/smtube/files/SMTube/18.11.0/smtube-18.11.0-x64.exe
  http://sourceforge.net/projects/smtube/files/SMTube/18.11.0/smtube-18.11.0-win32.exe
Software summary / short description:
  Useful FOSS add-on for SMPlayer (which already has a chocolatey package) -- YouTube Browser

## Package Expectations
Has 32bit and 64 versions

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/smtube

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/smtube

Can be closed.
