### ISSUE TITLE
RFP - Magicsplat Tcl/Tk for Windows

### ISSUE THREAD

**Issue by snmishra** [chocolatey-community/chocolatey-package-requests#590]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.magicsplat.com/tcl-installer/
Direct download URL for the software / installer : https://sourceforge.net/projects/magicsplat/files/magicsplat-tcl/tcl-8.6.9-installer-1.9.1-x64.msi/download
Software summary / short description: The Magicsplat Tcl/Tk for Windows distribution is a binary Windows Installer based distribution of Tcl/Tk for Windows systems. It includes commonly used libraries, extensions and development tools.

It's an MSI installer and defaults to non-administrator install into %LOCALAPPDATA%. There is ActiveTcl already in Chocolatey, but it's only free for personal use.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/magicsplat-tcl-tk-installer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/magicsplat-tcl-tk

Can be closed.
