### ISSUE TITLE
RFM - wings3d

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#591]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/wings3d  
Package source URL: https://github.com/hcorion/choco-wings3d

## Other Info
Current stable 2.2.4  
Changelog: http://www.wings3d.com/forum/showthread.php?tid=2811

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be pushed: https://github.com/chtof/chocolatey-packages/tree/master/automatic/wings3d

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/wings3d

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/wings3d

Can be closed.
