### ISSUE TITLE
RFM - Natron

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#592]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] ~I have~ User reporting this has followed the Package Triage Process and ~I~ they do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/Natron
Package source URL: https://github.com/Summerspecial/ChocoCont

**Comment by chtof** [comment]
https://natron.fr unavailable today (connection timeout). To check later if it is temporary or not.

**Comment by chtof** [comment]
Seems to be the new URL: https://natrongithub.github.io

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/natron
- https://chocolatey.org/packages/natron.install
- https://chocolatey.org/packages/natron.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/natron
- https://chocolatey.org/packages/natron.install
- https://chocolatey.org/packages/natron.portable

Can be closed.
