### ISSUE TITLE
RFP - VirtualDub2

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#593]
## Package Details

Software project URL : https://sourceforge.net/projects/vdfiltermod/
Direct download URL for the software / installer : https://sourceforge.net/projects/vdfiltermod/files/latest/download
Software summary / short description: A streamlined video editor with simple frame-by-frame timeline. Free, open-source, portable. The default package is ready for use with many essential plugins included, and can be further extended with 3rd party codecs and filters.  Previous name of this project: VirtualDub FilterMod. Maintained successor to VirtualDub.

Virtual Dub 2: http://virtualdub2.com/
Virtual Dub original: http://virtualdub.org/

## Package Expectations
- Add shims for CLI exe's - `vdub64.exe`, `vdub.exe` (just a single one for appropriate host OS type would be fine)
- Add menu link to GUI - `VirtualDub64.exe` or `VirtualDub.exe`

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/virtualdub2

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/virtualdub2

Can be closed.
