### ISSUE TITLE
RFM - LastPass

### ISSUE THREAD

**Issue by bdukes** [chocolatey-community/chocolatey-package-requests#594]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/lastpass
Package source URL: https://github.com/bdukes/Chocolatey-Packages/tree/master/automatic/lastpass

I currently maintain the LastPass package, but they've recently removed the option for a silent installer.  I [was advised](https://chocolatey.org/packages/lastpass#comment-4443490714) to see if anyone is interested in using AutoHotkey to automate the installer.  I don't have any experience using AutoHotKey, and am happy to hand over management of the package.  I'm also willing to maintain the package going forward if anyone wants to contribute the AutoHotKey automation.

**Comment by mkevenaar** [comment]
@bdukes could you add me as a maintainer? Username @mkevenaar

**Comment by bdukes** [comment]
done

**Comment by mkevenaar** [comment]
Currently the LastPass installer won't even start inside Windows Server 2012 R2. I'm trying to figure out why

![image](https://user-images.githubusercontent.com/834643/57132714-bfb4c180-6da0-11e9-868e-b01fa61b3cb3.png)

**Comment by AdmiringWorm** [comment]
@mkevenaar could be that one of the services failed to start. Check if the LDAP service for LastPass have started

**Comment by mkevenaar** [comment]
@bdukes I got it working again. Could you please remove your AU script?

**Comment by bdukes** [comment]
It's been removed, thanks @mkevenaar!
