### ISSUE TITLE
RFP - ssl-verifier

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#597]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.sysadmins.lv/projects/sslverifier/default.aspx
Direct download URL for the software / installer: https://www.sysadmins.lv/dl/4.aspx
Software summary / short description: verify SSL/TLS connection to servers
Source URL: https://github.com/Crypt32/SSLVerifier.WPF

## Package Expectations
Please embed the package.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/sslverifier

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/sslverifier

Can be closed.
