### ISSUE TITLE
RFP - RaiDrive

### ISSUE THREAD

**Issue by amitkeret** [chocolatey-community/chocolatey-package-requests#598]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.raidrive.com/
Direct download URL for the software / installer :
* From project website (can't seem to resolve to file, resolves to webpage instead): https://www.raidrive.com/download.latest.php
* From Softpedia (direct file URI): https://softpedia-secure-download.com/dl/3e1e27a4c35ed253674a6e3cf897bd36/5ccd08f4/100258610/software/tweak/RaiDrive_1.6.2.416.exe
Software summary / short description: RaiDrive is a Windows utility that maps cloud storage services (Google Drive, Google Photos, OneDrive, Dropbox) as Windows drives. It allows for easy integration of cloud-based filesystems to the desktop without having to sync/download all the files in the cloud storage to the local disk.

## Package Expectations
* Automatically open the dialog to add new cloud drives

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/raidrive

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/raidrive

Can be closed.

**Comment by amitkeret** [comment]
? re-open

```
C:\> choco install -y raidrive

Installing the following packages:
raidrive
By installing you accept licenses for the packages.
Progress: Downloading raidrive 1.6.4.518... 100%

raidrive v1.6.4.518 [Approved]
raidrive package files install completed. Performing other installation steps.
Installing raidrive...
WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\raidrive\tools\RaiDrive.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The install of raidrive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\raidrive\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - raidrive (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\raidrive\tools\chocolateyinstall.ps1'.
 See log for details.
```

Here's the [log file](https://pastebin.com/TpVFXBfU).
Looks like the executable is named `RaiDrive_1.6.4.518.exe`, but the installation script is sending a generic `RaiDrive.exe` parameter?

PS: I already have `dotnetfx` and `vcredist2013` installed.

**Comment by pauby** [comment]
@amitkeret This issue was for the package being created which it has and published so the issue was closed. If there are issues with the package can you use the 'Contact Maintainers' link ont he package page to let them know?

**Comment by chtof** [comment]
@Amitkeret A fix was already submitted yesterday (and waiting currently for approval). See https://chocolatey.org/packages/raidrive/1.6.4.51800
