### ISSUE TITLE
RFP - CorsixTH

### ISSUE THREAD

**Issue by SpaceAgeHero** [chocolatey-community/chocolatey-package-requests#599]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/CorsixTH/CorsixTH
Direct download URL for the software / installer : https://github.com/CorsixTH/CorsixTH/releases
Software summary / short description: A reimplementation of the 1997 Bullfrog business sim Theme Hospital. As well as faithfully recreating the original, CorsixTH adds support for modern operating systems (Windows, macOS, Linux and BSD), high resolutions and much more.

**Comment by chtof** [comment]
Status: **In progress**
- corsixth.install is under review : https://chocolatey.org/packages/corsixth.install
- corsixth.portable and corsixth (meta/virtual package) coming soon.

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/corsixth
- https://chocolatey.org/packages/corsixth.install
- https://chocolatey.org/packages/corsixth.portable

Can be closed.
