### ISSUE TITLE
RFP - Voicemeeter

### ISSUE THREAD

**Issue by wickles** [chocolatey-community/chocolatey-package-requests#600]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.vb-audio.com/Voicemeeter/index.htm ([banana](https://www.vb-audio.com/Voicemeeter/banana.htm), [potato](https://www.vb-audio.com/Voicemeeter/potato.htm))
Direct download URL for the software / installer (**potato version**) : [exe](https://download.vb-audio.com/Download_CABLE/Voicemeeter8Setup.exe), [~~zip/portable~~ zipped exe](https://download.vb-audio.com/Download_CABLE/Voicemeeter8Setup_v3007.zip)

Software summary / short description: 

> Voicemeeter is Audio Mixer Application endowed with Virtual Audio Device used as Virtual I/O to mix and manage any audio sources from or to any audio devices or applications.

Voicemeeter is donationware. For some reason they ship tiered versions with better feature sets (**potato > banana > basic**). The higher tiered versions include the lesser versions, so it's probably best to just make one package for the top tier version that includes everything (potato version).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/voicemeeter

**Comment by wickles** [comment]
You're right, there's not a portable version. My mistake. I'm not sure what you mean by your second point?

**Comment by wickles** [comment]
Updated for clarity. The download links I put are for potato version, like I said this should be the default version.

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/voicemeeter
- https://chocolatey.org/packages/voicemeeter.install
- https://chocolatey.org/packages/voicemeeter.portable

Can be closed.
