### ISSUE TITLE
RFP - milton

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#601]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/serge-rgb/milton

Direct download URL for the software / installer : https://github.com/serge-rgb/milton/releases/tag/v1.6.0

Software summary / short description:  
Milton is an open source application that lets you Just Paint.

There are no pixels, you can paint with (almost) infinite detail. It feels raster-based but it works with vectors. It is not an image editor. It is not a vector graphics editor. It is a program that lets you draw, sketch and paint. There is no save button, your work is persistent with unlimited undo.

https://github.com/serge-rgb/milton/blob/master/README.md#windows

![Milton Paint ss](http://i.imgur.com/4pdHeeI.png)

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/milton
- https://chocolatey.org/packages/milton.install
- https://chocolatey.org/packages/milton.portable

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/milton
- https://chocolatey.org/packages/milton.install
- https://chocolatey.org/packages/milton.portable

Can be closed.
