### ISSUE TITLE
RFP - Playlist Creator

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#602]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.oddgravity.de/app-opc.php
Direct download URL for the software / installer : https://www.oddgravity.de/download.php?id=100

Software summary / short description:
  Following the Unix philosophy "one tool for one job" Playlist Creator enables you to create playlists of your precious music within seconds.

Makes .pls or .m3u playlist files

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/playlist-creator
- https://chocolatey.org/packages/playlist-creator.install
- https://chocolatey.org/packages/playlist-creator.portable
