### ISSUE TITLE
RFP - pdf2djvu

### ISSUE THREAD

**Issue by amitkeret** [chocolatey-community/chocolatey-package-requests#605]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : [Project](http://jwilk.net/software/pdf2djvu) | [GitHub](https://github.com/jwilk/pdf2djvu)
Direct download URL for the software / installer : [Link](https://github.com/jwilk/pdf2djvu/releases/download/0.9.12/pdf2djvu-win32-0.9.12.zip)

Software summary / short description:

pdf2djvu is a command-line tool to create DjVu files from PDF files.
It's able to extract:
* graphics,
* text layer,
* hyperlinks,
* document outline (bookmarks),
* metadata (including XMP metadata).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/pdf2djvu

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/pdf2djvu

Can be closed.
