### ISSUE TITLE
RFM - sqlitebrowser

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#606]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/sqlitebrowser
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/sqlitebrowser/

**Comment by mkevenaar** [comment]
I am willing to try this one.

**Comment by pauby** [comment]
You are too quick @mkevenaar

**Comment by mkevenaar** [comment]
https://chocolatey.org/packages/sqlitebrowser/3.11.2
https://chocolatey.org/packages/sqlitebrowser.install/3.11.2
https://chocolatey.org/packages/sqlitebrowser.portable/3.11.2

**Comment by mkevenaar** [comment]
Package is published.
