### ISSUE TITLE
RFP - MBOX Viewer

### ISSUE THREAD

**Issue by Ashkaan** [chocolatey-community/chocolatey-package-requests#608]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://sourceforge.net/projects/mbox-viewer/
Direct download URL for the software / installer : https://sourceforge.net/projects/mbox-viewer/files/v1.0.3.1/mbox-viewer.exe-v1.0.3.1.zip/download
Software summary / short description: It opens MBOX files on Windows

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/mboxviewer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/mboxviewer

Can be closed.
