### ISSUE TITLE
RFP - KLatexFormula

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#609]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://klatexformula.sourceforge.io/
Direct download URL for the software / installer : https://sourceforge.net/projects/klatexformula/
Software summary / short description: 

KLatexFormula is an easy-to-use graphical application for generating images (that you can drag and drop, copy and paste or save to disk) from LaTeX equations.

**Comment by chtof** [comment]
Status: **In progress**
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/klatexformula
- klatexformula needs Latex so will depend on miktex. But currently there is an error to install miktex/miktex.install (binary file can't be installed and a newer version is available). I have just sent a message to maintainer to know if he has planned to update miktex.install.

**Comment by Foadsf** [comment]
I know I'm not supposed to say this here, but dear @chtof you are an awesome human being. you have my ❤ and respect. please share your Patreon account here.

**Comment by chtof** [comment]
Hi Foad, thank you for your comment! I am glad you have appreciate some of my packages.
My Patreon account is available [here](https://www.patreon.com/chtof).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/klatexformula

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/klatexformula

Can be closed.
