### ISSUE TITLE
RFP - spacedesk

### ISSUE THREAD

**Issue by amitkeret** [chocolatey-community/chocolatey-package-requests#610]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://spacedesk.net/
Direct download URL for the software / installer : [64-bit](https://spacedesk.net/downloadidd64) | [32-bit](https://spacedesk.net/downloadidd32)
Software summary / short description: 

**spacedesk** expands the Windows desktop computer screen to other computers over the local area network. At least 2 machines are needed to operate spacedesks:
1. Primary: Windows PC, laptop or Surface Pro tablet. It runs the spacedesk DRIVER software.
2. Secondary: runs spacedesk VIEWER program which acts as the secondary display.
    * [Windows](https://spacedesk.net/downloadclient) ( 7 / 8.1 / 10 )
    * [Android](https://play.google.com/store/apps/details?id=ph.spacedesk.beta) (> version 4.1)
    * [iOS](https://itunes.apple.com/us/app/spacedesk-datronicsoft/id1069217220) (> version 9.3)
    * [HTML5](http://spacedesk.ph/html5viewer/) ( Chrome (> 16), Safari (> 5.1) Internet Explorer (> 10), Opera (> 27) )

**Comment by chtof** [comment]
Status: **In progress**
- https://chocolatey.org/packages/spacedesk-server (In review)
- https://chocolatey.org/packages/spacedesk-client (coming soon)

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/spacedesk-server
- https://chocolatey.org/packages/spacedesk-client

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/spacedesk-server
- https://chocolatey.org/packages/spacedesk-client

Can be closed.
