### ISSUE TITLE
RFM - internet-download-manager

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#611]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/internet-download-manager
Package source URL: https://github.com/Elderry/chocolatey-packages/tree/master/automatic/internet-download-manager

**Comment by AdmiringWorm** [comment]
@FranklinYu how and when did you try contacting the existing maintainer of the package?

**Comment by FranklinYu** [comment]
I think I have used "Contact Maintainer". If there is no record in the internal server I can do it again.

**Comment by AdmiringWorm** [comment]
There probably are a record (I do not have access to the servers as I am not employed by chocolatey).

What about the second part of the question? When did you try contacting the maintainer?

**Comment by FranklinYu** [comment]
A week ago; I typically leave Disqus comment as public timestamp.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/internet-download-manager

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/internet-download-manager/6.33

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/internet-download-manager/6.33

Can be closed.
