### ISSUE TITLE
RFP - Auto-Dark-Mode

### ISSUE THREAD

**Issue by SZanlongo** [chocolatey-community/chocolatey-package-requests#613]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/Armin2208/Windows-Auto-Night-Mode
Direct download URL for the software / installer: https://github.com/Armin2208/Windows-Auto-Night-Mode/releases/download/2.2/AutoDarkMode_Setup.exe
Software summary / short description: Automatically switches between the dark and light theme of Windows 10 at scheduled times.

## Package Expectations
Simple download of the installer and silent install.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/auto-dark-mode
