### ISSUE TITLE
RFM - Scilab

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#614]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/SciLab
Package source URL: https://www.scilab.org/download/6.0.2

Date the maintainer was contacted: two months ago
How the maintainer was contacted: via [this ](http://disq.us/p/20r3btn) Disqus comment and [this ](https://github.com/dtgm/chocolatey-packages/issues/452) GitHub issue

## Other:

According to [this comment](http://disq.us/p/229jlbn), this formula should be auto-updatable. However, it doesn't seem to be the case.

**Comment by basictheprogram** [comment]
Given what I see in the git repo, it looks like this package is maintained by the DEPRECATED - Using Chocolatey Package Updater with 3rd party tool Ketarin method. 

I find both chocopkgup and AU convoluted. I just maintain my packages by hand.

Does a RFM allow for me to pull the package out of https://github.com/dtgm/chocolatey-packages.git project and just maintain the SciLab package by hand?

**Comment by pauby** [comment]
@basictheprogram there is no requirement to have your packages automatically updated using AU or anything else so yes you can update by hand.

**Comment by basictheprogram** [comment]
We use this package internally so I will adopt and maintain the package. I'll upload a package after I know I've become the maintainer.

**Comment by AdmiringWorm** [comment]
@basictheprogram to become the new maintainer, you will need to use the `Contact Site Admins` link on the package page.

Just request there to be added as a maintainer, and link to this isue.

**Comment by chtof** [comment]
So this one can also be closed?

**Comment by AdmiringWorm** [comment]
looks that way.

@basictheprogram in the future, please leave a comment on the issue when:

1. You start working on a package
2. You push the package to chocolatey.org
3. When the package have been approved by the moderators.

This way we can label the issue correctly according the what the status of the request is.

**Comment by basictheprogram** [comment]
I assumed the commit at https://github.com/basictheprogram/chocolatey-packages-dtgm/commit/c1940aafdb679f3eb57f55ee5cb9423cf9f466ba did all of those things.

**Comment by AdmiringWorm** [comment]
@basictheprogram the commit would only close this issue when the PR gets merged, and only **if** the person merging the PR have permissions to close issues in this repository.

However, we also add/change labels according to the state of the package (as I mentioned in my previous comment), and without a comment on the respective issue we wouldn't know what the state is, and can not add/change the labels according to the state of the package.
