### ISSUE TITLE
RFP - JModelica

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#615]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://jmodelica.org/
Direct download URL for the software / installer : https://jmodelica.org/downloads/JModelica.org-2.4.exe
Software summary / short description:  from [their website](https://jmodelica.org/):
> JModelica.org is an extensible Modelica-based open source platform for optimization, simulation and analysis of complex dynamic systems.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/jmodelica

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/jmodelica

Can be closed.
