### ISSUE TITLE
RFP - Extraterm

### ISSUE THREAD

**Issue by dimqua** [chocolatey-community/chocolatey-package-requests#616]
## Package Details
**Software project URL**: http://extraterm.org/

**Direct download URL for the software/installer**: https://github.com/sedwards2009/extraterm/releases

**Software summary / short description**: 
Extraterm is an open source project to build a terminal emulator and expand it with new features to support modern workflows and do more than just act like a glorified teletype.
## Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/extraterm
- https://chocolatey.org/packages/extraterm.install
- https://chocolatey.org/packages/extraterm.portable
