### ISSUE TITLE
RFP DISM++

### ISSUE THREAD

**Issue by necrose99** [chocolatey-community/chocolatey-package-requests#617]
## Package Details

Software project URL : https://www.chuyu.me/en/index.html 
Direct download URL for the software / installer : http://cdn.chuyu.me/Dism++10.1.1000.100_2d2bf466baca088c4b35248f5a7316f4e00cac0b.zip 
Software summary / short description:Dism++ can be considered as a GUI frontend of DISM, but it is based on low-level Component Based Servicing (CBS) interface instead of DISM API or DISM Core API.

**can be handy in PE if nothing else works , for UEFI fixes...** 
**[gandalfs-PE ](http://windowsmatters.com/2018/07/10/gandalfs-win10pe-x64-redstone-3-build-16299-version-07-10-2018/), Choco install dism++ --HELL-YEAH** 
[1806/1809 have a F#$%^%$# You on the fixboot at times... ](https://www.disk-partition.com/windows-10/fixboot-access-denied-windows-10.html)  however the average user wont have the patience. 
**the fix health option is less hair pulling... period..** 

### ZIP includes , 
**x64 
x86 
arm64**  (as of yet Choco istn yet??? supporting arm64 , however 
https://www.raspberrypi.org/forums/viewtopic.php?t=215345
https://github.com/WOA-Project/WOA-Deployer-Rpi ) 
however 
urlA64=$url in this use case. 

 ## Package Expectations
SHIM-gen , for appropriate $Arch util Start-menu or desktop a plus. 
a64 support inside would be forward thinking though.

**Comment by pauby** [comment]
@necrose99 can you go back and fix your request to use the template provided.

**Comment by pauby** [comment]
No update. Closing. If it's fixed at a later time we can reopen.

**Comment by necrose99** [comment]
Ill make the pkg template.. 
Etc.. 
Just havent had a sec.

**Comment by pauby** [comment]
@necrose99 Once you submit the package let us know and we can reopen this at that time.
