### ISSUE TITLE
RFP - GB Studio

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#618]
![GB Studio][screenshot]

# GB Studio
A free and easy to use retro adventure game creator for your favourite handheld video game system 

## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details
|[]()  | |
|------|------|
| Software project URL 	| https://www.gbstudio.dev/ 	|
| Direct download URL for the software/installer 	| https://github.com/chrismaltby/gb-studio/releases/download/v1.1.0/GB.Studio-win32-x64-squirrel-1.1.0.zip (64-bit installer) 	|
| Alternative downloads 	| https://www.gbstudio.dev/download/ or https://github.com/chrismaltby/gb-studio/releases 	|

[screenshot]: https://www.gbstudio.dev/img/screenshot_win.png "GB Studio"

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/gbstudio
- https://chocolatey.org/packages/gbstudio.install
- https://chocolatey.org/packages/gbstudio.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/gbstudio
- https://chocolatey.org/packages/gbstudio.install
- https://chocolatey.org/packages/gbstudio.portable

Can be closed.
