### ISSUE TITLE
RFP - TeXmacs 

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#619]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.texmacs.org/tmweb/home/welcome.en.html
Direct download URL for the software / installer : https://www.texmacs.org/tmweb/download/windows.en.html
Software summary / short description: GNU TeXmacs is a free wysiwyw (what you see is what you want) editing platform with special features for scientists.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/texmacs

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/texmacs

Can be closed.
