### ISSUE TITLE
RFP - SciDAVis

### ISSUE THREAD

**Issue by naoliv** [chocolatey-community/chocolatey-package-requests#620]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: http://scidavis.sourceforge.net/
Direct download URL for the software / installer: https://downloads.sourceforge.net/project/scidavis/SciDAVis/1.25/scidavis.1.25-win-dist.msi
Software summary / short description: data analysis and visualization of scientific data

SciDAVis is a user-friendly data analysis and visualization program primarily aimed at high-quality plotting of scientific data. It strives to combine an intuitive, easy-to-use graphical user interface with powerful features such as Python scriptability.

## Package Expectations
Have it installed and created an icon at the desktop, if possible.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/scidavis

**Comment by naoliv** [comment]
Thank you!

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/scidavis

Can be closed.

**Comment by naoliv** [comment]
Closing. Thanks a lot again!
