### ISSUE TITLE
RFP - dexed

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#621]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL:  http://asb2m10.github.io/dexed/  
Direct download URL for the software/installer: https://github.com/asb2m10/dexed/releases/download/v0.9.4hf1/dexed-0.9.4-win.zip  
Software summary / short description:  
A software synth closely modeled on the Yamaha DX7

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/dexed

**Comment by AdmiringWorm** [comment]
looks like the package have been approved
