### ISSUE TITLE
RFP - Wireguard for Windows

### ISSUE THREAD

**Issue by churchthecat** [chocolatey-community/chocolatey-package-requests#622]
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.wireguard.com/install/#windows-pre-alpha
Direct download URL for the software / installer : https://download.wireguard.com/windows-client/wireguard-amd64-0.0.14.msi
Software summary / short description:

Official wireguard client for Windows. (64 bit)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/wireguard

**Comment by AdmiringWorm** [comment]
Looks like the package was automatically exempted as it was submitted as a pre-release.
