### ISSUE TITLE
RFM - MFCMapi

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#623]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/MFCMapi
Package source URL: https://github.com/stephenegriffin/mfcmapi
Date the maintainer was contacted: June 3, 2019
How the maintainer was contacted: “Contact Maintainer” link

See also bill-long/chocolatey-packages#2.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/mfcmapi

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/mfcmapi

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/mfcmapi

Can be closed.
