### ISSUE TITLE
RFP - povray

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#625]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: http://povray.org/
Direct download URL for the software / installer: http://www.povray.org/redirect/www.povray.org/ftp/pub/povray/Official/povwin-3.7-agpl3-setup.exe  
Note:  
> POV-Ray for Windows requires Windows XP or later, and has been tested on versions up to and including Windows 8. We recommend having at least 100mb or so of free disk space (for temporary file storage during renders) and at least 1GB of available memory, though less is OK if you are not doing complicated scenes. Since the POV-Ray for Windows distribution package includes both the 32 and 64-bit binaries, the setup file determines which one to provide as the main program link (all versions are installed). Full documentation and sample scene files are also included.

Software summary / short description:
FOSS tool for creating stunning three-dimensional graphics.

**Comment by AdmiringWorm** [comment]
is this the package you are requesting?
https://chocolatey.org/packages/pov-ray

**Comment by luzpaz** [comment]
Yes! sorry it is spelled differently in other places.
