### ISSUE TITLE
RFM - Kid3

### ISSUE THREAD

**Issue by CypherNL** [chocolatey-community/chocolatey-package-requests#627]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

**Package URL:** https://chocolatey.org/packages/kid3
**Package source URL:** The Chocolatey packages repo of the maintainer is gone. The source was previously located at: https://github.com/svnpenn/p/tree/master/kid3
You can download the raw nupkg file here: https://chocolatey.org/api/v2/package/kid3/3.3

**Date the maintainer was contacted:** 21-06-2019
**How the maintainer was contacted:** With the "Contact Maintainer" function.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/kid3

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/kid3

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/kid3

Can be closed.
