### ISSUE TITLE
RFM - Hadoop

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-package-requests#628]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Existing Package Details

Package URL: https://chocolatey.org/packages/hadoop
Package source URL: https://github.com/jtcmedia/chocolatey-packages/tree/master/hadoop

**Comment by mkevenaar** [comment]
@jtcmedia could you add me as a maintainer please? Username mkevenaar

Thanks

**Comment by jtcmedia** [comment]
done, it's pending approval. Thanks!

**Comment by AdmiringWorm** [comment]
@mkevenaar any status update for this request? Or is it still in progress?

**Comment by AdmiringWorm** [comment]
@mkevenaar what is the current status of this request? Have it been completed, or is it still in progress?

**Comment by mkevenaar** [comment]
@AdmiringWorm I am still working on this.

**Comment by pauby** [comment]
@mkevenaar Have you got an update on this?

**Comment by pauby** [comment]
New version was pushed in September 2019 which is after this request was made so closing this now. If we need to reopen let us know.

**Comment by jtcmedia** [comment]
Can this be re-opened @pauby ? @mkevenaar  never picked this up and I no longer wish to maintain it.

**Comment by mkevenaar** [comment]
That must have slipped my mind, I am sorry. Will look at it tomorrow!

**Comment by mkevenaar** [comment]
An updated version of hadoop 3.3.3 is pushed: https://community.chocolatey.org/packages/hadoop/3.3.3

**Comment by mkevenaar** [comment]
A new version is released and approved

**Comment by mkevenaar** [comment]
That must have slipped my mind, I am sorry. Will look at it tomorrow!

Verstuurd vanaf mijn iPhone

**Comment by pauby** [comment]
You're already maintaining and updating this package @mkevenaar .... 😄
