### ISSUE TITLE
RFM - WinXcorners

### ISSUE THREAD

**Issue by GecoMynx** [chocolatey-community/chocolatey-package-requests#629]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/winxcorners
Package source URL: https://apps.codigobit.info/2015/10/winxcorners-hot-corners-for-windows-10.html
Date the maintainer was contacted: Last Week, I think it was the 3rd of July
How the maintainer was contacted: Via Twitter (longer ago), via GitHub (also longer ago) via Chocolatey because the triage process requested it (this one was on 3rd July).

**Comment by pauby** [comment]
A new version of this package was submitted on 7 July by @sanshiro so I'm going to go ahead and close this just not as the package is actively being maintained.

**Comment by GecoMynx** [comment]
It didn't change a thing, here is the Chocolatey Log and Transcript of the installation Process:
[Choco install WinXcorners Log.pdf](https://github.com/chocolatey-community/chocolatey-package-requests/files/3367492/Choco.install.WinXcorners.Log.pdf)

**Comment by pauby** [comment]
@GecoMynx This is a request for a new maintainer. The reason this was closed is there is no need for a new maintainer as the package is being actively maintained (last submitted version was yesterday).

If there are issues with the package then you need to use the [Package Triage Process](https://chocolatey.org/docs/package-triage-process).

**Comment by GecoMynx** [comment]
I have done that, as you can read in my Post.
I got no response and the issue also still isn't resolved and I'm still not the only one having the exact same issue with installing it.

**Comment by pauby** [comment]
@GecoMynx I haven't seen any messages to the Site Admins (see [step 4](https://chocolatey.org/docs/package-triage-process#the-triage-process))? Did you do that? If you haven't can you do that now, I'll pick it up and we can follow this through via email and report the result here (rather than filling this with messages which are off-topic)?

I've sent the maintainer an email just now as from your logs it looks like the download URL is a Google Drive / Google Docs URL which we need more information on.

**Comment by GecoMynx** [comment]
Yes, I did that, two times in fact: First time to the Maintainer a few days ago and then today morning to the site admin.

**Comment by pauby** [comment]
@GecoMynx I can see no message from you or one about WinXCorners in my email. If you can do that agaian (use COntact Site Admins on the package page) I will pick it up and we can take this offline and report the resolution back here.

**Comment by GecoMynx** [comment]
Sure thing, just give me a few minutes, doing it inside my work hours right now.
