### ISSUE TITLE
RFP - Altcopy

### ISSUE THREAD

**Issue by jeff9315** [chocolatey-community/chocolatey-package-requests#630]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://altcopy.net/
Direct download URL for the software / installer :  https://altcopy.net/setup.exe
Software summary / short description:
Altcopy is a free program that allows you to copy/paste between a Windows PC and a smart device (e.g., phone). 

Copy text from your PC to your Smart device's clipboard, and Paste text from your device's clipboard to your PC, instantly! All you need is the PC application, and the Android application on your device.

Sorry, I didn't kn ow the checklist was used. I've added it in now.

**Comment by pauby** [comment]
@jeff9315 Can you go back and edit your request to use the template? The checklist is important.

**Comment by jeff9315** [comment]
OK ... Sorry @pauby ... I didn't realize that was important. I've added it in now.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/altcopy

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/altcopy

Can be closed.
