### ISSUE TITLE
RFP - Clockify

### ISSUE THREAD

**Issue by amitkeret** [chocolatey-community/chocolatey-package-requests#632]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://clockify.me/
Direct download URL for the software / installer : [Link](https://clockify-resources.s3.eu-central-1.amazonaws.com/downloads/Clockify_Setup_1_6_4.exe)
Software summary / short description:
Clockify is the only 100% free time tracking app for Windows that lets you and your team log hours straight from your desktop while working.
Icon: [Link](https://clockify.me/assets/images/clockify-logo.png)

**Comment by chtof** [comment]
Hi @amitkeret , it seems the download link needs to be logged on Clockify.me to be used. Do you have another link which doesn't requires to be logged on Clockify.me?

**Comment by AdmiringWorm** [comment]
@chtof seems like the downnload link can be aquired from here: https://clockify.me/apps

It seems to work without being logged in.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/clockify

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/clockify

Can be closed.

**Comment by amitkeret** [comment]
great news! however...
checksum failure for Clockify_Setup.exe
actual checksum: 68D2A2B1514D54C1A62689C1372C313E60B1AF84DEC2DC34505A284FB5326A3E

**Comment by chtof** [comment]
Thank you. Version 1.7.3 has been released, so we have if possible to find another way to be be informed about new versions.

**Comment by amitkeret** [comment]
how would this work for other apps?
download-page parsing? JSON/XML URI with version?

**Comment by chtof** [comment]
It's often a download-page parsing when the version number is displayed in the download-page or in the name of the installer.
In the current case, there is another way but it's a little bit more complicated to implement.
