### ISSUE TITLE
RFP - Keeper

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#633]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://keepersecurity.com
Direct download URL for the software / installer : https://keepersecurity.com/download.html
Software summary / short description: 

 

> Cybersecurity starts with password security
>
> Keeper is the top-rated password manager for protecting you, your family and your business from password-related data breaches and cyberthreats.

**Comment by steviecoaster** [comment]
I'll take this one. Good excuse for an upcoming Azure Devops demo

**Comment by qqgg231** [comment]
It may not matter, but iirc installer uses nupkg package during install, maybe this can be used by Choco script, but I am not sure

**Comment by steviecoaster** [comment]
This is pushed to the community repository pending moderation.

**Comment by chtof** [comment]
Hi @steviecoaster , could you tell us under which name can we find this package on chocolatey? I haven't find any package named "keeper" or "keepersecurity" on chocolatey.

**Comment by AdmiringWorm** [comment]
Moving back to "Available for maintainers" due to lack of response, and no package found matching expected keywords.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/keeper

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/keeper

Can be closed.
