### ISSUE TITLE
RFM - DMDE - DM Disk Editor and Data Recovery Software

### ISSUE THREAD

**Issue by qqgg231** [chocolatey-community/chocolatey-package-requests#634]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://dmde.com/
Direct download URL for the software / installer : https://dmde.com/download.html
Software summary / short description:  

> DMDE is a powerful software for data searching, editing, and recovery on disks. It may recover directory structure and files in some complicated cases through the use of special algorithms when other software can't help. The software is listed, reviewed, and awarded in magazines and catalogs.
> 
> DMDE has a number of freeware features such as disk editor, simple partition manager (e.g. allows partition undeleting), a tool to create disk images and clones, RAID constructor, file recovery from the current panel. Paid editions support file and directory recovery without the restriction, DMDE Professional Edition has additional features to recover data for clients
> 
> (...)
> 
> DMDE is portable and runs just after extracting.

**Comment by AdmiringWorm** [comment]
Changed to RFM due to package existing.
Package was submitted in 2014, currently failing, is unlisted and author have removed github repository. Assuming it is no longer being maintained.
https://chocolatey.org/packages/dmde

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/dmde

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/dmde

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/dmde

Can be closed.
