### ISSUE TITLE
RFM - Folder Colorizer

### ISSUE THREAD

**Issue by joachimschmidt557** [chocolatey-community/chocolatey-package-requests#635]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/foldercolorizer
Package source URL: https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/tree/master/manual/foldercolorizer

There is a new version of Folder Colorizer available, but currently I don't have the time to work on getting the correct URL. The [download URL of the homepage](https://softorino.com/foldercolorizer2/) somehow redirects and I can't seem to get the file via PowerShell.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/foldercolorizer

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/foldercolorizer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/foldercolorizer

Can be closed.
