### ISSUE TITLE
RFM -plantronicshub

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-package-requests#636]
## Current Maintainer: amoisis

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X ] There is no existing open maintainer request for this package;

## Checklist

- [ X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/plantronicshub
Package source URL: n/a

Date the maintainer was contacted: 2019-04-27 & previous unknown date earlier in the year
How the maintainer was contacted: https://chocolatey.org/packages/plantronicshub/ContactOwners

> From: noreply=chocolatey.org@mg.chocolatey.org <noreply=chocolatey.org@mg.chocolatey.org> On Behalf Of bcurran3
> Sent: Saturday, April 27, 2019 8:11 PM
> To: bcurran3 <redacted>
> Subject: [Chocolatey.org] Message for maintainers of the package 'plantronicshub'
> 
> User bcurran3 <redacted> sends the following message to the maintainers of Package 'plantronicshub'.
> Hi. Just an FYI that this is a couple versions out of date.
> Package Url: https://chocolatey.org/packages/plantronicshub
> Pro-tip: It is recommended to (also) post your answer to the plantronicshub comment section so that the information is publicly available.
> This can prevent you from receiving the same question from multiple users.
> Package comments: http://chocolatey.org/packages/plantronicshub#disqus

If no one else is interested, I will probably pick it up.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/plantronicshub

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/plantronicshub

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/plantronicshub

Can be closed.
