### ISSUE TITLE
RFP - Google2SRT 0.7.7

### ISSUE THREAD

**Issue by fox272** [chocolatey-community/chocolatey-package-requests#637]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - Google2SRT ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://sourceforge.net/projects/google2srt/
Direct download URL for the software / installer : https://sourceforge.net/projects/google2srt/files/Google2SRT/0.7.7/google2srt-0.7.7.msi
Software summary / short description:
Google2SRT allows you to download, save and convert multiple subtitles and translations from YouTube and Google Video to SubRip (.srt) format, which is recognized by most video players. You can download XML subtitles or simply type video's URL, Google2SRT will do the rest.

Features
Download YouTube subtitles - Closed Captions (CC)
Convert YouTube subtitles to SRT (SubRip)
Download YouTube subtitle translations
Download YouTube ASR (Automatic Speech Recognition) subtitles and their translations
Download multiple YouTube subtitles and translations at once
Proxy support

**Comment by pauby** [comment]
@fox272 Can you use the issue template that is provided?

**Comment by fox272** [comment]
it's ok like that

**Comment by pauby** [comment]
@fox272 If you complete the checklist then we're good to go.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/google2srt
https://chocolatey.org/packages/google2srt.install
https://chocolatey.org/packages/google2srt.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/google2srt
- https://chocolatey.org/packages/google2srt.install
- https://chocolatey.org/packages/google2srt.portable

Can be closed.
