### ISSUE TITLE
RFP - dust3d

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#638]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://dust3d.org/  
Direct download URL for the software / installer :  https://github.com/huxingyi/dust3d/releases/tag/1.0.0-beta.21  
Software summary / short description:  
Dust3D is a cross-platform open-source modeling software. It helps you create a 3D watertight model in seconds. Use it to speed up your character modeling in game making, 3D printing, and so on.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/dust3d

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/dust3d

Can be closed.
