### ISSUE TITLE
RFP - softros

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#639]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://messenger.softros.com/
Direct download URL for the software / installer: https://download.softros.com/SoftrosLANMessengerSetup.exe
Software summary / short description: P2P messenger within a LAN

## Package Expectations

Add the [`trial` tag](https://chocolatey.org/packages?q=tag%3Atrial) because this is a 30-days trial.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/slm

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/slm

Can be closed.
