### ISSUE TITLE
RFP - LabPlot

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#640]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://labplot.kde.org/
Direct download URL for the software / installer : https://download.kde.org/stable/labplot/2.6.0/labplot-2.6.0-64bit-setup.exe.mirrorlist
Software summary / short description: LabPlot is a KDE application for interactive graphing and analysis of scientific data.   LabPlot provides an easy way to create, manage and edit plots.

**Comment by chtof** [comment]
Status: **In progress**
- Should be submitted before the end of the week.

**Comment by AdmiringWorm** [comment]
@chtof any status update for this request? Or is it still in progress?

**Comment by chtof** [comment]
Still in progress. Should be submitted really soon.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/labplot

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/labplot

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/labplot

Can be closed.
