### ISSUE TITLE
RFP - Ren'Py

### ISSUE THREAD

**Issue by risk1996** [chocolatey-community/chocolatey-package-requests#641]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.renpy.org
Direct download URL for the software / installer : https://www.renpy.org/dl/7.3.2/renpy-7.3.2-sdk.7z.exe
Software summary / short description: The Ren'Py Visual Novel Engine

**Comment by risk1996** [comment]
I will try to maintain this package myself.

**Comment by AdmiringWorm** [comment]
@risk1996 have you had any luck? or do you wish to open this request up for someone else to pick up instead?

**Comment by AdmiringWorm** [comment]
closing as there seem to be an approved package.

@risk1996 in the future, please respond to issues to give the status of a request (In progress, Review, approved) so we can attach the correct state, and close the issue when the package is approved.
