### ISSUE TITLE
RFP - matlab runtime 2019

### ISSUE THREAD

**Issue by ghost** [chocolatey-community/chocolatey-package-requests#642]
-->
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://in.mathworks.com/products/compiler/matlab-runtime.html
Direct download URL for the software / installer : http://ssd.mathworks.com/supportfiles/downloads/R2019a/Release/4/deployment_files/installer/complete/win64/MATLAB_Runtime_R2019a_Update_4_win64.zip
Software summary / short description: Allows to run standalone programs in matlab without needing to install matlab.

**Comment by pauby** [comment]
@teknowledgist as you maintain the other Matlab packages would you be interested in picking this one up?

**Comment by teknowledgist** [comment]
Sure.  I can do that.

**Comment by AdmiringWorm** [comment]
@teknowledgist I will assign the issue to you then.
Thanks for taking care of it.

**Comment by teknowledgist** [comment]
mcr-2019a package submitted.

**Comment by AdmiringWorm** [comment]
Seems like the request have been completed.

@teknowledgist in the future, please post a comment so we know what the status of the request is at (In progress, Review, Approved). This way we can mark the request with the correct label, and close the request when it have been completed.
