### ISSUE TITLE
RFP - concourse

### ISSUE THREAD

**Issue by cholmquist** [chocolatey-community/chocolatey-package-requests#643]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://concourse-ci.org/
Direct download URL for the software / installer : https://github.com/concourse/concourse/releases/download/v5.4.0/concourse-5.4.0-windows-amd64.zip
Software summary / short description:
Concourse is an open-source continuous thing-doer.
Built on the simple mechanics of resources, tasks, and jobs, Concourse presents a general approach to automation that makes it great for CI/CD.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/concourse

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/concourse

Can be closed.
