### ISSUE TITLE
RFP — Keyferret

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#644]
### 1. Checklist

- [x] The package I am requesting does not already exist on **<https://chocolatey.org/packages>**;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login.

### 2. Package Details

+ Software project URL: **<https://www.keyferret.com/>**
+ Direct download URL for the software/installer: **<https://www.keyferret.com//download/11/>**
+ Direct download URL for portable version: **<https://keyferret.com/download/7/>**
+ Software summary/short description: software for print special symbols, accents, maths, Cyrillic, Greek and IPA

### 3. Software Description

In my experience, Keyferret really simple way to type special characters.

Examples from official documentation:

+ à: Type a, then <kbd>RAlt</kbd>+`
+ œ: Type <kbd>RAlt</kbd>+oe
+ þ (thorn): Type <kbd>RAlt</kbd>+t
+ – (en dash) : Type <kbd>RAlt</kbd>+-
+ ½: Type <kbd>RAlt</kbd>+1/2
+ ²: Type 2, then <kbd>RAlt</kbd>++
+ ≠: Type =, then <kbd>RAlt</kbd>+/
+ 𝑥: Type x, then <kbd>RAlt</kbd>+\i
+ ⊈: Type <kbd>RAlt</kbd>+<s=/
+ ∰: Type <kbd>RAlt</kbd>+=SSSo

Thanks.

**Comment by chtof** [comment]
Status: **In progress**
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/keyferret.install

keyferret.portable and keyferret (virtual/meta package) are coming soon.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/keyferret
- https://chocolatey.org/packages/keyferret.install
- https://chocolatey.org/packages/keyferret.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/keyferret
- https://chocolatey.org/packages/keyferret.install
- https://chocolatey.org/packages/keyferret.portable

Can be closed.
