### ISSUE TITLE
RFP - Meshroom

### ISSUE THREAD

**Issue by yamlCase** [chocolatey-community/chocolatey-package-requests#645]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://alicevision.org/#meshroom
Direct download URL for the software / installer : https://github.com/alicevision/meshroom/releases/latest
Software summary / short description: Meshroom is an open-source 3D Reconstruction Software based on the AliceVision Photogrammetric Computer Vision framework.

Package Expectations: The download is a zipped directory containing the executable and all the required files, so it will need a shim.  The exe launches a GUI application.

**Comment by chtof** [comment]
Binary for Windows is hosted on FossHub (https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2019.1.0-win64.zip).

According https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub, we can't implement a package with a binary hosted on FossHub. Also, these package can't be embedded (its size is about 300 MB).

Do you know an alternate official download location? Maybe you can ask to the software editor?

**Comment by yamlCase** [comment]
well this is unfortunate.  I will make a feature request on their issue board, see what comes of it.

**Comment by yamlCase** [comment]
good news: Meshroom will be releasing their Windows binary on github at the next version. Should be this week.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/meshroom

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/meshroom

Can be closed.
