### ISSUE TITLE
RFP — Briss

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#646]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=briss) on **<https://chocolatey.org/packages>**;
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+Briss);
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;
- [x] The program can't install via package manager (as pip or npm).

### 2. Package Details

+ Software project URL: **<https://github.com/mbaeuerle/Briss-2.0>**;
+ Direct download URL for portable version: **<https://github.com/mbaeuerle/Briss-2.0/releases/download/v2.0-alpha/Briss-2.0.zip>**;
+ Software summary/short description: [**open source**](https://github.com/mbaeuerle/Briss-2.0) GUI for mass PDF crop.

### 3. Software Description

In my experience, nice tool for quick mass PDF cropping. I use it for PDF book creating.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/briss

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/briss

Can be closed.
