### ISSUE TITLE
RFP — TCP/IP Manager

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#647]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=tcp%2Fip%20manager) on **<https://chocolatey.org/packages>**;
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tcp%2Fip+manager);
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

### 2. Package Details

+ Software project URL: **<https://tcpipmanager.sourceforge.io/>**;
+ Direct download URL for x64 installer: **<https://sourceforge.net/projects/tcpipmanager/files/tcpipmanager_stable/TCP_IP_Manager_v4.1.1_%28Build_29%29/TCP_IP_Manager_v4.1.1.29_x64_Setup.exe/download>**;
+ Direct download URL for x86 installer: **<https://sourceforge.net/projects/tcpipmanager/files/tcpipmanager_stable/TCP_IP_Manager_v4.1.1_%28Build_29%29/TCP_IP_Manager_v4.1.1.29_x86_Setup.exe/download>**;
+ Direct download URL for x64 portable version: **<https://sourceforge.net/projects/tcpipmanager/files/tcpipmanager_stable/TCP_IP_Manager_v4.1.1_%28Build_29%29/TCP_IP_Manager_v4.1.1.29_x64.7z/download>**;
+ Direct download URL for x86 portable version: **<https://sourceforge.net/projects/tcpipmanager/files/tcpipmanager_stable/TCP_IP_Manager_v4.1.1_%28Build_29%29/TCP_IP_Manager_v4.1.1.29_x86.7z/download>**;
+ Software summary/short description: [**open source**](https://sourceforge.net/p/tcpipmanager/code/HEAD/tree/) network configuration manager.

### 3. Software example of usage

I have network problem. I want to find out if the problem is in my router. I pull out the Ethernet cable from router → I insert it to PC.

#### 3.1. Without TCP/IP Manager

`Control Panel` → `Network and Sharing Center` → `Ethernet` → `Properties` → `Internet Protocol Version 4 (TCP/IPv4)` → `Properties` → I need manually fill in all fields each time (and press `OK`):

![IPv4 Properties](https://i.imgur.com/fFyoUHH.png)

I lose a lot of time.

#### 3.2. With TCP/IP Manager

I create 2 profiles:

+ `NesterWithRouter` — network settings, if router enabled:

    ![With router](https://i.imgur.com/kvGvGzW.png)

+ `NesterWithoutRouter` — network settings, if router disabled and Ethernet cable insert in my PC without intermediaries:

    ![Without router](https://i.imgur.com/Whhd81p.png)

Now:

1. If I need to connect to network without router, I select `NesterWithoutRouter` → `Apply settings` → PROFIT.
1. Else I need to connect backward, use router → I insert cables backward → I select `NesterWithoutRouter` → `Apply settings`.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/tcpipmanager
- https://chocolatey.org/packages/tcpipmanager.install
- https://chocolatey.org/packages/tcpipmanager.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/tcpipmanager
- https://chocolatey.org/packages/tcpipmanager.install
- https://chocolatey.org/packages/tcpipmanager.portable

Can be closed.
