### ISSUE TITLE
RFP - Microsoft Edge Insider

### ISSUE THREAD

**Issue by ghuntley** [chocolatey-community/chocolatey-package-requests#648]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.microsoftedgeinsider.com/en-us/
Direct download URL for the software / installer : https://c2rsetup.officeapps.live.com/c2r/downloadEdge.aspx?ProductreleaseID=Edge&platform=Default&version=Edge&Channel=Dev&language=en&Consent=1&IID=fc537d39-772a-5a6b-a29d-883ea931577f

**Comment by AdmiringWorm** [comment]
A note for anyone interested in picking this up, there are separate installers for Windows 7, 8, 8.1 and 10.

As such, custom logic would most likely be needed to install the correct version depending on the platform of the user.

**Comment by gep13** [comment]
An example of the type of custom logic that might be required can be found in the PowerShell package.

**Comment by chtof** [comment]
The difficult is to grab the checksum as the link is each time the same but the checksum is different so the installer is different for each version (even if I was able to install the installer for Windows 10 on Windows 2012 ;-) ).
So I think the Microsoft website should detect the OS version used.
A solution can be to test with different user agent but maybe you have an easier solution?

**Comment by dawesi** [comment]
There are also 3 builds now - beta, dev and canary (and I'm sure there will soon be a fourth - GA

I think there should be a choco package for each release band... that way choco could simply detect current os version and grab appropriate one

anyway, would be super great to have this in choco #excited (haven't said that since just after IE4 came out and was only browser with wysiwyg)

**Comment by ionred** [comment]
Request to close -- I created Insider Beta and Insider Dev releases. Special handling not required for each OS when using the enterprise MSI to deploy. 

Does anyone have a desire for a canary build? There's no enterprise build for canary so there will be a little more legwork required to get that up and running.
