### ISSUE TITLE
RFP — DjVuLibre

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#649]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=djvulibre) on **<https://chocolatey.org/packages>**;
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+djvulibre);
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

### 2. Package Details

+ Software project URL: **<http://djvu.sourceforge.net/>**;
+ Direct download URL for installer: **<https://sourceforge.net/projects/djvu/files/latest/download>**;
+ Software summary/short description: [**free set of utilities and libraries for viewing, creating and editing DjVu files**](https://ru.wikipedia.org/wiki/DjVuLibre).

### 3. Note

It would be nice, if folder with `.exe` files of [**DjVuLibre CLI utilities**](http://djvu.sourceforge.net/doc/index.html) will be added to `PATH` environment variable.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/djvu-libre

**Comment by Kristinita** [comment]
@chtof,

**Type: Question :question:**

### 1. Summary

Will the DjVuLibre folder add to PATH environment variable? See item 3 of my request. If yes, how you do it?

### 2. Not helped

I view [**your DjVuLibre package source**](https://github.com/chtof/chocolatey-packages/tree/master/automatic/djvu-libre) → I can't find [**`Install-ChocolateyPath`**](https://chocolatey.org/docs/helpers-install-chocolatey-path#description) in DjVuLibre source and in [**your chocolatey-packages repository**](https://github.com/chtof/chocolatey-packages/search?q=Install-ChocolateyPath&unscoped_q=Install-ChocolateyPath) at all.

Thanks.

**Comment by chtof** [comment]
@Kristinita Corrected, thank you!

**Comment by AdmiringWorm** [comment]
@chtof you shouldn't really rely on the package being available in only a single location.
Considering it is a NSIS installer, a user may decide to install it to a different location using the correct installer argument, in which case the package would fail to install.

Consider using the `Get-AppInstallLocation` available in the [chocolatey-core.extension](https://chocolatey.org/packages/chocolatey-core.extension) package and check the that it isn't empty.

**Comment by chtof** [comment]
Improved version is submitted. Thank you @AdmiringWorm 

Status: **Review**
https://chocolatey.org/packages/djvu-libre/3.5.27.41101

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/djvu-libre/3.5.27.41101

Can be closed.
