### ISSUE TITLE
RFP — jPdf Tweak

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#651]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=jPdf%20Tweak) on **<https://chocolatey.org/packages>**;
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+jPdf+Tweak);
- [x] The issue title starts 'RFP — ';
- [x] The download URL is public and not locked behind a paywall / login.

### 2. Package Details

+ Software project URL: **<http://jpdftweak.sourceforge.net/>**;
+ Binary download, compact version: **<https://sourceforge.net/projects/jpdftweak/files/jpdftweak/jpdftweak-1.1/jpdftweak-compact-1.1.zip/download?use_mirror=netcologne&download=>**;
+ Binary download, normal version: **<https://sourceforge.net/projects/jpdftweak/files/jpdftweak/jpdftweak-1.1/jpdftweak-1.1.zip/download?use_mirror=netcologne&download=>**;
+ Binary download, Windows x64 version: **<https://sourceforge.net/projects/jpdftweak/files/jpdftweak/jpdftweak-1.1/jpdftweak-windows-x64-1.1.zip/download?use_mirror=netcologne&download=>**;
+ Binary download, Windows x86 version: **<https://sourceforge.net/projects/jpdftweak/files/jpdftweak/jpdftweak-1.1/jpdftweak-windows-x86-1.1.zip/download?use_mirror=netix&download=>**;
+ Software summary/short description: [**open source**](https://sourceforge.net/p/jpdftweak/code/HEAD/tree/trunk/jpdftweak/) GUI for PDF editing. jPdf Tweak has [**many features**](http://jpdftweak.sourceforge.net/manual/index.html); I use it for make the pages size standard and [**renumber PDF pages**](https://askubuntu.com/a/511598/582218).

#### 3.1. Dependencies

From [**official site**](http://jpdftweak.sourceforge.net/):

> jPDF Tweak requires Java 5 or higher.

It would be nice add Java to Chocolatey package dependencies.

#### 3.2. Difference between versions

From [**official site**](http://jpdftweak.sourceforge.net/):

> There are two platform independent binary versions available, a compact one and a normal one. The compact one uses an obfuscator to make the application smaller. So, the compact one has the same features as the normal one. Only if you have problems using the compact one for a task, or if you want to report a bug, try the normal one. The normal version produces better error messages, and - of course - the obfuscator might have bugs as well. If you want to download the libraries separately, there is another version without libraries available (it won't work without libraries).

Thanks.

**Comment by AdmiringWorm** [comment]
> From official site:
> 
> > jPDF Tweak requires Java 5 or higher.

> It would be nice add Java to Chocolatey package dependencies.

Anyone picking this request up should test if the a java dependency is needed.
Most java applications I have tested in the past (that have been compiled for windows platforms), do not need java as a dependency.

**Comment by Kristinita** [comment]
@AdmiringWorm,

**Type: Reply**

### 1. General case

> Anyone picking this request up should test if the a java dependency is needed.
Most java applications I have tested in the past (that have been compiled for windows platforms), do not need java as a dependency.

Thanks, I will remember this for the future.

### 2. jPdf Tweak

#### 2.1. Summary

Maybe I don’t know something, but I don't understand, how jPdf Tweak can work without Java.

#### 2.2. Argumentation

jPdf Tweak doesn't contain `.exe` files.

Files of 64-bit version (I also looked at files from another versions):

```text
D:\SashaPrograms\jpdftweak-windows-x64-1.1>tree /F
Folder PATH listing
Volume serial number is 00000042 1835:AC7C
D:.
│   icon.ico
│   jmupdf64.dll
│   jpdftweak.bat
│   jpdftweak.jar
│   license.txt
│   README.txt
│
├───icons
│       icon128.png
│       icon16.png
│       icon256.png
│       icon32.png
│       icon48.png
│       icon64.png
│
├───lib
│       bcmail.jar
│       bcprov.jar
│       bctsp.jar
│       forms.jar
│       itext.jar
│       jgoodies-common.jar
│       JMuPdf.jar
│
└───manual
        index.html
        screenshot.png
        shot01.png
        shot02.png
        shot03.png
        shot04.png
        shot04a.png
        shot05.png
        shot06.png
        shot07.png
        shot08.png
        shot09.png
        shot10.png

```

+ `jpdftweak.bat`:

```batch
@java -jar jpdftweak.jar %*
```

I don't understand, how possible run it without Java.

Thanks.

**Comment by AdmiringWorm** [comment]
When I said
> that have been compiled for windows platforms

I assumed that the windows specific archives was compiled to a `.exe` file, when it isn't you of course need to have java installed.

**Comment by chtof** [comment]
@Kristinita What is the difference between "normal" version and "windows-x86" and "windows-x84" versions?
I have read "In addition, there are platform dependent binary versions available for Windows (x86/x64) and Linux (x86/x64); these bundle native JMuPdf libraries so that you can use the image export features out of the box." but I didn't how they can been different.
Maybe compact and normal versions need Java and windows versions doesn't need Java as dependency?

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/jpdftweak

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/jpdftweak

Can be closed.

**Comment by chtof** [comment]
> Status: **Published**
> https://chocolatey.org/packages/jpdftweak
> 
> Can be closed.
