### ISSUE TITLE
RFP - Embree

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#652]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL:  
https://www.embree.org/  
Direct download URL for the software / installer:  
https://github.com/embree/embree#windows-msi-installer  
Software summary / short description:  
Intel® Embree is a collection of high-performance ray tracing kernels, developed at Intel. The target users of Intel® Embree are graphics application engineers who want to improve the performance of their photo-realistic rendering application by leveraging Embree's performance-optimized ray tracing kernels.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/embree
- https://chocolatey.org/packages/embree.install

@luzpaz  Ping us (or create a new request referencing this issue if this one is closed) if you think necessary to create package for the ZIP files linked against Visual Studio versions.
ZIP files where Embree is linked against the Visual Studio 2013 (VC12) runtime and and Visual Studio 2015/2017 (VC14) runtime:
embree-3.5.2.x64.vc12.windows.zip
embree-3.5.2.x64.vc14.windows.zip

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/embree
- https://chocolatey.org/packages/embree.install

Can be closed.

**Comment by luzpaz** [comment]
Thanks!

**Comment by luzpaz** [comment]
@chtof can the version be bumped to 3.6.1? Just noticed that a new stable was released 5 days ago:  
https://github.com/embree/embree/releases/tag/v3.6.1

**Comment by chtof** [comment]
@luzpaz At the bottom of the Chocolatey page, you can see versions waiting approval (because I create the update.ps1 script just before closing issue).

**Comment by luzpaz** [comment]
sorry for missing that. Thanks again. Cheers
