### ISSUE TITLE
RFM - fontforge

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#655]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: http://fontforge.github.io/
Package source URL: https://github.com/fontforge/fontforge/releases/download/20190801/FontForge-2019-08-01-Windows.exe

Date the maintainer was contacted: Sometime around 08/08/19
How the maintainer was contacted: through the package page 'Contact Maintainers' with no response

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/fontforge

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/fontforge

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/fontforge

Can be closed.

**Comment by luzpaz** [comment]
Thank you @chtof!
