### ISSUE TITLE
RFP - ospray

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#658]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.ospray.org/downloads.html
Direct download URL for the software / installer :  
https://github.com/ospray/OSPRay/releases/download/v1.8.5/ospray-1.8.5.msi  
https://github.com/ospray/OSPRay/releases/download/v1.8.5/ospray-1.8.5.windows.zip  
requires [x64 Microsoft* Visual C++* 2015 Redistributable](https://www.microsoft.com/download/details.aspx?id=53840)

Software summary / short description:  
The Open, Scalable, and Portable Ray Tracing Engine

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/ospray
- https://chocolatey.org/packages/ospray.install
- https://chocolatey.org/packages/ospray.portable

**Comment by luzpaz** [comment]
Thanks!
