### ISSUE TITLE
RFP — Sejda

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#659]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=sejda&moderatorQueue=true&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+Sejda)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<http://sejda.org/>**
+ Download page URL: **<https://github.com/torakiki/sejda/releases/latest>**
+ Direct download URL for portable version: **<https://github.com/torakiki/sejda/releases/download/v3.2.84/sejda-console-3.2.84-bin.zip>**
+ Have this software command-line interface (CLI)? Yes
+ If «yes» for previous question, what folder(s) must be added to the `PATH` environment variable? `./sejda-console-{version}/bin`
+ Software summary/short description: Open source SDK for operations to PDF files. [**Full list of available tasks**](https://github.com/torakiki/sejda/wiki/Tasks#list-of-available-tasks-in-sejda-sdk). [**It is used**](http://sejda.org/) [**PDFsam**](https://chocolatey.org/packages/pdfsam) and **<https://www.sejda.com/>**.

Thanks.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/sejda
