### ISSUE TITLE
RFP - TikZiT

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#660]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://tikzit.github.io/index.html
Direct download URL for the software / installer : latest versions are available in the above home page or here https://github.com/tikzit/tikzit/releases/
Software summary / short description: TikZiT is a super simple GUI editor for graphs and string diagrams. Its native file format is a subset of PGF/TikZ, which means TikZiT files can be included directly in papers typeset using LaTeX.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/tikzit

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/tikzit

Can be closed.
