### ISSUE TITLE
RFP - VBACKUP

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#661]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.fileviewer.com/vbackup/
Direct download URL for the software / installer :http://www.fileviewer.com/FTP/VBackup08.zip
http://www.fileviewer.com/FTP/VBackup08-x64.zip
Software summary / short description:VBackup is a command line program for Windows that is used to make backup copies of directories.
It is similar in functionality to XCOPY and ROBOCOPY, however, VBackup implements file versioning. This means that you can not only restore files from the latest backup, but you can also restore them from any previous backup.

**Comment by pauby** [comment]
@Ohrwerk Can you go back and complete all of the fields in the template please?

**Comment by Ohrwerk** [comment]
done

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vbackup
