### ISSUE TITLE
RFP - Display Changer 

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#663]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://12noon.com/?page_id=80
Direct download URL for the software / installer : https://12noon.com/files/dc-setup.exe
Software summary / short description:
    Display Changer changes your monitor’s resolution.
    Display Changer runs your application.
    Display Changer restores the original resolution.

**Comment by pauby** [comment]
@Ohrwerk When adding the `x` between the `[]` please don't leave a space. It should look like [x] but ends up looking like [x ]. Thank you.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/display-changer
