### ISSUE TITLE
RFP - Clavier+

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#664]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://utilfr42.free.fr/util/Clavier.php?sLang=en
Direct download URL for the software / installer : http://utilfr42.free.fr/dn/ClavierSetup64.exe
Software summary / short description:
Allows creating keyboard shortcuts involving almost any key, including the Windows keys.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/clavier-plus
- https://chocolatey.org/packages/clavier-plus.install
- https://chocolatey.org/packages/clavier-plus.portable
