### ISSUE TITLE
RFP - VB-CABLE Virtual Audio Device (VB-Audio)

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#665]
## Checklist

- [x]  The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.vb-audio.com/Cable/index.htm
Direct download URL for the software / installer : vincent.burel.free.fr/VirtualAudioApps/VBCABLE_Driver_Pack43.zip
Software summary / short description:
VB-CABLE is a virtual audio device working as virtual audio cable. All audio signals coming in the CABLE input is transported to the CABLE output. Then It becomes simple to make computer audio recording or to connect a player application to a recorder one.

**Comment by pauby** [comment]
I am convinced this is a package on the community repository already but can I find it? I'll pick this up.

**Comment by Ohrwerk** [comment]
Thank you.
There is only a package for Voicemeeter from VB-Audio, but this include also a mixer.
https://chocolatey.org/packages?q=VOICEMEETER
https://www.vb-audio.com/Voicemeeter/index.htm

There are also Voicemeter Banana/Potato/VBAN on the site, but i think these are a little bit overpowered for most people like me.
Extremley usefull for others but most people dosnt know "Superhero" Software like this.

I put the links here, because the names banana and potato do not immediately indicate real software.
https://www.vb-audio.com/Voicemeeter/banana.htm
https://www.vb-audio.com/Voicemeeter/potato.htm
https://www.vb-audio.com/Voicemeeter/vban.htm

**Comment by pauby** [comment]
> There is only a package for Voicemeeter from VB-Audio, but this include also a mixer.

That was it! Thank you for confirming I wasn't imagining things!

**Comment by Ohrwerk** [comment]
you are welcome

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vb-cable

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/vb-cable

Can be closed.
