### ISSUE TITLE
RFP - VSTHOST

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#666]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://www.hermannseib.com/english/vsthost.htm
Direct download URL for the software / installer :
http://www.hermannseib.com/programs/vsthostx86.zip
http://www.hermannseib.com/programs/vsthostx64.zip
http://www.hermannseib.com/documents/VSTHost.pdf

Software summary / short description:
It's a VST-compatible host that's capable of:
loading VST effects (aka "plugins")
parameterizing / editing them
sound output for VSTis
MIDI-input and -output
loading / saving .fxb / .fxp files
I/O through either Windows MME or ASIO drivers
Wave Player / Recorder
MIDI Player

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vsthost
