### ISSUE TITLE
RFP - VirtualMIDISynth

### ISSUE THREAD

**Issue by Ohrwerk** [chocolatey-community/chocolatey-package-requests#667]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://coolsoft.altervista.org/en/virtualmidisynth
Direct download URL for the software / installer : https://coolsoft.altervista.org/download/CoolSoft_VirtualMIDISynth_2.7.3.exe
Software summary / short description:
VirtualMIDISynth is a software MIDI synthesizer implemented as a Windows multimedia user driver, accessible as a standard MIDI Out device.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/virtualmidisynth

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/virtualmidisynth

Can be closed.
