### ISSUE TITLE
RFP - AusweisApp des Bundes

### ISSUE THREAD

**Issue by RufusJWB** [chocolatey-community/chocolatey-package-requests#669]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.ausweisapp.bund.de
Direct download URL for the software / installer : https://www.ausweisapp.bund.de/uploads/tx_ausweisdownloads/AusweisApp2-1.16.2.msi
Software summary / short description: This is the app to use the German federal ID card on Windows

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/ausweisapp2

(Note: @RufusJWB , the package already exists but have never been approved: https://chocolatey.org/packages/AusweisApp2. You can't find it with the search feature of Chocolatey but it can be found trying the direct url as showned above even if you don't respect characters case, you can find it also with https://chocolatey.org/packages/ausweisapp2/ as url).

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/ausweisapp2

Can be closed.
