### ISSUE TITLE
RFM - vcvrack

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#670]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  
* https://vcvrack.com/
* Github: https://github.com/VCVRack/Rack  

Direct download URL for the software / installer : https://vcvrack.com/downloads/Rack-1.1.4-win.exe  

Software summary / short description:
Open-source virtual modular synthesizer

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vcvrack

**Comment by chtof** [comment]
@luzpaz Note: This package already exists on chocolatey but has never been approved.

Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/vcvrack

**Comment by luzpaz** [comment]
hmm....i thought i searched for it and nothing came up. Apologies

**Comment by AdmiringWorm** [comment]
@luzpaz when a package have never been approved, it won't come up in searches. The only way to find the program then is to type in the url manually.

Anyways, changing to RFM

**Comment by luzpaz** [comment]
Thanks for the heads up.  
BTW, vcvrack is getting a lot of attention these days, dev is very active.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/vcvrack

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/vcvrack

Can be closed.

**Comment by luzpaz** [comment]
Thank you!
