### ISSUE TITLE
RFM - Pyzo

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#671]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Existing Package Details

Package URL: https://chocolatey.org/packages/pyzo
Package source URL: n/a
Date the maintainer was contacted: 2019-08-27
How the maintainer was contacted: https://chocolatey.org/packages/pyzo/ContactOwners

Maintainer's response (email address obscured):

> from: | Pascal Godejohann <dev@------.de>
> to: | map------@gmail.com
> date: | 27 Aug 2019, 09:36
> subject: | Re: [Chocolatey.org] Message for maintainers of the package 'pyzo'
> 
>Hi Matt,
>Please feel free to look for a new maintainer.
>Kind regards,

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/pyzo

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/pyzo
- https://chocolatey.org/packages/pyzo.install
- https://chocolatey.org/packages/pyzo.portable

**Comment by AdmiringWorm** [comment]
@chtof looks like you need to add a comment on the `pyzo` meta package, as it somehow wasn't added back to queue when it succeeded the automated tests.

**Comment by chtof** [comment]
> @chtof looks like you need to add a comment on the `pyzo` meta package, as it somehow wasn't added back to queue when it succeeded the automated tests.

Done, thank you.

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/pyzo
- https://chocolatey.org/packages/pyzo.install
- https://chocolatey.org/packages/pyzo.portable

Can be closed.
