### ISSUE TITLE
RFP - git-it

### ISSUE THREAD

**Issue by karlhorky** [chocolatey-community/chocolatey-package-requests#672]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/jlord/git-it-electron (releases page: https://github.com/jlord/git-it-electron/releases/latest)
Direct download URL for the software / installer : https://github.com/jlord/git-it-electron/releases/download/4.4.0/Git-it-Win-ia32.zip
Software summary / short description: Learning Program for Learning Git / GitHub

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/git-it

**Comment by AdmiringWorm** [comment]
Package have been approved

**Comment by karlhorky** [comment]
Thanks everyone!

**Comment by karlhorky** [comment]
And @jlord, ping to let you know that `git-it` is on the Windows Chocolatey package manager now too!
