### ISSUE TITLE
RFP - RealPopup LAN chat

### ISSUE THREAD

**Issue by andrewstreet** [chocolatey-community/chocolatey-package-requests#673]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.realpopup.it
Direct download URL for the software / installer : https://www.realpopup.it/download.html
Software summary / short description: Send messages from PC to PC, create chat groups, transfer files and get a remote desktop sharing over a local network without using the Internet or dedicated servers.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/realpopup

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/realpopup

Can be closed.
