### ISSUE TITLE
RFP - papagayo-ng

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#674]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://morevnaproject.org/papagayo-ng/

Direct download URL for the software / installer : https://sourceforge.net/projects/papagayo-ng/files/stable/1.4.2/PapagayoNG-1.4.2-2017.07.31-65704-win-32bit.exe/download   
Source Code Repo: https://github.com/morevnaproject/papagayo-ng

Software summary / short description:
```
“Papagayo” is a lip-syncing program designed to line up phonemes (mouth shapes) with the actual recorded sound of actors speaking.

Papagayo was originally developed and released as open-source by Lost Marble. The version presented here is maintained by Morevna Project and have following differences:

Support for various languages (English, Dutch, Finnish, German, Hungarian, Italian, Norwegian, Portuguese, Russian, Spanish, Swedish, Turkish, Ukrainian).
Support for various phoneme sets (Preston-Blair or Flemming-Dobbs).
```

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/papagayo-ng

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/papagayo-ng

Can be closed.
