### ISSUE TITLE
RFP - photoflow

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#675]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://aferrero2707.github.io/PhotoFlow
Direct download URL for the software / installer : https://github.com/aferrero2707/PhotoFlow/releases/download/v0.2.8/photoflow-0.2.8.zip      
Software summary / short description:  
The aim of the project is to provide a fully non-destructive photo retouching program with a complete workflow including RAW image development.

**Comment by chtof** [comment]
Status: **In progress**
- Can't published currently the package (`System.ApplicationException: An error has occurred. It's possible the package version already exists on the repository. ---> System.InvalidOperationException: Failed to process request. 'This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown.'.`)
- New package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/photoflow

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/photoflow

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/photoflow

Can be closed.
