### ISSUE TITLE
RFP - pkcs11admin

### ISSUE THREAD

**Issue by RufusJWB** [chocolatey-community/chocolatey-package-requests#676]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.pkcs11admin.net
Direct download URL for the software / installer : https://github.com/Pkcs11Admin/Pkcs11Admin/releases/latest
Software summary / short description: Pkcs11Admin is an open-source GUI tool for administration of PKCS#11 enabled devices (smartcards, HSMs etc.) which runs under .NET 4.5 on MS Windows

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/pkcs11admin

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/pkcs11admin

Can be closed.

**Comment by RufusJWB** [comment]
Work wonderful! Thank you very much!
