### ISSUE TITLE
RFP - openorienteering-mapper

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#677]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.openorienteering.org/apps/mapper/
Github: https://github.com/OpenOrienteering/mapper  
Direct download URL for the software / installer: https://github.com/OpenOrienteering/mapper/releases/tag/v0.8.4  

Software summary / short description:

OpenOrienteering Mapper is an orienteering mapmaking program and provides a free and open source alternative to existing commercial software. OpenOrienteering Mapper runs on Android, Windows, Mac OS X and Linux.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/openorienteering-mapper
https://chocolatey.org/packages/openorienteering-mapper.install
https://chocolatey.org/packages/openorienteering-mapper.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/openorienteering-mapper
- https://chocolatey.org/packages/openorienteering-mapper.install
- https://chocolatey.org/packages/openorienteering-mapper.portable

Can be closed.
