### ISSUE TITLE
RFP - SoftHSM

### ISSUE THREAD

**Issue by RufusJWB** [chocolatey-community/chocolatey-package-requests#678]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.opendnssec.org/softhsm/
Direct download URL for the software / installer : https://github.com/disig/SoftHSM2-for-Windows/releases/download/v2.5.0/SoftHSM2-2.5.0.msi
Software summary / short description: SoftHSM is an implementation of a cryptographic store accessible through a PKCS #11 interface. You can use it to explore PKCS #11 without having a Hardware Security Module.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/softhsm
https://chocolatey.org/packages/softhsm.install
https://chocolatey.org/packages/softhsm.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/softhsm
- https://chocolatey.org/packages/softhsm.install
- https://chocolatey.org/packages/softhsm.portable

Can be closed.

**Comment by RufusJWB** [comment]
Works very well, thank you!
