### ISSUE TITLE
RFP - AsciiDocFX

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#679]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/asciidocfx/AsciidocFX
Direct download URL for the software / installer : https://github.com/asciidocfx/AsciidocFX/releases
Software summary / short description: Asciidoc Editor and Toolchain written with JavaFX 8 (Build PDF, Epub, Mobi and HTML books, documents and slides) http://www.asciidocfx.com/

**Comment by AdmiringWorm** [comment]
A note to anyone wishing to pick this request up, a version of this was once tried to be pushed to chocolatey (in 2016), but was never approved.
As such contact the site admins on the following package page (https://chocolatey.org/packages/asciidocfx) to be added as a maintainer.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be published: https://github.com/chtof/chocolatey-packages/tree/master/automatic/asciidocfx

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/asciidocfx
- https://chocolatey.org/packages/asciidocfx.install
- https://chocolatey.org/packages/asciidocfx.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/asciidocfx
- https://chocolatey.org/packages/asciidocfx.install
- https://chocolatey.org/packages/asciidocfx.portable

Can be closed.
