### ISSUE TITLE
RFP - hdrmerge

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#680]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://jcelaya.github.io/hdrmerge/  
Direct download URL for the software / installer :  
https://github.com/jcelaya/hdrmerge/releases/download/v0.5.0/hdrmerge-setup-0.5.0.exe  
https://github.com/jcelaya/hdrmerge/releases/download/v0.5.0/hdrmerge-setup64-0.5.0.exe

Software summary / short description:  
> HDRMerge combines two or more raw images into a single raw with an extended dynamic range. It can import any raw image supported by LibRaw, and outputs a DNG 1.4 image with floating point data. The output raw is built from the less noisy pixels of the input, so that shadows maintain as much detail as possible. This tool also offers a GUI to remove ghosts from the resulting image.

ref: https://github.com/jcelaya/hdrmerge/issues/166

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/hdrmerge

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/hdrmerge

Can be closed.
