### ISSUE TITLE
RFP - Watchman - A file watching service

### ISSUE THREAD

**Issue by kungfutse** [chocolatey-community/chocolatey-package-requests#682]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://facebook.github.io/watchman/
Direct download URL for the software / installer : 
https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D&pr=false
Software summary / short description:
Watchman exists to watch files and record when they change. It can also trigger actions (such as rebuilding assets) when matching files change.

**Comment by pauby** [comment]
Note the Windows version is currenrly in Beta.

**Comment by chtof** [comment]
Hi @kungfutse, How can we see if a new version has been build to update the Chocolatey package (a build number for example)? To sum up, do you have another solution than downloading the build (7 MB) each day to check if the checksum has changed?

**Comment by kungfutse** [comment]
The provided link is a redirect to a latest successful build artifact. The redirect link will reveal the build number (currently b2260), so comparing those is a possibility I think.

```
curl -v https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D&pr=false
...
 Location: https://appveyorcidatav2.blob.core.windows.net/wez-25370/watchman/b2260/30fjy77rvyhlf4b6/watchman.zip?sv=2015-12-11&sr=c&sig=oK20iqZv0tB7UzoBTwNN4jKsTnk8xl19YzRtT8hOyVw%3D&st=2019-10-08T09%3A34%3A12Z&se=2019-10-08T09%3A40%3A12Z&sp=r
```

**Comment by boubou** [comment]
@chtof , do you pick that package ?

**Comment by dgalbraith** [comment]
I am happy to pick this one up

**Comment by dgalbraith** [comment]
The [Watchman package](https://www.chocolatey.org/packages/watchman) is now ready for review.

**Comment by dgalbraith** [comment]
The [Watchman package](https://www.chocolatey.org/packages/watchman) has now been reviewed and is now available in the community package repository.
