### ISSUE TITLE
Abuse Report for Package 'pip' Version '1.2.0 - gary requested a ticket

### ISSUE THREAD

**Issue by based2** [chocolatey-community/chocolatey-package-requests#684]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer [X]

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [ ] There is no existing open maintainer request for this package;

## Checklist

- [ ] Issue title starts with 'RFM - '

## Existing Package Details

Package URL:
Package source URL:

Date the maintainer was contacted:
How the maintainer was contacted:

**Comment by based2** [comment]
Current pip is using a detected compromised dependency
https://chocolatey.org/packages/easy.install, 
making the current install unusable and dangerous.

**Comment by gep13** [comment]
@based2 can you please read through the issue template and do and provide all the details, that it asks for? Thanks

**Comment by AdmiringWorm** [comment]
Closing due to the template not being updated, and no response.
