### ISSUE TITLE
RFP - helio-workstation

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#685]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://helio.fm/
Direct download URL for the software / installer :  
https://ci.helio.fm/helio-2.3.exe  

Software summary / short description:
> libre music composition software  

> Helio Workstation is free and open-source music sequencer, designed to be used on all major platforms.
>
> Why another sequencer?
>Most of the DAW interfaces often seem overcomplicated, and they only tend to get more and more bloated over time. Many of them are commercial, proprietary-licensed and almost none of them support all major operating systems at the same time.
>
> Helio is an attempt to rethink a music sequencer to create a tool that feels right.
>
> It aims to be a modern music creation software, featuring linear-based sequencer with a clean interface, high-performance C++ core, integrated version control providing intelligent synchronization between devices, saved undo history, translations to many languages and more.

**Comment by mkevenaar** [comment]
I will pick this one up.

**Comment by mkevenaar** [comment]
Submitted for review:
https://chocolatey.org/packages/helio-workstation
https://chocolatey.org/packages/helio-workstation.install
https://chocolatey.org/packages/helio-workstation.portable

**Comment by mkevenaar** [comment]
Released!
