### ISSUE TITLE
RFP - WindowGrid

### ISSUE THREAD

**Issue by amitkeret** [chocolatey-community/chocolatey-package-requests#686]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://windowgrid.net/
Direct download URL for the software / installer : http://windowgrid.net/download/1.3.1.1
Icon : http://windowgrid.net/public/images/logo-128x128.png

Software summary / short description:
WindowGrid is a modern window management program for Windows.
Allows the user to quickly and easily layout their windows on a dynamic grid using just the mouse.
Gives functionality to the normally useless right mouse button when moving a window. Doing this will enable the grid snap mode.

**Comment by boubou** [comment]
Will check to build a package soon.

**Comment by boubou** [comment]
hummm
https://bitbucket.org/joshua_wilding/windowgrid-binaries/issues/27/no-license
should I pack it ?
not open-source
no license
just the bins

TheCakeIsNaOH @TheCakeIsNaOH 11:06
That seems to be an official mirror, the original site is here- http://windowgrid.net/
I would have it download during install script and not include the binary in the package.

Sébastien Boulianne @boubou 11:29
yes but download it and open the .zip file
you will get an exe file
do u know this guys ?
Is he trustable ?
The WindowGrid32.dll may need to be added to some virus scanners exclusion lists.

**Comment by boubou** [comment]
In progress.

**Comment by amitkeret** [comment]
> hummm
> https://bitbucket.org/joshua_wilding/windowgrid-binaries/issues/27/no-license
> should I pack it ?
> not open-source
> no license
> just the bins

hmmm I just went based on AlternativeTo.net stating it's free software... apologies
thanks @boubou for following-up on this!

**Comment by boubou** [comment]
Packaged an approuved!
Ticket can be close!

**Comment by boubou** [comment]
https://chocolatey.org/packages/windowgrid
