### ISSUE TITLE
RFP - photoflare

### ISSUE THREAD

**Issue by luzpaz** [chocolatey-community/chocolatey-package-requests#687]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://photoflare.io/
Direct download URL for the software / installer :  
* https://launchpad.net/photofiltre-lx/trunk/v1.5.8.1/+download/PhotoFlare_CE_1.5.9_amd64.msi  
* https://launchpad.net/photofiltre-lx/trunk/v1.5.8/+download/PhotoFlare_CE_1.5.9_amd64_win_portable.zip  

Software summary / short description:  
> Photoflare is a cross-platform image editor with an aim to balance between powerful features and a very friendly graphical user interface. It suits a wide variety of different tasks and users who value a more nimble workflow. Features include basic image editing capabilities, paint brushes, image filters, colour adjustments and more advanced features such as Batch image processing.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/photoflare
- https://chocolatey.org/packages/photoflare.install
- https://chocolatey.org/packages/photoflare.portable

**Comment by AdmiringWorm** [comment]
Seems that all three packages have been approved
