### ISSUE TITLE
RFM - Fritzing

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#688]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/fritzing
Package source URL:  https://fritzing.org/home/

Date the maintainer was contacted: 5 months ago 
How the maintainer was contacted: by [this Disqus comment](http://disq.us/p/21n0o0x)

## Issue:

The package has had checksum mismatch for the last 5 month.

**Comment by pauby** [comment]
@Foadsf Can you use the 'Contact Maintainers' link on the package page as per the process? Let us know if you get a response from 'purity'?

**Comment by Foadsf** [comment]
@pauby there are three of them, which one should I contact?

**Comment by pauby** [comment]
If you complete the form at that link it sends it to them all.

**Comment by boubou** [comment]
Its easy to rebuild the package.
If they dont answer, I can rebuild the package.

**Comment by Foadsf** [comment]
> If you complete the form at that link it sends it to them all.

@pauby so far they haven't replied. 


> Its easy to rebuild the package.
> If they dont answer, I can rebuild the package.

@boubou That would be great

**Comment by AdmiringWorm** [comment]
@Foadsf typically we allow for 7 days since the contacting the maintainers until we decide that they are unresponsive. Please allow for a few more days.

**Comment by pauby** [comment]
@Foadsf Can you confirm if the maintainers responded?

**Comment by Foadsf** [comment]
@pauby Not really. I haven't had any replies neither in Disqus nor via email.

**Comment by pauby** [comment]
@Foadsf Thanks for letting us know. I've made it available now.

**Comment by ionred** [comment]
@pauby  I'll take it over. Putting together the package now. Should be ready in a little bit.

**Comment by ionred** [comment]
@pauby  Ready to push https://github.com/ionred/chocolatey-packages/tree/master/automatic/fritzing

**Comment by AdmiringWorm** [comment]
@ionred if you haven't already, please use the `Contact Site Admins` (on the package page) requesting to be added as a maintainer for this request, remember to also link to this issue.

**Comment by ionred** [comment]
Roger, just completed the form.
