### ISSUE TITLE
RFP — Registry File (.REG) Validator

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#689]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=registry+validator&moderatorQueue=&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?q=is%3Aissue+registry+validator)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<https://forum.xda-developers.com/showthread.php?t=770382>**
+ Direct download URL: **<https://forum.xda-developers.com/attachment.php?attachmentid=397939&d=1284039287>**
+ Direct download URL for command-line version: **<https://forum.xda-developers.com/attachment.php?attachmentid=397962&d=1284040833>**
+ Have this software command-line interface (CLI)? Yes
+ If «yes» for previous question, what folder(s) must be added to the `PATH` environment variable? `.`
+ Software summary/short description: Validator for Windows Registry files (`.reg`)

### 3. Note

Yes, I understand, that Registry File Validator is old software. But:

1. It works.
1. I'ven't found any alternative checker/linter/validator.

#### 4.1. Registry Checker Tool

[**`Scanregw filename`**](https://support.microsoft.com/en-us/help/184023/command-line-switches-for-the-registry-checker-tool) no longer valid for Windows 10, see posts from an official Microsoft forum:

1. [**Can't run `Scanreg.exe`**](https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/cant-run-scanregexe/d81bff91-dfb9-4c31-98ed-b18e5a95b74b)
1. [**Don't have `scanregw.exe` on my PC**](https://answers.microsoft.com/en-us/windows/forum/all/dont-have-scanregwexe-on-my-pc-every-forum-says/3a9f5c14-6edc-42e8-abf1-863ac24e3346)

#### 4.2. System File Checker

It [**can check**](https://www.thewindowsclub.com/how-to-scan-repair-a-single-file-using-system-file-checker), for example, `.exe` files, but not `.reg`;

```text
D:\KiraTwickenham>sfc /SCANFILE=D:\KiraTwickenham\KiraExampleReg.reg

Windows Resource Protection could not perform the requested operation.
```

Thanks.

**Comment by chtof** [comment]
There is no license to allow to distribute these zip files and so, we can't embed them.
I have tried to handle the download links (headers options and cookies) but without success...
I hope someone else will be able to create this Chocolatey package.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/registryfiles-validator
- https://chocolatey.org/packages/registryfiles-validator-commandline

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/registryfiles-validator
- https://chocolatey.org/packages/registryfiles-validator-commandline

Can be closed.
