### ISSUE TITLE
RFP - EpiData.install

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey-community/chocolatey-package-requests#690]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.epidata.dk/
Direct download URL for the software/installer: http://www.epidata.dk/php/downloadc.php?file=setup.all-in-one.4.6.0.0.exe
Software summary / short description: statistics and analysis; see [Wikipedia](https://en.wikipedia.org/wiki/Epidata)

## Package Expectations

Embed the binary. The website says that it cannot be distributed with cost, which implies that it can be distributed freely (free as in beer).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/epidata

Note : @FranklinYu, I haven't prefered to do not embed the package because distribution is with cost in the Pro version of Chocolatey.

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/epidata

Can be closed.
