### ISSUE TITLE
RFP - wslgit

### ISSUE THREAD

**Issue by neilime** [chocolatey-community/chocolatey-package-requests#691]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/andy-5/wslgit (releases page: https://github.com/andy-5/wslgit/releases/latest)
Direct download URL for the software / installer : https://github.com/andy-5/wslgit/releases/download/v0.7.0/wslgit.exe
Software summary / short description: Use Git installed in Bash on Windows/Windows Subsystem for Linux (WSL) from Windows and Visual Studio Code (VSCode)

Exe file should be copy in "C:\tools\wslgit\wslgit.exe"

**Comment by boubou** [comment]
In progress!

**Comment by AdmiringWorm** [comment]
@boubou please do not pick up request until we have assigned the issue with the label "Available for maintainers".

If we haven't assigned that label it means we have not yet had the chance to verify the request yet (ie, does not exist, is available on windows, is not behind a paywall or login, etc...)

**Comment by boubou** [comment]
Can be close now sir!
