### ISSUE TITLE
RFM - RapidMiner Studio

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey-community/chocolatey-package-requests#692]
# RapidMiner Studio

> RapidMiner is a data science software platform developed by the company of the same name that provides an integrated environment for data preparation, machine learning, deep learning, text mining, and predictive analytics. It is used for business and commercial applications as well as for research, education, training, rapid prototyping, and application development and supports all steps of the machine learning process including data preparation, results visualization, model validation and optimization. RapidMiner is developed on an open core model. The RapidMiner Studio Free Edition, which is limited to 1 logical processor and 10,000 data rows is available under the AGPL license. Commercial pricing starts at $5,000 and is available from the developer. <sub>[Description from Wikipedia](https://en.wikipedia.org/wiki/RapidMiner)</sub>

---

## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/rapidminer
Package source URL: https://releases.rapidminer.com/latest/rapidminer-studio/rapidminer-studio-win64-install.exe?utm_source=nexus&utm_medium=nexus
Offical Website: https://rapidminer.com/

Date the maintainer was contacted: 2019-09-09 and 2019-09-11
How the maintainer was contacted: "Contact Maintainer" Button

> Hi [...],
> 
> your package "RapidMiner" is very out of date. The current version is 9.3 and is out for some time now.
> 
> My previous message to you was very short so maybe you overread it.
> 
> Could you please upgrade the package or (if you no longer want to maintain it) open a Request for Maintainer Ticket?
> 
> You can reach me via [...]
> 
> Thank you!

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/rapidminer-studio
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/automatic/rapidminer

**Comment by pauby** [comment]
@chtof You haven't been added as maintainer of the `rapidminer` package as yet. Can you request that again?

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/rapidminer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/rapidminer

Can be closed.
