### ISSUE TITLE
RFP - Orfeo Toolbox

### ISSUE THREAD

**Issue by maphew** [chocolatey-community/chocolatey-package-requests#693]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.orfeo-toolbox.org/
Direct download URL for the software / installer : https://www.orfeo-toolbox.org/packages/OTB-6.6.1-Win64.zip (https://www.orfeo-toolbox.org/download/)
Software summary / short description:  An open-source project for state-of-the-art remote sensing. It can process high resolution optical, multispectral and radar images at the terabyte scale. ...from ortho-rectification or pansharpening, all the way to classification, SAR processing, and much more. Algorithms are accessible from Monteverdi, QGIS, Python, the command line or C++. Monteverdi is an easy to use visualization tool with an emphasis on hardware accelerated rendering for high resolution imagery (optical and SAR). End-users can visualize huge raw imagery products and access all of the applications in the toolbox. From resource limited laptops to high performance MPI clusters, OTB is available on Linux, macOS and Windows. It is community driven, extensible and heavily documented.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/orfeo-toolbox

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/orfeo-toolbox

Can be closed.
