### ISSUE TITLE
RFP - IIS CORS Module

### ISSUE THREAD

**Issue by jackfox10** [chocolatey-community/chocolatey-package-requests#694]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package; 
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.iis.net/downloads/microsoft/iis-cors-module
Direct download URL for the software / installer : https://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=cors
Software summary / short description:
The Microsoft IIS CORS Module is an extension that enables web sites to support the CORS (Cross-Origin Resource Sharing) protocol.

The IIS CORS Module enables support for the Cross-Origin Resource Sharing (CORS) protocol. CORS is a mechanism to let a user-agent access resources from a domain outside of the domain from which the first resource was served. CORS defines a way by using additional HTTP headers to allow request permissions to access a selected resource. In addition, some requests may even a trigger a preflight request probing supported HTTP methods from the server with an HTTP OPTIONS request. The IIS CORS module helps with setting appropriate response headers and responding to preflight requests. Once installed, the IIS CORS module is configured via a site or application web.config and has its own cors configuration section within system.webserver.

**Comment by boubou** [comment]
I will pick the package.

**Comment by boubou** [comment]
https://chocolatey.org/packages/iis-cors-module/1.0

**Comment by pauby** [comment]
@boubou Can you help us out by giving us a status rather than just posting a URL?

**Comment by boubou** [comment]
Ready for review ;)
Since some days. ;)
