### ISSUE TITLE
RFP Visio & Project

### ISSUE THREAD

**Issue by necrose99** [chocolatey-community/chocolatey-package-requests#695]
https://chocolatey.org/packages/office2019-proplus 
_(basically could recycle the template it works mostly. )_  -x64 -x32 a nice add to force upgrade/etc to ie 64bit. if some older office is installed.  just tweek config xml's for x64/32 ... 

(**https://www.wincert.net/forum/topic/13912-new-office-2019-download-links/**)

https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/ProjectStd2019Retail.img (ProjectStd, English)

https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/VisioStd2019Retail.img (VisioStd, English)

https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/ProjectPro2019Retail.img (ProjectPro, English)

https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/VisioPro2019Retail.img (VisioPro, English)

for biz users --lang=en-br or =??-?? for users lang could be added. 

--key= my licence key/z could also be a plus to post install set key.. via batch file/puppet chef gpo etc. .. and chocolatey.  still riggable via other but....

**Comment by pauby** [comment]
@necrose99 Can you go back and use the template we provided?

**Comment by AdmiringWorm** [comment]
Closing as issue have not been been updated with the necessary template.

@necrose99 if/when you update the issue we can then re-open the this issue.
