### ISSUE TITLE
Package Windows-Repair-Toolbox outdated since many many weeks.

### ISSUE THREAD

**Issue by boubou** [chocolatey-community/chocolatey-package-requests#696]
Package Windows-Repair-Toolbox outdated since many many weeks.

**Comment by boubou** [comment]
I wrote to the maintainer today.

**Comment by chtof** [comment]
Hi @boubou , for the next packages like this one, write to the maintainer, and if you don't received an answer after **one week**;
- Create the updated script and send an email using the "Contact Site Admins" to inform you have an updated version ready to be published on your GitHub repository, and as reference add the date when you have wrote to the maintainer and the link to your updated version on your GitHub repository.
- Or if you dont't want to be the maintainer of this package, create a new issue, usinf the RFM template.

In other words, you haven't to create a such issue. You have to request to be added as maintainer after one week without having received any answer or to create a RFM issue here. It's useless for us to know you have wrote to the maintainer as he can answer you and even if he doesn't answer you after one week, maybe you will update the package by yourself requesting to be added as maintainer using "Contact Site Admins" link or you will open a RFM issue if you are not interested by this package but we can't guess it.
Thank you, have a nice week-end!
