### ISSUE TITLE
RFM -  Toolwiz Time Freeze

### ISSUE THREAD

**Issue by SlrG** [chocolatey-community/chocolatey-package-requests#697]
## Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
http://www.toolwiz.com/lead/toolwiz_time_freeze/

Direct download URL for the software / installer : 
http://www.toolwiz.com/downloadfiles/Setup_Timefreeze.exe

Software summary / short description:
Toolwiz Time Freeze is an easy and effective Instant system restore software to keep your system safe and protect your computer from unwanted changes. Turning on the Time Freeze mode, the whole system is running in the "sandbox". Only the changes to the files in the exclusion list will be saved.
Support OS:WinXP/Win2003/Vista/Win7/Win8/Win10(32/64bit)

**Comment by boubou** [comment]
Published!

**Comment by SlrG** [comment]
@pauby 
Sorry! I don't know how I could miss it beeing RFP  - Title in the checklist and writing RFP: Title instead.

**Comment by SlrG** [comment]
@boubou 
Thank you very much for publishing. :+1:

**Comment by chtof** [comment]
> Published!
@SlrG 

@boubou Do not confuse published and under review (submitted). For me, published is when a package as been submitted and approved and so publicly available.
As you haven't specified where the package is available (annoying for me and other moderators as we have to search the package, check if you are the owner and it's not a duplicate), it seems the package is under review here : https://chocolatey.org/packages/toolwiz-time-freeze/
So, the package has been submitted, is under review, verification testing has failed and so, not yet available.
For next packages, could you specify the status (Review or In Progress) adding the URL(s) referring to the Chocolatey pages? And once the package is approved, you can update the issue to request the closure of the issue saying the package has been published.
Thank your for your comprehension and for your help!

**Comment by pauby** [comment]
@boubou This package has been rejected as it wasn't fixed in the grace period. Can you confirm what you happen to it?

**Comment by pauby** [comment]
As there has been no update to this I'm changing this to a 'RFM' request (as we already have a package albeit not working).

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Chocolatey package ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/automatic/toolwiz-time-freeze

**Comment by pauby** [comment]
@chtof There is currently an issue with messages being sent to the Site Admins through the website. I've added you as a maintainer of the package.
