### ISSUE TITLE
RFP - VirtualHere Windows USB Client

### ISSUE THREAD

**Issue by SlrG** [chocolatey-community/chocolatey-package-requests#698]
## Checklist
- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://www.virtualhere.com/usb_client_software

Direct download URL for the software / installer :
https://www.virtualhere.com/sites/default/files/usbclient/vhui32.exe
https://www.virtualhere.com/sites/default/files/usbclient/vhui64.exe

Software summary / short description:
The VirtualHere USB Client runs on Windows, OSX, Linux and Android. The client was created to be intuitive and extremely easy to use. The client needs to be run on any machine that wants to use USB devices shared by the VirtualHere USB Server.

The software will automatically find USB devices shared by VirtualHere USB Servers on the network. Available USB devices will be displayed in a tree. Right click on the device you want to use and select Use. It will then appear to be directly connected to your machine and can be used just like a local device!

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/virtualhere-client

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/virtualhere-client

Can be closed.

**Comment by SlrG** [comment]
Thank you very much. :)
