### ISSUE TITLE
RFP - VirtualHere Windows USB Server

### ISSUE THREAD

**Issue by SlrG** [chocolatey-community/chocolatey-package-requests#699]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://www.virtualhere.com/windows_server_software

Direct download URL for the software / installer :
https://www.virtualhere.com/sites/default/files/usbserver/vhusbdwin32.exe
https://www.virtualhere.com/sites/default/files/usbserver/vhusbdwin64.exe

Software summary / short description:
VirtualHere allows USB devices to be used remotely over a network just as if they were locally connected!

Traditionally USB devices needed to be plugged directly into your computer to be used. With VirtualHere this is no longer required, the network itself becomes the cable transmitting USB signals (also known as USB over IP, USB/IP, USB over WiFi, USB over Ethernet, USB Device Server).

This USB server solution is perfect for allowing USB devices to be used remotely over a LAN network, over the Internet, or in the Cloud without the USB device needing to be physically attached to remote client machine. The USB device appears as if it was directly attached even though it is plugged in to a remote server, therefore all existing drivers and software work, no special changes required.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/virtualhere-server

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/virtualhere-server

Can be closed.

**Comment by SlrG** [comment]
Thank you very much. :)
