### ISSUE TITLE
RFM - TinyPDF

### ISSUE THREAD

**Issue by SlrG** [chocolatey-community/chocolatey-package-requests#700]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
http://www.tinypdf.com/

Direct download URL for the software / installer :
http://www.tinypdf.com/InstallTinyPDF.exe

Software summary / short description:
TinyPDF is one of the world smallest PDF creation software. 586KB!
Create professional quality PDF files from virtually any printable document.

**Comment by boubou** [comment]
Published!

**Comment by SlrG** [comment]
Oh wow. You were so fast. :) Thank you very much. I really appreciate it.

**Comment by ionred** [comment]
Package did not pass validation - checksum

**Comment by chtof** [comment]
@boubou Also, you have specified silentArgs for a MSI file. TinyPDF uses "Inno Setup" as installer so silentArgs should be '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'

**Comment by pauby** [comment]
@boubou This package was rejected as it was not fixed during the grace period. Can you confirm what you want to happen to it?

**Comment by pauby** [comment]
As there has been no update to this I'm changing this to a 'RFM' request (as we already have a package albeit not working).

**Comment by teknowledgist** [comment]
Notice to anyone thinking about building this package, it is **32-bit only**.  [It will not work/install on 64-bit Windows.](http://tinypdf.com/support.html#Does%20TinyPDF%20work%20on%20Windows%2064-bit)

**Comment by SlrG** [comment]
@teknowledgist 
Thank you, for letting me know. I did not know this until now and I think its better to withdraw my package request under this circumstances. Would not make sense to put work into a package limited to 32-bit only.

**Comment by AdmiringWorm** [comment]
@SlrG if you look at http://tinypdf.com/products.html
the page specifically mentions:
> Now support Windows 10 32-bit and optionally support Windows 10 64-bit..

Even if the software only worked for 32bit, it would still be a valid request (it can be determined during installation what the os architecture is).
I'm not going to re-open the request now, as that would be up to you if you still want to request a package for tinypdf

**Comment by teknowledgist** [comment]
Just for the record... When you attempt to install TinyPDF on 64-bit windows, a message pops up:

````
TinyPDF has detected that you are running a 64-bit edition of
Microsoft Windows. But unfortunately TinyPDF is free for
Microsoft Windows 32-bit only.
````

Of course, this package could be made to require a 32-bit system, but that is a dying breed.

**Comment by SlrG** [comment]
Yes, the developer has (sadly but understandably) abandoned the free program for a commercial one, which is 64-bit compatible. I really liked it because of its tiny size compared to other pdf printers and really would have liked for it to be made compatible. But as this is not desired by the developer and as you said 32-bit is a dead horse, we will have to let this package go too.
