### ISSUE TITLE
RFP - mpv.net

### ISSUE THREAD

**Issue by 4ft35t** [chocolatey-community/chocolatey-package-requests#701]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://mpv-net.github.io/mpv.net-web-site/

Direct download URL for the software / installer : 
https://github.com/stax76/mpv.net/releases

Software summary / short description:
mpv.net is a Windows player similar to the original mpv, with context menu, settings dialog, key map editor and support for C# and Python extensions.

**Comment by boubou** [comment]
Is it that ?
https://chocolatey.org/packages/mpvnet.install
