### ISSUE TITLE
RFP - OpenVPN Connect v3

### ISSUE THREAD

**Issue by AzimsTech** [chocolatey-community/chocolatey-package-requests#702]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://openvpn.net/client-connect-vpn-for-windows/

Direct download URL for the software / installer : 
https://openvpn.net/downloads/openvpn-connect-v3-windows.msi

sha256 signature : 
2886ff012ca33956529110b2a959f8dd6e431dd3b5a42e2715b394e1e8b9e53e

Software summary / short description : 
This is a Beta version of OpenVPN client based on OpenVPN 3 Core C++ library. https://github.com/OpenVPN/openvpn3

**Comment by pauby** [comment]
Is this not a candidate for a new version of the current Open VPN package? Do we need to provide a separate package for it?

**Comment by AdmiringWorm** [comment]
@pauby from my understanding, these are two different programs.
I will admit I may be completely wrong in thinking that though.

**Comment by chtof** [comment]
_Can the new and the old client co-exist ? Yes, you may continue to use both v2 and v3 on the same connect device and import the profiles desired into each. If you like, you can run either one or both._

_Is the old client still available? The OpenVPN client v1 was called “OpenVPN Desktop Client” and is no longer available. It is also not safe to use this anymore as it hasn’t been maintained for many years. It was replaced with the OpenVPN client v2.

The OpenVPN client v2 is called “OpenVPN Connect Client” and has been in use for many years. It is still available from our website and offered in the OpenVPN Access Server client web interface itself.

The OpenVPN client v3 is called “OpenVPN Connect” and is the latest generation of our software. It is available on our website as a beta version, and will be included soon in Access Server releases._

So this new version branch v3x has a new name. For me, It's not clear if v3 can completely replace v2 (for old Access Server for example) as they said both old and new can be installed and used. In other words, there is maybe a good reason to have both installed and I don't know if Chocolatey allows to install 2 versions of a same package (if not possible, my opinion should be to have a separate package)?

Note: Another point, I think profiles are not automatically imported from an upgrade v2 to v3. If it's the case, we should add a warning in the package description (or check if it's possible to do that in command-line).

**Comment by jan-win1993** [comment]
I would like to create and maintain this package.

**Comment by jan-win1993** [comment]
The package is published.

**Comment by fraenki** [comment]
https://community.chocolatey.org/packages/openvpn-connect
This issue should be closed.
