### ISSUE TITLE
RFP - NeatMouse

### ISSUE THREAD

**Issue by kaffeekanne** [chocolatey-community/chocolatey-package-requests#703]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
- https://neatdecisions.com/products/neatmouse/
- https://github.com/neatdecisions/neatmouse/
Direct download URL for the software / installer : 
- https://neatdecisions.com/downloads/neatmouse/neatmouse-1.05.002-setup.exe
- https://github.com/neatdecisions/neatmouse/releases/download/v1.05.002/neatmouse-1.05.002-setup.exe
- https://github.com/neatdecisions/neatmouse/releases

Software summary / short description:

(From their Homepage)

NeatMouse is a small tool for Windows that allows controlling your mouse cursor via keyboard.

This is very useful when your physical mouse is unavailable:

* If you haven’t installed its driver yet, and Windows was unable to do this automatically.
* If you use wireless mouse and its battery is low so you need to charge it.
* If you are a person with reduced mobility.

## Package Expectations

I think that would be a nice package in the chocolatey repositories as the build in mouse emulation of windows is less costumizable. I have no idea if github or their own homepage is their preferred download location. But since they have an RSS feed maybe their homepage as source can be tracked as convenient as github.

If somebody also searching for mouse emulation picks it up, thanks a lot!

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/neatmouse

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/neatmouse

Can be closed.
