### ISSUE TITLE
RFP - Intel ispc

### ISSUE THREAD

**Issue by cholmquist** [chocolatey-community/chocolatey-package-requests#704]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://ispc.github.io/

Direct download URL for the software / installer :
https://sourceforge.net/projects/ispcmirror/files/v1.12.0/ispc-v1.12.0-windows.zip/download
https://netix.dl.sourceforge.net/project/ispcmirror/v1.12.0/ispc-v1.12.0-windows.zip

Software summary / short description:
ispc is a compiler for a variant of the C programming language, with extensions for "single program, multiple data" (SPMD) programming.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/ispc

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/ispc

Can be closed.
