### ISSUE TITLE
RFP - Wireguard

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#705]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.wireguard.com/install/
Direct download URL for the software / installer : https://download.wireguard.com/windows-client/wireguard-amd64-0.0.32.msi
Software summary / short description : A next-generation vpn client aiming to be faster, simpler, and more secure than OpenVPN. It's cross-platform, and widely deployable.

**Comment by AdmiringWorm** [comment]
@houstdav000 is this the package that you are looking for: https://chocolatey.org/packages/wireguard

**Comment by houstdav000** [comment]
Wasn't aware there was a "pre" section. My mistake.

**Comment by houstdav000** [comment]
I will contact wireguard to see if they can get the chocolatey install added to their website
