### ISSUE TITLE
RFM - wc3270

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#706]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://x3270.bgp.nu/
Direct download URL for the software / installer : https://newcontinuum.dl.sourceforge.net/project/x3270/x3270/3.6ga8/wc3270-3.6ga8-setup.exe
Software summary / short description: An IBM 3270 terminal emulator for Windows Console.

Emulates either an IBM 3279 (color) or 3278 (monochrome). It supports:

- The full TN3270E protocol
- SSL/TLS (via the OpenSSL library) for encrypted sessions
- APL2 characters
- Non-English character sets, including Russian, Turkish, Hebrew and DBCS Chinese and Japanese
- IND$FILE file transfer
- NVT mode (emulating a color xterm)
- A pop-up keypad for 3270-specific keys
- A scrollbar
- Printer session integration
- Extensive debugging and scripting facilities

Can also be found at https://sourceforge.net/projects/x3270/

**Comment by houstdav000** [comment]
Sorry about the previous one. This one I know isn't in Chocolatey

**Comment by AdmiringWorm** [comment]
> Sorry about the previous one. This one I know isn't in Chocolatey

Actually it is: https://chocolatey.org/packages/wc3270
however since the version submitted was never approved, it won't show up in searches at all.

Changing request to RFM since it never was approved.

**Comment by mkevenaar** [comment]
I will pick this one up.

**Comment by AdmiringWorm** [comment]
@mkevenaar well you know the drill, shoot of a message to the site admins 😺

**Comment by mkevenaar** [comment]
Submitted:

https://chocolatey.org/packages/wc3270
https://chocolatey.org/packages/wc3270.install
https://chocolatey.org/packages/wc3270.portable

**Comment by mkevenaar** [comment]
Deze zijn nu beschikbaar.
