### ISSUE TITLE
RFP - AudioFlyout

### ISSUE THREAD

**Issue by andrizmitnick** [chocolatey-community/chocolatey-package-requests#710]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ADeltaX/AudioFlyout
Direct download URL for the software / installer : 
https://github.com/ADeltaX/AudioFlyout/releases/download/0.9.2.0/AudioFlyout.zip
https://github.com/ADeltaX/AudioFlyout/releases/download/0.9.2.0/AudioFlyoutUA.zip
Software summary / short description:
Replace the Volume/SMTC UI with a custom one. fluent design style and more available additional controls.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/audioflyout

**Comment by AdmiringWorm** [comment]
I see that this package have also been approved now.

**Comment by andrizmitnick** [comment]
awesome.. thank you very much!!
