### ISSUE TITLE
RFM - Minetest

### ISSUE THREAD

**Issue by Moth-Tolias** [chocolatey-community/chocolatey-package-requests#711]
## I DON'T Want To Become The Maintainer

- [x] There is no existing open maintainer request for this package;
- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/minetest
Package source URL: http://www.minetest.net/

Date the maintainer was contacted: 11/11/19
How the maintainer was contacted: email [via "contact site admins" button; current maintainer has been out of action for several years]

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/automatic/minetest

**Comment by AdmiringWorm** [comment]
@chtof I do not see any messages sent for the `minetest` package, would you mind sending the email again?

**Comment by chtof** [comment]
Hi @AdmiringWorm, the mail was sent on saturday, 16th of november 2019 15:36 GMT.

_Hello,_

_Could you add me as maintainer for this package?_
_- Abandonned package: https://github.com/chocolatey-community/chocolatey-package-requests/issues/711_
_- Updated version is ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/automatic/minetest_

_Message sent from Chocolatey.org_

_Current Maintainer(s): adgellida_
_Package Url: https://chocolatey.org/packages/minetest/0.4.10.20141201_

**Comment by AdmiringWorm** [comment]
@chtof unfortunately I can not see any trail at all, so there may have happened something during the sending of the email.

If you could send of a new email, we could get you added immediately.

**Comment by chtof** [comment]
@AdmiringWorm Request sent again just now via contact admink link of the pkg.

**Comment by AdmiringWorm** [comment]
hmm, oddly enough the email is not getting through it seems.
However I have went ahead and added you as a maintainer anyhow (pending confirmation of course).

@pauby this may be something you guys should look into on why the email never gets through.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/minetest/5.1.0

https://github.com/chocolatey/package-verifier/issues/70
