### ISSUE TITLE
RFP - Rockstar Games Launcher

### ISSUE THREAD

**Issue by jimbo98** [chocolatey-community/chocolatey-package-requests#714]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://socialclub.rockstargames.com/rockstar-games-launcher
Direct download URL for the software / installer : https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe
Software summary / short description:

**Comment by jimbo98** [comment]
https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe

**Comment by AdmiringWorm** [comment]
@jimbo98 can you please update the issue with the project url and and brief software summary (I have updated the other things, and moved the download url to the first comment).

**Comment by jimbo98** [comment]
Software project URL :https://socialclub.rockstargames.com/rockstar-games-launcher
Software summary / short description:games download shop and center

**Comment by AndreTheHunter** [comment]
Any progress on this?

**Comment by Zoullx** [comment]
I have become the maintainer of this package and pushed an updated package that is currently going through the approval process.

**Comment by TheCakeIsNaOH** [comment]
Package has been approved. Thanks @Zoullx
