### ISSUE TITLE
RFM - redis

### ISSUE THREAD

**Issue by danielskowronski** [chocolatey-community/chocolatey-package-requests#715]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/redis
Package source URL: https://github.com/jeff-french/chocolatey-packages
Date the maintainer was contacted: via form on package page
How the maintainer was contacted: 2019-11-16

**Comment by mkevenaar** [comment]
I am willing to pick this op

**Comment by pauby** [comment]
@mkevenaar You're not a maintainer on this package (using the URL in the OP)?

**Comment by pauby** [comment]
@mkevenaar Can you update us on this?

**Comment by mkevenaar** [comment]
@pauby I have marked it available again as I don't have time for it currently.

**Comment by Thilas** [comment]
I can pick this one up. I've just sent a request to become maintainer.

**Comment by Thilas** [comment]
Done, I just pushed 4 new versions of the package.
