### ISSUE TITLE
RFM - PDQ Deploy

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-package-requests#728]
https://chocolatey.org/packages/pdq-deploy

I have no interest in the package, don't wish to maintain it anymore, and so it's up for grabs.

If you're interested, contact me via the Contact Maintainers link on the package web page. Please state why you want to maintain (i.e. You use it.) and if you have or currently maintain any packages. If you're a virgin package maintainer I will be glad to offer guidance. I will also remain on as a backup maintainer.

**Comment by mkevenaar** [comment]
Hi Bill,

Thank you for these issues, however could I ask you to please update this issue and use the template? This way we can make sure all the information is available for a new maintainer.

Thanks in advance.

**Comment by pauby** [comment]
After 14 days this issue will be closed due to the template not being used.

**Comment by bcurran3** [comment]
All information has been provided, requiring strict adherence to the template is absurd. Closing this "due to the template not being used" is not in the best interest of the community.

## Current Maintainer

- [X] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [X ] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: see first post
Package source URL: available via the download button on the package page on chocolatey.org
