### ISSUE TITLE
RFM - Malwarebytes

### ISSUE THREAD

**Issue by LoZeno** [chocolatey-community/chocolatey-package-requests#730]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/malwarebytes
Package source URL: https://github.com/aronovgj/choco-auto

Date the maintainer was contacted: 12/11/2019
How the maintainer was contacted: via Disqus; via "Contact maintainers" link; via github issue on their github repo for chocolatey packages.

**Comment by pauby** [comment]
I use this so I'll pick it up. Will send a request shortly.

**Comment by pauby** [comment]
New version has been pushed.
