### ISSUE TITLE
RFP - Doxie for Windows

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#731]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.getdoxie.com/info/apps.html
Direct download URL for the software / installer : https://download.getdoxie.com/DoxieSetup-2.12.2.exe

Software summary / short description:
Companion software intended for use with most Doxie-branded portable scanners. Enables importing of scans via USB connection, SD cards, or Wi-Fi connection, edits for organization (multiple pages, interleaving, stitching, OCR), readability adjustments (contrast, rotations, crops), and exporting via multiple image file formats (JPEG, PNG, PDF).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/doxie

**Comment by brogers5** [comment]
The package as linked above appears to have been published and approved 3 days ago. I think we're clear to close this one out.

Thanks @chtof for picking this up!
