### ISSUE TITLE
RFP - Standard Notes

### ISSUE THREAD

**Issue by Mavorsa** [chocolatey-community/chocolatey-package-requests#732]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://standardnotes.org/
Direct download URL for the software / installer : https://standardnotes.org/extensions?downloaded=windows
Software summary / short description: 
Standard Notes is a free, open source, privacy oriented, encrypted cloud cross-platform note taking app. It can use extensions and utilizes both free and paid hosting plans.

**Comment by teknowledgist** [comment]
I'll take this on as a package.

**Comment by teknowledgist** [comment]
`standardnotes` package has been submitted.

**Comment by pauby** [comment]
@teknowledgist This is 'waiting on maintainer'?

**Comment by teknowledgist** [comment]
Yes.  It is a per-user install only.  

I've asked for that to be changed, but it was within [a post about creating the Chocolatey package](https://github.com/standardnotes/forum/issues/821) that was moved from a desktop issue into the "forum".  I'm going to open a specific ticket for the desktop app.

**Comment by pauby** [comment]
Can you update here so we can keep a track of what is happening? Thanks.

**Comment by teknowledgist** [comment]
[Here is the issue that's getting traction.](https://github.com/standardnotes/desktop/issues/469)

**Comment by pauby** [comment]
@teknowledgist Thanks for updating us on this. I note the author is testing this out for the next release and there have been three releases since his comment. Do you know if this has been included?

**Comment by teknowledgist** [comment]
I'm asking about it.  I can't actually test anything at the moment because of some life and technical complications, but I won't forget about it.

**Comment by pauby** [comment]
@teknowledgist Any update to this?

**Comment by teknowledgist** [comment]
Nope.  (Personal) Life and technical complications remain (preventing me from testing), and [the issue at Standard Notes](https://github.com/standardnotes/desktop/issues/469) has stalled.  I'm sure they would welcome help with configuring Electron-Builder to make a machine install, but I don't have that level of knowledge (or time).

**Comment by pauby** [comment]
Thanks for updating us. I'm minded to close this issue just now with "Can't implement" and re-open if / when they release an installer that allows a machine wide install.

Thoughts?

**Comment by teknowledgist** [comment]
I have no argument with that.  I should get notifications for any updates on the issue, and I should be able to push a fixed package pretty quickly once the installer is corrected.
