### ISSUE TITLE
RFP - SoundSwitch

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#733]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://soundswitch.aaflalo.me/
Direct download URL for the software / installer : https://github.com/Belphemur/SoundSwitch/releases/download/v4.16.1/SoundSwitch_v4.16.1.34861_Release_Installer.exe
Software summary / short description:
Resident utility to enable Windows users to quickly switch between Playback and Recording audio devices. Switching can be done via a tray menu or binding an optional hotkey sequence.

**Comment by Sylian1** [comment]
I use soundswitch everyday since several years.
Could I hope to see it in a new package from Chocolatey ?
Thanks a lot

**Comment by teknowledgist** [comment]
[SoundSwitch package](https://chocolatey.org/packages/soundswitch) created and submitted.

**Comment by brogers5** [comment]
Package has been approved as of yesterday. We should be clear to close this one out.
