### ISSUE TITLE
RFP - PowerChute Personal Edition

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#734]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.apc.com/shop/us/en/categories/power/uninterruptible-power-supply-ups-/ups-management/powerchute-personal-edition/N-1b6nbpp
Direct download URL for the software / installer : https://download.schneider-electric.com/files?p_enDocType=Software+-+Released&p_Doc_Ref=APC_PCPE_310&p_File_Name=PCPE_3.1.0.exe
Software summary / short description:
Management software for APC-branded uninterruptible power supplies. Enables configuration of UPS behavior (e.g. battery backup alarm, electrical noise sensitivity, voltage fluctuation thresholds, etc.) and monitoring of current status and historical performance.

**Comment by tunisiano187** [comment]
I've created it, you can follow the process here : https://chocolatey.org/packages/powerchute-personal/3.1.0
Have a nice day

**Comment by brogers5** [comment]
Package has been approved as of yesterday. This issue can be closed.
