### ISSUE TITLE
RFP - FalconX

### ISSUE THREAD

**Issue by sandriaas** [chocolatey-community/chocolatey-package-requests#737]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar
Direct download URL for the software / installer :
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/download/1.3.2.0/FalconX_16.11.2019_1.3.2.0.zip
Software summary / short description:
Center Windows taskbar icons with a variety of animations and options

**Comment by kamack38** [comment]
This package is already published: https://community.chocolatey.org/packages/taskbarx

**Comment by TheCakeIsNaOH** [comment]
Thanks for noticing that @kamack38
