### ISSUE TITLE
RFP - Strawberry Music Player

### ISSUE THREAD

**Issue by b16r05** [chocolatey-community/chocolatey-package-requests#739]
Software project URL : https://www.strawberrymusicplayer.org/
Direct download URL for the software / installer : https://github.com/jonaski/strawberry/releases
Software summary / short description: Strawberry is a music player and music collection organizer. It is a fork of Clementine...

**Comment by pauby** [comment]
@b16r05 Can you go back and complete _all_ of the template?

**Comment by pauby** [comment]
After 14 days this issue will be closed due to the template not being used.

**Comment by b16r05** [comment]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.strawberrymusicplayer.org/
Direct download URL for the software / installer :
32-bit: https://files.jkvinge.net/packages/strawberry/StrawberrySetup-0.6.7-x86.exe
64-bit: https://files.jkvinge.net/packages/strawberry/StrawberrySetup-0.6.7-x64.exe

Software summary / short description:  

Strawberry is a music player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors, enthusiasts and audiophiles. The name is inspired by the band Strawbs. It's based on a heavily modified version of Clementine created in 2012-2013. It's written in C++ and Qt 5.

 ## Package Expectations

- default options are fine

**Comment by b16r05** [comment]
How do I re-open this request? Or, do I create a new one?

**Comment by dtantono** [comment]
The maintainer attempt to make it live on Chocolatey (https://chocolatey.org/packages/strawberrymusicplayer). But, the approval hadn't already given. Is there a problem Chocolatey backend side?

**Comment by b16r05** [comment]
Thank you @dtantono for the note. I am excited to see some action, of my original request from over a year ago. This project is a fork of clementine, which is already available through chocolatey, ... but maybe enough things have changed to cause issues.

**Comment by b16r05** [comment]
I noticed that chocolatey page for Strawberry Music Player shows version 0.8.1 from Last Update on 16 Oct 2020: https://chocolatey.org/packages/strawberrymusicplayer

A new version, 0.8.5, was released on Dec 19, 2020: https://github.com/strawberrymusicplayer/strawberry/releases

I am not sure if someone contacted the maintainer, so, I opened a ticket letting him know: https://github.com/strawberrymusicplayer/strawberry/issues/649

**Comment by dtantono** [comment]
Hi
I think you should notify the maintainer on the chocolatey site or strawberry forum (https://forum.strawberrymusicplayer.org/) to improve the visibility of your request.

**Comment by b16r05** [comment]
Hi @dtantono The software author @jonaski is active. He replied on the chocolatey page: https://chocolatey.org/packages/strawberrymusicplayer and also, my ticket when I contacted him: https://github.com/strawberrymusicplayer/strawberry/issues/649

However, I have no idea about the package maintainer: https://chocolatey.org/profiles/samon53. This package might need a new maintainer. I was wondering if package maintainers of ClemetineMusicPlayer: **purity** and **chocolatey-community**, might be interested in taking it over. But, I have no idea on how to contact them.

**Comment by dtantono** [comment]
Hi
I think our best bet is to contact the chocolatey support team (https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#package-is-outdated) and see their response for this issue.

**Comment by b16r05** [comment]
@dtantono I sent the maintainer a message, asking him to come in here. From what I understand from the link you provided, since this ticket is closed, I have to create a new one and see how that goes. I will hold off for now and give it a few days. Thanks for your help!

**Comment by dtantono** [comment]
Hi, I also communicate with strawberry developers as well and you can track them here (https://github.com/strawberrymusicplayer/strawberry/issues/635) and (https://forum.strawberrymusicplayer.org/topic/194/feature-request-add-flatpak-package-and-other-repositories)

**Comment by BrandonKMLee** [comment]
@b16r05 @dtantono it seems that the newer version of the package is also broken, can someone please help out?

**Comment by dtantono** [comment]
@BrandonKMLee you can contact the strawberry maintainer for this issue (https://github.com/strawberrymusicplayer/strawberry)

**Comment by BrandonKMLee** [comment]
@dtantono the development team made the statement that it is on the side of the chocolatey package developers that are responsible.

**Comment by dtantono** [comment]
you can consult this site (https://chocolatey.org/support)
