### ISSUE TITLE
RFM - LMMS

### ISSUE THREAD

**Issue by Moth-Tolias** [chocolatey-community/chocolatey-package-requests#740]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/lmms
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/lmms/

Date the maintainer was contacted: Nov 24, 2019
How the maintainer was contacted: email [via "contact maintainers" button on site]

**Comment by teknowledgist** [comment]
I'm willing to be the maintainer of this.

**Comment by AdmiringWorm** [comment]
@teknowledgist please send a message using the `Contact Site Admins` on the package page, then let us know when you have gotten added as a maintainer.

**Comment by teknowledgist** [comment]
Maintainership gained.  Updated package submitted.

**Comment by pauby** [comment]
Published.
