### ISSUE TITLE
RFP - NetTraffic

### ISSUE THREAD

**Issue by fds39** [chocolatey-community/chocolatey-package-requests#743]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.venea.net/web/nettraffic
Direct download URL for the software / installer : https://www.venea.net/web/downloads
Software summary / short description: Essential network bandwidth usage monitor.
Real time data rate chart. Network usage history. Quota usage meter. Multi-language. Installer & portable. Lightweight. Freeware.

**Comment by fds39** [comment]
Sorry, it's RFP, not RFM. Please edit the title.

**Comment by AdmiringWorm** [comment]
On their download page, they specifically request not to use external downloading software. (Which chocolatey would kind of be).

There also isn't any license that specifically allows redistribution of the software, so the only reason this could be created is either by the developers of the software or through explicit permission to redistribute.

For now, I will be putting this issue in a Triage state, as there are known issues with creating a package for this.

**Comment by pauby** [comment]
@AdmiringWorm What are your thoughts around not labelling this 'Can't Implement' and closing it? What are we hoping the next stage is here that requires keeping it open?

**Comment by AdmiringWorm** [comment]
@pauby the reason why I am not closing this issue immiedately, is because it can still be created. However, it will require direct permission from the developers of the software.

> What are we hoping the next stage is here that requires keeping it open?

The next stage would be for anyone wishing to create a package for this, to contact the developers to request permissions to redistribute the software, we don't have any labels in this repository that reflects this though (Which is why I use the Triage license).

**Comment by pauby** [comment]
> The next stage would be for anyone wishing to create a package for this, to contact the developers to request permissions to redistribute the software, we don't have any labels in this repository that reflects this though (Which is why I use the Triage license).

As we are opening for anyone to create the package I think we should just use the `Available For Maintainers` label - they can then see the discussion here and work through it?

**Comment by AdmiringWorm** [comment]
Fair enough, I will change the labels.

**Comment by teknowledgist** [comment]
I've contacted the developer about distribution in an embedded package.  He is considering it.  I will update here for either decision.

**Comment by pauby** [comment]
Awesome @teknowledgist !

**Comment by AdmiringWorm** [comment]
@teknowledgist I have assigned the issue to you, let us now how everything goes.

**Comment by pauby** [comment]
@teknowledgist Any update on this?

**Comment by teknowledgist** [comment]
This is what I received earlier this week:

> Hello,
> 
> sorry for long reply time.
> 
> At download page are only tips what to do when download not start.
> 
> License can be found here (https://www.venea.net/web/nettraffic#license). License prohibit merging (~ bundling).
> 
> Scenario you describe ("some packages are not embedded and will automatically download an installer") is possible:
> - unmodified NetTraffic (installer or / and portable) can be stored in chocolatey.org repository,
> - package without embedded (bundled) NetTraffic, in ~ metadata file may contains URL to unmodified NetTraffic at chocolatey.org repository and usual / default ~ metadata (like where to unzip, command to run installer in default or silent mode).
> 
> Here is description of silent mode installer (https://www.venea.net/web/nettraffic_silent).
> 
> Best regards,
> Michael 

I think he is not understanding.  I will follow up.

**Comment by pauby** [comment]
Thanks @teknowledgist - much appreciated.

**Comment by teknowledgist** [comment]
So, it appears that the developer is more concerned about the installer being "bundled" (like in a .nupkg) than about distribution.  He is saying that the license allows it to be distributed as is from other sites and that a Chocolatey package can download it from wherever that is.  He seems unwilling to amend or make an exception to the license to allow it to be embedded.  

Specifically:

> thank you for explanation.

>On website hot-link protection is enabled. It's not possible (in direct way) to download file when downloading is not initiated from download page.

>According to license unmodified NetTraffic can be copied to, stored and served from any server (or service like Google Drive). Chocolatey package may contain URL to this other server.

>There is no requirement in license to download NetTraffic from original website. If you can (re)define point 1 as "metadata and instructions to download from the original (or other) site and install/unzip the software" no special permission will not be required to create Chocolatey package in such way. 

"Point 1" from my email was exactly what he quoted minus the "(or other)".

So, what are the rules about that?  Is there any requirement that the installer come from an official site?  Should there be a `VERIFICATION.txt` file even though it's not embedded?  TBH, I don't even know where one could host a random binary like that.

**Comment by fds39** [comment]
@teknowledgist , I could not imagine the legal difficulties that had to be overcome to create such a small Chocolatey package.
I thank you for persisting in trying to find a technical solution (even if it ends in failure).

**Comment by teknowledgist** [comment]
@fds39 Bah, not difficult; Just a few emails and no lawyers!  😄 

As for ending in failure, it's not over quite yet.  It depends on the ruling of the admins.

**Comment by pauby** [comment]
@teknowledgist thanks for persevering with this.

Given the difficulties with all the options it sounds like it must be embedded (as the installer is not available to download directly from the vendor)? If the installer is hosted by an unofficial site then, if I was moderating it, I'd not approve it.

Embedding the installer sounds like the best option. If you could get an agreement from the vendor that it's okay to do that then you can add that to the package along with the installer. However, it doesn't sound like that's what they want to do?

I would be happy to get involved here with the vendor to try and help from a Chocolatey standpoint if you think that would help?

**Comment by teknowledgist** [comment]
I just sent one last email thanking the developer for his patience.  I also said that if he won't make an exception to distributing NetTraffic in a Chocolatey package from the public repository, then I will inform the "community" that a NetTraffic package is not possible at this time.  

If he doesn't respond in the next week or he confirms that he won't make exceptions to the license, I think we have no choice but to close this issue and label it "can't implement".  Of course, if he reaches out and agrees at any time in the future, I am happy to build/push the package.

**Comment by teknowledgist** [comment]
Hi.  The developer writes:

> I'm thinking about establishing subdomain like cdn.venea.net from which direct download will be possible. Will subdomain with direct download URL solve Chocolatey moderators doubts? 

I would think it's OK, but I don't want to promise something I can't deliver.

**Comment by pauby** [comment]
@teknowledgist As this would be an official download location and as long as the moderator can verify it is official, this would be good.

Awesome work!

**Comment by pauby** [comment]
@teknowledgist Are we any further forward with this?

**Comment by teknowledgist** [comment]
I let the author know that we could work with an alternate download from his site (or a subdomain).  I also asked if it wouldn't just be easier to make an exception to the distribution rule.  Either way, I have not received any information in return.  

I'm trying to not be too annoying since *we* are asking *him* for something in which he clearly isn't all that interested, and we've already gone back and forth like a half-dozen times.

**Comment by pauby** [comment]
Awesome. Just keen to get this moving but it's all in somebody else's hands 😄

**Comment by teknowledgist** [comment]
From the developer:

> sorry for long reply time. I'm working on update with will be released within few days.

> I will establish subdomain providing direct download (approximately at beginning of march). License will remain unchanged. I will inform you when it will be done.

**Comment by pauby** [comment]
@teknowledgist Any update on this?

**Comment by teknowledgist** [comment]
I've queried the author a couple times now, but no response yet.

**Comment by pauby** [comment]
If we are getting no response from the author then I'm inclined to mark this as Invalid?

**Comment by teknowledgist** [comment]
Maybe.  Especially since there have been several releases since I last heard from them, so it's not like it's on ice for the pandemic.

I have to say that I don't get it.  The software is free (of charge), and anyone is free to copy/host it from anywhere.  Don't zip it up with metadata though!  Even if you ask politely, include the license and links to the home site, allow folks to verify identicality, and the end result is more people get to use/enjoy it.  

I wonder if it is a language thing.  English is clearly not the author's first language.  Based on the language credits, I would guess Hungarian or Polish in case there is anyone here who thinks they can explain/understand the thinking.

**Comment by pauby** [comment]
Any update on this?

**Comment by teknowledgist** [comment]
I've received no reply whatsoever despite several messages.  I'm happy to build/maintain the package if someone else can convince the author of any of:

1) to make a shift in his license statement.
2) to make an exception for a Chocolatey package.
3) to make an official download site that allows scripted downloads.

Unfortunately, until then, this package is not possible.

**Comment by AdmiringWorm** [comment]
@teknowledgist just to follow up, have you heard anything back from the author?

**Comment by teknowledgist** [comment]
I just sent one last email re-explaining Chocolatey, listing the options we have for this to work, and requesting an answer (one way or another) from the author.  I think if we don't get a response within a week or so we have to assume a NetTraffic Chocolatey package is not possible.

**Comment by pauby** [comment]
@teknowledgist I'm assuming there was no response?

**Comment by teknowledgist** [comment]
Not a peep.  

Given that the author was quite responsive back in January/February, that there does not appear to have been any activity on the site since April, and that the global pandemic has been raging through most of this, I'm grimly wondering if an answer is not possible.  

Either way, it does not appear a Chocolatey package is possible.

**Comment by pauby** [comment]
I'll mark this as 'Can't Implement' for the time being.

Thanks for all your work on the @teknowledgist !

**Comment by fds39** [comment]
Hi @pauby and @teknowledgist 
Maybe a very last hope with this message received 2 weeks ago at the end of this thread. Here is the copy of the mail I received
![screenshot_24](https://user-images.githubusercontent.com/40143934/97145725-f76ab280-1766-11eb-951c-1fcb50d454ac.jpg)

**Comment by teknowledgist** [comment]
Thanks @fds39 for poking the bear.  I guess I was being too polite.  😄 

Good news!  The CDN that should allow scripted downloads of NetTraffic is up.

I am working on completing the package.  It's not as simple as I had hoped though for several reasons, so it's taking a little longer.  I won't bore anyone with the details unless I get really stuck.

Soon.  There will be a NetTraffic package soon.

**Comment by fds39** [comment]
@teknowledgist you're just kiding me ;)
My message wasn't very polite at all, but yours was particularly elegant. But in the end, the average of our messages responded to a certain condescension of our interlocutor. Also my English is not very good :)

**Comment by teknowledgist** [comment]
I've pushed [the NetTraffic package](https://chocolatey.org/packages/nettraffic).  

Thanks for being patient.

**Comment by fds39** [comment]
@teknowledgist I'm not sure I understand what to expect from now on. 
I tested the installation but it doesn't seem to work. Forgive me for asking these awkward questions.
![screenshot_445](https://user-images.githubusercontent.com/40143934/98220961-57bfd800-1f4f-11eb-8dd8-4be2ec97b9a0.png)

**Comment by teknowledgist** [comment]
@fds39 The NetTraffic package has not yet been approved by the Chocolatey repository moderators, so you have to add the --version switch like this:

    choco install nettraffic -y --version 1.66.1 --params '"/autorun"'

Of course, you should only do that if you trust that the package won't do anything malicious.  😄 That's what the moderators are for: to check that the package is "safe" (generally).

The thread is closed because we believed that the author of NetTraffic was not interested in making necessary accommodations to allow for a Chocolatey package.  Coincidentally, after this was closed, he started replying again to my queries and we were able to get it done.

**Comment by fds39** [comment]
I come here to close our long thread to warmly thank the protagonists of this NetTraffic package. :pray::pray:
I just realized that the package has been approved by the moderators.

So thanks to @teknowledgist the package maintainer, @pauby, @AdmiringWorm and of course VENEA.NET for their authorization. May the latter forgive me for my momentary harshness. :worried:

Long live this great package :stuck_out_tongue_winking_eye:
