### ISSUE TITLE
RFP - weasis

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#744]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://nroduit.github.io/en/
Direct download URL for the software / installer : https://nroduit.github.io/en/getting-started/
Software summary / short description: dicom viewer

from the direct download link there are the wind32/64, linux and mac download link

**Comment by teknowledgist** [comment]
[Package submitted](https://chocolatey.org/packages/weasis)

**Comment by AdmiringWorm** [comment]
I see that the package have been approved. Closing this one.
