### ISSUE TITLE
RFP - Clipto Pro

### ISSUE THREAD

**Issue by andrizmitnick** [chocolatey-community/chocolatey-package-requests#745]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://github.com/clipto-pro/Desktop
https://clipto.pro
Direct download URL for the software / installer :
https://github.com/clipto-pro/Desktop/releases/download/v1.8.6/clipto.pro-1.8.6.exe
Software summary / short description:
Write easily and quickly on any device
Clipto Pro is an effortless, super fast and flexible notes taking app and clipboard manager.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/clipto-pro
- https://chocolatey.org/packages/clipto-pro.install

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/clipto-pro
- https://chocolatey.org/packages/clipto-pro.install

Can be closed.
