### ISSUE TITLE
RFP - Microsoft SQL Server 2019 Reporting Services

### ISSUE THREAD

**Issue by mkelley1972** [chocolatey-community/chocolatey-package-requests#747]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://www.microsoft.com/en-us/download/details.aspx?id=100122
Direct download URL for the software / installer :  https://www.microsoft.com/en-us/download/confirmation.aspx?id=100122
Software summary / short description:  2019 SQL Server Reporting Services is a server-based reporting platform that provides comprehensive reporting functionality.

**Comment by dgalbraith** [comment]
Package creation in progress.

**Comment by dgalbraith** [comment]
Package ready for review - https://chocolatey.org/packages/ssrs-2019/15.0.7243.37714

**Comment by dgalbraith** [comment]
Package has bee reviewwed and is now available - https://chocolatey.org/packages/ssrs-2019
