### ISSUE TITLE
RFP - ROCCAT Swarm

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#748]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://en.roccat.org/Support/Product/ROCCAT-Swarm
Direct download URL for the software / installer : https://en.roccat.org/software/ROCCAT-Swarm/roccat-swarm-v19361-v1.zip
Software summary / short description: Peripheral management and configuration utility for Roccat branded hardware. Supports most Roccat mice, keyboards, headsets, and mousepads,

**Comment by Cossey** [comment]
I've got this one, please assign to me. Cheers!

**Comment by pauby** [comment]
@Cossey Done. Please keep us updated on when this is submitted and approved.

**Comment by Cossey** [comment]
This might take a few days, as whoever creates/distributes this software is an idiot and distributes the installer exe inside of a zip file (which only reduces the file size by 800kB). Fortunately I've recorded the InstallShield .iss files needed to perform the silent install and uninstall of the software and in testing they appear to work fine. I have just been experimenting with the correct way to go about the install script.

**Comment by AdmiringWorm** [comment]
@Cossey please refrain from name-calling. Your comment have been edited to remove this.

**Comment by Cossey** [comment]
Package submitted [here](https://chocolatey.org/packages/roccatswarm).
Passed automated checks, ready for review.

**Comment by brogers5** [comment]
Package was approved yesterday. Should be clear to close this one out.

Thanks again @Cossey for stepping up!

**Comment by Cossey** [comment]
Package approved.

Package will be automatically maintained via my Package Update script at [github script link](https://github.com/Cossey/choco) running on docker in a server instance in the cloud.
