### ISSUE TITLE
RFP - WD Security for Windows

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#749]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://support.wdc.com/downloads.aspx?p=172
Direct download URL for the software / installer : https://downloads.wdc.com/wdapp/WDSecuritySetup_for_web_2.0.0.70.zip
Software summary / short description: 

The WD Security software implements password protection and the 256-bit hardware data encryption capabilities of your supported WD hard drive. Use the WD Security software to:

- Create a password to keep others from accessing the files on your drive
- Change your password
- Remove password protection
- Unlock your drive on any computer—whether the WD Security software is installed there or not

**Comment by mkevenaar** [comment]
I am willing to pick this one up.

**Comment by mkevenaar** [comment]
This package is submitted:
https://chocolatey.org/packages/wd-security

**Comment by mkevenaar** [comment]
Available for install.
