### ISSUE TITLE
RFP - WD SmartWare

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#750]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://support.wdc.com/downloads.aspx?p=259
Direct download URL for the software / installer : https://downloads.wdc.com/smartware/WD_SmartWare_Installer_2.4.21.1.zip
Software summary / short description: Backup software for WD external hard-drives.

**Comment by mkevenaar** [comment]
I am willing to pick this one up.

**Comment by mkevenaar** [comment]
Submitted: https://chocolatey.org/packages/wd-smartware

**Comment by brogers5** [comment]
Package has been approved. We should be clear to close this one out.
