### ISSUE TITLE
RFM - Linux Reader

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#752]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/linux-reader
Package source URL: https://github.com/TheCakeIsNaOH/chocolatey-packages/tree/master/Linux%20Reader 

There is no practical way to create an AU script for this package, and no way to get notification of updates. So I would be happy to hand this one over to someone.

**Comment by AdmiringWorm** [comment]
I can take over the maintenance for this package

@TheCakeIsNaOH would you mind adding me as a maintainer for the package?

**Comment by dgalbraith** [comment]
While not optimal from a bandwidth usage perspective it is possible to automate here in the absence of version informaiton on the package source download pages.  The version can be determined from the file meta-data eg.

`(Get-Item '.\Linux_Reader.exe').VersionInfo.FileVersion`

**Comment by AdmiringWorm** [comment]
@dgalbraith usually pretty easy to get the necessary information (even in the case where a file must be downloaded), and still not needing to download the file on every update run.

I have done that on a few packages I already maintain, and will be using that method on this one as well.

**Comment by TheCakeIsNaOH** [comment]
@AdmiringWorm Request sent, thanks.

Just so you know, they the version at https://www.diskinternals.com/linux-reader lies, as they do not update the page on minor version changes.

**Comment by AdmiringWorm** [comment]
@TheCakeIsNaOH I just found out. Still not a problem though. But thanks for letting me know

**Comment by AdmiringWorm** [comment]
A new version have been pushed (and also is automatically updated 😃)

**Comment by AdmiringWorm** [comment]
New version have been approved
