### ISSUE TITLE
RFM: winaero-tweaker

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-package-requests#753]
## Current Maintainer

- [x ] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [X ] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/winaero-tweaker
Package source URL: available on the package page on chocolatey.org

**Comment by dgalbraith** [comment]
I would be happy to pick this up

**Comment by bcurran3** [comment]
Let me know your Chocolatey account.

**Comment by dgalbraith** [comment]
Chocolatey account is [dgalbraith](https://www.chocolatey.org/profiles/dgalbraith)

**Comment by bcurran3** [comment]
Excellent.
I just sent you the maintainer request.
