### ISSUE TITLE
RFP - Microsoft Edge Stable

### ISSUE THREAD

**Issue by karlhorky** [chocolatey-community/chocolatey-package-requests#755]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.microsoft.com/en-us/edge
Direct download URL for the software / installer : https://c2rsetup.officeapps.live.com/c2r/downloadEdge.aspx?ProductreleaseID=Edge&platform=Default&version=Edge&source=EdgeStablePage&Channel=Stable&language=en
Software summary / short description: web browser

Related (request for Microsoft Edge Insider edition): #648
Related (existing Edge Insider package): https://github.com/ionred/chocolatey-packages/tree/master/automatic/microsoft-edge-insider

cc @ionred

**Comment by pauby** [comment]
Is this not [this package](https://chocolatey.org/packages/microsoft-edge)?

**Comment by karlhorky** [comment]
Ah, this wasn't there when I submitted. Looks like a package was added for this in the meantime! Thanks for the heads up. Closing this issue.
