### ISSUE TITLE
RFP - keepass2-haveibeenpwned

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#756]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/andrew-schofield/keepass2-haveibeenpwned
Direct download URL for the software / installer : https://github.com/andrew-schofield/keepass2-haveibeenpwned/releases/download/v1.3.6/HaveIBeenPwned.plgx
Software summary / short description: Plugin for KeePass 2 to enable checking password database entries against known breach lists and report compromised credentials. Supports searches based on site/domains, usernames, and password hashes.

 ## Package Expectations
- Has a dependency on [keepass](https://chocolatey.org/packages/keepass).
- Binary should be deployed to KeePass's Plugins directory.
- I would recommend naming the package "keepass-plugin-haveibeenpwned" or something similar to follow the naming convention adopted by most of the other plugin packages.

**Comment by pauby** [comment]
I already maintain Keepass so I'll pick this up too.

**Comment by boubou** [comment]
Hi,
Do you have an ETA for that plugin ?
Thanks.

**Comment by pauby** [comment]
This has been pushed at https://chocolatey.org/packages/keepass-plugin-haveibeenpwned

**Comment by brogers5** [comment]
Package has been approved as of July 21st. Should be clear to close this one out.
