### ISSUE TITLE
RFP - KeePass RuleBuilder

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#757]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ihanson/KeePass-Rule-Builder
Direct download URL for the software / installer : https://github.com/ihanson/KeePass-Rule-Builder/releases/download/v1.0/RuleBuilder.dll
Software summary / short description: Plugin for KeePass 2 to track and simplify password generation with password policy rules (e.g. maximum password lengths, character set requirements, character exclusions, etc.) customized on a site-by-site basis.

 ## Package Expectations
- Has a dependency on [keepass](https://chocolatey.org/packages/keepass).
- DLL should be deployed to KeePass's Plugins directory.
- I would recommend naming the package "keepass-plugin-rulebuilder" or something similar to follow the naming convention adopted by most of the other plugin packages.

**Comment by pauby** [comment]
As I already maintain Keepass I'll pick this up.

**Comment by pauby** [comment]
This has been pushed at https://chocolatey.org/packages/keepass-plugin-rulebuilder

**Comment by brogers5** [comment]
Package has been approved as of July 26th. Should be clear to close this one out.
