### ISSUE TITLE
RFP - TextExpander for Windows

### ISSUE THREAD

**Issue by localhorst** [chocolatey-community/chocolatey-package-requests#759]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://textexpander.com/download/
Direct download URL for the software / installer: https://textexpander.com/cgi-bin/redirect.pl?cmd=download&platform=windows
Software summary / short description: TextExpander lets you instantly insert snippets of text from a repository of emails, boilerplate and other content, as you type – using a quick search or abbreviation.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/textexpander
