### ISSUE TITLE
RFP - Microsoft SQL Server Compact 4.0

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#761]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.microsoft.com/en-in/download/details.aspx?id=17876
Direct download URL for the software / installer : 
32 bit: https://download.microsoft.com/download/0/5/D/05DCCDB5-57E0-4314-A016-874F228A8FAD/SSCERuntime_x86-ENU.exe
64 bit: https://download.microsoft.com/download/0/5/D/05DCCDB5-57E0-4314-A016-874F228A8FAD/SSCERuntime_x64-ENU.exe
Software summary / short description: Microsoft SQL Server Compact 4.0 is a free, embedded database that software developers can use for building ASP.NET websites and Windows desktop applications. SQL Server Compact 4.0 has a small footprint and supports private deployment of its binaries within the application folder, easy application development in Visual Studio and WebMatrix, and seamless migration of schema and data to SQL Server.

**Comment by dgalbraith** [comment]
I will pick ths one up for packaging.

**Comment by AdmiringWorm** [comment]
@dgalbraith any update on this?

**Comment by AdmiringWorm** [comment]
@dgalbraith Do you have any update on this request?
If there is no update within the next 7 days I will move this request back to being available to new maintainers.

**Comment by dgalbraith** [comment]
@AdmiringWorm packaging is in flight.  The base package is done but I have gone done a bit of a rabbit hole with i18n and hit some issues.  Will review this weekend and look to either progress or pull out the i18n and address separately later.

**Comment by pauby** [comment]
@dgalbraith Any update on this?

**Comment by dgalbraith** [comment]
[SQL Server Compact 4.0 package](https://www.chocolatey.org/packages/mssqlserver-compact4.0/4.0.8876.1) has been pushed and is waiting for moderation.

**Comment by dgalbraith** [comment]
Moderation is complete and the [SQL Server Compact 4.0 package](https://www.chocolatey.org/packages/mssqlserver-compact4.0/4.0.8876.1) is now available.
