### ISSUE TITLE
RFP - gh

### ISSUE THREAD

**Issue by karlhorky** [chocolatey-community/chocolatey-package-requests#763]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://cli.github.com/
Direct download URL for the software / installer: https://github.com/cli/cli/releases/download/v0.5.4/gh_0.5.4_windows_amd64.zip
Software summary / short description: `gh` brings the GitHub experience right to your terminal

---

Description: New February 2020 GitHub CLI "gh"

**Comment by karlhorky** [comment]
This CLI supersedes the `hub` package maintained by @pauby:

https://chocolatey.org/packages/hub

**Comment by pauby** [comment]
It does. Which is why I'll pick it up! 😄

**Comment by pauby** [comment]
I've just pushed 0.5.5 of this just now. Once it's approved I'll deprecate `hub`.

**Comment by karlhorky** [comment]
Thanks @pauby!

**Comment by karlhorky** [comment]
Ah, just reading over the `hub` documentation, and I can't find anything that says it's deprecated or mentions `gh`...

And also in the new docs, they are seemingly talking about it as if `hub` will live on, in parallel:

> ## Comparison with `hub`
> 
> For many years, `hub` was the unofficial GitHub CLI tool. `gh` is a new project for us to explore what an official GitHub CLI tool can look like with a fundamentally different design. While both tools bring GitHub to the terminal, `hub` behaves as a proxy to `git` and `gh` is a standalone tool.

Ref: https://github.com/cli/cli#comparison-with-hub

**Comment by karlhorky** [comment]
So maybe `hub` shouldn't be deprecated after all?

**Comment by pauby** [comment]
@karlhorky That is a valid point - I would _assume_ that once gh is out of beta then they would look to deprecate hub themselves but maybe doing so at this point would be premature. 

So yeah, lets leave hub as it for the time being (unless somebody knows anything we don't).
