### ISSUE TITLE
RFM - Screenpresso

### ISSUE THREAD

**Issue by brutaldev** [chocolatey-community/chocolatey-package-requests#765]
## Current Maintainer

- [X] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/screenpresso
Package source URL: https://github.com/brutaldev/chocolatey-packages/tree/master/Screenpresso

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/automatic/screenpresso

**Comment by brutaldev** [comment]
@chtof Added you as a maintainer.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/screenpresso

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/screenpresso/1.7.16

Can be closed.
