### ISSUE TITLE
RFM - MusicBee

### ISSUE THREAD

**Issue by brutaldev** [chocolatey-community/chocolatey-package-requests#766]
## Current Maintainer

- [X] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/musicbee
Package source URL: https://github.com/brutaldev/chocolatey-packages/tree/master/MusicBee

**Comment by boubou** [comment]
Hi,
It looks like there is a new version since today.
3.3.7367
Released on March 11, 2020
For Win7/ Win8/ Win10
Please add me as a maintainer then I will update it and maintain it in futur.
Thanks.

**Comment by brutaldev** [comment]
@boubou I've added your username (boubou) as a maintainer for the package.
For automation you can check the [XML file](https://github.com/brutaldev/chocolatey-packages/blob/master/MusicBee/musicbee.xml) I used with Ketarin.

**Comment by boubou** [comment]
Im sorry, I didnt see your message.
Package Maintainer(s):
werner
I didnt receive an email that you added me as a maintainer.
Thanks.

**Comment by brutaldev** [comment]
Hi @boubou 

It's been stuck on "pending approval" for quite some time, should I remove and re-add?

![image](https://user-images.githubusercontent.com/1929531/77652440-e3639600-6f76-11ea-9867-60acbac5a5b2.png)

**Comment by pauby** [comment]
As thwre has been no update in a month I'm going to open this up to other maintainers.

**Comment by mkevenaar** [comment]
I’ll pick this up.

**Comment by mkevenaar** [comment]
New version up and running.
