### ISSUE TITLE
RFM - MediaInfo

### ISSUE THREAD

**Issue by brutaldev** [chocolatey-community/chocolatey-package-requests#767]
## Current Maintainer

- [X] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/mediainfo
Package source URL: https://github.com/brutaldev/chocolatey-packages/tree/master/MediaInfo

**Comment by mkevenaar** [comment]
I am willing to maintain this one? Could you please add me as a maintainer? username mkevenaar

**Comment by brutaldev** [comment]
Thanks, added you as a maintainer.

**Comment by mkevenaar** [comment]
A new version of this package has been pushed. This package is now an embedded package.

**Comment by mkevenaar** [comment]
Hi, a new, embedded version, is now published
