### ISSUE TITLE
RFP - DeepL

### ISSUE THREAD

**Issue by dallyingllama** [chocolatey-community/chocolatey-package-requests#768]
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

_Software project URL_ : https://www.deepl.com/home
_Direct download URL for the software / installer_ : https://www.deepl.com/windows/download/full/DeepLSetup.exe
_Software summary / short description_: This is a very good machine translator for translation between many European languages.

When installing via the .exe it makes an icon on the desktop, and some sort of service in the tray. During installation there is a pop-up to tell you the short cut keys for triggering the tool to pop up so you can translate. Maybe it is possible to silence this and instead log in the screen output to inform the installed that they can use those keys to trigger the app.

**Comment by chtof** [comment]
https://www.deepl.com/windows/download/full/DeepLSetup.exe is redirected to https://appdownload.deepl.com/windows/full/DeepLSetup.exe

https://appdownload.deepl.com/windows/full/DeepLSetup.exe downloads DeepLSetup.exe as "content-type: **text/plain**' according "response headers" but the file is really a binary as I can correctly launch manually the downloaded file D:\Temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe

In D:\Temp\chocolatey_cache\deepl\1.11.0\, there is also another file "DeepLSetup.exe.istext"
and Chocolatey sends an error when an executable is a text file (cf. https://github.com/chocolatey/choco/commit/d7b4de5b469ca9a9623167fb5eb68e25f603cdf2).

So, I don't know how to handle this...
Some logs:

> https://appdownload.deepl.com/windows/full/DeepLSetup.exe 
> {
> Connection: keep-alive
> Accept-Ranges: bytes
> Content-Length: 145224280
> Content-Type: text/plain
> Date: Mon, 02 Mar 2020 19:05:20 GMT
> ETag: "5e43aceb-8a7f258"
> Last-Modified: Wed, 12 Feb 2020 07:44:43 GMT
> Server: nginx
> }.
> System.Net Information: 0 : [16172] ConnectStream#28555771::ConnectStream(Buffered 145224280 bytes.)
> System.Net Information: 0 : [16172] Associating HttpWebRequest#41950770 with ConnectStream#28555771
> System.Net Information: 0 : [16172] Associating HttpWebRequest#41950770 with HttpWebResponse#24191173
> _**WARNING: D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe is of content type text/plain**_
> System.Net Information: 0 : [16172] ContentLength=145224280
> Downloading https://appdownload.deepl.com/windows/full/DeepLSetup.exe to D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe
> Progress: 100% - Completed download of D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe (138.5 MB).
> Download of DeepLSetup.exe (138.5 MB) completed.
> No runtime virus checking built into FOSS Chocolatey. Check out Pro/Business - https://chocolatey.org/compare
> Verifying package provided checksum of '1498BFCA4361B90D9F7F0345A5E0981B257270CC2D52761B4D3464FE22F8C6F4' for 'D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe'.
> Running Get-ChecksumValid -file 'D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe' -checksum '1498BFCA4361B90D9F7F0345A5E0981B257270CC2D52761B4D3464FE22F8C6F4' -checksumType 'sha256' -originalUrl 'https://appdownload.deepl.com/windows/full/DeepLSetup.exe'
> checksum.exe found at 'C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe'
> Executing command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="1498BFCA4361B90D9F7F0345A5E0981B257270CC2D52761B4D3464FE22F8C6F4" -t="sha256" -f="D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe"]
> Hashes match.
> Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="1498BFCA4361B90D9F7F0345A5E0981B257270CC2D52761B4D3464FE22F8C6F4" -t="sha256" -f="D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe"] exited with '0'.
> Running Install-ChocolateyInstallPackage -packageName 'deepl' -fileType 'exe' -silentArgs '/s' -file 'D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe' -validExitCodes '0' -useOnlyPackageSilentArguments 'False'
> Running Get-ProcessorBits -compare '32'
> Installing deepl...
> Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'D:\temp\chocolatey_cache\deepl\1.11.0' -statements '/s ' -exeToRun 'D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe'
> Unable to use current location for Working Directory. Using Cache Location instead.
> Test-ProcessAdminRights: returning True
> Elevating permissions and running ["D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe" /s ]. This may take a while, depending on the statements.
> _**ERROR: The file was a text file but is attempting to be run as an executable - 'D:\temp\chocolatey_cache\deepl\1.11.0\DeepLSetup.exe'**_
>  at Start-ChocolateyProcessAsAdmin, C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1: line 198
> at Install-ChocolateyInstallPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyInstallPackage.ps1: line 335
> at Install-ChocolateyPackage, C:\ProgramData\chocolatey\helpers\functions\Install-ChocolateyPackage.ps1: line 408
> at <ScriptBlock>, C:\ProgramData\chocolatey\lib\deepl\tools\chocolateyinstall.ps1: line 13
> at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 49
> at <ScriptBlock>, <No file>: line 1
> Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\deepl\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '4'.
> Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
>

**Comment by pauby** [comment]
@chtof Have you contacted the author to let them know their website is broken? If they fix it everything should work?

**Comment by chtof** [comment]
@pauby I haven't contacted the author as it works properly outside Chocolatey.

**Comment by pauby** [comment]
Can I suggest you raise an issue on [chocolatey\choco](https://github.com/chocolatey/choco/issues)?

**Comment by pauby** [comment]
@chtof Did you raise an issue for this?

**Comment by tunisiano187** [comment]
I have a working package for this, just need to download the file and install from local

**Comment by tunisiano187** [comment]
Pushed, should be OK

**Comment by tunisiano187** [comment]
https://chocolatey.org/packages/deepl/1.11.0.1

**Comment by tunisiano187** [comment]
Can you assign it to me ? to ease the followup.
Thank you

**Comment by tunisiano187** [comment]
This package as been approved, you can close this issues.
Thank you
