### ISSUE TITLE
RFP - RealVNC Server

### ISSUE THREAD

**Issue by procdaddy11** [chocolatey-community/chocolatey-package-requests#769]
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.realvnc.com/en/connect/download/vnc/
Direct download URL for the software / installer : https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.7.1-Windows-msi.zip
Software summary / short description: Popular VNC Server

**Comment by AdmiringWorm** [comment]
@procdaddy11 is this the package that you are looking for? https://chocolatey.org/packages/vnc-connect

While it is called vnc connect, it seems it installs the realvnc server.

**Comment by procdaddy11** [comment]
VNC Connect is no longer maintained to my knowledge as it’s still called that but has been split into two packages (server/viewer). Does this mean that the VNC Connect maintainer needs to update their installer?

**Comment by AdmiringWorm** [comment]
The maintainer of the vnc-connect package have split out a new package for the viewer, and is using the server in the vnc-connect package.

It should probably be deprecated and split out to a new package with the correct name.
In all though, you would still need to contact the maintainer of that package (can be done through the package page) to make that happen.

**Comment by pauby** [comment]
@procdaddy11 @AdmiringWorm Can we close this?

**Comment by procdaddy11** [comment]
Yes
