### ISSUE TITLE
RFM - Lammer Context Menu

### ISSUE THREAD

**Issue by brutaldev** [chocolatey-community/chocolatey-package-requests#770]
## Current Maintainer

- [X] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/lammercontextmenu
Package source URL: https://github.com/brutaldev/chocolatey-packages/tree/master/LammerContextMenu

Package is currently not passing verification which I suspect is due to the fact that the latest installer is not completely silent or has a dependency not available on the new server-based testing instances (such as .NET 4.x).

**Comment by pauby** [comment]
@brutaldev Are you listing this package for a new maintainer purely because you cannot get it through testing?

**Comment by brutaldev** [comment]
@pauby No, I have no time to maintain any packages other than my own software so I'm handing ll of them over to whoever wants to look after them. I've submitted quite a few packages here to find new maintainers. Was just providing additional information for the potential maintainer(s) to be aware of.

**Comment by pauby** [comment]
@brutaldev Thanks for clarifying that.

**Comment by chtof** [comment]
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Corrected package with .Net 3.5 as dependency is ready to be submitted: https://github.com/chtof/chocolatey-packages/tree/master/manual/lammercontextmenu

**Comment by brutaldev** [comment]
@chtof Added you as a maintainer.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/lammercontextmenu/1.3.0.1901

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/lammercontextmenu/1.0.3.1901

Can be closed.
