### ISSUE TITLE
RFP - ffmpeg-batch

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#771]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://sourceforge.net/projects/ffmpeg-batch/
Direct download URL for the software / installer : https://sourceforge.net/projects/ffmpeg-batch/files/latest/download
Software summary / short description: It is a GUI for batch processing audio/video using ffmpeg commands.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/ffmpeg-batch
- https://chocolatey.org/packages/ffmpeg-batch.install
- https://chocolatey.org/packages/ffmpeg-batch.portable

**Comment by opusforlife2** [comment]
Off-topic:
@abejenaru Please update fre:ac to the new stable version.

**Comment by AdmiringWorm** [comment]
I see that the packages have been approved, as such I am closing this issue and marking it as published.
