### ISSUE TITLE
RFP - arduino-cli

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#772]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://github.com/arduino/arduino-cli
Direct download URL for the software / installer : https://arduino.github.io/arduino-cli/installation/#use-the-install-script
Software summary / short description: arduino command line interface

**Comment by jtcmedia** [comment]
Package submitted: [https://chocolatey.org/packages/arduino-cli/0.9.0](https://chocolatey.org/packages/arduino-cli/0.9.0)
