### ISSUE TITLE
RFP - avrdude

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#773]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://savannah.nongnu.org/projects/avrdude
Direct download URL for the software / installer: from here there are all the downloads (http://download.savannah.gnu.org/releases/avrdude/) i think this would be the most appropriate (http://download.savannah.gnu.org/releases/avrdude/avrdude-6.3-mingw32.zip)
Software summary / short description: utility to play with avr mcu

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/avrdude
