### ISSUE TITLE
RFM - gMKVExtractGUI

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#774]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gmkvextractgui
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/gmkvextractgui

**Comment by boubou** [comment]
I will keep it!
Please add me as a maintainer and I will maintain it with pleasure!
Thanks.
Seb

**Comment by abejenaru** [comment]
Thanks so much Seb, that's wonderful!

**Comment by boubou** [comment]
Did you add me as a maintainer on your package ?
Please add boubou as a maintainer.
Thanks Abejenaru!

**Comment by abejenaru** [comment]
> Did you add me as a maintainer on your package ?
> Please add boubou as a maintainer.
> Thanks Abejenaru!

Yes I did!
It also looks like you have to confirm being a Maintainer somewhere on the package page: https://chocolatey.org/packages/gmkvextractgui/
Many thanks!

**Comment by abejenaru** [comment]
@boubou can you check your email (spam folder as well) for emails from chocolatey.org.
You will need to click on the confirmation link in that email to accept being added as a maintainer.

**Comment by boubou** [comment]
Ok, sorry for the delay.
I will check it when I will be back at home.

**Comment by abejenaru** [comment]
For this package as well, I have re-added you as a maintainer, hopefully that will trigger the confirmation email!
Thank you for your interest!

**Comment by pauby** [comment]
Any update on this?

**Comment by AdmiringWorm** [comment]
Moving back to available for maintainers due to lack of response.

**Comment by tunisiano187** [comment]
@AdmiringWorm the package is up-to-date, now maintained by @boubou 
So this issue can be closed.

Thank you

**Comment by abejenaru** [comment]
> @AdmiringWorm the package is up-to-date, now maintained by @boubou
> So this issue can be closed.
> 
> Thank you

I confirm, I'm not the maintainer anymore. Thanks!
