### ISSUE TITLE
RFM - freac

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#775]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/freac
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/freac

**Comment by pauby** [comment]
@abejenaru Can you please raise one issue per package. I agree it makes sense for the same maintainer to pick up both but it is not required.

**Comment by abejenaru** [comment]
> @abejenaru Can you please raise one issue per package. I agree it makes sense for the same maintainer to pick up both but it is not required.

Even if I'm not really maintaining the .portable version ?  I haven't update it in ~ 3 years.

**Comment by pauby** [comment]
Yes please.

**Comment by abejenaru** [comment]
> Yes please.

done!

**Comment by boubou** [comment]
I will keep it!
Please add me as a maintainer and I will maintain it with pleasure!
Thanks.
Seb

**Comment by abejenaru** [comment]
Thank you Seb, that is really wonderful!

**Comment by boubou** [comment]
Did you add me as a maintainer on your package ?
Please add boubou as a maintainer.
Thanks Abejenaru!

**Comment by abejenaru** [comment]
> Did you add me as a maintainer on your package ?
> Please add boubou as a maintainer.
> Thanks Abejenaru!

I did! Please check the package page for confirmation.
Thanks!

**Comment by opusforlife2** [comment]
@boubou The package page still lists @abejenaru as the sole maintainer.

**Comment by mkevenaar** [comment]
Let's keep this issue open until an updated version of the package is published. I am leaving this one open for other maintainers to pick up.

**Comment by AdmiringWorm** [comment]
@boubou remember to check your email spam folder for emails from chocolatey.org.
Sometimes the emails appear there instead of in your inbox.

You will need to click on the confirmation link in that email to accept being added as a maintainer.

**Comment by boubou** [comment]
Im sorry, I just saw it!

**Comment by boubou** [comment]
I pushed an update 2 days ago!
