### ISSUE TITLE
RFM - freac.portable

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#776]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/freac.portable
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/freac.portable

**Comment by boubou** [comment]
I will keep it!
Please add me as a maintainer and I will maintain it with pleasure!
Thanks.
Seb

**Comment by abejenaru** [comment]
Wonderful, thank you!

**Comment by boubou** [comment]
Did you add me as a maintainer on your package ?
Please add boubou as a maintainer.
Thanks Abejenaru!

**Comment by abejenaru** [comment]
> Did you add me as a maintainer on your package ?
> Please add boubou as a maintainer.
> Thanks Abejenaru!

I did! Please check the package page, I think you must confirm the change.
Thanks!

**Comment by abejenaru** [comment]
@boubou can you check your email (spam folder as well) for emails from chocolatey.org.
You will need to click on the confirmation link in that email to accept being added as a maintainer.

**Comment by boubou** [comment]
Hi
I checked my spam folder and I didn't find anything.
Can you send me it please ?

**Comment by boubou** [comment]
Hi,
I message you and I asked you to add me as a maintainer then I will keep it up to date.
I checked my spam folder but I didn't find your email.
Please resend me the email!
Thanks in advance!

**Comment by abejenaru** [comment]
I have re-added you as a maintainer, hopefully that will trigger the confirmation email!
Thank you for your interest!

**Comment by pauby** [comment]
Any update on this?

**Comment by AdmiringWorm** [comment]
Moving back to available for maintainers due to lack of response.

**Comment by tunisiano187** [comment]
it's been pushed by boubou, so you can assign him, and maybe close

**Comment by AdmiringWorm** [comment]
@tunisiano187 considering that he had not responded on any of the issues that he had been assigned to, I am inclined to consider him unresponsive, and personally would like someone else to pick up the package due to this.

@pauby what are your thoughts on this?

**Comment by tunisiano187** [comment]
OK, depending on the decision, i can take it if you want.
Thank you

**Comment by pauby** [comment]
@AdmiringWorm As we both agree, I'll just assign this to @tunisiano187 just now.

**Comment by tunisiano187** [comment]
OK, so i assume i'll need to ask via admins form too ?

**Comment by AdmiringWorm** [comment]
@tunisiano187 yes that is correct.

**Comment by opusforlife2** [comment]
A newer version (1.1.3) was successfully published 2 weeks later. freac was published a few days earlier than that.

**Comment by tunisiano187** [comment]
I've pushed the update.
in case you have another request about this package, you can ask directly on my git at : https://github.com/tunisiano187/Chocolatey-packages/issues
@AdmiringWorm you can close this issue.
Thank you

**Comment by opusforlife2** [comment]
@tunisiano187 That's what I meant. That this issue could be closed successfully.
