### ISSUE TITLE
RFP - NoSQL Workbench for Amazon DynamoDB

### ISSUE THREAD

**Issue by JohannesKonings** [chocolatey-community/chocolatey-package-requests#777]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/workbench.html

Direct download URL for the software / installer : https://nosql-workbench-for-amazon-dynamodb.s3.amazonaws.com/NoSQL+Workbench+for+Amazon+DynamoDB-win-1.0.0.exe

Software summary / short description: NoSQL Workbench for Amazon DynamoDB is a cross-platform client-side application for modern database development and operations and is available for Windows and macOS. NoSQL Workbench is a unified visual tool that provides data modeling, data visualization, and query development features to help you design, create, query, and manage DynamoDB tables.

**Comment by jtcmedia** [comment]
Package pushed: [https://chocolatey.org/packages/nosql-workbench/](https://chocolatey.org/packages/nosql-workbench/)
