### ISSUE TITLE
RFP - SALOME

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#778]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.salome-platform.org/
Direct download URL for the software / installer : https://www.salome-platform.org/downloads/current-version/DownloadDistr?platform=SP.W10&version=9.4.0
Software summary / short description: SALOME is an open-source software that provides a generic Pre- and Post-Processing platform for numerical simulation.

**Comment by Foadsf** [comment]
Dear @pauby , it is SALOME actually.

**Comment by pauby** [comment]
@Foadsf I saw this and changed it:

![image](https://user-images.githubusercontent.com/12760779/76433267-01909a00-63ac-11ea-9a9f-06ab3f1e7615.png)

I'll change it back.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/salome

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/salome

Can be closed.
