### ISSUE TITLE
RFP - Check Point Endpoint Security VPN

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#779]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.checkpoint.com/products/remote-access-vpn/
Direct download URL for the software / installer : http://dl3.checkpoint.com/paid/18/18608e05b30b4a5b2545bf61a2f9c373/E82.40_CheckPointVPN.msi?HashKey=1584123725_510de208639c1d01b91f39645c6f8bbb&xtn=.msi
Software summary / short description: Desktop remote access client for Check Point VPN endpoints.

## Package Expectations
The installation wizard should support the installation of 3 different products (Endpoint Security VPN, Check Point Mobile, and SecuRemote). The package should be installing Endpoint Security VPN (this should be the default selection in the GUI).

**Comment by pauby** [comment]
@brogers5 That download URL appears to be locked behind a login?

![image](https://user-images.githubusercontent.com/12760779/76655314-e917af80-6564-11ea-9511-db1d14f4233d.png)

**Comment by brogers5** [comment]
@pauby, I grabbed the URL from this page:
https://supportcenter.checkpoint.com/supportcenter/portal/role/supportcenterUser/page/default.psml/media-type/html?action=portlets.DCFileAction&eventSubmit_doGetdcdetails=&fileid=103038

Relevant link should be the first download button. In particular, I noticed the HashKey param seems to change every time the page is accessed. So it appears the URL isn't static as I previously believed, which might a problem...

**Comment by pauby** [comment]
That is going to be a problem and almost impossible to automate any updates for.

**Comment by brogers5** [comment]
I looked around and couldn't find a static URL that is publicly exposed. I've reached out to their support to see if they'd be willing to assist, will update if/when I hear back.

**Comment by pauby** [comment]
@brogers5 Any update on this from support?

**Comment by brogers5** [comment]
Nope, never heard back from them.
