### ISSUE TITLE
RFP - Waterfox Classic

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-package-requests#780]
A package for Waterfox Classic (half way down https://www.waterfox.net/download/)

There already exists a package for Waterfox Current.

**Comment by mkevenaar** [comment]
@mstick99 would you please go back and create an issue using the template?

**Comment by pauby** [comment]
@mstick99 Is there a reason you've closed this? Is the package is still needed?

**Comment by mstick99** [comment]
Closed RFP and put in as an Issue as requested.

**Comment by pauby** [comment]
I'm a little confused. Nobody requested you to close this RFP. Where did you 'put it in as an Issue'?

**Comment by mstick99** [comment]
Received this request:
 

Maurice Kevenaar <notifications@github.com> | Maurice Kevenaar <notifications@github.com> | Mar 17, 2020, 5:54 AM (1 day ago)
mstick99 would you please go back and create an issue using the template?

So closed the RFP and input an Issue at http://github.com/chocolatey-community/chocolatey-coreteampackages/issues

**Comment by mkevenaar** [comment]
@mstick99 I updated the comment asking you to update your issue.
