### ISSUE TITLE
RFP - beets

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#781]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/beetbox/beets, https://beets.io/
Direct download URL for the software / installer : https://github.com/beetbox/beets/releases
Software summary / short description: It is a music library manager, for organising and tagging music.

**Comment by pauby** [comment]
There is no Windows binary for this. Instead it's install via `pip` (at least that is what the homepage says).

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/beets

**Comment by opusforlife2** [comment]
It's been approved.
