### ISSUE TITLE
RFP - Winja

### ISSUE THREAD

**Issue by shvchk** [chocolatey-community/chocolatey-package-requests#782]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.phrozen.io/projects/2020/03/winja-virustotal-uploader-binary/
Direct download URL for the software / installer : https://www.phrozen.io/bin/winja7-1.zip
Software summary / short description: Winja is a free VirusTotal Uploader that lets you find potential malware on your system. It uses the scanning engine of virtually all antivirus products in the market to give you a very precise idea of the risk posed by a particular file.

To do this, Winja first uses the VirusTotal public API to submit the fingerprint of a file. If this fingerprint exists, Winja returns the existing analysis report. If not (with your previously set permission), Winja sends the unknown file to VirusTotal servers for scanning. It is also possible for you to have files (called samples) analyzed again at any time to update the detection ratio.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/winja
- https://chocolatey.org/packages/winja.install
- https://chocolatey.org/packages/winja.portable
