### ISSUE TITLE
RFP - iA Writer

### ISSUE THREAD

**Issue by cqiy297** [chocolatey-community/chocolatey-package-requests#783]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://ia.net/writer
Direct download URL for the software / installer : https://ia.net/writer/windows/trial/download
Software summary / short description: iA Writer is a text editor developed by the design company, Information Architects (iA).  iA states that the purpose is "to keep you focused on just writing". 

The installer provides a 30-day trial that can be unlocked with license key.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/iawriter
