### ISSUE TITLE
RFM -  Software Ideas Modeler

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#786]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/software-ideas-modeler
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/software-ideas-modeler

**Comment by boubou** [comment]
Please add boubou as a maintainer.
Thanks Abejenaru!

**Comment by abejenaru** [comment]
> Please add boubou as a maintainer.
> Thanks Abejenaru!

Done! You still have to confirm it, probably on the package page: https://chocolatey.org/packages/software-ideas-modeler.
Thank you so much!
