### ISSUE TITLE
RFM - nteract

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#787]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/nteract
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/nteract

**Comment by boubou** [comment]
Hi,
I message you and I asked you to add me as a maintainer then I will keep it up to date.
I checked my spam folder but I didn't find your email.
Please resend me the email!
Thanks in advance!

**Comment by abejenaru** [comment]
I have re-added you as a maintainer, hopefully that will trigger the confirmation email!
Thank you for your interest!

**Comment by pauby** [comment]
@boubou Any update on this?

**Comment by AdmiringWorm** [comment]
Moving back to available for maintainers due to lack of response.

**Comment by tunisiano187** [comment]
I'll take it
I'm seding the message via the admins form.

**Comment by AdmiringWorm** [comment]
@tunisiano187 any update on this request?

**Comment by tunisiano187** [comment]
It's done sorry.
Thank you
