### ISSUE TITLE
RFM - nteract (Install)

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#788]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/nteract.install
Package source URL: https://github.com/abejenaru/chocolatey-packages/tree/master/automatic/nteract.install

**Comment by tunisiano187** [comment]
@abejenaru 
Hello, i'll pick this up to join with the meta.
Can you add me as maintainer? tunisiano

Thank you

**Comment by abejenaru** [comment]
Done! Thanks for your interest @tunisiano187 ! 
PS. I've also added you to the .portable version, hope it's not a problem!

**Comment by AdmiringWorm** [comment]
@tunisiano187 you may want to hit up @boubou as well, as it seems he is maintaining a meta-package (but as a full-blown package instead) for nteract (https://chocolatey.org/packages/nteract).

**Comment by tunisiano187** [comment]
Yes, I'll talk with him to check.
Thanks
