### ISSUE TITLE
RFP - Xtreme Download Manager (xdm)

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#789]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/subhra74/xdm
Direct download URL for the software / installer : https://github.com/subhra74/xdm/releases
Software summary / short description: A download manager.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/xdm
