### ISSUE TITLE
RFP - SteelSeries Engine

### ISSUE THREAD

**Issue by Nischi85** [chocolatey-community/chocolatey-package-requests#790]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://steelseries.com/engine/
Direct download URL for the software / installer : https://engine.steelseriescdn.com/SteelSeriesEngine3.17.6Setup.exe
Software summary / short description: One application for all your settings 
Engine was designed to have a low impact on your gaming rig while handling all of your important gaming settings.

Automatic game configurations 
User configurations like the Rival 710's OLED display can change based on which game you're playing. 

Illumination, macros, binds and more
Customize illumination settings on your Arctis 5, or set up advanced macros and binds for your Apex M750 or Apex M750 TKL keyboard.

Tactile alerts
Use Engine to customize the vibration patterns, duration, intensity, and triggers for your Rival 500 or Rival 710.

Settings across platforms
SteelSeries CloudSync lets you backup, share and sync your settings across all your platforms. Create a SteelSeries ID, login, and send your data to the cloud.

Gamesense
Use in-game events like ammo, health, and cooldowns to trigger real-time illumination changes, OLED updates, and tactile alerts.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/steelseries-engine
