### ISSUE TITLE
RFP - Last.fm Desktop Scrobbler 3.X

### ISSUE THREAD

**Issue by Nischi85** [chocolatey-community/chocolatey-package-requests#791]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.last.fm/about/trackmymusic
Direct download URL for the software / installer : https://cdn.last.fm/client/Win/LastFM_Scrobbler_3.1.29.msi
Software summary / short description: The Last.fm Desktop Scrobbler for Windows is a simple app that runs in the background and automatically updates your profile with what you’ve been playing on your computer via native media players such as Windows Media Player or iTunes.

**Comment by chtof** [comment]
Not updated for a while but this package already exists: https://chocolatey.org/packages/lastfmscrobbler

**Comment by Nischi85** [comment]
It's the wrong package you linked to. This is the current version, the vesion you linked to is an outdated no more updated version. Therefore my title with the version 3.X in the name.

**Comment by chtof** [comment]
It's the same software. Have you tried to contact the package maintainer of lastfmscrobbler?

**Comment by Nischi85** [comment]
They basically do the same thing, but they are different versions supporting different settings and operating systems. they are both accessable through the last.fm webpage, the legacy is still there because of legacy reasons. It would feel weird to "update" the old legacy version with this new 3.X version. If you say that is the correct path to go, then I will ask the current package maintainer to do so, but I feel I would to a disservice to a lot of users that way since the programs do not support the same range of music applications and operating systems.

**Comment by pauby** [comment]
The legacy application's last version is 2.1.37. The new version is 3.1.29.

If both of these applications do exactly the same thing and if the natural progression for the application is from the legacy / old version to this then it makes sense for the current Chocolatey package to be updated with the new version. The old version will never be updated so three is no risk of having to release a new version of it.

If people want to stick to the current old version they can pin it. ALternatively if they want to install the old version they can use the `choco install lastfmscrobbler --version=2.1.36` parameter in `choco.exe`.

If we are going to go down that road I'd also fix the last version (2.1.37) of the old / legacy version on Chocolatey.org which failed validation and verification.

**Comment by Nischi85** [comment]
okay thanks for your'e input pauby, I will contact the current maintaner and see.

**Comment by pauby** [comment]
@Nischi85 Do you have an update on this?

**Comment by Nischi85** [comment]
@pauby Yes I've contacted the maintainer, he said he would update to the latest 3.X version. It seems to be stuck now at waiting for maintainer to take corrective action according to https://chocolatey.org/packages/lastfmscrobbler/3.1.29

**Comment by pauby** [comment]
:+1: As the package is in progress on the repository I'm going to go ahead and close this now as it's no longer needed.
