### ISSUE TITLE
RFP - Adobe Connect

### ISSUE THREAD

**Issue by ttabaka** [chocolatey-community/chocolatey-package-requests#792]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: **https://helpx.adobe.com/adobe-connect/connect-downloads-updates.html**

Direct download URL for the software/installer: **http://www.adobe.com/go/Connectmsi**

Software summary / short description:
- Release Notes: **https://helpx.adobe.com/adobe-connect/connect-releasenotes.html**

None.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/adobe-connect
