### ISSUE TITLE
RFP - Cisco Webex Meetings

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#793]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.webex.com/video-conferencing
Direct download URL for the software / installer : https://akamaicdn.webex.com/client/webexapp.msi
Software summary / short description: 

Video conferencing is as simple and seamless as meeting in person. With the Webex mobile app, you can meet absolutely anywhere. Hosting is easy and joining is easier—simply click on your link to join. You can even learn about the people you’re meeting for the first time, with instant access to participants’ background and company.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/webex-meetings
