### ISSUE TITLE
RFP - Cisco Webex Teams

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#794]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.webex.com/team-collaboration.html
Direct download URL for the software / installer : https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/WebexTeams.msi
Software summary / short description:

Whether on the go, at a desk, or together in a meeting room, Webex Teams helps speed up projects, build better relationships, and solve business challenges. It’s got all the team collaboration tools you need to keep work moving forward and connects with the other tools you use to simplify life.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/webex-teams
