### ISSUE TITLE
RFP - Jigdo

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#795]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.einval.com/~steve/software/jigdo/
Direct download URL for the software / installer : https://www.einval.com/~steve/software/jigdo/download/jigdo-win-0.8.0.zip
Software summary / short description:

Jigsaw Download (for short "jigdo"), is a tool designed to ease the distribution of very large files over the internet, for example CD or DVD images. Its aim is to make downloading the images as easy for users as a click on a direct download link in a browser, while avoiding all the problems that server administrators have with hosting such large files.

Should make `jigdo-file` and `jigdo-lite` available.

**Comment by pauby** [comment]
This _might_ be embeddable - I couldn't find a license though.

**Comment by houstdav000** [comment]
Had to look at the git tree, it's GPLv2

https://git.einval.com/cgi-bin/gitweb.cgi?p=jigdo.git;a=blob;f=COPYING;h=d60c31a97a544b53039088d14fe9114583c0efc3;hb=HEAD

**Comment by pauby** [comment]
Awesome! You're eyes are better than mine! 😄

**Comment by corbob** [comment]
I would like to create this package.

**Comment by pauby** [comment]
@corbob Any update on this?

**Comment by corbob** [comment]
@pauby apologies for the delay. I've submitted the package for moderation. Just working through validation errors.

**Comment by corbob** [comment]
The package has been uploaded: https://chocolatey.org/packages/jigdo/0.8.0 The only thing to note with it: jigdo itself doesn't have an icon, I opted for the Debian icon as it seems to be most often associated with Debian 🤷
