### ISSUE TITLE
'RFP - doxybook2

### ISSUE THREAD

**Issue by aster94** [chocolatey-community/chocolatey-package-requests#796]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/matusnovak/doxybook2
Direct download URL for the software / installer : https://github.com/matusnovak/doxybook2/releases
Software summary / short description: a nice utility to convert doxygen xml files to markdown

**Comment by Xav83** [comment]
I pick up this package 🙂

**Comment by Xav83** [comment]
FYI, I pushed a chocolatey package [here](https://chocolatey.org/packages/doxybook2/1.1.3), which is currently passing the tests.

**Comment by Xav83** [comment]
Update:
All the tests passed for the [chocolatey package](https://chocolatey.org/packages/doxybook2/1.1.3).
It is now waiting for a moderator to review it 😉

**Comment by Xav83** [comment]
For information @aster94, the version of the package on chocolatey is the version `1.1.3`. The version `1.1.4` will be automatically pushed when the version `1.1.3` will be validated by a maintainer. 😉

**Comment by aster94** [comment]
thank you :)

Il giorno gio 21 mag 2020 alle ore 10:49 Xav83 <notifications@github.com>
ha scritto:

**Comment by Xav83** [comment]
The chocolatey package have been validated and is now available to the users 😄 
https://chocolatey.org/packages/doxybook2
