### ISSUE TITLE
RFP - PhantomBot

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#798]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=PhantomBot&moderatorQueue=true&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?&q=is%3Aissue+PhantomBot)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<https://phantombot.tv/>**
+ Download URLs: **<https://github.com/PhantomBot/PhantomBot/releases>**
+ Have this software command-line interface (CLI)? Yes, but no needs to add any path to the PATH environment variable
+ Software summary/short description: [**Free and open source**](https://github.com/PhantomBot/PhantomBot) Twitch bot. [**Features list**](https://phantombot.tv/features/).

Thanks.

**Comment by Kristinita** [comment]
@scaniatv, @IllusionaryOne, @BrandenB, @gmt2001, @TheCynicalLiger, please, pay attention to this request.

Thanks.

**Comment by TheCynicalLiger** [comment]
@Kristinita why me i'm not a dev?i just push fixes when i find bugs

**Comment by Kristinita** [comment]
@TheCynicalLiger , I just looked at the list of [**top and active PhantomBot contributors**](https://github.com/PhantomBot/PhantomBot/graphs/contributors). I'm sorry, I deleted your mention.

Thanks.

**Comment by gmt2001** [comment]
1. **Don't go arbitrarily tagging people like that.**
2. We will absolutely **NOT** provide support for single-platform distribution channels
3. We have enough distribution channels already
4. We have a Discord and a Forums, which are **WAY** more appropriate places for a request like this, yet I see that you failed to even **TRY** to use them

This request is Denied

**Comment by pauby** [comment]
@gmt2001 What request are you denying?

**Comment by gmt2001** [comment]
This one. The user made this issue for the sole purpose of tagging contributors at the PhantomBot repo to ask them to do it, instead of using our existing communication tools.

**Comment by Xav83** [comment]
I pick up this package 🙂

**Comment by pauby** [comment]
@gmt2001 I'm still not sure what you're denying. The _request_ was made for a package to be created. The software is licensed under GPL which allows distribution if the package maintainer wanted to add the software to the package. If users want to create a Chocolatey package from this then there is nothing in the license that prohibits that so I'm unsure what you want me us to do, if anything.

**Comment by Xav83** [comment]
For information, I created a chocolatey package, and it is currently passing the tests.
You can follow it [here](https://chocolatey.org/packages/phantombot/3.1.2)

**Comment by Xav83** [comment]
The chocolatey package have been validated and is now available to the users 😄 
https://chocolatey.org/packages/phantombot
