### ISSUE TITLE
RFP - WinSize2

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#799]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=winsize&moderatorQueue=true&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?&q=is%3Aissue+winsize)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<https://sourceforge.net/projects/winsize2/>**
+ Download URL: **<https://sourceforge.net/projects/winsize2/files/latest/download>**
+ Have this software command-line interface (CLI)? Yes
+ If “yes” for previous question, what folder(s) must be added to the PATH environment variable? `./WinSize2_{version}/WinSize2`

### 3. Software description

User set coordinates for specific program (Firefox in example):

![Firefox coordinates](https://i.imgur.com/zZfKzlC.png)

User run WinSize2 → WinSize2 change Firefox window to the given parameters → user can't resize a window, when WinSize2 run:

+ [**WinSize2 demo GIF**](https://i.imgur.com/TU0puhK.gif)

WinSize2 is necessary if neediest the exact coordinates of the windows. I use it for placing windows in my streams.

More details in `Handbook WinSize2 EN.pdf` file inside software ZIP.

### 4. Notes

Yes, this software is old ([**last update date — 2013-05-28**](https://sourceforge.net/projects/winsize2/)), but:

1. It successfully works for my Windows 10 64-bit Version 1909 (OS Build 18363.720).
1. I couldn't find any free alternative with same functionality. If anyone knows it, please, [**let others know**](https://superuser.com/q/240362/572069).

Thanks.

**Comment by corbob** [comment]
I would like to create this package.

**Comment by pauby** [comment]
@corbob Any update on this?

**Comment by corbob** [comment]
@pauby I believe I've corrected the validation issues, just need to have an admin move it back to submitted so I can reupload it.

**Comment by pauby** [comment]
@corbob I did that this morning for you (after your email).

**Comment by corbob** [comment]
@pauby thanks. I just need to figure out what I missed (or what my build script failed to strip out) and then I can get it submitted again.

**Comment by corbob** [comment]
Package has been published to the Community Repository: https://chocolatey.org/packages/winsize2
