### ISSUE TITLE
RFP - Avro Keyboard

### ISSUE THREAD

**Issue by pidus** [chocolatey-community/chocolatey-package-requests#801]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.omicronlab.com/avro-keyboard-download.html
Direct download URL for the software / installer : https://www.omicronlab.com/download/setup_avrokeyboard_5.6.0.exe
Software summary / short description: Unicode/ANSI supported Bangla typing software & Spell Checker for Windows.

**Comment by pauby** [comment]
@pidus I can't connect to the omicronlab.com site. Getting the error:

![image](https://user-images.githubusercontent.com/12760779/78884633-2cc1e400-7a53-11ea-90e1-faedc38639d3.png)

Could be a temporary issue. Is this working for anybody else?

**Comment by AdmiringWorm** [comment]
@pauby the website and download location seems to work as it should for me.
I am opening it up for maintainers.

**Comment by pauby** [comment]
:+1: Very weird. Still not working for me in 3 different browsers.

**Comment by AdmiringWorm** [comment]
@pauby could be a misconfiguration on the server that you get connected to.

**Comment by pauby** [comment]
@AdmiringWorm It could be. As long as it's working for everybody else just ignore my woes 😄

**Comment by corbob** [comment]
I would like to create this package.

**Comment by BorhnN** [comment]
Hi @corbob, if you're willing, I would like to contribute.

I was learning about chocolatey package creation for this package. Then found this.

**Comment by corbob** [comment]
Hi @BorhnN, sure. It looks like I created an empty package and hadn't actually got to filling out the nuspec or coming up with the ChocolateyInstall.ps1 before being distracted by life.

Let me know if there's any assistance I can provide.

**Comment by corbob** [comment]
It looks like @BorhnN has gotten this done, and it's in the community repository. Could this be assigned over to them @AdmiringWorm?

**Comment by AdmiringWorm** [comment]
Looks to also be approved.
Considering this request as completed.
