### ISSUE TITLE
RFP - Korg drivers and firmware update tools

### ISSUE THREAD

**Issue by mcandre** [chocolatey-community/chocolatey-package-requests#802]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.korg.com/us/support/
Software summary / short description: Korg drivers and firmware update tools

**Comment by pauby** [comment]
@mcandre You missed `Direct download URL for the software / installer :` - we need this.

**Comment by pauby** [comment]
No response in 14 days. Closing.
