### ISSUE TITLE
RFP - Kyma CLI

### ISSUE THREAD

**Issue by JohannesKonings** [chocolatey-community/chocolatey-package-requests#804]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://github.com/kyma-project/cli
Direct download URL for the software / installer : https://github.com/kyma-project/cli/releases
Software summary / short description:
Kyma CLI is a command line tool which supports Kyma developers. It provides a set of commands you can use to install, manage, and test Kyma.

**Comment by dgalbraith** [comment]
I will pick this one up for package creation.

**Comment by dgalbraith** [comment]
[Kyma CLI](https://www.chocolatey.org/packages/kyma-cli) packaged and ready for review.

**Comment by dgalbraith** [comment]
[Kyma CLI](https://www.chocolatey.org/packages/kyma-cli) package is now approved and available.
