### ISSUE TITLE
RFP - SanDisk SSD Dashboard

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#805]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://kb.sandisk.com/app/answers/detail/a_id/15108/~/sandisk-ssd-dashboard-support-information
Direct download URL for the software / installer : https://downloads.sandisk.com/Dashboard/SanDiskSSDDashboardSetup.exe
Software summary / short description: The SanDisk SSD Dashboard helps users maintain peak performance of the SanDisk SSD in Windows® operating systems with a user-friendly graphical interface for the user. The SanDisk SSD Dashboard includes tools for analysis of the disk (including the disk model, capacity, firmware version, and SMART attributes) and firmware updates.

**Comment by AdmiringWorm** [comment]
NOTE for anyone looking to create a package for this one, remember to put the mention of only using the software on internal SSD drives in the description of the package (possibly also as a warning when installing the package).

**Comment by brogers5** [comment]
SanDisk SSD Dashboard was discontinued a while ago, and has been superseded by [Western Digital Dashboard](https://support.wdc.com/downloads.aspx?p=279).

As noted in Western Digital Dashboard's [release notes](https://wddashboarddownloads.wdc.com/wdDashboard/WesternDigitalDashboardReleaseNotes.pdf) for version 3.0:
> * Unify “WD SSD Dashboard” and “SanDisk SSD Dashboard” to the new single “Dashboard” application

Note that the direct download URL I provided is still live, but points to a binary similar to Western Digital Dashboard's web installer.

Canceling this request and closing the issue, as SanDisk SSD Dashboard is no longer available for download via the official distribution point.

Side note for any subscribers: I recently [submitted a package for Western Digital Dashboard](https://community.chocolatey.org/packages/wd-dashboard), which may be of interest in lieu of this.
