### ISSUE TITLE
RFP - CairoShell

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#806]
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=Cairo&moderatorQueue=&moderationStatus=all-statuses&prerelease=true&sortOrder=relevance) on **<https://chocolatey.org/packages>**
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?&q=is%3Aissue+Cairo)
- [x] The issue title starts 'RFP — '
- [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

+ Software project URL: **<https://cairoshell.com/>**
+ Download URLs (for 32-bit and 64-bit Windows): **<https://github.com/cairoshell/cairoshell/releases>**
+ Have this software command-line interface (CLI)? No

### 3. Software description

CairoShell is [**open source**](https://github.com/cairoshell/cairoshell) alternative for default Windows `explorer.exe`. CairoShell users have custom taskbar, programs menu and desktop.

[**Video**](https://www.youtube.com/watch?v=Ce1hxbom3IA), how it works.

Some images from official site:

![Top taskbar](https://cairoshell.com/img/top_bg.jpg)

![Bottom taskbar](https://cairoshell.com/img/ss_taskbar.png)

Thanks.

**Comment by Xav83** [comment]
I pick up this package

**Comment by Xav83** [comment]
FYI, I pushed a chocolatey package [here](https://chocolatey.org/packages/cairoshell/0.3.7015), which is currently passing the tests.

**Comment by pauby** [comment]
@Xav83 The package failed verification on 26 May.

**Comment by Xav83** [comment]
Oh, I didn't see it, I will see to fix that during the week 🙂

**Comment by Xav83** [comment]
FYI The package passed the automatic tests and is waiting for the review by the moderator 🙂
