### ISSUE TITLE
RFP - WD Backup

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#808]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://support.wdc.com/downloads.aspx?p=249
Direct download URL for the software / installer : https://downloads.wdc.com/wdapp/WD_Backup_1.9.7375.5719.zip
Software summary / short description: WD Backup is an easy-to-use backup application. It automatically protects your files, photos and documents with on premise backups to a WD drive as primary storage. Off-premise backups to a cloud as secondary storage for disaster recovery purpose.

**Comment by mkevenaar** [comment]
I would like to pick this up

**Comment by mkevenaar** [comment]
Pushed and ready for review

**Comment by brogers5** [comment]
[Package](https://chocolatey.org/packages/wd-backup) was approved yesterday. Should be clear to close this one out.

**Comment by mkevenaar** [comment]
Package published.
