### ISSUE TITLE
RFM - Android Studio

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-package-requests#810]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/AndroidStudio
Package source URL: https://github.com/jtcmedia/chocolatey-packages/tree/master/androidstudio

The download for this is now behind a modal that you have to scroll through and check a box at the bottom to accept the license agreement. I use AU and I don't know how to get around this for automated updates or if it's even legal to.

**Comment by dgalbraith** [comment]
I am happy to pick this one up - Chocolatey user name is dgalbraith

**Comment by jtcmedia** [comment]
@dgalbraith I believe I have added you as a maintainer. You just need to approve. My repo has the current package https://github.com/jtcmedia/chocolatey-packages/tree/master/androidstudio if you want a starting point.

**Comment by dgalbraith** [comment]
Package and history have been migrated with the [initial version](https://www.chocolatey.org/packages/AndroidStudio/4.0.1.0) now pushed using the new [repository source](https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/androidstudio).
