### ISSUE TITLE
RFP - sd: Intuitive find & replace CLI

### ISSUE THREAD

**Issue by mardukbp** [chocolatey-community/chocolatey-package-requests#811]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/chmln/sd
Direct download URL for the software / installer : https://github.com/chmln/sd/releases/download/v0.7.4/sd-0.7.4.x86_64-pc-windows-msvc.zip
Software summary / short description: sd is a cross-platform sed alternative designed with an emphasis in usability and productivity. Being a single statically linked binary, it has no dependencies.

## Package Expectations

The package should add the installation directory to the user %PATH%

**Comment by dgalbraith** [comment]
I will pick this one up for packaging.

**Comment by mardukbp** [comment]
Great! Thank you. I will notify the author of sd when the package is ready.

**Comment by dgalbraith** [comment]
[Package](https://www.chocolatey.org/packages/sd-cli/0.7.5) has been uploaded and is ready for review.

**Comment by mardukbp** [comment]
Great! Thank you so much!

**Comment by dgalbraith** [comment]
Review is complete and the [sd-cli](https://www.chocolatey.org/packages/sd-cli) package is now approved and available.

**Comment by mardukbp** [comment]
Thank you so much @dgalbraith! I already added the installation instructions for Windows to the README file of sd.
