### ISSUE TITLE
RFM - Kindle

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#812]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/Kindle
Package source URL: https://github.com/AnthonyMastrean/chocolateypackages
Date the maintainer was contacted: 22 April 2020
How the maintainer was contacted: Using the 'Contact Maintainers' link on the package page.

**Comment by dgalbraith** [comment]
I will pick this up.

**Comment by dgalbraith** [comment]
An update to the Package Maintainers is needed for me to be able to push package updates.  Is it possible for my Chocolatey account [dgalbraith](https://www.chocolatey.org/profiles/dgalbraith) to be added as a maintainer?

**Comment by TheNavyBear** [comment]
Thank you @dgalbraith for taking over this project. Kindle is an app I use regularly, and I like having all my apps from either the Windows Store or Chocolatey. Thank you for helping keep this package alive. I look forward to an updated version once they get you added to the Package Maintainers. Be well.

**Comment by AdmiringWorm** [comment]
@dgalbraith typically we would have asked you to use the `Contact Site Admins` link on the package page to request being added as a maintainer. Unfortunately, this does not work correctly at the moment,and as such, I have added you as a maintainer now (you should have received an email with a link to confirm the addition).

**Comment by dgalbraith** [comment]
@AdmiringWorm is the issue with notifications impacting package maintiner updates at all?  I have not received an email to confirm the maintainer addition at all (I have checked in Spam, against automated rults etc - the only emails I have received are from package submissions/reviews).

**Comment by pauby** [comment]
@dgalbraith The issue with emails is only affecting 'Contact Site Admins' on the package page. It's not affecting any other emails being sent. I will caveat that with _as far as we know_.

Emails do occasionally get lost so I'm going to put this down to that.

**Comment by TheNavyBear** [comment]
@dgalbraith will the Kindle package be put on the 'Chocolatey Automatic Package Update Model (AU)' like you did with TuneIn, or is that even possible with Kindle? I ask cause I know Amazon is not the best at announcing new versions of the Kindle app, but I also don't mind keeping an eye on it and letting the maintainers know when a new version is ready if the package isn't auto-updated. (Sorry if this isn't the right forum for this question, I wasn't sure where to ask.)

**Comment by pauby** [comment]
@dgalbraith Is there an update on this? I ask as I see you are still pending as a maintainer.

**Comment by dgalbraith** [comment]
@pauby I have not received an email to validate the addition as a maintainer.  Not sure if there is another way to update the status on this / accept assignment as a package maintainer without using the email?

**Comment by tunisiano187** [comment]
@dgalbraith, you can contact the admins via the form on the package page, it's working again.

**Comment by dgalbraith** [comment]
thanks @tunisiano187.  Maintainers contacted ([Chocolatey.org Message for maintainers of the package 'Kindle'.pdf](https://github.com/chocolatey-community/chocolatey-package-requests/files/4839855/Chocolatey.org.Message.for.maintainers.of.the.package.Kindle.pdf)) - will update here on the outcome.

**Comment by dgalbraith** [comment]
No response from the package maintainers to date.

There is also a [pull request](https://github.com/AnthonyMastrean/chocolateypackages/pull/383) for a version update that has been outstanding since 31-March so not sure if maintenance is still taking place.

**Comment by TheNavyBear** [comment]
So Amazon servers are no longer serving the version that Chocolatey is trying to pull, so the install through Chocolatey fails. The pull request for a newer (but now outdated) version from March still hasn't been resolved. A new maintainer willing to take over can't get a response to be made maintainer.

I know Chocolatey is open source, and is driven by volunteers, and as such no one really wants to start yanking projects from people, as that leads to hurt feelings and bad relations, and makes people not want to volunteer. I fully understand that, but there is now a package dead in the water because the current maintainer has quit maintaining it, and a willing replacement can't get access to do so. 

Please Chocolatey team, I am begging you not to let this package die. I use Kindle regularly. I know I could just go download it from Amazon as has been said in the comments of the package, but that defeats the purpose of Chocolatey's existence. I get all my apps from the Windows Store or Chocolatey, so that in two easy actions all my apps are up to date, and I don't have to go digging through apps and sites to make sure all my software is up to date. To date I have been able to get every app I need from Windows Store and Chocolatey, but now that is not possible because of this package, and that makes me very sad. 

Please, if possible, get this corrected without (too much) damage to developer community relations?

**Comment by tunisiano187** [comment]
Hello, the triage process is working correctly, of course it happend that the maintainer isn't answering, but after a week the triage process ask to submit it to the site admins, who are answering maximum 3 days after.
I see some people have pushed it, so they can follow the process, if it's not working, don't hesitate to ask me, i'm interested in this product so i can maintain it if neede ;-)
Have a nice day

**Comment by tunisiano187** [comment]
@dgalbraith , i see you haven't received the mail to confirm you want to be maintainer, i had a problem with another maintainer that had unchecked the notifications in his profile, so my tests to add him as maintainer were not sent, is it checked for you ?

**Comment by dgalbraith** [comment]
@tunisano187 thanks for the suggestion - I have checked my profile setup and notifications are enabled.

@TheNavyBear this may well be down to me using GitHub for the comms here - I have reviewed the process and have contacted the Site Admins on the request to be added as a package maintainer (noting that this was done previously, I just didn't receive the email to confirm) - I am sure that this will be sorted shortly.

I do have an updated package ready to go (just need to merge, build and push) and it is one that will update automatically going forward.

**Comment by pauby** [comment]
@TheNavyBear 

> A new maintainer willing to take over can't get a response to be made maintainer.

As has already been pointed out by @dgalbraith, he was actually added as a new maintainer but failed to get the email (the email has a link in there for him to click on to confirm to take over as maintainer). He has since sent a subsequent email, 12 hours ago, which I've now responded to and hopefully he has that new email with the link.

>  know Chocolatey is open source, 

Just to be clear here Chocolatey != Chocolatey Community Repository. They are two distinct entities.

> and is driven by volunteers, and as such no one really wants to start yanking projects from people, 

It's not a case of yanking projects from people. There is a [Package Triage Process](https://chocolatey.org/docs/package-triage-process) that is followed when a package is out of date / broken etc. The link on the package page help to point people to that. So if a package is broken / out of date then it's not really being yanked from anybody if they are not responding to messages. It's more of a case of, as you said, we'd considered the package abandoned and somebody else can take over maintaining it.

> Please Chocolatey team, I am begging you not to let this package die.

Again, just to be very clear, the Chocolatey Community Repository is maintained by the community, largely of volunteers and an increasing number of vendors. The community maintains the packages. I raised this issue here on behalf of somebody else but it is down to the community to pick up and maintain the package. In that respect the Chocolatey Team are not letting packages die. The only issue here was an email not being received (which has now hopefully been rectified).

> Please, if possible, get this corrected without (too much) damage to developer community relations?

In all my time as a moderators I've never seen anybody complain when their package was taken over. I have, once, been asked why a new maintainer was added to a package. So there is no damage to developer relations.

@tunisiano187 

>  site admins, who are answering maximum 3 days later.

3 days I would say is the maximum over a weekend. I check the mailbox for moderation requests every morning so that is likely to be very much faster. And you should know as you are the receiver of most of them these days 😉

**Comment by dgalbraith** [comment]
@pauby confirming that I have received and actioned the maintainer addition this time around - thanks!

Will push the new package as soon as I merge the history and overlay the updates.  Wil do so asap, but may take me until the weekend given a few things in flight.

**Comment by tunisiano187** [comment]
@pauby , ys it was the idea ;-) real maximum is 3 days (weekend included ;-) )
That's really amazing by the way ;-) thanl you all for this !!!

**Comment by TheNavyBear** [comment]
@pauby thank you very much for the information. I really do appreciate the insight. It was made clear after the fact that it was a true comms issue and not a lack or care or concern. I apologize if I came across too harsh.

Thank you everyone for the effort and dedication to keep this package going, it is really truly appreciated.

**Comment by pauby** [comment]
@TheNavyBear 

> I apologize if I came across too harsh.

No need to apologise. You didn't come across that way. I did feel that maybe there was some understanding that was missing on how things flow, hence my message. Glad it helped! So we're good here 😄

**Comment by dgalbraith** [comment]
Package has been pushed and updated from the new package source and is ready for review.  Pushed package versions are:

- [Kindle for PC 1.28.57030](https://www.chocolatey.org/packages/Kindle/1.28.57030); and
- [Kindle for PC 1.29.58059](https://www.chocolatey.org/packages/Kindle/1.29.58059)

1.28.57030 was a manual push and 1.29.58059 is the latest version which was pushed by the automatic updater.

It looks as though Amazon have now removed older executable versions (prior to 1.28.57030) and it is likely that they will continue with this.  The package notes have been updated to reflect that older versions of the package may not work.

**Comment by dgalbraith** [comment]
Review has been completed and the updated package is now available on the community feed.
