### ISSUE TITLE
RFP - Keys

### ISSUE THREAD

**Issue by houstdav000** [chocolatey-community/chocolatey-package-requests#813]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://keys.pub/
Direct download URL for the software / installer : https://github.com/keys-pub/app/releases/download/v0.0.39/Keys-0.0.39.msi
Software summary / short description:

Key management is hard. We need tools, libraries, apps and documentation to help us.

- Manage cryptographic keys, sigchains and user identities.
- Search for keys, verify and import them.
- Securely store passwords and secrets.
- Encrypt, decrypt, sign, verify (using Saltpack).
- Create a secure connection (Wormhole) between 2 computers (using Noise).
- Most features available in both the app and on the command line.
- 100% open source (github.com/keys-pub) and cross platform (macOS, Windows, Linux).
- Coming soon: Backup keys/secrets to your private self-hosted storage on S3, GCP, Dropbox, etc.
- Coming soon: Support for hardware keys like SoloKeys, YubiKeys, FIDO2.
- Coming soon: Mobile apps.

**Comment by dgalbraith** [comment]
I will pick this one up for packaging.

**Comment by dgalbraith** [comment]
[Package](https://www.chocolatey.org/packages/keys/) has been uploaded and is ready for review.

**Comment by dgalbraith** [comment]
Review is complete and the [keys](https://www.chocolatey.org/packages/keys) package is now approved and available.
