### ISSUE TITLE
RFM - MiKTeX

### ISSUE THREAD

**Issue by me-and** [chocolatey-community/chocolatey-package-requests#814]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/miktex.install
Package source URL: https://github.com/aronovgj/choco-auto/tree/master/miktex.install
Date the maintainer was contacted: 3 April 2020
How the maintainer was contacted: GitHub Issues at aronovgj/choco-auto#41

**Comment by pauby** [comment]
@me-and Can you contact the maintainer using the 'Contact Package Maintainers' link on the package page, wait a week and then update this if no response?

**Comment by me-and** [comment]
Done. I'll come back if there's no response.

**Comment by pauby** [comment]
Can you update the issue either way? If there is a response we need to close this.

**Comment by me-and** [comment]
Hello, it's now been eight days and I've not heard anything from the maintainer after contacting them that way either.

**Comment by AdmiringWorm** [comment]
Opening this one up for new maintainers.

**Comment by teknowledgist** [comment]
MiKTeX is an interesting install and upgrade.  I'll try to wrangle this one, but I don't want to discourage anyone who is particularly gung ho about doing it.

**Comment by tunisiano187** [comment]
FYI, I'm looking into it, just reading the previous version to see if i'm able to convert it to automatic

**Comment by teknowledgist** [comment]
@tunisiano187 Feel free to take a look at [what I have so far](https://github.com/teknowledgist/Chocolatey-packages/tree/master/Under%20Construction/miktex.install).  

I have the automatic piece done, but I'm trying to do the updates the "right" way "installing" only the setup utility and using that for installation.  MiKTeX doesn't like to install overtop itself, and it's built-in package manager will upgrade itself to the latest milestone making the download much smaller.  

I'm stuck on getting it to install via `Start-ChocolateyProcessAsAdmin` (getting weird errors), but the rest is pretty good.

**Comment by teknowledgist** [comment]
One thing I [found out](https://github.com/MiKTeX/miktex/issues/553#issuecomment-635135996) is that the version of the installer is not the same as the milestone of MiKTeX.  I'm trying to make the Chocolatey package match the milestone rather than the version of the installer.

**Comment by tunisiano187** [comment]
I have some other way to do that if needed, i install it on my runner, and get the real version from the installed apps on windows... if it can help

**Comment by tunisiano187** [comment]
I'll let you work on this one, i will work on another

**Comment by tunisiano187** [comment]
Any progress? or you really need help ?

**Comment by teknowledgist** [comment]
@tunisiano187 It's basically done.  I'm just playing with adding an option to identify a specific repository for installation.  Either way, I can't push an update until the admins make me a maintainer.  I get the feeling (from some other requests) that they are very busy.  😄

**Comment by AdmiringWorm** [comment]
@teknowledgist 
> @tunisiano187 It's basically done. I'm just playing with adding an option to identify a specific repository for installation. Either way, I can't push an update until the admins make me a maintainer. I get the feeling (from some other requests) that they are very busy. 😄

Have you used to `Contact Site Admins` on the package page to request being added as a maintainer?

**Comment by teknowledgist** [comment]
> Have you used to `Contact Site Admins` on the package page to request being added as a maintainer?

Not for this package.  I've been assigned to other packages through these issues before without doing that, so I was assuming things were just behind.  I can make the request, sorry for the delay.

**Comment by AdmiringWorm** [comment]
@teknowledgist I now I had added you once or twice through these issues. However, this was during a time that the `Contact Site Admins` emails were never received. As such, we only had that option. Since that issue was fixed, we require the contact to go through Site Admins again.

The only other times is if the poster of the request is the maintainer of the package, in those cases, we recommend then that the maintainer adds you as a new maintainer, but that is not the case here.

**Comment by teknowledgist** [comment]
I didn't realize there was anything different, but it's not a problem at all.  Request submitted.  Thanks.

**Comment by pauby** [comment]
@teknowledgist Can you give us an update on this one? Are you picking up all of these packages:

- https://github.com/chtof/chocolatey-packages/tree/master/automatic/miktex
- https://github.com/chtof/chocolatey-packages/tree/master/automatic/miktex.install
- https://github.com/chtof/chocolatey-packages/tree/master/automatic/miktex.portable

**Comment by teknowledgist** [comment]
The miktex.install package is done.  I was waiting because (I would swear that) [the new versioning scheme](https://miktex.org/announcement/new-release-versioning-scheme) said "middle of June" 10-12 days ago, so I thought I would wait (a couple days).  Since it now says "end of June", I will push the package anyway.  

I can easily (and should) pick up the `miktex` package, and I may as well take the `miktex.portable` package too.

**Comment by teknowledgist** [comment]
Thinking about the meta-package, `miktex`, is there any way to pass package parameters given for the meta package onto the dependency, `miktex.install`, package?  

If not, is there a standard to just remove the description of parameters from the meta package and have a default install of the dependency?  IOW, only users who dig deeper into the dependency will see the parameter options?

Thanks.

**Comment by pauby** [comment]
> Thinking about the meta-package, miktex, is there any way to pass package parameters given for the meta package onto the dependency, miktex.install, package?

There is this parameter:

```
     --paramsglobal, --params-global, --packageparametersglobal, --package-parameters-global, --applyparamstodependencies, --apply-params-to-dependencies, --apply-package-parameters-to-dependencies
     Apply Package Parameters To Dependencies  - Should package parameters be 
       applied to dependent packages? Defaults to false.
```

> I can easily (and should) pick up the miktex package, and I may as well take the miktex.portable package too.

Can you send a request for each of those packages and reference this issue?

**Comment by AdmiringWorm** [comment]
@teknowledgist if the meta package and the install/portable package id are the same (excluding `.install`/`.portable`), then any parameters (and arguments) passed to the meta package should also be passed to the dependency.

**Comment by teknowledgist** [comment]
The miktex and miktex.install packages are done and working (mostly -- some folks are having upgrade issues, but I'll sort them out).  I don't yet have the .portable package updated, but that wasn't really in the scope of this RFM.  I think this can be closed.
