### ISSUE TITLE
RFP - HakuNeko

### ISSUE THREAD

**Issue by Neolel** [chocolatey-community/chocolatey-package-requests#815]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] The issue title starts 'RFP - ';
- [x] There is no open issue for this package;
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/manga-download/hakuneko
Direct download URL for the software / installer : https://github.com/manga-download/hakuneko/releases/download/v6.1.7/hakuneko-desktop_6.1.7_windows-setup_amd64.exe
Software summary / short description:
"HakuNeko is a cross-platform downloader for manga and anime from various websites. HakuNeko was made to help users downloading media for circumstances that require offline usage. The philosophy is ad-hoc consumption, get it when you going to read/watch it. It is not meant to be a mass downloader to stock up thousands of chapters that are just collected and will probably never be read."

**Comment by dgalbraith** [comment]
I will pick this one up for package creation.

**Comment by dgalbraith** [comment]
Packaging is complete and ready for review.  There are 3 separate packages covering this:
* A meta-package [haku-neko](https://www.chocolatey.org/packages/haku-neko);
* An install package [haku-neko.install](https://www.chocolatey.org/packages/haku-neko.install); and
* A portable package [haku-neko.portable](https://www.chocolatey.org/packages/haku-neko.portable)

**Comment by dgalbraith** [comment]
Package has been reviewed and is now generally available.
