### ISSUE TITLE
RFP - TuneIn Radio Desktop App

### ISSUE THREAD

**Issue by TheNavyBear** [chocolatey-community/chocolatey-package-requests#816]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://tunein.com/
Direct download URL for the software / installer : https://tunein.com/get-tunein/download/
Software summary / short description: The new TuneIn desktop app improves how you browse and discover content from all over the world, and enables you to seamlessly listen and save favorites across all of your devices.

**Comment by dgalbraith** [comment]
I will pick this one up.

**Comment by dgalbraith** [comment]
[Package](https://www.chocolatey.org/packages/tunein-radio) is complete and ready for review.

**Comment by dgalbraith** [comment]
[Package](https://www.chocolatey.org/packages/tunein-radio) reviewed and available.
