### ISSUE TITLE
RFP - Freetube

### ISSUE THREAD

**Issue by chantisnake** [chocolatey-community/chocolatey-package-requests#817]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

**Software project URL** : https://freetubeapp.io/
**Direct download URL for the software / installer** :
- EXE: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.7.2-beta/FreeTube.Setup.0.7.2.exe
- ZIP: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.7.2-beta/FreeTube-0.7.2-win.zip

**Software summary / short description**:
FreeTube is an open source desktop YouTube player built with privacy in mind. Use YouTube without advertisements and prevent Google from tracking you with their cookies and JavaScript. Available for Windows, Mac & Linux thanks to Electron.

Please note that FreeTube is currently in Beta. While it should work well for most users, there are still bugs and missing features that need to be addressed.

**Source code**: https://github.com/FreeTubeApp/FreeTube

**Comment by Xav83** [comment]
I pick up this package 🙂

**Comment by Xav83** [comment]
There is actually a package already on Chocolatey for Freetube.
You can find it [here](https://chocolatey.org/packages/freetube).

@chantisnake you may want to ping the maintainers of this [package](https://chocolatey.org/packages/freetube) to have them update it to the last version 😉

**Comment by chantisnake** [comment]
@Xav83 thanks, I guess I did not check for pre-release, my fault of course. 

I see that the new version is pushed and waiting to approve. I guess I will close this issue then.
