### ISSUE TITLE
RFP - Visual Studio Community 2019 English Language Pack

### ISSUE THREAD

**Issue by rkitover** [chocolatey-community/chocolatey-package-requests#818]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://visualstudio.microsoft.com/
Direct download URL for the software / installer : https://visualstudio.microsoft.com/en/thank-you-downloading-visual-studio/?sku=Community&rel=16
Software summary / short description: English Language Pack Component

If the Windows installation on which a user installs the various `visualstudio2019` packages is not English, the English language pack will not be installed.

The English language pack is required for some build and package tools to function correctly, such as vcpkg.

Currently the solution is to open the visual studio installer GUI and add the English language pack, but it would be nice if it could be installed as a package on the command line.

**Comment by pauby** [comment]
@jberezanski is this something you'd consider adding to your Visual Studio packages?

**Comment by rkitover** [comment]
I had to actually remove my Russian language pack entirely, because even these commands in my powershell `$profile` still made some tools output russian:

```powershell
chcp 65001 > $null

set-culture en-US
```

And this caused this `cmake` bug for me:

https://gitlab.kitware.com/cmake/cmake/issues/17191

Once I removed the Russian language pack entirely and left just the English language pack, my `cmake` + `ninja` builds started working again.

Perhaps my issue is wrong, and what we really need is a commandline method of managing Visual Studio language packs, rather than just an English package.

What do you guys think?

**Comment by pauby** [comment]
@rkitover I'm not an avid user of Visual Studio and when I am I use the English version so I don't come across these issues. So to answer your question, without answering your question, I don't have an answer.

This repo is really for requesting packages or new maintainers for existing packages. I'm keen for any discussion around this issue to stay on-topic. My immediate thoughts are we leave this issue open to see if anybody can answer your question here. If no response then we close this issue and you ask the question in a more relevant area that will give you an answer? Then you can come back and raise a new issue or we re-open this one?

Thoughts?

**Comment by AdmiringWorm** [comment]
@rkitover @pauby considering that the visual studio packages already have a package parameter that allows the selection of the language pack to install (along with additional language packs), I am not really sure that a separate package for language packs is really needed.

![image](https://user-images.githubusercontent.com/1474648/82810097-e7843500-9e8d-11ea-8bb2-686196f6eabe.png)

The following image is also available for the vs2019 packages:
![image](https://user-images.githubusercontent.com/1474648/82810135-ff5bb900-9e8d-11ea-9ef3-5736c20920c4.png)

**Comment by rkitover** [comment]
@AdmiringWorm I did not know it was possible to pass extra parameters to packages, my apologies for not looking more deeply into the documentation.

**Comment by AdmiringWorm** [comment]
@rkitover no worries.
Be mindful that package parameters are not supported by all packages, as additional code is required by the maintainers to add support for different package parameters.
Typically when package parameters are supported, these are detailed on the package details page by the maintainer.

**Comment by jberezanski** [comment]
Sorry everyone for the long silence, I somehow missed this issue and only stumbled upon it by accident today.
Yes, the existing packages do support specifying all desired languages at install time. What they do not support right now is adding a language to an _existing_ VS installation. (One could probably hack it by installing any of the workload packages with the relevant language parameter added.)
Making dedicated packages for installing/removing language packs would be possible, but it would be much work for little gain, I believe.

**Comment by rkitover** [comment]
It may be worthwhile to consider defaulting to English on even non-English Windows installations, as the non-English build tool message output can sometimes break other build tools, and developers generally want to use these tools in English, but that's up to you guys.
