### ISSUE TITLE
HWiNFO version outdated

### ISSUE THREAD

**Issue by dandanio** [chocolatey-community/chocolatey-package-requests#819]
There is a new version of a popular package HWiNFO.
Your repo includes 6.26-4160 and the newest one is: 6.27-4170 Beta.

Please update and keep up the great work!

**Comment by AdmiringWorm** [comment]
The package [hwinfo](https://chocolatey.org/packages/hwinfo) is not maintained in this repository, please contact the maintainer of the package.

**Comment by AdmiringWorm** [comment]
Sorry, I thought I was in a different repository.

Please fill out the templated that was requested of you when you opened this issue.

**Comment by pauby** [comment]
Closing this as no update after 14 days.
