### ISSUE TITLE
RFM - Chrome History View (Nirsoft)

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#820]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/chromehistoryview
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/chromehistoryview/
Date the maintainer was contacted: 6 Sept 2019 via GitHub, 13 May 2020 via Chocolatey.org form
How the maintainer was contacted: Via Github issue and by the contact maintainers form on chocolatey.org

**Comment by tunisiano187** [comment]
Hello,
I have created the package for this one too, i'll ask to become maintainer too

**Comment by tunisiano187** [comment]
Package uploaded, waiting for verification
@pauby can ou change the label? Thank you

**Comment by tunisiano187** [comment]
Can you assign it to me ? to have the notifications.
Thank you

**Comment by TheCakeIsNaOH** [comment]
The new version by @tunisiano187 has been approved. Thanks for taking over this package.
