### ISSUE TITLE
RFM - Foldit

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-package-requests#821]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/foldit
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/foldit/
Date the maintainer was contacted: 13 May 2020
How the maintainer was contacted: Via contact maintainers form on Chocolatey.org.

**Comment by tunisiano187** [comment]
Hello,
I'll look into it this evening, as i'm already maintaining some of his packages.

**Comment by tunisiano187** [comment]
OK, package ready, i'll ask to be added as maintainer

**Comment by tunisiano187** [comment]
Package sent waiting for testing

**Comment by tunisiano187** [comment]
/attach @tunisiano187 tunisiano
You attach my user if it can help ;-)

**Comment by TheCakeIsNaOH** [comment]
Package version approved as of today, thanks for picking this up @tunisiano187
