### ISSUE TITLE
RFP - 20 missing packages

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#824]
1. Daemon Tools Lite [Disc Soft Ltd.]
2. AMD Chipset Drivers v2.04.28.626 [AMD]
3. AMD Radeon Software v20.5.1 (x64) [AMD]
4. AMD Ryzen Master v2.2.0.1543 [AMD]
5. ASUS AI Suite 3 v3.00.52 [ASUS]
6. ASUS AURA Lighting Control for Graphic card v0.0.6.7 [ASUS]
7. ASUS Boot Setting (Direct BIOS) v1.00.22 [ASUS]
8. ASUS EZ Update v3.00.11 [ASUS]
9. ASUS GPU Tweak II v2.1.7.1 [ASUS]
10. Samsung NVMExpress v3.3 [Samsung]
11. Rockstar Games Launcher [Rockstar Games]
12. Howard E-Mail Notifier v1.72 [The Sz Development]
13. iStripper v1.2.242 [TotemCore Ltd]
14. CPUID HW Monitor Pro v1.41 [CPUID]
15. The Matrix (Screensaver) v1.14 meticulous-Software.co.uk
16. TranslucentTB v4.4 [Sylveon - Github]
17. Winamp PlayaControl v1.66 android.malzner.net
18. Winamp Playlist File Remover forums.winamp.com/showthread.php?t=157049
19. O&O AppBuster v1.1.1339 [O&O Software GmbH]
20. Freemake YouTube To MP3 Boom [Freemake]

**Comment by tunisiano187** [comment]
Hi, you need to follow the guidelines here : https://github.com/chocolatey-community/chocolatey-package-requests/raw/master/README.md to make the work easier for everyone to follow the packages separately and follow the evolution.
Thank you

**Comment by mkevenaar** [comment]
Hi @EpsilonsQc just like @tunisiano187 already said, please create an issue for each of the items in the list. Also please use the template provided when you create the issue on GitHub and fill in all the required items.

**Comment by EpsilonsQc** [comment]
OK thanks for the heads up. Will do in due time.
