### ISSUE TITLE
RFM - cpu.z*

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-package-requests#827]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Existing Package Details

Package source URL:
https://github.com/majkinetor/au-packages/tree/master/cpu-z
https://github.com/majkinetor/au-packages/tree/master/cpu-z.portable
https://github.com/majkinetor/au-packages/tree/master/cpu-z.install

**Comment by tunisiano187** [comment]
I think i can take them in my automatic repository.

**Comment by majkinetor** [comment]
OK, thx, I am keeping them for now, I wanted to see if there is an interest.
