### ISSUE TITLE
RFM - Electron

### ISSUE THREAD

**Issue by petitchou** [chocolatey-community/chocolatey-package-requests#828]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/electron
Package source URL: https://github.com/electron/electron
Date the maintainer was contacted: June 17, 2020 - see below
How the maintainer was contacted: I did not attempt to contact the maintainer directly, unfortunately, but instead mailed the moderation team because I did not see that I was supposed to contact the package maintainer first. The moderation team said that this maintainer is no longer updating their packages, however, and the package is eight versions behind and plainly abandoned at this point.

**Comment by tunisiano187** [comment]
I'm trying to update it, i'll keep you in touch

**Comment by tunisiano187** [comment]
Package sumited, waiting for verification and approval

**Comment by petitchou** [comment]
Thanks! I appreciate it!

**Comment by tunisiano187** [comment]
OK, in moderation, if you need it quickly, you can force by using : choco install electron --version=8.3.3

**Comment by tunisiano187** [comment]
@AdmiringWorm , This package is now published. you can close this issue.
Thank you
