### ISSUE TITLE
RFP - Daemon Tools Lite

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#829]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.daemon-tools.cc/products/dtLite

Direct download URL for the software / installer : 
https://mirror07.daemon-tools.cc/getfile.php?p=http://na-us7.disc-tools.com/490c5175bff30bb11d317ca70e46a76f/DTLiteInstaller.exe

Software summary / short description: 
DAEMON Tools Lite allows you to mount all known types of disc image files and emulates up to 4 DT + SCSI + HDD devices. It enables you to create images of your optical discs and access them via well-organized catalog. Made by Disc Soft Ltd.

**Comment by AdmiringWorm** [comment]
This is not a request that can be be honored, due to publisher have requested the package basically not to exist.
See: https://github.com/chocolatey-community/chocolatey-package-requests/issues/372#issuecomment-408102941 for the more information.

**Comment by EpsilonsQc** [comment]
> This is not a request that can be be honored, due to publisher have requested the package basically not to exist.
> See: [#372 (comment)](https://github.com/chocolatey-community/chocolatey-package-requests/issues/372#issuecomment-408102941) for the more information.

Well, it's quite old (July 2018), so I just contacted the developer of Daemon Tools to see if they changed their mind. Will update this post accordingly if and when I receive a response from their end. Thanks.

> Dear Disc Soft Ltd, 

I would like to know if you changed your mind regarding "Daemons Tools Lite" being available as a package on chocolatey ?

https://github.com/chocolatey-community/chocolatey-package-requests/issues/829

Thank you.
