### ISSUE TITLE
RFP - AMD Chipset Drivers

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#830]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.amd.com/en/products/chipsets-am4

Direct download URL for the software / installer : 
https://drivers.amd.com/drivers/amd_chipset_software_2.04.28.626.exe

Software summary / short description: 
The AMD Ryzen™ Chipset Driver installation package contains various independent drivers. Made by AMD.

**Comment by AdmiringWorm** [comment]
@EpsilonsQc it looks like this is the package you are looking for: https://chocolatey.org/packages/amd-ryzen-chipset

If it is this package, and it isn't up to date please contact the maintainer of the package to get it updated (if there is no response from the maintainer, then follow the [triage process](https://chocolatey.org/docs/package-triage-process#package-is-outdated) to get it updated.

**Comment by EpsilonsQc** [comment]
> @EpsilonsQc it looks like this is the package you are looking for: https://chocolatey.org/packages/amd-ryzen-chipset
> 
> If it is this package, and it isn't up to date please contact the maintainer of the package to get it updated (if there is no response from the maintainer, then follow the [triage process](https://chocolatey.org/docs/package-triage-process#package-is-outdated) to get it updated.

I'll try to contact the package manager and update this post accordingly if I receive a message. Else I'll go with the triage process. Thanks.

**Comment by AdmiringWorm** [comment]
@EpsilonsQc can you give us a status update on this one?
Did you ever receive a response for this package?
Or did it get updated?

**Comment by EpsilonsQc** [comment]
> @EpsilonsQc can you give us a status update on this one?
> Did you ever receive a response for this package?
> Or did it get updated?

I did receive an update on Disqus from the package maintainer [dgatto](https://chocolatey.org/profiles/dgatto) claiming he is going through the process of getting an updated version approved.

https://chocolatey.org/packages/amd-ryzen-chipset

**Comment by tunisiano187** [comment]
The package is still waiting for approval, but the version is lower than the latest approved, so it won't be installed except if he hides the others and the users have to allow downgrade... Not really easy.

**Comment by EpsilonsQc** [comment]
> The package is still waiting for moderation, but the new version is lower than the latest approved, so it won't be installed except if he hides the others and the users have to allow downgrade... Not really easy.

Yeah the maintainer discussed about that issue with the reviewer :

> Unfortunately AMD has changed their versioning and recent drivers are semantically lower then previous releases. I wanted to sort through the package validation issues before addressing the version.
> 
> Would you be able to advise on a way to version the package? Keeping in mind that AMD may change their mind again. Maybe base the package version on release date (e.g. 2020.6.3) and add the actual driver version into the description?
> 
> Thanks again!

Their conversation can be found here :
https://chocolatey.org/packages/amd-ryzen-chipset/2.04.28.626
