### ISSUE TITLE
RFP - AMD Ryzen Master

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#832]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.amd.com/en/technologies/ryzen-master

Direct download URL for the software / installer : 
https://download.amd.com/Desktop/AMD-Ryzen-Master.exe

Software summary / short description: 
AMD Ryzen Master Utility for Overclocking Control. Made by AMD.

**Comment by Ocramius** [comment]
Related? https://github.com/dmariogatto/choco/blob/master/amd-ryzen-master/amd-ryzen-master.nuspec (sorry, I am profane of Microsoft/Windows ecosystem dependency/build tools)

**Comment by mikeee** [comment]
Doesn't look like the package was ever pushed, I'll pick this package up

**Comment by mikeee** [comment]
Pushed, awaiting moderation etc

**Comment by mikeee** [comment]
https://community.chocolatey.org/packages/amd-ryzen-master

Package request complete
