### ISSUE TITLE
RFP - Samsung NVMExpress

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#838]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.samsung.com/semiconductor/minisite/ssd/download/tools/

Direct download URL for the software / installer : 
https://s3.ap-northeast-2.amazonaws.com/global.semi.static/SamsungNVMExpressDriver3.3/7322A6707A720E1A71EF11A3BE1EED819E011D317626415F0281A78151C/Samsung_NVM_Express_Driver_3.3.exe

Software summary / short description: 
Samsung Driver for M.2 NVMe drive. Made by Samsung.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/samsung-nvme-driver

@EpsilonsQc: It needs to have the drive connected to install the package so I am not able to test. Is it possible for you to uninstall your current driver, restart your computer and test this Chocolatey package:
`choco install samsung-nvme-driver --pre --version="3.3"`

If it doesn't work, you will have to re-install manually your Samsung NVMe driver.

**Comment by EpsilonsQc** [comment]
> @EpsilonsQc: It needs to have the drive connected to install the package so I am not able to test. Is it possible for you to uninstall your current driver, restart your computer and test this Chocolatey package:
> `choco install samsung-nvme-driver --pre --version="3.3"`
> 
> If it doesn't work, you will have to re-install manually your Samsung NVMe driver.

**Tried to install the package but the console gave me this error :**

```
PS C:\Users\Epsilons> choco install samsung-nvme-driver --pre --version="3.3"
Chocolatey v0.10.15
samsung-nvme-driver
By installing you accept licenses for the packages.
Progress: Downloading samsung-nvme-driver 3.3... 100%

samsung-nvme-driver v3.3 - Possibly broken
samsung-nvme-driver package files install completed. Performing other installation steps.
Downloading samsung-nvme-driver
  from 'https://s3.ap-northeast-2.amazonaws.com/global.semi.static/SamsungNVMExpressDriver3.3/7322A6707A720E1A71EF11A3BE1EED819E011D317626415F0281A78151C/Samsung_NVM_Express_Driver_3.3.exe'
Progress: 100% - Completed download of C:\Users\Epsilons\AppData\Local\Temp\chocolatey\samsung-nvme-driver\3.3\Samsung_NVM_Express_Driver_3.3.exe (4.72 MB).
Download of Samsung_NVM_Express_Driver_3.3.exe (4.72 MB) completed.
Hashes match.
Installing samsung-nvme-driver...
ERROR: Running ["C:\Users\Epsilons\AppData\Local\Temp\chocolatey\samsung-nvme-driver\3.3\Samsung_NVM_Express_Driver_3.3.exe" /q ] was not successful. Exit code was '3010'. See log for possible error messages.
  samsung-nvme-driver may be able to be automatically uninstalled.
 The install of samsung-nvme-driver was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - samsung-nvme-driver (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
```

**Comment by chtof** [comment]
@EpsilonsQc 
Exit code was '3010', it means "Pending restart".
I added 3010 as valid exit code.
Could you try again?

- Uninstall your current driver
- Restart your computer
- Test this Chocolatey package:
`choco install samsung-nvme-driver --pre --version="3.3"`
- Test if the driver works as expected after the installation.

If it doesn't work, you will have to re-install manually your Samsung NVMe driver.

**Comment by EpsilonsQc** [comment]
@chtof The installation worked flawlessly and this is what I received from the console (note that the last 2 lines were in bold red) :

```
Chocolatey v0.10.15
Installing the following packages:
samsung-nvme-driver
By installing you accept licenses for the packages.
Progress: Downloading samsung-nvme-driver 3.3... 100%

samsung-nvme-driver v3.3 - Possibly broken
samsung-nvme-driver package files install completed. Performing other installation steps.
Downloading samsung-nvme-driver
  from 'https://s3.ap-northeast-2.amazonaws.com/global.semi.static/SamsungNVMExpressDriver3.3/7322A6707A720E1A71EF11A3BE1EED819E011D317626415F0281A78151C/Samsung_NVM_Express_Driver_3.3.exe'
Progress: 100% - Completed download of C:\Users\Epsilons\AppData\Local\Temp\chocolatey\samsung-nvme-driver\3.3\Samsung_NVM_Express_Driver_3.3.exe (4.72 MB).
Download of Samsung_NVM_Express_Driver_3.3.exe (4.72 MB) completed.
Hashes match.
Installing samsung-nvme-driver...
samsung-nvme-driver has been installed.
  samsung-nvme-driver may be able to be automatically uninstalled.
 The install of samsung-nvme-driver was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - samsung-nvme-driver (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
```

**Comment by chtof** [comment]
@EpsilonsQc Is the driver working as expected with the disk after the installation and the required reboot?

**Comment by EpsilonsQc** [comment]
> @EpsilonsQc Is the driver working as expected with the disk after the installation and the required reboot?

@chtof yes.
