### ISSUE TITLE
RFP - Rockstar Games Launcher

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#839]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://socialclub.rockstargames.com/rockstar-games-launcher

Direct download URL for the software / installer : 
https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe

Software summary / short description: 
Download and play the latest Rockstar Games PC titles. Made by Rockstar Games.

**Comment by chtof** [comment]
Duplicate: https://github.com/chocolatey-community/chocolatey-package-requests/issues/714

**Comment by AdmiringWorm** [comment]
Duplicate of #714

**Comment by AdmiringWorm** [comment]
thanks @chtof must have missed that when opening this up for maintainers
