### ISSUE TITLE
RFP - iStripper v1.2.242

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#841]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.istripper.com/

Direct download URL for the software / installer : 
https://www.istripper.com/fileaccess/software

Software summary / short description: 
Hot babes perform exclusive erotic shows on your desktop. Made by TotemCore Ltd.

**Comment by pauby** [comment]
This isn't a package that we would make available on the Community Repository. Closing the issue.
