### ISSUE TITLE
RFP - The Matrix Screensaver

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#842]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.meticulous-software.co.uk/downloads.shtml

Direct download URL for the software / installer : 
https://www.meticulous-software.co.uk/TheMatrix.exe

Software summary / short description: 
This is the best version of the Matrix Screensaver that exist, emulating the introduction to the movie and the code. Made by Meticulous-Software.

**Comment by teknowledgist** [comment]
I can take this one.

**Comment by AdmiringWorm** [comment]
@teknowledgist any update on this?

**Comment by teknowledgist** [comment]
Ah!  Sorry.  [It is long done](https://chocolatey.org/packages/thematrix).
