### ISSUE TITLE
RFP - TranslucentTB

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#843]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://github.com/TranslucentTB/TranslucentTB

Direct download URL for the software / installer : 
https://github.com/TranslucentTB/TranslucentTB/releases/download/2020.1/TranslucentTB-setup.exe

Software summary / short description: 
A lightweight utility that makes the Windows taskbar translucent/transparent on Windows 10.

**Comment by pauby** [comment]
I've actually been looking for something like this for a while so I'll pick this up!

**Comment by pauby** [comment]
This has been pushed - https://chocolatey.org/packages/translucenttb

**Comment by chtof** [comment]
Status: **Published**

- https://chocolatey.org/packages/translucenttb

Can be closed.

**Comment by EpsilonsQc** [comment]
I know you just pushed this package, but their is a new version available (Version 4 Hotfix 5 | 2020.2) that released 4 days ago.

https://github.com/TranslucentTB/TranslucentTB/releases/tag/2020.2

**Comment by EpsilonsQc** [comment]
@pauby @chtof I know you just pushed this package, but their is a new version available (Version 4 Hotfix 5 | 2020.2) that released 4 days ago.

https://github.com/TranslucentTB/TranslucentTB/releases/tag/2020.2
