### ISSUE TITLE
RFP - Valorant

### ISSUE THREAD

**Issue by yoanmalie** [chocolatey-community/chocolatey-package-requests#849]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://playvalorant.com
Direct download URL for the software / installer : https://valorant.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.live.eu.exe
Software summary / short description :
Valorant is a free-to-play multiplayer tactical first-person shooter developed and published by Riot Games.

The URL I provided contain "eu" and I don't know if this change something or not for others continents. If it's different, so by making differents packages with valorant-eu valorant-us etc can resolve the issue.

Thanks!

**Comment by AdmiringWorm** [comment]
Other urls for different regions seems to be available:
North America: https://valorant.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.live.na.exe
Asia: https://valorant.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.live.ap.exe

Probably others as well, didn't check any further.
Opening this one up to maintainers anyhow as I am sure something could be worked out to get the correct installer.

**Comment by ptanmay143** [comment]
Another thing I would like to mention for the maintainers is that this software does not provide a simple way of getting the version. So basically the chocolatey package would stay on the same version. Think of this as a online installer that would be the same downloaded anytime and anywhere. The rest of the content will be downloaded through the application, and not through the chocolatey package. Also, updating the software happens through in-built patches. So a chocolatey package update is also out of the question. I would like to know what the chocolatey community guidelines for such kind of software are.

**Comment by kamack38** [comment]
Package in the review: https://community.chocolatey.org/packages/valorant/41.0.5.4098838

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @kamack38
