### ISSUE TITLE
RFM - autoruns

### ISSUE THREAD

**Issue by Ashkaan** [chocolatey-community/chocolatey-package-requests#852]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [ ] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns

**Comment by tunisiano187** [comment]
Hello, 
I think it's already there : https://chocolatey.org/packages/autoruns
Are they different?

**Comment by AdmiringWorm** [comment]
@tunisiano187 
> We found both a section for the current maintainer and the one section for those not being the current maintainer being used. If you are not the current maintainer of the package, please remove the section with the header ### Current Maintainer. If you are the current maintainer, please remove the section with the header ### I DON'T Want To Become The Maintainer. We have stopped remaining validation, and will continue the validation check when you have updated the issue.

Because the template is not up to scratch, the validator don't get that far to validate that. He also have checked that he is the current maintainer.

@Ashkaan Please update the template as per the `Package Request Validation` comment.

**Comment by tunisiano187** [comment]
OK, missunderstood the request sorry.

i can take it if you add me as maintainer.
tunisiano
Have a nice day

**Comment by AdmiringWorm** [comment]
@tunisiano187 until a package has been marked as `Status: Available for maintainer(s)` it is not available to be picked up from this repository.

**Comment by Ashkaan** [comment]
Please give me instructions.  I reached out to the site admins and they told me that I only have to post here to be relieved.

**Comment by AdmiringWorm** [comment]
@Ashkaan see the comment from the bot: https://github.com/chocolatey-community/chocolatey-package-requests/issues/852#issuecomment-649500914

You may get additional requested changes once you have fixed the one it already have mentioned (since it it aborted the validation when it noticed conflicting sections).
