### ISSUE TITLE
RFM - bonjour

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#853]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/bonjour
Package source URL: https://support.apple.com/downloads/DL999/en_US/BonjourPSSetup.exe

Date the maintainer was contacted (in YYYY-MM-DD): 2020-06-08
How the maintainer was contacted: xmha97 used the 'Contact Maintainers' link on the package page.

**Comment by pauby** [comment]
The binaries cannot be embedded and @xmha97 confirmed that the latest installer is not available on the official Apple download page. Will update this with more info when I have it.

**Comment by xmha97** [comment]
You can see the latest version of bonjour into iTunes setup:

## iTunes 64-bit
![PeaZip](https://user-images.githubusercontent.com/23485114/85996612-b57e6980-ba1d-11ea-90e9-ab2cce4fa20e.png)

## iTunes 32-bit
![PeaZip](https://user-images.githubusercontent.com/23485114/85996636-bca57780-ba1d-11ea-9515-f2b382153e36.png)

iTunes can be downloaded from the following link:
https://www.apple.com/itunes/download/win64
https://www.apple.com/itunes/download/win32

**Comment by tunisiano187** [comment]
I'm already working on it, but was stuck with one thing, now it's working, so it's in moderation state

**Comment by xmha97** [comment]
> I'm already working on it, but was stuck with one thing, now it's working, so it's in moderation state

There is Bonjour v2.0 on the Chocolatey... I need Bonjour v3.1.0.2

**Comment by vexx32** [comment]
It's there, just currently in moderation. Once it passes the moderation requirements it will be available. 🙂

**Comment by xmha97** [comment]
> It's there, just currently in moderation. Once it passes the moderation requirements it will be available. 🙂

Great 👏

**Comment by tunisiano187** [comment]
It's Accepted, so this issue can be closed ;-)
Thank you
