### ISSUE TITLE
RFM - FreePlane

### ISSUE THREAD

**Issue by cmorty** [chocolatey-community/chocolatey-package-requests#854]
## I Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/FreePlane
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/freeplane

Date the maintainer was contacted (in YYYY-MM-DD): 2020-04-09
How the maintainer was contacted: https://github.com/dtgm/chocolatey-packages/issues/496

**Comment by gep13** [comment]
I have just added @tunisiano187 as a maintainer of this package.

**Comment by tunisiano187** [comment]
@gep13 , can you assign it to me?
That's usefull to follow what is still in progress.

Thank you

**Comment by AdmiringWorm** [comment]
@tunisiano187 Gary could not have added you until you added a comment to the issue.
This is a limitation of GitHub. (Just so you know).

**Comment by tunisiano187** [comment]
Thank you, didn't knew it.

**Comment by AdmiringWorm** [comment]
@tunisiano187 I don't think most people know that. I found that first out myself last weekend (while working on some upcoming enhancements to the request validator).

**Comment by tunisiano187** [comment]
Maybe you should add it in the Readme as a requisite to became maintainer ?

**Comment by AdmiringWorm** [comment]
I am planning to make some changes to the docs, to add a section of what is expected when a new maintainer is picking up a request.
I have not yet gathered the full thoughts of how this is detailed yet, though.

**Comment by tunisiano187** [comment]
This package as his first version approved a new one has been sent, so i think you can close the issue.
Thank you
