### ISSUE TITLE
RFM - SDIO

### ISSUE THREAD

**Issue by Spunkie** [chocolatey-community/chocolatey-package-requests#855]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/sdio
Package source URL: https://github.com/Spunkie/chocolatey-packages/tree/master/automatic/sdio

___
This package has been a constant thorn in my side.

The _developer_ always seems to be making minor tweaks to naming conventions, caplizations, internal dir structure, etc for no real reason. Then he stopped providing releases on sourceforge so I had to try to build a script that pull the latest version directly from the website([https://www.snappy-driver-installer.org/download/](https://www.snappy-driver-installer.org/download/)), but this also sporadically changes structure every few months so I just gave up. 

All this combined means the majority of the packages releases over the last 3 years don't work. So, I don't have the time or desire to babysit this package and I hope someone that uses is and cares can take it off my hand.

**Comment by Spunkie** [comment]
@AdmiringWorm Well the bot's broken, my https://chocolatey.org/profiles/Spunkie is linked to github correctly. Might have something to do with the link to the pkg source is broken on the current `SDIO` pkg.

**Comment by AdmiringWorm** [comment]
@Spunkie it is not broken, (at least not in that case). You didn't replace `your-chocolatey-username` with you actual chocolatey username.

**Comment by JuanJ67m** [comment]
we need a update

**Comment by tunisiano187** [comment]
Hello,
I'll take this one, @Spunkie can you add tunisiano as maintainer?
Thank you

**Comment by tunisiano187** [comment]
Package ready to be pushed

**Comment by tunisiano187** [comment]
Done and approved, so you can close this issue.
