### ISSUE TITLE
RFM - Windows Firewall Control

### ISSUE THREAD

**Issue by aelisya** [chocolatey-community/chocolatey-package-requests#856]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/windowsfirewallcontrol
Package source URL: https://www.binisoft.org/wfc

Date the maintainer was contacted (in YYYY-MM-DD): 2020-06-28
How the maintainer was contacted: https://chocolatey.org/packages/windowsfirewallcontrol/ContactOwners

**The new version is 6.3.0.0 out on 2020 JUNE 27, and the chocolatey one is 6.0.2.0 (2019 APRIL 17), many version are out since last update.**

**Comment by Cossey** [comment]
If no one takes up maintaining this package i might look into doing so, but i can only start work on it in 7-10 days time.

Just a note that they keep the exe file name the same every update so if someone tries to install an old version on the community repo then those installs will fail the hash check.

**Comment by tunisiano187** [comment]
I've requested maintinership monday, but still don't have any answer.
I'll ask the site admins for it
Th package is already ready

**Comment by tunisiano187** [comment]
Request sent to site admins

Le dim. 12 juil. 2020 à 03:33, Stewart Cossey <notifications@github.com> a
écrit :

**Comment by tunisiano187** [comment]
Package ready, just waiting for have the maintainer role andi'll push it asap

**Comment by aelisya** [comment]
@tunisiano187 thanks a lot :), i really like this software (since the way to monitor windows firewall is so... unfriendly for normal user)

**Comment by tunisiano187** [comment]
You're welcome

**Comment by aelisya** [comment]
@tunisiano187 new version failed the test (i will mark this closed thanks for all)

**Comment by AdmiringWorm** [comment]
@aelisya the request is not considered to be completed until the package has been approved by a moderator, thus I am re-opening this request again.

**Comment by aelisya** [comment]
@AdmiringWorm we have received the update, can i close it now ?

**Comment by AdmiringWorm** [comment]
@aelisya yup, now that the package version have been approved, this request is considered completed and can be closed.

**Comment by aelisya** [comment]
@tunisiano187 i just want to say on the website it say 6.3.0 and on the software installed 6.3.0.0, so it lead to perimed logo to show everytime (or it's juste me ?)

**Comment by tunisiano187** [comment]
Perimed logo ?, i'm using their installer so ...

**Comment by aelisya** [comment]
@tunisiano187 no sorry it was a bug on my side (it's why i have rapidly removed my comment)
