### ISSUE TITLE
RFM - Transmission

### ISSUE THREAD

**Issue by beefday** [chocolatey-community/chocolatey-package-requests#857]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/transmission
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/transmission/

Date the maintainer was contacted (in YYYY-MM-DD): 2020-07-07
How the maintainer was contacted: via email (using the 'Contact Maintainers' link on the package page.)

**Comment by tunisiano187** [comment]
As soon as the triage process is passed, i'll take this package, ass it is from DTGM to ;-)

**Comment by beefday** [comment]
> As soon as the triage process is passed, i'll take this package, ass it is from DTGM to ;-)

Great, thank you very much! :-)

**Comment by AdmiringWorm** [comment]
@tunisiano187 if you haven't already, please send off a message to the site admins to get added as a maintainer.

**Comment by tunisiano187** [comment]
Already done ;-) And the package is ready, and the PR too

**Comment by tunisiano187** [comment]
The package as been approved, you can close the issue.
Thank you
