### ISSUE TITLE
RFP - DroidCam

### ISSUE THREAD

**Issue by Daebis** [chocolatey-community/chocolatey-package-requests#858]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.dev47apps.com/
Direct download URL for the software / installer : https://files.dev47apps.net/DroidCam.Setup.6.3.0.exe
Software summary / short description: use your smartphone cam on PC (need install droidcam on you device)

**Comment by Daebis** [comment]
stupid bot are broken with bold xD

**Comment by AdmiringWorm** [comment]
@Daebis don't make changes to the layout of the template, the bot requires the layout itself to be unchanged.

**Comment by Daebis** [comment]
> @Daebis don't make changes to the layout of the template, the bot requires the layout itself to be unchanged.

i supose a human read that and it's better for eyes to have a little of bold :/
thanks for the help

**Comment by AdmiringWorm** [comment]
> i supose a human read that and it's better for eyes to have a little of bold :/

I can't speak of other people of course, but to me, I find it easier to read when it isn't bold.


BTW, any reason why you closed the issue? Do you no longer want to request a package for the software?

**Comment by Daebis** [comment]
mistake x)

**Comment by AdmiringWorm** [comment]
NOTE TO UPCOMING MAINTAINERS

The link on the download page is being invoked using javascript, so additional parsing may be necessary if being made as an automatic package.

**Comment by frankitox** [comment]
Hi @AdmiringWorm I'd like to maintain this package, I'm currently using DroidCam in Windows. Just created a [repository](https://github.com/frankitox/droidcam-chocolatey) for the package and push it. Now waiting for moderation.

**Comment by AdmiringWorm** [comment]
> Now waiting for moderation.

Please supply a link to the package when you push, this helps both us and the user requesting the package (as well as any user coming across the issue in the future) without having to look up and down to find it.

**Comment by frankitox** [comment]
This is the link to the [Chocolatey package](https://chocolatey.org/packages/droidcam/6.3.3) (Not approved yet).

**Comment by AdmiringWorm** [comment]
@frankitox and it won't be approved either, as you currently have a failing requirement (you should have gotten an email to the registered email account with the information).

![image](https://user-images.githubusercontent.com/1474648/97428973-0e500700-1917-11eb-9837-d2204408659e.png)


As long as the validator is failing, moderators won't even see the package until they are fixed (or if they can not be fixed, you leave a comment in the review section).

**Comment by pauby** [comment]
@frankitox Are you planning on fixing the package that was pushed? If not, we should close this and open an RFM request.

**Comment by frankitox** [comment]
Hi Paul. No, you can close it.
