### ISSUE TITLE
RFP - colour-contrast-analyser

### ISSUE THREAD

**Issue by charmarkk** [chocolatey-community/chocolatey-package-requests#859]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ThePacielloGroup/CCAe
Direct download URL for the software / installer : https://github.com/ThePacielloGroup/CCAe/releases/download/v3.1.1/CCA-Setup-3.1.1.msi
Software summary / short description: The Colour Contrast Analyser (CCA) helps you determine the legibility of text and the contrast of visual elements, such as graphical controls and visual indicators.

**Comment by nils-a** [comment]
https://chocolatey.org/packages/colour-contrast-analyser/3.1.1

**Comment by nils-a** [comment]
The package has been approved.

@AdmiringWorm could you please close this issue?
