### ISSUE TITLE
RFP - Compiler for 💎 Crystal language 💎

### ISSUE THREAD

**Issue by alexanderadam** [chocolatey-community/chocolatey-package-requests#860]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://crystal-lang.org/
Direct download URL for the software / installer: https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows#running-crystal-compiler-on-windows-bootstrapping
Software summary / short description: The Crystal Programming Language

## Further information

[Gary advised me to open this issue](https://twitter.com/gep13/status/1283656124491878403) (hi Gary! :wave:) and I want you to  keep in mind that publishing Crystal on Windows is currently still not finished. So I hope that I also speak for others when I say that you are very welcome to help to bring Crystal to the Windows ecosystem if you're interested.

* https://github.com/crystal-lang/distribution-scripts/issues/64
* https://github.com/crystal-lang/crystal/issues/5430#issuecomment-641872261
* https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows#running-crystal-compiler-on-windows-bootstrapping

**PS:** There's also the possibility [to use it with WSL](https://crystal-lang.org/install/on_wsl/) (apart from the currently mentioned unfinished native way)

**Comment by pauby** [comment]
Given this has had no update since created and it looks like it needs to be [compiled from source](https://github.com/crystal-lang/crystal/wiki/Porting-to-Windows#building-crystal-for-windows) I'm going to go ahead and close this. If we need to reopen it again, we can do.
