### ISSUE TITLE
RFP - travis-cli

### ISSUE THREAD

**Issue by mcsitter** [chocolatey-community/chocolatey-package-requests#861]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/travis-ci/travis.rb
Direct download URL for the software / installer : https://github.com/travis-ci/travis.rb/releases/latest
Software summary / short description: This is the command line interface to interact with travis. You can read more on the project page. Travis CI is a well known and widely used CI/CD platform especially for open source repositories.

This is a package which is installed with gem. I suppose that means, that ruby has to be defined as a dependency.
Ruby luckily is a package already: https://chocolatey.org/packages/ruby

**Comment by AdmiringWorm** [comment]
Notice to any upcoming maintainer, this request will require a request on ruby and installation to happen through a call to `gem`.

**Comment by naveen521kk** [comment]
I will take up this. I have done an [automatic updating package](https://github.com/naveen521kk/au-packages/tree/master/travis) but when running in Appveyor, It gives an [error](https://ci.appveyor.com/project/naveen521kk/au-packages/builds/34599681#L115) like below
```sh
     Chocolatey v0.10.15 Attempting to push travis.1.8.8.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. (7.40s)
``` 
Is it due to anybody else working on this or is it reserved or something? But when I visit https://chocolatey.org/packages/travis I get a 404. Can anybody help on this?

**Comment by tunisiano187** [comment]
It is possible that the package already exist but is hidden

**Comment by pauby** [comment]
@naveen521kk Have you packed Travis or the CLI? Your package name is `travis` not `travis-cli`.

See https://github.com/chocolatey/chocolatey.org/issues/613 for your issue.

**Comment by AdmiringWorm** [comment]
@naveen521kk you are most likely being affected with a known problem on chocolatey.org (https://github.com/chocolatey/chocolatey.org/issues/613).
Unfortunately there isn't any known workaround AFAIK right now, the only thing you can do is to try again later.

@tunisiano187 even if the package is hidden (or unlisted, fully rejected, and so on) they will still show up when you go to the package url.

**Comment by AdmiringWorm** [comment]
@pauby I would actually suggest that he would keep it with the `travis` id, as that would be consistent with what is used on other package managers (on linux): https://repology.org/project/travis/versions

**Comment by naveen521kk** [comment]
I will try pushing it later. Also, I will keep the id as `travis` as it is consistent with other package manager. 
Cheers

**Comment by naveen521kk** [comment]
That error shows still now. Anything can be done?

**Comment by naveen521kk** [comment]
Still doesn't allow me to push.

**Comment by gep13** [comment]
@naveen521kk I have just raised this issue on your repository:

https://github.com/naveen521kk/au-packages/issues/2

Which explains what is going on with this package.

**Comment by naveen521kk** [comment]
Package has been successfully pushed. @gep13 Thanks for informing about that. :)

**Comment by naveen521kk** [comment]
Approved
