### ISSUE TITLE
RFM - spybot

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#863]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/spybot/2.8.68.0
Package source URL: https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/spybot

PR are accepted too if you have the solution
https://github.com/tunisiano187/Chocolatey-packages/issues/9

**Comment by chtof** [comment]
It looks like it's a know issue since version 2.7: https://forums.spybot.info/showthread.php?77434-Install-Spybot-2-8-67-0-Silent-Mode-Batch&p=484652
