### ISSUE TITLE
RFP - wsl-ubuntu-2004

### ISSUE THREAD

**Issue by michaelmhoffman** [chocolatey-community/chocolatey-package-requests#865]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.microsoft.com/store/apps/9n6svws3rx71
Direct download URL for the software / installer : https://aka.ms/wslubuntu2004
Software summary / short description:

This packages installs Ubuntu 20.04 LTS (Focal Fossa) for Windows Subsystem for Linux.

Manual download instructions from Microsoft: https://docs.microsoft.com/en-us/windows/wsl/install-manual

Previous package: https://chocolatey.org/packages/wsl-ubuntu-1804
Previous package source: https://github.com/bcurran3/ChocolateyPackages/tree/master/wsl-ubuntu-1804

Previous package does not work perfectly as it requires some manual setup (see below).

## Package Expectations

1. ~Enable WSL2 (required for Ubuntu 20.04)~
2. Perform initial setup of the distro as the Microsoft Store download does — creating a user within WSL and setting that as the default user when calling from Windows
3. Ensure that it can be used when not under elevation

**Comment by pauby** [comment]
I will pick this up.

**Comment by Trance-Paradox** [comment]
yes very much appreciated thank you

**Comment by daronmcintosh** [comment]
I created a package for this without realizing that this repo exists. 

Package: https://chocolatey.org/packages/wsl-ubuntu-2004
Github: https://github.com/daronmcintosh/chocolatey-packages/tree/master/wsl-ubuntu-2004

@michaelmhoffman

> Enable WSL2 (required for Ubuntu 20.04)

Where did you see that wsl2 is required for 20.04? I just tested it and wsl1 can be used with 20.04. 

Some things to note:
- wsl1 or wsl2 is **NOT** installed with this package because both require a restart if wsl wasn't installed before (fresh installs of windows)
- if wsl 1 was installed before, you can install https://chocolatey.org/packages/wsl2 (I maintain this package) to enable wsl 2. 

See both packages' description for more info.


> Perform initial setup of the distro as the Microsoft Store download does — creating a user within WSL and setting that as the default user when calling from Windows

Based on my knowledge, you have to open up the app after it is installed from the store then configure a username and password. Although, I could add a param like "/DefaultUser:root" that sets the default user.

>  Ensure that it can be used when not under elevation

You should be able to use ubuntu when not elevated but let me know if you encounter any issue by creating an issue under the github repo.

**Comment by pauby** [comment]
@daronmcintosh I've not had a chance to look at this as yet but that package should provide a consistent experience alongside the other WSL packages. So if it's doing something different then we should look more closely at that.

> wsl1 or wsl2 is NOT installed with this package because both require a restart if wsl wasn't installed before (fresh installs of windows)

Does this not happen with the other WSL packages?

> Based on my knowledge, you have to open up the app after it is installed from the store then configure a username and password. Although, I could add a param like "/DefaultUser:root" that sets the default user.

Does the other packages provide this?

Apologies for many questions that I can look up the answers to. I don't have the time at the moment but will have tomorrow. I just wanted to get those questions in here just now.

**Comment by daronmcintosh** [comment]
`wsl-ubuntu-2004` checks if wsl is installed. If wsl is installed, it downloads the `.appx` package from `https://aka.ms/wslubuntu2004` and installs it with `Add-AppxPackage`. If wsl is not installed, it fails the installation.

When you say other package, I assumed you're referring to https://chocolatey.org/packages/wsl-ubuntu-1804.

> Does this not happen with the other WSL packages?

Yeah, `wsl-ubuntu-1804` declares a dependency on wsl 1 [here](https://github.com/bcurran3/ChocolateyPackages/blob/master/wsl-ubuntu-1804/wsl-ubuntu-1804.nuspec#L32). However, a user that runs `choco install wsl-ubuntu-1804` on a system where wsl wasn't enabled before will always get back an error even though there is a dependency on wsl 1. choco log showing error:
```
2020-09-03 11:36:18,407 1136 [INFO ] - VERBOSE: See https://aka.ms/wslinstall for details.
2020-09-03 11:36:18,407 1136 [INFO ] - VERBOSE: WslRegisterDistribution failed with error: 0x8007019e
2020-09-03 11:36:18,407 1136 [INFO ] - VERBOSE: 
2020-09-03 11:36:18,407 1136 [INFO ] - VERBOSE: The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
2020-09-03 11:36:18,407 1136 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\unzipped\ubuntu1804.exe" install --root ] exited with '1'.
2020-09-03 11:36:18,422 1136 [ERROR] - ERROR: Running ["C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\unzipped\ubuntu1804.exe" install --root ] was not successful. Exit code was '1'. See log for possible error messages.
2020-09-03 11:36:18,454 1136 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\tools\ChocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '1'.
2020-09-03 11:36:18,454 1136 [DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
2020-09-03 11:36:18,470 1136 [DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
2020-09-03 11:36:18,532 1136 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804'
2020-09-03 11:36:18,532 1136 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\wsl-ubuntu-1804\Ubuntu_1804.2019.522.0_x64.appx.txt'
```
> Does the other packages provide this?

Yes and no, it sets the default user to root and you can't change this. See: https://github.com/bcurran3/ChocolateyPackages/blob/master/wsl-ubuntu-1804/tools/ChocolateyInstall.ps1#L26

**Comment by daronmcintosh** [comment]
> Although, I could add a param like "/DefaultUser:root" that sets the default user.

I realized that this cannot be done. 

However, a param that could be added is "/InstallRoot" which sets the default user as root.

**Comment by pauby** [comment]
Thanks for clarifying that @daronmcintosh. While this isn't your issue, I'm concerned about:

> Yeah, wsl-ubuntu-1804 declares a dependency on wsl 1 here. However, a user that runs choco install wsl-ubuntu-1804 on a system where wsl wasn't enabled before will always get back an error even though there is a dependency on wsl 1. 

I'm wondering if the issue is just a reboot.

> However, a param that could be added is "/InstallRoot" which sets the default user as root.

I thought the default user was root?

**Comment by daronmcintosh** [comment]
> I'm wondering if the issue is just a reboot.

Yeah, the PC has to be rebooted before the distro can be installed.

I faced a similar issue with the `wsl2` package that I solved with a param and documentation. See the package description for more info: <https://chocolatey.org/packages/wsl2#description>

> I thought the default user was root?

Only if you run `ubuntu.exe install --root`. If you open the app from the start menu or run `ubuntu.exe`, it will ask you to create a user that will be set as the default user.

Btw, I added the "/InstallRoot" param to the `wsl-ubuntu-2004` [package](https://chocolatey.org/packages/wsl-ubuntu-2004)

**Comment by pauby** [comment]
> Only if you run ubuntu.exe install --root. If you open the app from the start menu or run ubuntu.exe, it will ask you to create a user that will be set as the default user.

You only really do this once so when I couldn't remember what happened.

> Btw, I added the "/InstallRoot" param to the wsl-ubuntu-2004 package

Awesome.

Thanks for clarifying that. I will now disappear back into the shadows 😄

**Comment by daronmcintosh** [comment]
> You only really do this once so when I couldn't remember what happened.

Yeah, this is only done once after you install the distro.

> Thanks for clarifying that. I will now disappear back into the shadows 😄

:v:

**Comment by michaelmhoffman** [comment]
Thanks for your work!

> Where did you see that wsl2 is required for 20.04? I just tested it and wsl1 can be used with 20.04.

I have tried using it with WSL1 before and it seems to work initially but some things that work with WSL1 and 18.04 only work for 20.04 if you have WSL2. In the blog post ["Ubuntu 20.04 and WSL 1"](https://discourse.ubuntu.com/t/ubuntu-20-04-and-wsl-1/15291/1), @sirredbeard explains some of the issues and recommends that Ubuntu 20.04 not be used with WSL1 for now. It looks like the underlying issue (microsoft/WSL#4898) was just fixed 10 d ago, but only in the Windows Beta channel and Release Preview channel.

To make a long story short, some things are broken on the Windows release channels for the combination of WSL 1 and Ubuntu 20.04, but maybe not for long. I retract my recommendation that the chocolatey package require WSL 1, but for the time being things aren't going to work well for some users if they are on WSL 1.

**Comment by Trance-Paradox** [comment]
Do I have to uninstall Ubuntu 2004 installed from windows store before installing with chocolatey?

**Comment by daronmcintosh** [comment]
> Do I have to uninstall Ubuntu 2004 installed from windows store before installing with chocolatey?

No, you don't have to and you can continue using the version installed through the store. But if you want to use the chocolatey version, I suggest unregistering Ubuntu 20.04 then installing the choco package.

**Comment by Trance-Paradox** [comment]
> > Do I have to uninstall Ubuntu 2004 installed from windows store before installing with chocolatey?
> 
> No, you don't have to and you can continue using the version installed through the store. But if you want to use the chocolaty version, I suggest unregistered Ubuntu 20.04 then installing the choco package.

ooo OK actually i was getting an error while installing Ubuntu 2004. I already have the store version installed so I thought that it was causing an collision with the chocolaty version.
