### ISSUE TITLE
RFM - ElasticSearch

### ISSUE THREAD

**Issue by peterbarendse** [chocolatey-community/chocolatey-package-requests#868]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/elasticsearch
Package source URL: https://github.com/elastic/chocolatey-elasticsearch

Date the maintainer was contacted (in YYYY-MM-DD): 2020-07-03
How the maintainer was contacted: Through Disquis and 'Contact Owners' from on chocolatey.org

**Comment by mkevenaar** [comment]
I recently become the maintainer for ElasticSearch and have pushed a new version.

**Comment by mkevenaar** [comment]
https://chocolatey.org/packages/elasticsearch/7.8.0
