### ISSUE TITLE
RFM - xmplay

### ISSUE THREAD

**Issue by zverev-iv** [chocolatey-community/chocolatey-package-requests#869]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to my **new account**

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/xmplay
Package source URL: https://github.com/zverev-iv/choco-xmplay

My old account - **zitter**. My new account - **zverev-iv**

**Comment by tunisiano187** [comment]
You can do it yourself here : https://chocolatey.org/packages/xmplay/ManagePackageOwners

**Comment by zverev-iv** [comment]
oh! thanks wery much!
