### ISSUE TITLE
RFP - Compressonator

### ISSUE THREAD

**Issue by cholmquist** [chocolatey-community/chocolatey-package-requests#874]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://gpuopen.com/compressonator/
Direct download URL for the software / installer :https://github.com/GPUOpen-Tools/compressonator/releases/download/V4.0.4855/CompressonatorCLI_x64_4.0.4855.exe
Software summary / short description:
Compressonator is a set of tools to allow artists and developers to more easily work with compressed assets and easily visualize the quality impact of various compression technologies.  

It consists of a GUI application, a command line application, and an SDK for easy integration into a developer toolchain.

**Comment by cholmquist** [comment]
I had provided an incorrect link to the executable in question. The correct one is
https://github.com/GPUOpen-Tools/compressonator/releases/download/V4.0.4855/CompressonatorCLI_x64_4.0.4855.exe

**Comment by tunisiano187** [comment]
I will take a look into that package

**Comment by tunisiano187** [comment]
https://chocolatey.org/packages/compressonator-cli/4.0.4855

**Comment by tunisiano187** [comment]
@AdmiringWorm , this package as been approved.
So this issue can be closed.
Thank you
