### ISSUE TITLE
RFM - Clojure

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey-community/chocolatey-package-requests#876]
https://chocolatey.org/profiles/matevarga

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/clojure
Package source URL: ???

This was noted as no updates in six years: https://chocolatey.org/packages/clojure#comment-5035127079

The message that came out of that was replied to directly in email by Mate: 

> "I'm happy to hand over the maintenance, I'm using WSL nowadays."

So I believe this is safe to say it is up for new maintainership.

**Comment by matevarga** [comment]
Hi, I confirm that I am the maintainer of the package and wish to pass it to someone else. Cheers,
Mate

**Comment by ferventcoder** [comment]
Overriding this tool.

**Comment by dgalbraith** [comment]
I am happy to pick this one up and update the package if my Chocolatey user name dgalbraith could be added as a maintainer.

**Comment by mikeee** [comment]
I've been assigned maintainer, will create a package and push this soon.

**Comment by mikeee** [comment]
Pushed, awaiting review etc

**Comment by mikeee** [comment]
Complete - https://community.chocolatey.org/packages/clojure#versionhistory
Three versions approved and functional.

**Comment by TheCakeIsNaOH** [comment]
Thanks for taking the package over @mikeee
