### ISSUE TITLE
RFP - amazon-chime

### ISSUE THREAD

**Issue by eugenelim** [chocolatey-community/chocolatey-package-requests#878]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://aws.amazon.com/chime/download/
Direct download URL for the software / installer : https://clients.chime.aws/win/latest
Software summary / short description: Amazon Chime is a communications service that lets you meet, chat, and place business calls inside and outside your organization, all using a single application.

**Comment by eugenelim** [comment]
Updated checklist in issue.

**Comment by tunisiano187** [comment]
Hello,
just saw this request, but i already have created this package.
https://chocolatey.org/packages/amazon-chime

Have a nice day
