### ISSUE TITLE
RFM - executor

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#880]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/executor
Package source URL: https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/Executor

**Comment by dgalbraith** [comment]
I have provided a pull request (https://github.com/tunisiano187/Chocolatey-packages/pull/2788) that will address the 406 error for your review.

I would suggest that you merge into a branch as there are a few other items that you will need to address before pushing the package, primarily the autostart following install which displays a GUI for initial setup immediately post install.

**Comment by tunisiano187** [comment]
Thank you for your help @dgalbraith .
