### ISSUE TITLE
RFM - qttabbar

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-package-requests#881]
## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/qttabbar
Package source URL: https://github.com/dtgm/chocolatey-packages/tree/master/automatic/qttabbar

Date the maintainer was contacted (in YYYY-MM-DD): 2020-08-02
How the maintainer was contacted: maintainer contact form and the other is dtgm who isn't active anymore

**Comment by tunisiano187** [comment]
the version 1038 exist and the version 1040 is only an update, not a complete installer

**Comment by tunisiano187** [comment]
@AdmiringWorm , FYI i've tryied some solutions, but the message is still the same

**Comment by AdmiringWorm** [comment]
@tunisiano187 you removed the `(in YYYY-MM-DD):` from the template.
It is not expected to have the template changed, only to fill out the necessary information.

**Comment by gep13** [comment]
@pauby it looks like this package has been picked up: https://community.chocolatey.org/packages/qttabbar Can we close this issue?
