### ISSUE TITLE
RFM - rubberduck

### ISSUE THREAD

**Issue by kevinoid** [chocolatey-community/chocolatey-package-requests#882]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/rubberduck
Package source URL: https://github.com/ptwales/Rubberduck-Choco

Date the maintainer was contacted (in YYYY-MM-DD): 2017-10-22
How the maintainer was contacted: Maintainer added "notification of orphaned repo" to README.md in ptwales/Rubberduck-Choco@a938ed1

**Comment by tunisiano187** [comment]
@AdmiringWorm , i'll take this one.

**Comment by AdmiringWorm** [comment]
@tunisiano187 if you haven't already, please send off an email using the `Contact Site Admins` link to get added (I assume you already have though, which is why I assigned you already. Usually we don't assign you until you get added).

**Comment by tunisiano187** [comment]
Thank you
the package is uploaded, just a problem on the verifier with the dotnet4.6.2 (dependency) that fails to install...

**Comment by kevinoid** [comment]
I've been using the [rubberduck package](https://chocolatey.org/packages/rubberduck) since shortly after it was approved on October 4 and it works like a charm.  Thanks for maintaining it @tunisiano187!

Safe to close as "Status: Published" @AdmiringWorm?

**Comment by tunisiano187** [comment]
Oups sorry, i forgot ask to close
