### ISSUE TITLE
RFM - naps2

### ISSUE THREAD

**Issue by CypherNL** [chocolatey-community/chocolatey-package-requests#885]
## Current Maintainer
- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist
- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/naps2
Package source URL: https://github.com/CypherNL/chocolatey-packages/tree/master/automatic/naps2

Package.install URL: https://chocolatey.org/packages/naps2.install
Package.install source URL: https://github.com/CypherNL/chocolatey-packages/tree/master/automatic/naps2.install

**Comment by dgalbraith** [comment]
I will pick these up - chocolatey user [dgalbraith](https://chocolatey.org/profiles/dgalbraith).

**Comment by CypherNL** [comment]
Added to the naps2 and naps2.install. My bad for taking so long. I wasn't aware i had to add you to the maintainers list myself.

**Comment by CypherNL** [comment]
@designxsteph Did you have received the request to be added as maintainer for the naps2 and naps2.install packages? I haven't received any confirmation that you've accepted the request as the maintainership status is still on pending approval.

**Comment by pauby** [comment]
@CypherNL I think you meant to tag @dgalbraith

**Comment by designxsteph** [comment]
> @designxsteph Did you have received the request to be added as maintainer for the naps2 and naps2.install packages? I haven't received any confirmation that you've accepted the request as the maintainership status is still on pending approval.

Hey there, I think maybe you meant to tag @dgalbraith ?

**Comment by CypherNL** [comment]
Yeah, i think i though it was the correct option but i didn't check if it was the correct option. Whoops...

**Comment by CypherNL** [comment]
@dgalbraith Do you still want to maintain this package? You're still pending in the maintainer list at both packages.

**Comment by dgalbraith** [comment]
@CypherNL yes - will pick up and maintain.  I don't have the maintainer addition requests on these.  Is it possible to resend them or do I need to ask the Site Admins to add me?

**Comment by CypherNL** [comment]
@dgalbraith I have re-added you as the maintainer of these 2 packages so you should get the request to approve for being a maintainer of these 2 packages pretty soon.

Let me know if you have received them and accepted them. If you didn't received them, let me also know.

**Comment by dgalbraith** [comment]
@CypherNL the maintenance of the packages has now been migrated - source code and history have been merged in to [dgalbraith/chocolatey-packages/naps2](https://github.com/dgalbraith/chocolatey-packages/naps2) and [dgalbraith/chocolatey-packages/naps2.install](https://github.com/dgalbraith/chocolatey-packages/naps2.install).

An automated updater has been implemented and the naps2.portable package also incorporated.

**Comment by pauby** [comment]
@dgalbraith @CypherNL Is there anything more that needs to be done here? Or can we close this request?

**Comment by CypherNL** [comment]
I think you can, not sure if @dgalbraith needs to do something, it seems everything's OK.

**Comment by dgalbraith** [comment]
@pauby Nothing further required - the migration of maintenance is done and the request can now be closed as it is complete.
