### ISSUE TITLE
RFP - gtkhash

### ISSUE THREAD

**Issue by valtoree** [chocolatey-community/chocolatey-package-requests#889]
##Software summary / short description:

A cross-platform desktop utility for computing message digests or checksums 

https://github.com/tristanheaven/gtkhash

https://github.com/tristanheaven/gtkhash/releases/

<!-- ## Package Expectations
adding icon to the desktop

P.s. yes I have searched for the package on chocolatey.org and its not there.

**Comment by AdmiringWorm** [comment]
Closing as the issue has not been updated.
