### ISSUE TITLE
RFP - Disk Usage

### ISSUE THREAD

**Issue by Ashkaan** [chocolatey-community/chocolatey-package-requests#890]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://docs.microsoft.com/en-us/sysinternals/downloads/du
Direct download URL for the software / installer : https://download.sysinternals.com/files/DU.zip
Software summary / short description: Command-Line Tool to get disk usage information.

## Package Expectations

Just install and be able to run "du" from PowerShell.

**Comment by tunisiano187** [comment]
This package already exists, is there a problem with it?

**Comment by Ashkaan** [comment]
Holy moly.  I swear I searched "Disk Usage" and couldn't find it on the website.  I'm so sorry for the trouble.
