### ISSUE TITLE
RFP - go-fonts

### ISSUE THREAD

**Issue by whitis** [chocolatey-community/chocolatey-package-requests#893]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL:
https://github.com/golang/image/tree/master/font/gofont

Direct download URL for the software / installer:
Download individual files: https://github.com/golang/image/tree/master/font/gofont/ttfs
License : https://github.com/golang/image/blob/master/font/gofont/ttfs/README
Download all files: https://go.googlesource.com/image/+archive/master/font/gofont/ttfs.tar.gz

Software summary / short description:
These are about the only fonts with properly distinguished (slashed or dotted) zeros and ones in both proportional and monospaced.    The go fonts are distributed as part of the go language (and might even be included in the chcoloatey package for the language [update: they are not]) but they should be available without installing an entire programming environment.  They also have a more permissive license than most other "free" fonts which can be very important when working on embedded systems or fonts as executable code.   Go fonts seem to be installed by default in ubuntu 18.04.  Windows users may encounter Go font in documents from Linux users.  Very useful for programmers and other technical users who need to be able to differentiate zeros from O as in Oscar and l as in lima and for ham radio operators.   After spending many hours going through freely available fonts with properly differentiated ones and zeros, the Go Fonts were the clear winner.  Competition: FiraCode has ligature nonsense and FiraCode, DejaVuSansMono, and Hack are monospace only.   Also many English speaking people prefer the slashed zeros to dotted ones. 

DejaVuSansMono package would make a good template, it uses the newer font install extension and the packaging itself (unlike the DejaVu font) is licensed similarly to the go fonts themselves.

Font files should be installed and registered with the system (both of which the chocolatey font extension will help with).

If one is on a roll, another font that has an even more open license (public domain) but less unicode coverage? and undiferentiated zeros is Canada1500 (not to be confused with Canada 150) and it has twice as many included glyphs as Go fonts.
https://typodermicfonts.com/wp-content/uploads/2017/06/canada1500.zip
https://typodermicfonts.com/canada1500/

**Comment by dgalbraith** [comment]
[Go-fonts package](https://www.chocolatey.org/packages/go-fonts) has been pushed and is ready for moderation.

**Comment by dgalbraith** [comment]
The [Go-fonts package](https://www.chocolatey.org/packages/go-fonts) is now available in the community repository.
