### ISSUE TITLE
RFP - tvrename

### ISSUE THREAD

**Issue by CypherNL** [chocolatey-community/chocolatey-package-requests#894]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/TV-Rename/tvrename
Software Homepage: https://www.tvrename.com
Direct download URL for the software / installer : https://github.com/TV-Rename/tvrename/releases/download/3.3.1/TVRename-3.3.1.exe
Software summary / short description: 
> TV Rename is a media management tool that runs on Windows 7 and later and looks after all your TV show files; making them presentable for Kodi (XBMC), Mede8er, PyTivo and other media hubs

**Comment by Xav83** [comment]
I pick up this package 🙂

**Comment by Xav83** [comment]
FYI, I pushed a chocolatey package [here](https://community.chocolatey.org/packages/tvrename), which is currently passing the tests.

**Comment by CypherNL** [comment]
Nice! Thanks for picking this up!

**Comment by pauby** [comment]
@Xav83 Just an FYI, the package failed Verification.

**Comment by Xav83** [comment]
Yes, I've seen it @pauby, I will investigate it this weekend, as I will have some time to work on it 😉

**Comment by Xav83** [comment]
I am currently having some issues with the silent mode of the Tvrename installer. 🤔 
Indeed, when I specify the option `/S` to install the program silently (since this is a NSIS installer), an error occurs.

For information, when I run the installer with this option directly on my machine, then no error occurs. It only seems to happen when running the tests in the Chocolatey Test environment.

Maybe you will have some insight about that kind of errors, @pauby, @CypherNL or anyone else.
Here is the error I currently have:
```
Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\tvrename\3.3.1' -statements '/S ' -exeToRun 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\tvrename\3.3.1\TVRename-3.3.1.exe'
Test-ProcessAdminRights: returning True
Elevating permissions and running ["C:\Users\Administrator\AppData\Local\Temp\chocolatey\tvrename\3.3.1\TVRename-3.3.1.exe" /S ]. This may take a while, depending on the statements.


Stderr from the command:



```

**Comment by jakublevy** [comment]
I have tested the package and there is also a problem that the uninstallation is not silent.
If you execute `"C:\Program Files (x86)\TVRename\Uninstall.exe" "/S"` it still shows one dialog.

![](https://i.ibb.co/ZVXvH6W/tvrename-uninstall.png)

You will need to script this using AutoHotkey/AutoIt, preferably with a package argument that let users choose whether to remove settings or not.

**Comment by Xav83** [comment]
The latest version (4.7.5) of tvrename actually passes the Chocolatey validation process ([Chocolatey package](https://community.chocolatey.org/packages/tvrename/4.7.5)). :tada: 
We are now waiting for a moderator to review it :slightly_smiling_face:

**Comment by TheCakeIsNaOH** [comment]
Package approved, thanks for creating the package @Xav83
