### ISSUE TITLE
RFP - scc

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#900]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/boyter/scc
Direct download URL for the software / installer : https://github.com/boyter/scc/releases/download/v2.13.0/scc-2.13.0-x86_64-pc-windows.zip
Software summary / short description:
> Sloc, Cloc and Code: scc is a very fast accurate code counter with complexity calculations and COCOMO estimates written in pure Go

**Comment by naveen521kk** [comment]
I will do this.

**Comment by naveen521kk** [comment]
Pushed it https://chocolatey.org/packages/scc
