### ISSUE TITLE
RFP - fantasque-sans

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#901]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/belluzj/fantasque-sans
Direct download URL for the software / installer :
https://github.com/belluzj/fantasque-sans/releases/download/v1.8.0/FantasqueSansMono-Normal.zip
Software summary / short description:
> A font family with a great monospaced variant for programmers.

**Comment by teknowledgist** [comment]
I've got this.  [Package created and submitted](https://chocolatey.org/packages/fantasque-sans.font).
