### ISSUE TITLE
RFP - vazir-fonts

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#902]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/rastikerdar/vazir-font
Direct download URL for the software / installer :
https://github.com/rastikerdar/vazir-font/releases/download/v26.0.2/vazir-font-v26.0.2.zip
Software summary / short description:
> A Persian (Farsi) Font - قلم (فونت) فارسی وزیر

**Comment by AdmiringWorm** [comment]
Note to anyone picking up this request.
Remember that all packages on the community repository requires the description of the software to be in English, even when the software (in this case the font) is for a different language.

**Comment by dgalbraith** [comment]
This one looks like it has been packaged https://chocolatey.org/packages/vazir-font and is available for use.

**Comment by AdmiringWorm** [comment]
@dgalbraith looks that way. Closing this issue as a result.
