### ISSUE TITLE
RFP - scratch

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#903]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://scratch.mit.edu/
Direct download URL for the software / installer :
https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe
Software summary / short description:
> Create stories, games and animations. Share with others around the world.

**Comment by tunisiano187** [comment]
This is one of the packages i'm maintaining, you can find it here : https://chocolatey.org/packages/scratch
