### ISSUE TITLE
RFP - taskbarx

### ISSUE THREAD

**Issue by joeltonyc** [chocolatey-community/chocolatey-package-requests#904]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://chrisandriessen.nl/taskbarx
Direct download URL for the software / installer : https://github.com/ChrisAnd1998/TaskbarX/releases/download/1.6.2.0/TaskbarX_1.6.2.0.zip
Software summary / short description: Allows you to centre taskbar icons and modify the aesthetics of the Windows Taskbar.
Also, the link is only valid for the v1.6.2.0(which is the latest version as of posting)

## Package Expectations
Open and run "TaskbarX Configurator.exe"
Add "TaskbarX.exe" to "shell:startup"

**Comment by pauby** [comment]
Closing this as no update, and there appears to be a package that covers this.
