### ISSUE TITLE
RFP - powerbi-report-builder

### ISSUE THREAD

**Issue by digitalnyc1** [chocolatey-community/chocolatey-package-requests#906]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.microsoft.com/en-us/download/details.aspx?id=58158
Direct download URL for the software / installer : https://download.microsoft.com/download/F/F/9/FF945E45-7D61-49DD-B982-C5D93D3FB0CF/PowerBiReportBuilder.en-US.msi
Software summary / short description: Power BI Report Builder is optimized for authoring paginated reports for the Power BI service. This download provides a stand-alone installer for Power BI Report Builder.  Power BI Report Builder provides data visualizations that include charts, maps, sparklines, and data bars that can help produce new insights well beyond what can be achieved with standard tables and charts.

**Comment by AdmiringWorm** [comment]
@digitalnyc1 what is the difference between this software you request a package for, and the package https://chocolatey.org/packages/PowerBI?

Or are these perhaps the same?

**Comment by digitalnyc1** [comment]
They're different packages that are part of the Power Platform.  https://chocolatey.org/packages/PowerBI is the Power BI Desktop software https://powerbi.microsoft.com/en-us/desktop/, the Power BI Report Builder (https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-power-bi) is a separate thing.  Unfortunately, I'm not really that well versed in what they actually do, because I don't use them directly.  However I do have to update them frequently for the users I support, and having both packages in Chocolatey would be of great value.

**Comment by AdmiringWorm** [comment]
I see. I am not familiar to either one, so it looked to me that they both were the same.
Thank you for clarifying, I'll open this issue up as available.

**Comment by pauby** [comment]
@cporteou Can you shed any light on them being different / same?

**Comment by cporteou** [comment]
It is indeed 2 different applications for different content types. Power BI Report Builder is essentially a re-skin of the SSRS (Reporting Services) Report Builder intended for paginated reports.

**Comment by teknowledgist** [comment]
I just pushed the [powerbi-reportbuilder package](https://chocolatey.org/packages/powerbi-reportbuilder).

**Comment by AdmiringWorm** [comment]
Looks like the package is approved.
