### ISSUE TITLE
RFM - arduino

### ISSUE THREAD

**Issue by jtcmedia** [chocolatey-community/chocolatey-package-requests#908]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

/confirm jtcmedia

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/arduino
Package source URL: https://github.com/jtcmedia/chocolatey-packages/tree/master/arduino

Currently using AU for this package but it has stopped working due to 308 Permanent Redirect. Uses AutoHotKey but users in the comments claim you don't need it.

**Comment by tunisiano187** [comment]
I'm interested to take this one, has it's one or the things i'm currently
using.
You can add Tunisiano.
Thanks

**Comment by jtcmedia** [comment]
I've added you as maintainer, thanks!

**Comment by jtcmedia** [comment]
@tunisiano187 Looks like you have migrated the package over to your own repo. Can you correct your README? It's not the CLI, it's the IDE. If you could submit a PR to my repo to remove arduino, that would be great and I can close this issue.

**Comment by tunisiano187** [comment]
Indeed, i've migrated because i don't use the same logic as yours.
I've changed the Readme... thanks for the tip.

Next time they'll release a new version, we'll see if everything is OK.
