### ISSUE TITLE
RFP - logitech-g-hub

### ISSUE THREAD

**Issue by ograna** [chocolatey-community/chocolatey-package-requests#910]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://www.logitechg.com/de-de/innovation/g-hub.html
Direct download URL for the software / installer : https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
Software summary / short description:
Logitech G HUB Software lets you customize Logitech G gaming mice, keyboards, headsets, speakers, and other devices

License: https://www.logitech.com/assets/65580/logitech-eula.pdf
Icon: https://www.logitech.com/assets/65549/lg-hub-logo.png
Documentation about Silent installation: https://www.logitech.com/assets/65441/windows-installation-guide.pdf
Just normal installation with Desktop Icon

**Comment by pauby** [comment]
Closing due to no update, and there looks to be a package covering this.
