### ISSUE TITLE
RFP - overwolf

### ISSUE THREAD

**Issue by ograna** [chocolatey-community/chocolatey-package-requests#911]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.overwolf.com/
Direct download URL for the software / installer : https://download.overwolf.com/installer/web_dl_btn2/OverwolfInstaller.exe
Software summary / short description: 
Overlay-Apps for several games

https://www.overwolf.com/legal/privacy
https://cdn2.iconfinder.com/data/icons/gaming-platforms-logo-shapes/250/overwolf_logo-512.png

**Comment by chtof** [comment]
- I didn't find switches to install this package silently.
- Windows Spy does not detect the name of buttons in installer so it seems not possible to use AutoHotKey.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/overwolf

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/overwolf
