### ISSUE TITLE
RFP - pluto-tv

### ISSUE THREAD

**Issue by TheNavyBear** [chocolatey-community/chocolatey-package-requests#913]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.pluto.tv
Direct download URL for the software / installer : http://on.pluto.tv/plutotv-pc
Software summary / short description: Pluto TV is free TV over the Internet

**Comment by TheNavyBear** [comment]
I noticed this is still in triage, is there any info or links I need to provide to help with the triage process?

**Comment by AdmiringWorm** [comment]
@TheNavyBear Most likely just been missed. I'll open this up to new maintainers.

But first, a note to anyone wanting to pick this up, the desktop application (and the service) seems to only be available to American consumers, this is something that needs to be noted in the description of the package.

**Comment by TheNavyBear** [comment]
@AdmiringWorm ,ah ok, and thank you. Also, I was unaware it was US only, or I would have noted that in my original request. Thank you again for the help.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/pluto-tv

**Comment by chtof** [comment]
Status: **Published**
 https://chocolatey.org/packages/pluto-tv
