### ISSUE TITLE
RFP - syncplay

### ISSUE THREAD

**Issue by vamartid** [chocolatey-community/chocolatey-package-requests#914]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://syncplay.pl/ , https://github.com/Syncplay/syncplay
Direct download URL for the software / installer : https://github.com/Syncplay/syncplay/releases/download/v1.6.7/Syncplay-1.6.7-Setup.exe
Software summary / short description: Syncplay synchronises the position and play state of multiple media players so that the viewers can watch the same thing at the same time. This means that when one person pauses/unpauses playback or seeks within their media player then this will be replicated across all media players connected to the same server and in the same 'room'. When a new person joins they will also be synchronised. Syncplay also includes text-based chat so you can discuss a video as you watch it.

**Comment by pauby** [comment]
Closing this as no update, and there is an existing package that looks to cover it.
