### ISSUE TITLE
Bluestacks

### ISSUE THREAD

**Issue by Trance-Paradox** [chocolatey-community/chocolatey-package-requests#915]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.bluestacks.com/
Direct download URL for the software / installer :  https://cdn3.bluestacks.com/downloads/windows/bgp/4.300.0.5129/f52990c3c794891856c1e3397fad91a2/BlueStacksMicroInstaller_4.300.0.5129_native.exe?filename=BlueStacksInstaller_4.300.0.5129_native_098cdb0275a33cab78a4a72e0456c4ed.exe
Software summary / short description: Android emulator
Automatic download and install bluestacks

**Comment by pauby** [comment]
Closing this due to no update.
