### ISSUE TITLE
RFP - kui

### ISSUE THREAD

**Issue by dex4er** [chocolatey-community/chocolatey-package-requests#918]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://kui.tools/
Direct download URL for the software / installer : https://win32-zip.kui-shell.org/
Software summary / short description: Kui combines the power of familiar CLIs with visualizations in high-impact areas. Kui enables you to manipulate complex JSON and YAML data models, integrate disparate tooling, and provides quick access to aggregate views of operational data.

Upgrading manually this package from ZIP is a real pain. I would love to see the choco package for this tool.

**Comment by dgalbraith** [comment]
A [https://www.chocolatey.org/packages/kui](kui package) has been pushed and is ready for moderation.

**Comment by dgalbraith** [comment]
Moderation is now complete and the package is available.
