### ISSUE TITLE
RFP - recyclenow

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey-community/chocolatey-package-requests#919]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://bluefive.pairsite.com/recyclenow.htm

Direct download URL for the software / installer: https://bluefive.pairsite.com/RecycleNOW.zip

Software summary / short description:

> RecycleNOW - Free Removal Tool
>
> RecycleNOW is a small utility that, when triggered, immediately empties the Recycle Bin.
>
> It is meant to be a time-saver as, especially on slower computers, emptying the Bin can take a while. There is no > interface, just run it and it will automatically empty the recycle bin. You can use a scheduler to run it, run it > from the command line etc. Very simple, but may be useful for some.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/recyclenow

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/recyclenow

**Comment by AdmiringWorm** [comment]
@chtof just a note. Please remember to mark the request as `Status: Published` when you close the issue.
Other than that, great work :smile:
