### ISSUE TITLE
RFP - xnshell

### ISSUE THREAD

**Issue by TheRec** [chocolatey-community/chocolatey-package-requests#920]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://www.xnview.com/en/xnshell/

Direct download URL for the software / installer :
http://download.xnview.com/XnShellEx64.exe

Software summary / short description:
XnShell is a powerful Shell extension for Windows Explorer, allowing you to preview and perform various operations within Windows Explorer context menu.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/xnshell
- https://chocolatey.org/packages/xnshell.install
- https://chocolatey.org/packages/xnshell.portable

**Comment by chtof** [comment]
Status: **Published**
- https://chocolatey.org/packages/xnshell
- https://chocolatey.org/packages/xnshell.install
- https://chocolatey.org/packages/xnshell.portable
