### ISSUE TITLE
RFP - dedrm

### ISSUE THREAD

**Issue by FrostedBrownies** [chocolatey-community/chocolatey-package-requests#921]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/apprenticeharper/DeDRM_tools
Direct download URL for the software / installer : https://github.com/apprenticeharper/DeDRM_tools/releases/download/v6.8.1/DeDRM_tools_6.8.1.zip
Software summary / short description: Calibre plugin for removing DRM from ebooks

Should install the plugin in Calibre, probably using `calibre-customize`.

**Comment by dgalbraith** [comment]
[DeDRM ackage](https://www.chocolatey.org/packages/calibre-dedrm) is now ready for moderation.

Note that the latest version for the 5.x series(python 3 based) of Calibre has been uploaded as 5.x are the current Calibre versions.  There is also a package for the 4.x series which will be uploaded on successful completion of moderation.

**Comment by FrostedBrownies** [comment]
Thanks for creating the package.

**Comment by dgalbraith** [comment]
Moderation is complete and the [calibre-dedrm package](https://chocolatey.org/packages/calibre-dedrm) for Calibre 5.x is now available in the community repository.
