### ISSUE TITLE
RFP - lively

### ISSUE THREAD

**Issue by FrostedBrownies** [chocolatey-community/chocolatey-package-requests#922]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://rocksdanister.github.io/lively/
Direct download URL for the software / installer : https://github.com/rocksdanister/lively/releases/download/v1.1.6.0/lively_setup_x86_full_v1160.exe
Software summary / short description: Video/Animation desktop wallpapers

**Comment by w0** [comment]
On it

**Comment by w0** [comment]
Complete: https://chocolatey.org/packages/lively

**Comment by FrostedBrownies** [comment]
Version 1.1.8.0 is now up, thanks @w0
