### ISSUE TITLE
RFP - fluidsynth

### ISSUE THREAD

**Issue by opusforlife2** [chocolatey-community/chocolatey-package-requests#923]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.fluidsynth.org/
Direct download URL for the software / installer : https://github.com/FluidSynth/fluidsynth/releases/download/v2.1.6/fluidsynth-2.1.6-win10-x64.zip
Software summary / short description: FluidSynth is a cross-platform, real-time software synthesizer based on the Soundfont 2 specification. FluidSynth generates audio by reading and handling MIDI events from MIDI input devices by using a SoundFont. It is the software analogue of a MIDI synthesizer. FluidSynth can also play MIDI files.

## Package Expectations

It could offer to become the default MIDI synthesizer on Windows.

## Additional Note
The only MIDI synthesizer currently available on Chocolatey is VirtualMIDISynth, which is closed source.

**Comment by opusforlife2** [comment]
@chtof Interested? You've snapped up my other package requests pretty quickly. :P

**Comment by dgalbraith** [comment]
A [fluidsynth package](https://www.chocolatey.org/packages/fluidsynth/) has been pushed and is ready for moderation.

**Comment by opusforlife2** [comment]
Awesome! Thank you so much! :D

**Comment by dgalbraith** [comment]
Moderation is now complete and the package is available.
