### ISSUE TITLE
RFP - testnav

### ISSUE THREAD

**Issue by nyrosis** [chocolatey-community/chocolatey-package-requests#927]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://download.testnav.com/
Direct download URL for the software / installer : https://download.testnav.com/_testnavinstallers/testnav-1.9.7.msi
Software summary / short description: Pearson Testing Software required in many states for secure k12 student testing.

Information copied from online features and demos on Jan 9th, 2021:

> TestNav 8 current capabilities include a wide-range of tools and features. TestNav is QTI-compliant and includes a wealth of testing tools, as well as built-in Early Warning System triggers and safeguards for student testing and options for accessibility.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/testnav

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/testnav
