### ISSUE TITLE
RFP - unpaper

### ISSUE THREAD

**Issue by githubnavigator** [chocolatey-community/chocolatey-package-requests#930]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/rodrigost23/unpaper/
Direct download URL for the software / installer : https://github.com/rodrigost23/unpaper/releases/download/unpaper-6.1/unpaper-6.1-windows-i686.zip
Software summary / short description: Allows processing of scanned images to perform functions such as splitting two-up pages into separate images. Used in conjunction with OCR software such as OCRmyPDF.

The forked project site I have listed above is for the Windows build workflow. The Unpaper project home is here: https://github.com/unpaper/unpaper

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/unpaper

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/unpaper
