### ISSUE TITLE
validate that current user have permissions to do this command (need write or triage access), unless the user have confirmed

### ISSUE THREAD

**Issue by NeuromancerMkII** [chocolatey-community/chocolatey-package-requests#931]
https://github.com/chocolatey-community/chocolatey-package-requests/blob/94f327f6d5262ca605b6ee4c03df954f46ae43ad/scripts/public/New-UserConnection.ps1#L66-L66

**Comment by pauby** [comment]
@NeuromancerMkII The issues here are for raising package requests. I understand this is for the automation here but it looks like it's just repeating what was in the TODO which isn't helpful.
