### ISSUE TITLE
RFP - flashpoint-launcher

### ISSUE THREAD

**Issue by scowalt** [chocolatey-community/chocolatey-package-requests#932]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/FlashpointProject/launcher
Direct download URL for the software / installer: https://github.com/FlashpointProject/launcher/releases/download/9.1.0/Flashpoint-9.1.0_win.exe
Software summary / short description: Launcher for the Flashpoint web preservation project.

**Comment by dgalbraith** [comment]
@scowalt just looking at this and I thought that it would be worth clarifying - is the intent here for a package of the FlashPoint launcher to be used for development purposes, or is the focus more on having a working install of the FlashPoint application configured with content?

If it is the former I have a package ready to push.  If it is the latter there are a few more things that need to be pulled together to realise that intent properly.

**Comment by scowalt** [comment]
> @scowalt just looking at this and I thought that it would be worth clarifying - is the intent here for a package of the FlashPoint launcher to be used for development purposes, or is the focus more on having a working install of the FlashPoint application configured with content?
> 
> If it is the former I have a package ready to push.  If it is the latter there are a few more things that need to be pulled together to realise that intent properly.

My primary intention was the second one you mentioned: to have an install that could be used to play games out of the box.

The [Flashpoint download page](https://bluemaxima.org/flashpoint/downloads/) mentioned three versions: "Ultimate", "Infinity", and "Core". In a perfect world, all three have separate packages that are actively maintained. For the purposes of my request, however, I care most about having the "Infinity" version. (can play games out of the box, but doesn't take up 500 gb)

**Comment by dgalbraith** [comment]
Ok, have a few packages ready for review on this:
* [flashpoint-launcher](https://www.chocolatey.org/packages/flashpoint-launcher) - the base launcher product which is sans any configuration or content - really for people wanting to roll their own usage of Flashpoint.
* [flashpoint-core](https://www.chocolatey.org/packages/flashpoint-core) - the core distribution that comes configured with example media sets for each class.  This is really targeted at contributors/curators who want to contribute new media content to the project.
* [flashpoint](https://www.chocolatey.org/packages/flashpoint) - a meta-package which points to the preferred distribution (which is at this stage flashpoint-infinity).  You can also use this one if your focus is accessing the content.
* [flashpoint-infinity](https://www.chocolatey.org/packages/flashpoint-infinity) - the distribution that is configured with all of the available content which will be downloaded on-demand at runtime.  **This is the package that most people will want**, either directly or via the [flashpoint](https://www.chocolatey.org/packages/flashpoint) meta-package.

What I have not packaged at this stage is the Flashpoint Ultimate distribution - I want to think about this a little more as I am wary of packaging something that represents a c. 500 Gb download.  Perhaps the approach here is to package the updater which can build an ultimate install via incremental update, and then add a flashpoint-ultimate package which leverages this but want to spend a little more thought on this.

Such a package would also need an exemption from verification testing (almost certain that a 500Gb download will time out on verification) and this should perhaps be agreed up front with the moderators.  Any thoughts on this @pauby?

@scowalt I do believe that the packages here should meet the requirements on the request but perhaps you could comment on this given the lack of a Flashpoint Ultimate package at this time?

**Comment by scowalt** [comment]
This all looks great from my perspective, thank you for your work!

**Comment by dgalbraith** [comment]
The main [flashpoint](https://www.chocolatey.org/packages/flashpoint) meta-package and the [flashpoint-infinity](https://www.chocolatey.org/packages/flashpoint-infinity) packages have been reviewed and are now generally available in the community repository.
