### ISSUE TITLE
RFP - win10-brightnessslider

### ISSUE THREAD

**Issue by scowalt** [chocolatey-community/chocolatey-package-requests#933]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/blackholeearth/Win10_BrightnessSlider
Direct download URL for the software / installer: https://github.com/blackholeearth/Win10_BrightnessSlider/releases/download/v1.7.9/Win10_BrightnessSlider.exe
Software summary / short description: This app puts a Monitor Brightness icon to on Taskbar Tray.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/win10-brightnessslider

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/win10-brightnessslider
