### ISSUE TITLE
RFP - mailslurper

### ISSUE THREAD

**Issue by fmoeqbcegt74gs9e** [chocolatey-community/chocolatey-package-requests#934]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://mailslurper.com/
Direct download URL for the software / installer : https://github.com/mailslurper/mailslurper/releases/download/1.14.1/mailslurper-1.14.1-windows.zip
Software summary / short description: 
> MailSlurper is a small SMTP mail server that slurps mail into oblivion! MailSlurper is perfect for individual developers or small teams writing mail-enabled applications that wish to test email functionality without the risk or hassle of installing and configuring a full blown email server. It's simple to use! Simply setup MailSlurper, configure your code and/or application server to send mail through the address where MailSlurper is running, and start sending emails! MailSlurper will capture those emails into a database for you to view at your leisure. (https://mailslurper.com/)

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/mailslurper

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/mailslurper
