### ISSUE TITLE
RFP - qelectrotech

### ISSUE THREAD

**Issue by silopolis** [chocolatey-community/chocolatey-package-requests#936]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://qelectrotech.org/
Direct download URL for the software / installer : https://download.tuxfamily.org/qet/tags/20190717/Windows/Installer_QElectroTech-0.70_x86_64-win64%2bgit5967-1.exe
Software summary / short description: QElectroTech est une application libre permettant de réaliser des schémas électriques. QElectroTech, ou QET pour faire court, est pour le moment disponible en version 0.70.
QElectroTech, QET for short, is a Free (Open Source) software for electrical, pneumatic, hydraulic, logic schemas and diagrams design.

## Package Expectations
Standard installation with start menu folder and shortcut (Dektop shortcut optional).
Better would be to bundle DXFtoQET utility with it (https://github.com/rdsivd/DXFtoQET-2020, https://download.tuxfamily.org/qet/builds/dxf_to_elmt/windows/2020-05-05/DXFtoQET.exe).
Best would be to have some a way to install the dev daily build (https://download.tuxfamily.org/qet/builds/nightly/), maybe like FreeCAD's package ``--pre`` option. But this may require upstream to add a "permalinkable" installer...

Thanks for all and in advance
May yall be safe

**Comment by teknowledgist** [comment]
I just submitted a [QElectroTech package](https://chocolatey.org/packages/qet), and another for [DXFtoQET](https://chocolatey.org/packages/dxftoqet).

I'll leave any `qet-daily` to someone else.

**Comment by silopolis** [comment]
Great ! Thank you ! 
Posted to the community to let them know
https://qelectrotech.org/forum/viewtopic.php?pid=14562

**Comment by scorpio810** [comment]
Great job, is amazing, thanks;-)

**Comment by AdmiringWorm** [comment]
Looks like the package is approved, and can be consumed normally.
Closing the request now as resolved.

**Comment by silopolis** [comment]
Great, thanks a lot again 🙏

Le mar. 23 mars 2021 à 08:28, Kim J. Nordmo ***@***.***> a
écrit :

**Comment by scorpio810** [comment]
We release new version 0.9 see https://qelectrotech.org/forum/viewtopic.php?id=2379
Tarball here : https://git.tuxfamily.org/qet/qet.git/snapshot/qet-0.9.tar.gz
Changelog : https://git.tuxfamily.org/qet/qet.git/diff/ChangeLog?h=0.9
