### ISSUE TITLE
RFP - awscli-session-manager

### ISSUE THREAD

**Issue by gliptak** [chocolatey-community/chocolatey-package-requests#937]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html#install-plugin-windows
Direct download URL for the software / installer : https://s3.amazonaws.com/session-manager-downloads/plugin/latest/windows/SessionManagerPluginSetup.exe
Software summary / short description: If you want to use the AWS Command Line Interface (AWS CLI) to start and end sessions that connect you to your managed instances, you must first install the Session Manager plugin on your local machine. The plugin can be installed on supported versions of Microsoft Windows, macOS, Linux, and Ubuntu Server. 

A plugin of https://chocolatey.org/packages/awscli

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/awscli-session-manager

**Comment by AdmiringWorm** [comment]
Package looks to be approved
