### ISSUE TITLE
RFM - rockbox

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-package-requests#938]
New release: 1.4.1
Released: 2019-11-15
Platform:
Windows (7 / 8 / 10)
Linux
OS X (10.4, 10.5, 10.6)

http://www.rockbox.org/wiki/RockboxUtility#Download

**Comment by mstick99** [comment]
We could not detect that you have specified a URL to the package in this issue, and we were not able to locate any package matching the id in the issue title. Please update the issue title to match the package name, or add the URL to the 'Package URL:' part of the issue.  https://chocolatey.org/packages/rockbox

**Comment by pauby** [comment]
@mstick99 Can you go back to your original request and use the template and fill in the fields that the bot requires? If that is nto done we will need to close this issue.

**Comment by pauby** [comment]
Closing this due to no update.
