### ISSUE TITLE
RFP - tartube

### ISSUE THREAD

**Issue by candrapersada** [chocolatey-community/chocolatey-package-requests#939]
## Checklist
* [x]  The package I am requesting does not already exist on https://chocolatey.org/packages;
* [x]  There is no open issue for this package;
* [x] The issue title starts with 'RFP - ';
* [x]  The download URL is public and not locked behind a paywall / login;
## Package Details
Software project URL: https://tartube.sourceforge.io
Direct download URL for the software / installer:
https://sourceforge.net/projects/tartube/files/v2.3.085/install-tartube-2.3.085-64bit.exe/download
Software summary / short description: Tartube - The Easy Way To Watch And Download Videos

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/tartube

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/tartube

**Comment by chtof** [comment]
@AdmiringWorm F.Y.I., I am not the maintainer but someone has already scripted the Chocolatey package, it's why I inform the package is under review to avoid someone else script also this package.

**Comment by AdmiringWorm** [comment]
@chtof ah, I see, I never checked the maintainer. In that case this request is considered already existing instead, since the maintainer never commented on the issue.

Thanks for letting me know.
