### ISSUE TITLE
RFP - gingerwriter

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#940]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

Package Details

Software project URL : https://www.gingersoftware.com/
Direct download URL for the software / installer : https://downloads.gingersoftware.com/files/windows/GingerWriterSetup.exe
Software summary / short description:
The software used for spell correction especially in English

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/gingerwriter

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/gingerwriter
