### ISSUE TITLE
RFP - starleaf

### ISSUE THREAD

**Issue by ThinkPadNL** [chocolatey-community/chocolatey-package-requests#944]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://support.starleaf.com/installing/starleaf-app/#Mass-dep
Direct download URL for the software / installer : https://s3.eu-central-1.amazonaws.com/downloads3.starleaf.com/app/StarLeaf-Installer-Windows.msi
Software summary / short description: Videoconferencing tool, similar to Zoom/MS Teams.

## Dependencies
.NET Framework 4.6

## Comments
The .msi does not have version numbering, so i think you will always get the latest version?

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/starleaf

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/starleaf
