### ISSUE TITLE
RFM - meshmixer

### ISSUE THREAD

**Issue by gep13** [chocolatey-community/chocolatey-package-requests#946]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/meshmixer
Package source URL: https://github.com/NovaViper/ChocolateyPackages/tree/master/meshmixer

Date the maintainer was contacted (in YYYY-MM-DD): 2021-02-26
How the maintainer was contacted: Maintainer reached out to support asking for their account on chocolatey.org to be removed

**Comment by AdmiringWorm** [comment]
@mkevenaar you know the drill, send a message using the site admins to get added to the package.

**Comment by mkevenaar** [comment]
A new version has been pushed, ready for review

**Comment by mkevenaar** [comment]
Package is approved.
