### ISSUE TITLE
RFP - asymptote

### ISSUE THREAD

**Issue by mmatera** [chocolatey-community/chocolatey-package-requests#948]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://asymptote.sourceforge.io/
Direct download URL for the software / installer : https://sourceforge.net/projects/asymptote/files/2.69/asymptote-2.69-setup.exe/download
Software summary / short description: 
Asymptote is a powerful descriptive vector graphics language that provides a natural coordinate-based framework for technical drawing. Labels and equations are typeset with LaTeX, the de-facto standard for typesetting mathematics.

A major advantage of Asymptote over other graphics packages is that it is a programming language, as opposed to just a graphics program. 

If there is a package in https://chocolatey.org/packages/asymptote, but it is not functional.

**Comment by teknowledgist** [comment]
I've got a package for this all ready to push.  I just have to be made a maintainer.

**Comment by teknowledgist** [comment]
[Asymptote v2.69](https://chocolatey.org/packages/asymptote) is up and waiting for review by moderators.

**Comment by mmatera** [comment]
I tried to use in the test of a project.  However, for some reason, I can not get that asy.exe appears in the path. Any clue?
[See logs in](https://github.com/Mathics3/pymathics-asy/actions/runs/652232008)

**Comment by teknowledgist** [comment]
@mmatera I guess because the installer doesn't add the path?  The Chocolatey package does nothing more than run the installer silently (and fix a little bug with where the start menu shortcut sits).  If you run the installer manually, `asy.exe` isn't on the path either.

I suppose I could have the path to `asy.exe` added, I just didn't know that was wanted.

**Comment by teknowledgist** [comment]
OK.  Adjusted package pushed.  Try it again.

**Comment by AdmiringWorm** [comment]
The package version 2.69 is approved.
