### ISSUE TITLE
RFP - mailbird

### ISSUE THREAD

**Issue by wickles** [chocolatey-community/chocolatey-package-requests#949]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.getmailbird.com/
Direct download URL for the software / installer : https://download.getmailbird.com/installers/MailbirdInstaller.exe
Software summary / short description:

> Email made easy & beautiful. Save time managing multiple accounts with the best email client for Windows.

**Comment by wickles** [comment]
There is a [package for mailspring](https://chocolatey.org/packages/mailspring) tagged with 'mailbird' and I am not aware if or how they are related.

**Comment by AdmiringWorm** [comment]
As there is already a package named `mailbird` and it links to the same location as specified in this issue, this looks like the exact same package that is being requested.

For any further actions, please follow the package triage documentation: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process
