### ISSUE TITLE
RFP - latino

### ISSUE THREAD

**Issue by MelvinG24** [chocolatey-community/chocolatey-package-requests#950]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
https://www.lenguajelatino.org

Direct download URL for the software / installer :
https://github.com/MelvinG24/Latino/releases/download/v1.3.0/Latino-1.3.0-Win.exe

Software summary / short description:
Latino is a new programming language with Spanish syntax. Latino is born from the need to increase education in computer science in Latino-America; Therefore, students, as well as professionals, could get motivated to enter the world of programming and develop applications with easy-to-learn syntax.

**Comment by MelvinG24** [comment]
Is there anything else may I have to do before this request is valid?

**Comment by AdmiringWorm** [comment]
@MelvinG24 only patience I'm afraid.

The approval of the requests are done manually, and only a few people do the approvals of them so it can sometimes take time until the requests are looked at.
Add that none of them speak Spanish (as far as I know), it can take longer.

Anyways, it is open to upcoming maintainers now, but first a note to them.

### Maintainer note

The latest executable was flagged by 4 different virus engines on [VirusTotal](https://www.virustotal.com/gui/file/0714e4ebb8a03c40cb9e9435ff0b063b233bfc24b092e51924dc8dcc482b8270/detection), this **may** cause a pushback from Chocolatey moderators if there are no provided reason for the installer to be flagged.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/latino

**Comment by MelvinG24** [comment]
Hi @chtof ,

On the Chocolatey packages website it's shows "Verification Testing Pending" am I have to do anything?

Thank you for your time

**Comment by chtof** [comment]
Hi @MelvinG24,
https://docs.chocolatey.org/en-us/faqs#what-is-moderation

**Comment by MelvinG24** [comment]
@chtof,

Thank you very much for the link.
I have noticed that Latino has passed all checks, is that mean Latino can be install from the choco commands? <3

**Comment by AdmiringWorm** [comment]
@MelvinG24 it hasn't yet been approved by the moderators so doing a normal `choco install` command will not work unless you also explicitly uses the `--version` argument as well.

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/latino
