### ISSUE TITLE
RFP - weasel-(traditional-chinese/hong-kong-chinese)

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#952]
## Current Maintainer

@chtof

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [ ] RFM - Weasel (but defaults to "Simplified, China" instead of "Traditional, Hong Kong")

## Existing Package Details

Package URL: https://chocolatey.org/packages/weasel
Package source URL: https://github.com/rime/weasel

Date the maintainer was contacted (in YYYY-MM-DD):
How the maintainer was contacted:

**Comment by AdmiringWorm** [comment]
Please use the correct template when you are opening an issue in this repository, as well as only request 1 package in each issue.

Please fix the items mentioned by the bot, otherwise we will most likely close this issue in 7 days.

**Comment by BrandonKMLee** [comment]
@AdmiringWorm apologies but I would like to raise an issue regarding a package behaving differently from a direct download from the site, and I hope that this can be addressed somehow, since the template is confusing.

**Comment by AdmiringWorm** [comment]
@BrandonKMLee that is not what this repository is.

This repository is for requesting new packages that people want, as well as part of the triage process of getting new maintainers of existing packages.

For issues regarding specific packages, you need to contact the maintainer of that package (either using `Contact Maintainers`, the disqus comments or through their source repository).
For that specific package, I believe the maintainer prefer using their source repository here: https://github.com/chtof/chocolatey-packages.

I will be closing this issue, as it seems your request don't align with what this repository is intended to be used for.
