### ISSUE TITLE
RFP - photosync

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#953]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://www.photosync-app.com/home.html
Direct download URL for the software / installer : https://www.photosync-app.com/tl_files/photosync/publish/win/photosync_setup.404/photosync_setup.exe
Software summary / short description:
This app is for sync photos between desktop and smartphones

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/photosync

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/photosync
