### ISSUE TITLE
RFP - qoppapdfstudio

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#954]
Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.qoppa.com/
Direct download URL for the software / installer : https://download.qoppa.com/pdfstudio/PDFStudio_win64.exe
Software summary / short description:
this app is for editing and reading pdf

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/pdfstudio

**Comment by TheCakeIsNaOH** [comment]
Package has been approved.
