### ISSUE TITLE
RFP - hasleoeasyuefi

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#956]
Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.easyuefi.com/index-us.html
Direct download URL for the software / installer : https://www.easyuefi.com/downloads/EasyUEFI_Trial.exe
Software summary / short description:
this app is for managing UEFI and partition for Windows

**Comment by chtof** [comment]
Status: **Review**
https://community.chocolatey.org/packages/easyuefi

**Comment by TheCakeIsNaOH** [comment]
Package has been approved.
