### ISSUE TITLE
RFP - evoluentmousemanager

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#957]
Checklist
- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://evoluent.com/
Direct download URL for the software / installer : https://evoluent.com/download/EvoSetup-6.0.9.2.msi
Software summary / short description:
this app is for managing type d evoluent vertical mouse

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/evoluentmousemanager

**Comment by TheCakeIsNaOH** [comment]
Package has been approved.
