### ISSUE TITLE
RFP - simpletransfer

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#960]
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://rambax.com/simpletransfer/
Direct download URL for the software / installer : https://rambax.com/simpletransfer/desktop/SimpleTransfer%20Desktop%20Setup%202.2.0.exe
Software summary / short description:
This app is for sync photos between desktop and smartphones

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/simpletransfer

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/simpletransfer
