### ISSUE TITLE
RFP - glow

### ISSUE THREAD

**Issue by muesli** [chocolatey-community/chocolatey-package-requests#961]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/charmbracelet/glow/
Direct download URL for the software / installer : https://github.com/charmbracelet/glow/releases/download/v1.4.0/glow_1.4.0_Windows_x86_64.zip
Software summary / short description: Render markdown on the CLI

**Comment by muesli** [comment]
Added the missing https scheme to the project URL.

**Comment by chtof** [comment]
Status: **Review**
https://chocolatey.org/packages/glow

**Comment by chtof** [comment]
Status: **Published**
https://chocolatey.org/packages/glow
