### ISSUE TITLE
RFP - sshfs-win

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#962]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/billziss-gh/sshfs-win
Direct download URL for the software / installer : https://github.com/billziss-gh/sshfs-win/releases/download/v3.7.21011/sshfs-win-3.7.21011-x64.msi
Software summary / short description: SSHFS For Windows

**Comment by teknowledgist** [comment]
Just a comment:  sshfs-win is dependent on [winfsp](https://github.com/billziss-gh/winfsp) which [already has a package](https://community.chocolatey.org/packages/winfsp) maintained by @billziss-gh, the author of both applications.  It may be worth asking them to take ownership and maintenance the package.

**Comment by jakublevy** [comment]
The package already exists here: https://community.chocolatey.org/packages/sshfs

**Comment by TheCakeIsNaOH** [comment]
Thanks for checking that.
