### ISSUE TITLE
RFM - spicetify-cli

### ISSUE THREAD

**Issue by jhg21** [chocolatey-community/chocolatey-package-requests#967]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/spicetify-cli
Package source URL: https://github.com/derkalaender/chocolatey-specify-cli

Date the maintainer was contacted (in YYYY-MM-DD): 2021-03-02
How the maintainer was contacted: Contacted him through 'Contact Maintainers' on the package page stating the package is no longer up to date. Have not received a reply.

I contacted the site admins on 2021-03-16 and have also not received a reply.

**Comment by jakublevy** [comment]
Hi, 
this package is currently out of date, seems to be still abandoned.
If you are looking for a maintainer, I could maintain it.

My chocolatey name is [Kubikola](https://community.chocolatey.org/profiles/Kubikola)

**Comment by jakublevy** [comment]
I was added as a maintainer, so I pushed an update that got approved.

This issue can be closed.
