### ISSUE TITLE
RFP - wekan

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#969]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://wekan.github.io/
Direct download URL for the software / installer : https://github.com/wekan/wekan/releases
Software summary / short description: A Trello-like application that is Free and Open Source

**Comment by BrandonKMLee** [comment]
@AdmiringWorm  so https://github.com/wekan/wekan/wiki/Install-Wekan-from-source-on-Windows ?

**Comment by BrandonKMLee** [comment]
checking https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing

**Comment by pauby** [comment]
It looks to me the Windows binaries are at https://github.com/wekan/wekan/releases

**Comment by pauby** [comment]
Given there still appears to be no installer / binary, I'm going to go ahead and close this.
