### ISSUE TITLE
RFP - taskboard

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#970]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://taskboard.matthewross.me/
Direct download URL for the software / installer : https://github.com/kiswa/TaskBoard/releases/download/v1.0.2/TaskBoard_v1.0.2.zip
Software summary / short description: Simple Kanban board used to keep track of work

**Comment by AdmiringWorm** [comment]
Please update the issue description with the direct URL to the archive/installer, instead of the release page.

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/taskboard) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/taskboard) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
