### ISSUE TITLE
RFP - flameshot

### ISSUE THREAD

**Issue by karlhorky** [chocolatey-community/chocolatey-package-requests#973]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/flameshot-org/flameshot/
Direct download URL for the software / installer : https://github.com/flameshot-org/flameshot/releases/download/v0.9.0/Flameshot-0.9.0-win64.msi
Software summary / short description: Powerful yet simple to use screenshot software

## Additional Details

Already available on:

- [`scoop`](https://github.com/lukesampson/scoop-extras/issues/5631)
- [`winget`](https://github.com/microsoft/winget-pkgs/issues/7072)

**Comment by w0** [comment]
I will pick this up

**Comment by TheCakeIsNaOH** [comment]
Actually, it appears like this package has been created since this issue was opened:
https://community.chocolatey.org/packages/flameshot#versionhistory
