### ISSUE TITLE
RFP - imazing

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-package-requests#974]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://imazing.com/
Direct download URL for the software / installer : https://downloads.imazing.com/windows/iMazing/iMazing2forWindows.exe
Software summary / short description: Mobile device management software that allows users to transfer files and data between iOS devices and Windows devices. Facilitates additional functionality not normally available via iTunes, such as extraction of files from iOS device backups.

**Comment by brogers5** [comment]
The package link provided by the bot is indeed what I was looking for. However, the package was rejected due to failing multiple rounds of automated testing and has seemingly been abandoned by the maintainer.

**Comment by AdmiringWorm** [comment]
@brogers5 since the package was submitted earlier this year, the triage process should be followed in this case (even though no version was approved).

If there is no response from the maintainer within 7 days, then this issue can be changed to a RFM request instead.

Triage process: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process
RFM issue template: https://raw.githubusercontent.com/chocolatey-community/chocolatey-package-requests/master/.github/ISSUE_TEMPLATE/mMaintainerRequest.md

**Comment by brogers5** [comment]
The maintainer has been contacted. I'll circle back when either the maintainer responds or 7 days elapse, whatever comes first.

**Comment by brogers5** [comment]
The maintainer got back to me this morning. He recently submitted another version, but is still blocked on automated testing. Appears to be missing a dependency: https://gist.github.com/choco-bot/27aa731128785ace006207c3a654d7a4

He invited me to submit a pull request, for which the package source is maintained here:
https://github.com/MANICX100/chocolatey/tree/master/imazing

With that said, I do not have experience with greenfield package development, nor do I have a package dev/test environment set up, so I'm probably not in the best position to pick this up. Sounds to me like a RFM is the way to go here.

**Comment by AdmiringWorm** [comment]
> Sounds to me like a RFM is the way to go here.

Unfortunately not, the current maintainer is responsive and is working toward getting the software available on chocolatey.org.
It would have been an RFM if the maintainer is unresponsive, unwilling or requests himself/herself a new maintainer.
As such, I will be closing this issue for now.

/CC @MANICX100
