### ISSUE TITLE
RFP - torifier

### ISSUE THREAD

**Issue by LinArcX** [chocolatey-community/chocolatey-package-requests#975]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.torifier.com/
Direct download URL for the software / installer : https://cutt.ly/ebfiiPz
Software summary / short description:  tunnel software applications through Tor without the need to reconfigure them

**Comment by AdmiringWorm** [comment]
@LinArcX where did you get the direct download link that you have specified in the issue?
It is not a link that I can see on the webpage, nor do it match any of the time-limited links on the cnet download page.

**Comment by dgalbraith** [comment]
@AdmiringWorm Just looking for a point of clarification on the licensing here.  The pertinent section is:

```
1. You can use the software free of charge for private and professional purposes. You may 
not however sell it for profit and you may not bundle Torifier in other software packages 
without affirmation of the author. 
2. You may offer a version of the program on a website that is free of charge for download 
or you can give exact copies of the original software to anyone. 
3. For any other form of publication, the author’s written permission is necessary. 
```

My reading of this was that clause 2 would appear to support binary redistribution.

Noticing that you marked this as blocked upstream I presume that I was mistaken on this?

If you could confirm and provide a view on the thinking here it would  be appreciated.

**Comment by dgalbraith** [comment]
Review on the [Torifier package](https://community.chocolatey.org/packages/torifier) has been completed and the package is now available.
