### ISSUE TITLE
RFP - flipflip

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#977]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/ififfy/flipflip
Direct download URL for the software / installer : https://github.com/ififfy/flipflip/releases/download/v3.1.2/FlipFlip-Windows.zip
Software summary / short description: Slideshow maker

**Comment by Xav83** [comment]
I pick up this package 🙂  

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/flipflip) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/flipflip/3.2.1) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
