### ISSUE TITLE
RFP - koodo-reader

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#978]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://koodo.960960.xyz/ and https://github.com/troyeguo/koodo-reader/releases
Direct download URL for the software / installer : https://github.com/troyeguo/koodo-reader/releases/download/v1.2.5/Koodo-Reader-1.2.5.exe
Software summary / short description: Ebook reader that is Open Source and Cross Platform

**Comment by dgalbraith** [comment]
A [package](https://community.chocolatey.org/packages/koodo-reader/1.2.5) for koodo-reader has been pushed and is under review.

**Comment by dgalbraith** [comment]
Review on the [Gephi package](https://community.chocolatey.org/packages/koodo-reader/1.2.5) has been completed and the package is now available.

**Comment by BrandonKMLee** [comment]
@dgalbraith testing the Koodo now
