### ISSUE TITLE
RFP - gephi

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#980]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://gephi.org/
Direct download URL for the software / installer : https://github.com/gephi/gephi/releases/download/v0.9.2/gephi-0.9.2-windows.exe
Software summary / short description: Graph creator and viewer

**Comment by dgalbraith** [comment]
A [package for Gephi](https://community.chocolatey.org/packages/gephi) has been pushed.

**Comment by dgalbraith** [comment]
Review on the [Gephi package](https://community.chocolatey.org/packages/gephi) is completed and the package is now available.
