### ISSUE TITLE
RFP - nheko-reborn

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#981]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/Nheko-Reborn/nheko
Direct download URL for the software / installer : https://github.com/Nheko-Reborn/nheko/releases/download/v0.8.2/nheko-v0.8.2-installer.exe
Software summary / short description: live updated fork for https://community.chocolatey.org/packages/nheko/0.1.0.484-nightly

**Comment by dgalbraith** [comment]
A package [nekho-reborn](https://community.chocolatey.org/packages/nheko-reborn/0.8.2) has been pushed and is going through review.

**Comment by dgalbraith** [comment]
[nheko-reborn](https://community.chocolatey.org/packages/nheko-reborn/) package is now available.

**Comment by BrandonKMLee** [comment]
@dgalbraith thank you.,

**Comment by BrandonKMLee** [comment]
ERROR: Running ["C:\ProgramData\chocolatey\lib\nheko-reborn\tools\nheko-v0.8.2-installer.exe" --accept-licenses --confirm-command install ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of nheko-reborn was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nheko-reborn\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by BrandonKMLee** [comment]
[logger.txt](https://github.com/chocolatey-community/chocolatey-package-requests/files/6677891/logger.txt)

**Comment by Xav83** [comment]
Hi @AdmiringWorm  @BrandonKMLee, 

I took a look at this issue, and the [following Chocolatey package](https://community.chocolatey.org/packages/nheko-reborn), maintained by @dgalbraith, is available and seems up to date with the [releases of nheko](https://github.com/Nheko-Reborn/nheko/releases). :slightly_smiling_face:

**Comment by pauby** [comment]
Thanks @Xav83 for updating this and letting us know!
