### ISSUE TITLE
RFM - etcd

### ISSUE THREAD

**Issue by abejenaru** [chocolatey-community/chocolatey-package-requests#989]
## Current Maintainer

- [x] I am the maintainer of the package and wish to pass it to someone else;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details
Package URL: https://chocolatey.org/packages/etcd
Package source URL: https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/etcd

**Comment by AdmiringWorm** [comment]
## New maintainer notes

- This package is hosted in the [GitHub chocolatey-coreteampackages](https://github.com/chocolatey-community/chocolatey-coreteampackages) repository, when picking up this request please do one of the following
  1. After being added as a new maintainer, please open a PR to remove the package and icon from the repository if you want to host the package in your own repository.
  2. After being added as a new maintainer, please open a PR to add yourself as a maintainer to the nuspec and CODEOWNERS files, if you want the package to still be hosted in that repository.

**Comment by dgalbraith** [comment]
I am happy to pick this one up - Chocolatey user name dgalbraith.

**Comment by abejenaru** [comment]
> I am happy to pick this one up - Chocolatey user name dgalbraith.

Alright then! I've added you as maintainer, please check your email (also in spam) for a confirmation message.
Cheers!

**Comment by dgalbraith** [comment]
Maintainer confirmation accepted.
