### ISSUE TITLE
RFM opera-beta

### ISSUE THREAD

**Issue by Redsandro** [chocolatey-community/chocolatey-package-requests#99]
Pretty outdated. Could use autopackage. After all, people actively seeking out the beta want cutting edge.

https://chocolatey.org/packages/opera-beta

**Comment by mkevenaar** [comment]
I'll be working on this one. Already asked the moderators to add me.

**Comment by mkevenaar** [comment]
I have pushed a new beta package to the repository. This package is a pre-release and will be approved once all the tests are done.

**Comment by mkevenaar** [comment]
https://chocolatey.org/packages/opera-beta/60.0.3255.60-beta Package is available.
