### ISSUE TITLE
RFP - freefilesync

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#995]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://freefilesync.org/
Direct download URL for the software / installer : https://freefilesync.org/download/FreeFileSync_11.10_Windows_Setup.exe
Software summary / short description: FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files. Instead of copying every file every time, FreeFileSync determines the differences between a source and a target folder and transfers only the minimum amount of data needed. FreeFileSync is Open Source software, available for Windows, macOS, and Linux.

**Comment by teknowledgist** [comment]
[This package exists](https://community.chocolatey.org/packages/freefilesync/10.2.0.20180914#description), but unless something has changed can no longer (to my knowledge/ability) work as a Chocolatey package.  It cannot be embedded and the developer has created multiple roadblocks to scripted downloading and silent install.  

If you have information that the developer (Zenju) has had a change of heart, point out where that can be seen and I will work on re-releasing the package.
