### ISSUE TITLE
RFP - megadownloader

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#997]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : http://megadownloaderapp.blogspot.com/
Direct download URL for the software / installer : https://appsformega.ovh/MegaDownloader_v1.8.exe
Software summary / short description:  MegaDownloader is a download client for MEGA.CO.NZ, allowing you to easily download files from MEGA.CO.NZ

**Comment by teknowledgist** [comment]
I got this:  https://community.chocolatey.org/packages/megadownloader

**Comment by TheCakeIsNaOH** [comment]
Package has been approved.
