### ISSUE TITLE
RFP - syncplay

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#998]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://syncplay.pl/
Direct download URL for the software / installer : https://github.com/Syncplay/syncplay/releases/download/v1.6.7/Syncplay-1.6.7-Setup.exe
Software summary / short description: Syncplay allows people to enjoy a shared viewing experience even if they are thousands of miles apart, so friends can watch anime, movies, TV shows and other media together. The Syncplay Client launches a media player on your computer, connects to a Syncplay server and joins a virtual room on that server. Pauses, unpauses and seeks made within that media player instance are relayed to fellow viewers via the server to allow for these actions to be replicated by the media players of everyone else in the same virtual room. The server keeps track of where everyone is in the video so if someone joins they can be brought to the right place, and so if someone is too far ahead they can be brought back in sync.

**Comment by soredake** [comment]
@digitalcoyote

**Comment by AdmiringWorm** [comment]
As it seems that this package exists, please follow up with the maintainer of the package instead.

I'll be closing this issue now.
