### ISSUE TITLE
RFP - yuzu

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#999]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://yuzu-emu.org/
Direct download URL for the software / installer : https://github.com/yuzu-emu/liftinstall/releases/download/1.9/yuzu_install.exe
Software summary / short description: yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of Citra.

**Comment by pauby** [comment]
As there has been no update to this since the other package was mentioned above, I'm going to go ahead and close it.
